// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: d45fc83457a20e72

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <utility>
#include <vector>
#include <FIX4.2/core/types.h>
#include <FIX4.2/core/null_fields.h>
#include <FIX4.2/core/field_id.h>
#include <FIX4.2/engine/protocol.h>
#include <FIX4.2/messages/Header.h>
#include <FIX4.2/messages/Trailer.h>

namespace fix42::messages {

class Logon {
	static constexpr std::size_t P_EncryptMethod                = 0;
	static constexpr std::size_t P_HeartBtInt                   = 1;
	static constexpr std::size_t P_RawDataLength                = 2;
	static constexpr std::size_t P_RawData                      = 3;
	static constexpr std::size_t P_ResetSeqNumFlag              = 4;
	static constexpr std::size_t P_MaxMessageSize               = 5;

	struct NoMsgTypes {
		static constexpr std::size_t P_RefMsgType                   = 0;
		static constexpr std::size_t P_MsgDirection                 = 1;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 43;

		types::STRING<32> m_RefMsgType{fields::RefMsgType_NULL};
		types::CHAR m_MsgDirection{fields::NULL_CHAR};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::STRING<32> &getRefMsgType() const noexcept { return m_RefMsgType; }
		const types::CHAR &getMsgDirection() const noexcept { return m_MsgDirection; }

		// mutators
		void setRefMsgType(const types::STRING<32> &v) noexcept { m_RefMsgType = v; m_presence |= (1ULL << P_RefMsgType); }
		void setMsgDirection(types::CHAR v) noexcept { m_MsgDirection = v; m_presence |= (1ULL << P_MsgDirection); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasRefMsgType() const noexcept { return (m_presence & (1ULL << P_RefMsgType)) != 0; }
		bool hasMsgDirection() const noexcept { return (m_presence & (1ULL << P_MsgDirection)) != 0; }
	};


	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1);
	static constexpr std::size_t MAX_ENCODE_SIZE = 140;

	Header m_Header{};
	Trailer m_Trailer{};

	types::INT m_EncryptMethod{fields::NULL_INT};
	types::INT m_HeartBtInt{fields::NULL_INT};
	types::LENGTH m_RawDataLength{fields::NULL_LENGTH};
	types::DATA<32> m_RawData{fields::RawData_NULL};
	types::BOOLEAN m_ResetSeqNumFlag{fields::NULL_BOOLEAN};
	types::INT m_MaxMessageSize{fields::NULL_INT};
	std::vector<NoMsgTypes> m_NoMsgTypesGroup{};

	uint64_t m_presence{0};

public:
	using Protocol = fix42::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "A";
	static constexpr bool IS_ADMIN = true;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		for (const auto &entry : m_NoMsgTypesGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::INT &getEncryptMethod() const noexcept { return m_EncryptMethod; }
	const types::INT &getHeartBtInt() const noexcept { return m_HeartBtInt; }
	const types::LENGTH &getRawDataLength() const noexcept { return m_RawDataLength; }
	const types::DATA<32> &getRawData() const noexcept { return m_RawData; }
	const types::BOOLEAN &getResetSeqNumFlag() const noexcept { return m_ResetSeqNumFlag; }
	const types::INT &getMaxMessageSize() const noexcept { return m_MaxMessageSize; }
	std::vector<NoMsgTypes> &getRefNoMsgTypesGroup() noexcept { return m_NoMsgTypesGroup; }
	const std::vector<NoMsgTypes> &getRefNoMsgTypesGroup() const noexcept { return m_NoMsgTypesGroup; }

	// mutators
	void setEncryptMethod(types::INT v) noexcept { m_EncryptMethod = v; m_presence |= (1ULL << P_EncryptMethod); }
	void setHeartBtInt(types::INT v) noexcept { m_HeartBtInt = v; m_presence |= (1ULL << P_HeartBtInt); }
	void setRawDataLength(types::LENGTH v) noexcept { m_RawDataLength = v; m_presence |= (1ULL << P_RawDataLength); }
	void setRawData(const types::DATA<32> &v) noexcept { m_RawData = v; m_presence |= (1ULL << P_RawData); }
	void setResetSeqNumFlag(types::BOOLEAN v) noexcept { m_ResetSeqNumFlag = v; m_presence |= (1ULL << P_ResetSeqNumFlag); }
	void setMaxMessageSize(types::INT v) noexcept { m_MaxMessageSize = v; m_presence |= (1ULL << P_MaxMessageSize); }
	void addNoMsgTypesGroup(const NoMsgTypes &item) { m_NoMsgTypesGroup.push_back(item); }
	void addNoMsgTypesGroup(NoMsgTypes &&item) noexcept { m_NoMsgTypesGroup.push_back(std::move(item)); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoMsgTypesGroup.empty()) { return true; }
		return false;
	}
	bool hasEncryptMethod() const noexcept { return (m_presence & (1ULL << P_EncryptMethod)) != 0; }
	bool hasHeartBtInt() const noexcept { return (m_presence & (1ULL << P_HeartBtInt)) != 0; }
	bool hasRawDataLength() const noexcept { return (m_presence & (1ULL << P_RawDataLength)) != 0; }
	bool hasRawData() const noexcept { return (m_presence & (1ULL << P_RawData)) != 0; }
	bool hasResetSeqNumFlag() const noexcept { return (m_presence & (1ULL << P_ResetSeqNumFlag)) != 0; }
	bool hasMaxMessageSize() const noexcept { return (m_presence & (1ULL << P_MaxMessageSize)) != 0; }
	bool hasNoMsgTypes() const noexcept { return !m_NoMsgTypesGroup.empty(); }
};

} // namespace fix42::messages
