// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Auto-generated FIX code. Do not edit by hand.

// Generated by FalconFIX Generator
// ContentHash: ac162b9775c7b0df

#include <FIX4.3/messages/Allocation.h>

#include <cstring>

#include <FIX4.3/utils/macros.h>
#include <FIX4.3/utils/parser.h>
#include <FIX4.3/utils/serializer.h>
#include <FIX4.3/utils/tag_constants.h>
#include <FIX4.3/utils/datetime.h>
#include <utils/string_utils.h>

namespace fix43::messages {

void Allocation::NoOrders::reset() noexcept {
	m_ClOrdID = fields::ClOrdID_NULL;
	m_OrderID = fields::OrderID_NULL;
	m_SecondaryOrderID = fields::SecondaryOrderID_NULL;
	m_SecondaryClOrdID = fields::SecondaryClOrdID_NULL;
	m_ListID = fields::ListID_NULL;
	m_presence = 0;
}

bool Allocation::NoOrders::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool Allocation::NoOrders::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;

		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }

		if (consumed && tag == field_id::ClOrdID) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix43::serialize::SOH) { ++p; }
		const char *valueEnd = p;
		if (p < end) { ++p; }

		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			return consumed;
		}
		consumed = true;
	}

	return consumed;
}

char *Allocation::NoOrders::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasClOrdID()) { WRITE_TAG3(fix43::tag_const::ClOrdID); std::memcpy(p, m_ClOrdID.data(), m_ClOrdID.size()); p += m_ClOrdID.size(); *p++ = fix43::serialize::SOH; }
	if (hasOrderID()) { WRITE_TAG3(fix43::tag_const::OrderID); std::memcpy(p, m_OrderID.data(), m_OrderID.size()); p += m_OrderID.size(); *p++ = fix43::serialize::SOH; }
	if (hasSecondaryOrderID()) { WRITE_TAG4(fix43::tag_const::SecondaryOrderID); std::memcpy(p, m_SecondaryOrderID.data(), m_SecondaryOrderID.size()); p += m_SecondaryOrderID.size(); *p++ = fix43::serialize::SOH; }
	if (hasSecondaryClOrdID()) { WRITE_TAG4(fix43::tag_const::SecondaryClOrdID); std::memcpy(p, m_SecondaryClOrdID.data(), m_SecondaryClOrdID.size()); p += m_SecondaryClOrdID.size(); *p++ = fix43::serialize::SOH; }
	if (hasListID()) { WRITE_TAG3(fix43::tag_const::ListID); std::memcpy(p, m_ListID.data(), m_ListID.size()); p += m_ListID.size(); *p++ = fix43::serialize::SOH; }

	return p;
}

bool Allocation::NoOrders::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::ClOrdID: setClOrdID({begin, len}); return true;
	case field_id::OrderID: setOrderID({begin, len}); return true;
	case field_id::SecondaryOrderID: setSecondaryOrderID({begin, len}); return true;
	case field_id::SecondaryClOrdID: setSecondaryClOrdID({begin, len}); return true;
	case field_id::ListID: setListID({begin, len}); return true;
	default: return false;
	}
}

void Allocation::NoExecs::reset() noexcept {
	m_LastQty = fields::NULL_QTY;
	m_ExecID = fields::ExecID_NULL;
	m_SecondaryExecID = fields::SecondaryExecID_NULL;
	m_LastPx = fields::NULL_PRICE;
	m_LastCapacity = fields::NULL_CHAR;
	m_presence = 0;
}

bool Allocation::NoExecs::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool Allocation::NoExecs::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;

		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }

		if (consumed && tag == field_id::LastQty) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix43::serialize::SOH) { ++p; }
		const char *valueEnd = p;
		if (p < end) { ++p; }

		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			return consumed;
		}
		consumed = true;
	}

	return consumed;
}

char *Allocation::NoExecs::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasLastQty()) { WRITE_TAG3(fix43::tag_const::LastQty); p += falconfix::dtoa(m_LastQty, p); *p++ = fix43::serialize::SOH; }
	if (hasExecID()) { WRITE_TAG3(fix43::tag_const::ExecID); std::memcpy(p, m_ExecID.data(), m_ExecID.size()); p += m_ExecID.size(); *p++ = fix43::serialize::SOH; }
	if (hasSecondaryExecID()) { WRITE_TAG4(fix43::tag_const::SecondaryExecID); std::memcpy(p, m_SecondaryExecID.data(), m_SecondaryExecID.size()); p += m_SecondaryExecID.size(); *p++ = fix43::serialize::SOH; }
	if (hasLastPx()) { WRITE_TAG3(fix43::tag_const::LastPx); p += falconfix::dtoa(m_LastPx, p); *p++ = fix43::serialize::SOH; }
	if (hasLastCapacity()) { WRITE_TAG3(fix43::tag_const::LastCapacity); *p++ = m_LastCapacity; *p++ = fix43::serialize::SOH; }

	return p;
}

bool Allocation::NoExecs::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::LastQty: setLastQty(fix43::parser::parse_double(begin, end)); return true;
	case field_id::ExecID: setExecID({begin, len}); return true;
	case field_id::SecondaryExecID: setSecondaryExecID({begin, len}); return true;
	case field_id::LastPx: setLastPx(fix43::parser::parse_double(begin, end)); return true;
	case field_id::LastCapacity: setLastCapacity(fix43::parser::parse_char(begin, end)); return true;
	default: return false;
	}
}

void Allocation::NoAllocs::NoMiscFees::reset() noexcept {
	m_MiscFeeAmt = fields::NULL_AMT;
	m_MiscFeeCurr = fields::MiscFeeCurr_NULL;
	m_MiscFeeType = fields::NULL_CHAR;
	m_presence = 0;
}

bool Allocation::NoAllocs::NoMiscFees::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool Allocation::NoAllocs::NoMiscFees::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;

		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }

		if (consumed && tag == field_id::MiscFeeAmt) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix43::serialize::SOH) { ++p; }
		const char *valueEnd = p;
		if (p < end) { ++p; }

		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			return consumed;
		}
		consumed = true;
	}

	return consumed;
}

char *Allocation::NoAllocs::NoMiscFees::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasMiscFeeAmt()) { WRITE_TAG4(fix43::tag_const::MiscFeeAmt); p += falconfix::dtoa(m_MiscFeeAmt, p); *p++ = fix43::serialize::SOH; }
	if (hasMiscFeeCurr()) { WRITE_TAG4(fix43::tag_const::MiscFeeCurr); std::memcpy(p, m_MiscFeeCurr.data(), m_MiscFeeCurr.size()); p += m_MiscFeeCurr.size(); *p++ = fix43::serialize::SOH; }
	if (hasMiscFeeType()) { WRITE_TAG4(fix43::tag_const::MiscFeeType); *p++ = m_MiscFeeType; *p++ = fix43::serialize::SOH; }

	return p;
}

bool Allocation::NoAllocs::NoMiscFees::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::MiscFeeAmt: setMiscFeeAmt(fix43::parser::parse_double(begin, end)); return true;
	case field_id::MiscFeeCurr: setMiscFeeCurr({begin, len}); return true;
	case field_id::MiscFeeType: setMiscFeeType(fix43::parser::parse_char(begin, end)); return true;
	default: return false;
	}
}

void Allocation::NoAllocs::reset() noexcept {
	m_AllocAccount = fields::AllocAccount_NULL;
	m_AllocPrice = fields::NULL_PRICE;
	m_AllocQty = fields::NULL_QTY;
	m_IndividualAllocID = fields::IndividualAllocID_NULL;
	m_ProcessCode = fields::NULL_CHAR;
	m_NotifyBrokerOfCredit = fields::NULL_BOOLEAN;
	m_AllocHandlInst = fields::NULL_INT;
	m_AllocText = fields::AllocText_NULL;
	m_EncodedAllocTextLen = fields::NULL_LENGTH;
	m_EncodedAllocText = fields::EncodedAllocText_NULL;
	m_AllocAvgPx = fields::NULL_PRICE;
	m_AllocNetMoney = fields::NULL_AMT;
	m_SettlCurrAmt = fields::NULL_AMT;
	m_SettlCurrency = fields::SettlCurrency_NULL;
	m_SettlCurrFxRate = fields::NULL_FLOAT;
	m_SettlCurrFxRateCalc = fields::NULL_CHAR;
	m_AccruedInterestAmt = fields::NULL_AMT;
	m_SettlInstMode = fields::NULL_CHAR;
	m_NestedParties.reset();
	m_CommissionData.reset();
	m_NoMiscFeesGroup.clear();
	m_presence = 0;
}

bool Allocation::NoAllocs::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	if (m_NestedParties.hasAnySet() && !m_NestedParties.checkRequired()) {
		return false;
	}
	if (m_CommissionData.hasAnySet() && !m_CommissionData.checkRequired()) {
		return false;
	}
	for (const auto &entry : m_NoMiscFeesGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

bool Allocation::NoAllocs::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;

		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }

		if (consumed && tag == field_id::AllocAccount) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix43::serialize::SOH) { ++p; }
		const char *valueEnd = p;
		if (p < end) { ++p; }

		switch (tag) {
		case field_id::NoMiscFees: {
			const std::size_t count = static_cast<std::size_t>(falconfix::atoi(valueBegin, valueEnd));
			m_NoMiscFeesGroup.clear();
			m_NoMiscFeesGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoMiscFeesGroup.emplace_back();
				if (!m_NoMiscFeesGroup.back().decode(p, end)) { return false; }
			}
			consumed = true;
			continue;
		}
		default: break;
		}
		switch (tag) {
		case field_id::NoNestedPartyIDs:
			p = tag_start;
			if (!m_NestedParties.decode(p, end, field_id::AllocAccount, true)) { return false; }
			consumed = true;
			continue;
		case field_id::Commission:
			p = tag_start;
			if (!m_CommissionData.decode(p, end, field_id::AllocAccount, true)) { return false; }
			consumed = true;
			continue;
		default: break;
		}
		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			return consumed;
		}
		consumed = true;
	}

	return consumed;
}

char *Allocation::NoAllocs::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasAllocAccount()) { WRITE_TAG3(fix43::tag_const::AllocAccount); std::memcpy(p, m_AllocAccount.data(), m_AllocAccount.size()); p += m_AllocAccount.size(); *p++ = fix43::serialize::SOH; }
	if (hasAllocPrice()) { WRITE_TAG4(fix43::tag_const::AllocPrice); p += falconfix::dtoa(m_AllocPrice, p); *p++ = fix43::serialize::SOH; }
	if (hasAllocQty()) { WRITE_TAG3(fix43::tag_const::AllocQty); p += falconfix::dtoa(m_AllocQty, p); *p++ = fix43::serialize::SOH; }
	if (hasIndividualAllocID()) { WRITE_TAG4(fix43::tag_const::IndividualAllocID); std::memcpy(p, m_IndividualAllocID.data(), m_IndividualAllocID.size()); p += m_IndividualAllocID.size(); *p++ = fix43::serialize::SOH; }
	if (hasProcessCode()) { WRITE_TAG3(fix43::tag_const::ProcessCode); *p++ = m_ProcessCode; *p++ = fix43::serialize::SOH; }
	if (hasNotifyBrokerOfCredit()) { WRITE_TAG4(fix43::tag_const::NotifyBrokerOfCredit); *p++ = m_NotifyBrokerOfCredit ? 'Y' : 'N'; *p++ = fix43::serialize::SOH; }
	if (hasAllocHandlInst()) { WRITE_TAG4(fix43::tag_const::AllocHandlInst); p += falconfix::itoa(m_AllocHandlInst, p); *p++ = fix43::serialize::SOH; }
	if (hasAllocText()) { WRITE_TAG4(fix43::tag_const::AllocText); std::memcpy(p, m_AllocText.data(), m_AllocText.size()); p += m_AllocText.size(); *p++ = fix43::serialize::SOH; }
	if (hasEncodedAllocTextLen()) { WRITE_TAG4(fix43::tag_const::EncodedAllocTextLen); p += falconfix::itoa(m_EncodedAllocTextLen, p); *p++ = fix43::serialize::SOH; }
	if (hasEncodedAllocText()) { WRITE_TAG4(fix43::tag_const::EncodedAllocText); std::memcpy(p, m_EncodedAllocText.data(), m_EncodedAllocText.size()); p += m_EncodedAllocText.size(); *p++ = fix43::serialize::SOH; }
	if (hasAllocAvgPx()) { WRITE_TAG4(fix43::tag_const::AllocAvgPx); p += falconfix::dtoa(m_AllocAvgPx, p); *p++ = fix43::serialize::SOH; }
	if (hasAllocNetMoney()) { WRITE_TAG4(fix43::tag_const::AllocNetMoney); p += falconfix::dtoa(m_AllocNetMoney, p); *p++ = fix43::serialize::SOH; }
	if (hasSettlCurrAmt()) { WRITE_TAG4(fix43::tag_const::SettlCurrAmt); p += falconfix::dtoa(m_SettlCurrAmt, p); *p++ = fix43::serialize::SOH; }
	if (hasSettlCurrency()) { WRITE_TAG4(fix43::tag_const::SettlCurrency); std::memcpy(p, m_SettlCurrency.data(), m_SettlCurrency.size()); p += m_SettlCurrency.size(); *p++ = fix43::serialize::SOH; }
	if (hasSettlCurrFxRate()) { WRITE_TAG4(fix43::tag_const::SettlCurrFxRate); p += falconfix::dtoa(m_SettlCurrFxRate, p); *p++ = fix43::serialize::SOH; }
	if (hasSettlCurrFxRateCalc()) { WRITE_TAG4(fix43::tag_const::SettlCurrFxRateCalc); *p++ = m_SettlCurrFxRateCalc; *p++ = fix43::serialize::SOH; }
	if (hasAccruedInterestAmt()) { WRITE_TAG4(fix43::tag_const::AccruedInterestAmt); p += falconfix::dtoa(m_AccruedInterestAmt, p); *p++ = fix43::serialize::SOH; }
	if (hasSettlInstMode()) { WRITE_TAG4(fix43::tag_const::SettlInstMode); *p++ = m_SettlInstMode; *p++ = fix43::serialize::SOH; }
	p = m_NestedParties.encode(p, includeMilliseconds);
	p = m_CommissionData.encode(p, includeMilliseconds);
	if (!m_NoMiscFeesGroup.empty()) {
		WRITE_TAG4(fix43::tag_const::NoMiscFees);
		p += falconfix::itoa(static_cast<int64_t>(m_NoMiscFeesGroup.size()), p);
		*p++ = fix43::serialize::SOH;
		for (const auto &entry : m_NoMiscFeesGroup) {
			p = entry.encode(p, includeMilliseconds);
		}
	}

	return p;
}

bool Allocation::NoAllocs::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::AllocAccount: setAllocAccount({begin, len}); return true;
	case field_id::AllocPrice: setAllocPrice(fix43::parser::parse_double(begin, end)); return true;
	case field_id::AllocQty: setAllocQty(fix43::parser::parse_double(begin, end)); return true;
	case field_id::IndividualAllocID: setIndividualAllocID({begin, len}); return true;
	case field_id::ProcessCode: setProcessCode(fix43::parser::parse_char(begin, end)); return true;
	case field_id::NotifyBrokerOfCredit: setNotifyBrokerOfCredit(fix43::parser::parse_bool(begin, end)); return true;
	case field_id::AllocHandlInst: setAllocHandlInst(falconfix::atoi(begin, end)); return true;
	case field_id::AllocText: setAllocText({begin, len}); return true;
	case field_id::EncodedAllocTextLen: setEncodedAllocTextLen(falconfix::atoi(begin, end)); return true;
	case field_id::EncodedAllocText: setEncodedAllocText({begin, len}); return true;
	case field_id::AllocAvgPx: setAllocAvgPx(fix43::parser::parse_double(begin, end)); return true;
	case field_id::AllocNetMoney: setAllocNetMoney(fix43::parser::parse_double(begin, end)); return true;
	case field_id::SettlCurrAmt: setSettlCurrAmt(fix43::parser::parse_double(begin, end)); return true;
	case field_id::SettlCurrency: setSettlCurrency({begin, len}); return true;
	case field_id::SettlCurrFxRate: setSettlCurrFxRate(fix43::parser::parse_double(begin, end)); return true;
	case field_id::SettlCurrFxRateCalc: setSettlCurrFxRateCalc(fix43::parser::parse_char(begin, end)); return true;
	case field_id::AccruedInterestAmt: setAccruedInterestAmt(fix43::parser::parse_double(begin, end)); return true;
	case field_id::SettlInstMode: setSettlInstMode(fix43::parser::parse_char(begin, end)); return true;
	default: return false;
	}
}

void Allocation::reset() noexcept {
	m_Header.reset();
	m_Trailer.reset();
	m_AllocID = fields::AllocID_NULL;
	m_AllocTransType = fields::NULL_CHAR;
	m_AllocType = fields::NULL_INT;
	m_RefAllocID = fields::RefAllocID_NULL;
	m_AllocLinkID = fields::AllocLinkID_NULL;
	m_AllocLinkType = fields::NULL_INT;
	m_BookingRefID = fields::BookingRefID_NULL;
	m_NoOrdersGroup.clear();
	m_NoExecsGroup.clear();
	m_Side = fields::NULL_CHAR;
	m_Instrument.reset();
	m_Quantity = fields::NULL_QTY;
	m_LastMkt = fields::LastMkt_NULL;
	m_TradeOriginationDate = fields::TradeOriginationDate_NULL;
	m_TradingSessionID = fields::TradingSessionID_NULL;
	m_TradingSessionSubID = fields::TradingSessionSubID_NULL;
	m_PriceType = fields::NULL_INT;
	m_AvgPx = fields::NULL_PRICE;
	m_Currency = fields::Currency_NULL;
	m_AvgPrxPrecision = fields::NULL_INT;
	m_Parties.reset();
	m_TradeDate = fields::NULL_LOCALMKTDATE;
	m_TransactTime = fields::NULL_UTCTIMESTAMP;
	m_SettlmntTyp = fields::NULL_CHAR;
	m_FutSettDate = fields::NULL_LOCALMKTDATE;
	m_GrossTradeAmt = fields::NULL_AMT;
	m_Concession = fields::NULL_AMT;
	m_TotalTakedown = fields::NULL_AMT;
	m_NetMoney = fields::NULL_AMT;
	m_PositionEffect = fields::NULL_CHAR;
	m_Text = fields::Text_NULL;
	m_EncodedTextLen = fields::NULL_LENGTH;
	m_EncodedText = fields::EncodedText_NULL;
	m_NumDaysInterest = fields::NULL_INT;
	m_AccruedInterestRate = fields::NULL_PERCENTAGE;
	m_TotalAccruedInterestAmt = fields::NULL_AMT;
	m_LegalConfirm = fields::NULL_BOOLEAN;
	m_NoAllocsGroup.clear();
	m_presence = 0;
}

bool Allocation::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	for (const auto &entry : m_NoOrdersGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	for (const auto &entry : m_NoExecsGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	if (m_Instrument.hasAnySet() && !m_Instrument.checkRequired()) {
		return false;
	}
	if (m_Parties.hasAnySet() && !m_Parties.checkRequired()) {
		return false;
	}
	for (const auto &entry : m_NoAllocsGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

FFStatus Allocation::setString(const char *&p, const char *end) noexcept {
	reset();

	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;

		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) {
				return FF_FIX_PARSE_ERR(MALFORMED_TAG, 0);
			}
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) {
			return FF_FIX_PARSE_ERR(MISSING_EQUALS, 0);
		}

		switch (tag) {
		case field_id::BeginString:
			p = tag_start;
			if (!m_Header.decode(p, end)) {
				return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::BeginString);
			}
			continue;
		case field_id::SignatureLength:
		case field_id::Signature:
		case field_id::CheckSum:
			p = tag_start;
			if (!m_Trailer.decode(p, end)) {
				return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::SignatureLength);
			}
			continue;
		case field_id::Symbol:
			p = tag_start;
			if (!m_Instrument.decode(p, end)) {
				return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::Symbol);
			}
			continue;
		case field_id::NoPartyIDs:
			p = tag_start;
			if (!m_Parties.decode(p, end)) {
				return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::NoPartyIDs);
			}
			continue;
		default:
			break;
		}

		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix43::serialize::SOH) {
			++p;
		}
		const char *valueEnd = p;
		if (p < end) {
			++p;
		}
		else {
			return FF_FIX_PARSE_ERR(MISSING_SOH, tag);
		}

		switch (tag) {
		case field_id::NoOrders: {
			const std::size_t count = static_cast<std::size_t>(falconfix::atoi(valueBegin, valueEnd));
			m_NoOrdersGroup.clear();
			m_NoOrdersGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoOrdersGroup.emplace_back();
				if (!m_NoOrdersGroup.back().decode(p, end)) { return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::NoOrders); }
			}
			continue;
		}
		case field_id::NoExecs: {
			const std::size_t count = static_cast<std::size_t>(falconfix::atoi(valueBegin, valueEnd));
			m_NoExecsGroup.clear();
			m_NoExecsGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoExecsGroup.emplace_back();
				if (!m_NoExecsGroup.back().decode(p, end)) { return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::NoExecs); }
			}
			continue;
		}
		case field_id::NoAllocs: {
			const std::size_t count = static_cast<std::size_t>(falconfix::atoi(valueBegin, valueEnd));
			m_NoAllocsGroup.clear();
			m_NoAllocsGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoAllocsGroup.emplace_back();
				if (!m_NoAllocsGroup.back().decode(p, end)) { return FF_FIX_PARSE_ERR(DECODE_FAILED, field_id::NoAllocs); }
			}
			continue;
		}
		default:
			break;
		}

		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			switch (tag) {
			case field_id::Account: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AdvId: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AdvRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AdvSide: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AdvTransType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BeginSeqNo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ClOrdID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Commission: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CommType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CumQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EndSeqNo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HandlInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOIid: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOIQltyInd: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOIRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOIQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOITransType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastCapacity: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LinesOfText: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MsgSeqNum: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MsgType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NewSeqNo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrderID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrderQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrdStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrdType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrigClOrdID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrigTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PossDupFlag: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Price: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RefSeqNum: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Rule80A: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SenderCompID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SenderSubID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SendingTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TargetCompID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TargetSubID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TimeInForce: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Urgency: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ValidUntilTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListSeqNo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotNoOrders: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListExecInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocAccount: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ProcessCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoRpts: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RptSeq: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CxlQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocRejCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecureDataLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecureData: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EmailType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RawDataLength: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RawData: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PossResend: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncryptMethod: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StopPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExDestination: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CxlRejReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrdRejReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOIQualifier: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HeartBtInt: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MinQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MaxFloor: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TestReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ReportToExch: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LocateReqd: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OnBehalfOfCompID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OnBehalfOfSubID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlCurrAmt: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlCurrency: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ForexReq: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrigSendingTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::GapFillFlag: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExpireTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DKReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DeliverToCompID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DeliverToSubID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IOINaturalFlag: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OfferPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OfferSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoMiscFees: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MiscFeeAmt: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MiscFeeCurr: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MiscFeeType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PrevClosePx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ResetSeqNumFlag: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SenderLocationID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TargetLocationID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OnBehalfOfLocationID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DeliverToLocationID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoRelatedSym: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Subject: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Headline: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::URLLink: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LeavesQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashOrderQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocAvgPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocNetMoney: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlCurrFxRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlCurrFxRateCalc: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AccruedInterestAmt: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlInstMode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocText: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlInstID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlInstTransType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EmailThreadID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlInstSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EffectiveTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StandInstDbType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StandInstDbName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StandInstDbID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlDeliveryType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlDepositoryCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlBrkrCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlInstCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecuritySettlAgentName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecuritySettlAgentCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecuritySettlAgentAcctNum: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecuritySettlAgentAcctName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecuritySettlAgentContactName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecuritySettlAgentContactPhone: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashSettlAgentName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashSettlAgentCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashSettlAgentAcctNum: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashSettlAgentAcctName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashSettlAgentContactName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashSettlAgentContactPhone: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidSpotRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidForwardPoints: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OfferSpotRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OfferForwardPoints: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrderQty2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::FutSettDate2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastSpotRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastForwardPoints: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecondaryOrderID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoIOIQualifiers: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CoveredOrUncovered: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NotifyBrokerOfCredit: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocHandlInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MaxShow: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PegDifference: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::XmlDataLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::XmlData: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlInstRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoRoutingIDs: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RoutingType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RoutingID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Spread: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Benchmark: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BenchmarkCurveCurrency: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BenchmarkCurveName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BenchmarkCurvePoint: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoStipulations: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StipulationType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StipulationValue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::YieldType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Yield: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingCouponPaymentDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingIssueDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingRepoCollateralSecurityType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingRepurchaseTerm: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingRepurchaseRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingFactor: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingRedemptionDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCouponPaymentDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegIssueDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegRepoCollateralSecurityType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegRepurchaseTerm: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegRepurchaseRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegFactor: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegRedemptionDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingCreditRating: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCreditRating: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradedFlatSwitch: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BasisFeatureDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BasisFeaturePrice: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SubscriptionRequestType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MarketDepth: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDUpdateType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AggregatedBook: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoMDEntryTypes: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoMDEntries: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntrySize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TickDirection: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDMkt: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteCondition: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeCondition: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDUpdateAction: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDReqRejReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryOriginator: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LocationID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DeskID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DeleteReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OpenCloseSettleFlag: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SellerDays: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryBuyer: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntrySeller: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDEntryPositionNo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::FinancialStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CorporateAction: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DefBidSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DefOfferSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoQuoteEntries: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoQuoteSets: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteCancelType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteEntryID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteRejectReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteResponseLevel: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteSetID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteRequestType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotQuoteEntries: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingIssuer: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityDesc: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityExchange: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSymbol: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSymbolSfx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingMaturityMonthYear: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingPutOrCall: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingStrikePrice: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingOptAttribute: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityRequestType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityResponseID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityResponseType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityStatusReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnsolicitedIndicator: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityTradingStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HaltReasonChar: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::InViewOfCommon: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DueToRelated: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BuyVolume: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SellVolume: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HighPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LowPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Adjustment: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContraTrader: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesMethod: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesMode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesStartTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesOpenTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesPreCloseTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesCloseTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesEndTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NumberOfOrders: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MessageEncoding: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedListExecInstLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedListExecInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedSubjectLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedSubject: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedHeadlineLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedHeadline: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedAllocTextLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedAllocText: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedUnderlyingIssuerLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedUnderlyingIssuer: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedUnderlyingSecurityDescLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedUnderlyingSecurityDesc: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AllocPrice: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteSetValidUntilTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteEntryRejectReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastMsgSeqNumProcessed: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OnBehalfOfSendingTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RefTagID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RefMsgType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SessionRejectReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidRequestTransType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContraBroker: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ComplianceID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SolicitedFlag: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecRestatementReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BusinessRejectRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BusinessRejectReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoContraBrokers: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MaxMessageSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoMsgTypes: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MsgDirection: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoTradingSessions: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotalVolumeTraded: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DiscretionInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DiscretionOffset: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ClientBidID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotalNumSecurities: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NumTickets: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SideValue1: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SideValue2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoBidDescriptors: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidDescriptorType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidDescriptor: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SideValueInd: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LiquidityPctLow: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LiquidityPctHigh: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LiquidityValue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EFPTrackingError: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::FairValue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OutsideIndexPct: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ValueOfFutures: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LiquidityIndType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::WtAverageLiquidity: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExchangeForPhysical: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OutMainCntryUIndex: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CrossPercent: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ProgRptReqs: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ProgPeriodInterval: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IncTaxInd: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NumBidders: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BasisPxType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoBidComponents: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Country: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotNoStrikes: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DayOrderQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DayCumQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DayAvgPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::GTBookingInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoStrikes: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListStatusType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NetGrossInd: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListOrderStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExpireDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListExecInstType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CxlRejResponseTo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingCouponRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingContractMultiplier: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContraTradeQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContraTradeTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LiquidityNumSecurities: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MultiLegReportingType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::StrikeTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ListStatusText: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedListStatusTextLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedListStatusText: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PartyIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PartyID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotalVolumeTradedDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotalVolumeTradedTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NetChgPrevDay: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PartyRole: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityAltID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityAltIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoUnderlyingSecurityAltID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityAltID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingSecurityAltIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingProduct: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingCFICode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TestMessageIndicator: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuantityType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::IndividualAllocID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RoundingDirection: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RoundingModulus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoRegistDtls: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MailingDtls: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::InvestorCountryOfResidence: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PaymentRef: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DistribPaymentMethod: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashDistribCurr: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CommCurrency: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CancellationRights: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MoneyLaunderingStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MailingInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TransBkdTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecPriceType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecPriceAdjustment: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DateOfBirth: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeReportTransType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CardHolderName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CardNumber: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CardExpDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CardIssNo: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PaymentMethod: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistAcctType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Designation: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TaxAdvantageType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistRejReasonText: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::FundRenewWaiv: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashDistribAgentName: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashDistribAgentCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashDistribAgentAcctNumber: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashDistribPayRef: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CardStartDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PaymentDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PaymentRemitterID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistRejReasonCode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistDetls: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoDistribInsts: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistEmail: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DistribPercentage: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RegistTransType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ExecValuationPoint: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrderPercent: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OwnershipType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoContAmts: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContAmtType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContAmtValue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContAmtCurr: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OwnerType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PartySubID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NestedPartyID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NestedPartyIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecondaryClOrdID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecondaryExecID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrderCapacity: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrderRestrictions: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MassCancelRequestType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MassCancelResponse: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MassCancelRejectReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotalAffectedOrders: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoAffectedOrders: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AffectedOrderID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AffectedSecondaryOrderID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NestedPartyRole: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoNestedPartyIDs: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingMaturityDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CashMargin: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NestedPartySubID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Scope: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MDImplicitDelete: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CrossID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CrossType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CrossPrioritization: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrigCrossID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoSides: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Username: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Password: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoLegs: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCurrency: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TotalNumSecurityTypes: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoSecurityTypes: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityListRequestType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SecurityRequestResult: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RoundLot: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MinTradeVol: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MultiLegRptTypeReq: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegPositionEffect: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCoveredOrUncovered: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegPrice: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradSesStatusRejReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeRequestID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeRequestType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PreviouslyReported: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeReportID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeReportRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MatchStatus: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MatchType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OddLot: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoClearingInstructions: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ClearingInstruction: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeInputSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::TradeInputDevice: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoDates: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::AccountType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::CustOrderCapacity: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ClOrdLinkID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MassStatusReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MassStatusReqType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OrigOrdModTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSettlmntTyp: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegFutSettDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::DayBookingInst: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BookingUnit: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PreallocMethod: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingCountryOfIssue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingStateOrProvinceOfIssue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingLocaleOfIssue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingInstrRegistry: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCountryOfIssue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegStateOrProvinceOfIssue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegLocaleOfIssue: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegInstrRegistry: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSymbol: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSymbolSfx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoLegSecurityAltID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityAltID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityAltIDSource: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegProduct: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCFICode: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityType: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegMaturityMonthYear: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegMaturityDate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegStrikePrice: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegOptAttribute: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegContractMultiplier: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegCouponRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityExchange: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegIssuer: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedLegIssuerLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedLegIssuer: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSecurityDesc: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedLegSecurityDescLen: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::EncodedLegSecurityDesc: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegRatioQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegSide: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::NoHops: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HopCompID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HopSendingTime: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::HopRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MidPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidYield: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MidYield: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OfferYield: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ClearingFeeIndicator: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::WorkingIndicator: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegLastPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PriorityIndicator: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::PriceImprovement: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::Price2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LastForwardPoints2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::BidForwardPoints2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::OfferForwardPoints2: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::RFQReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MktBidPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MktOfferPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MinBidSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::MinOfferSize: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteStatusReqID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingLastPx: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::UnderlyingLastQty: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::LegRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::ContraLegRefID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlCurrBidFxRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SettlCurrOfferFxRate: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::QuoteRequestRejectReason: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			case field_id::SideComplianceID: return FF_FIX_PARSE_ERR(UNEXPECTED_FIELD, tag);
			default: return FF_FIX_PARSE_ERR(UNKNOWN_FIELD_ID, tag);
			}
		}
	}

	return FF_OK();
}

FFStatus Allocation::toString(falconfix::FastBuffer &out, bool includeMilliseconds) const noexcept {
	static constexpr std::string_view HDR = "8=FIX4.3\x01""9=000000\x01""35=J\x01";
	static constexpr std::size_t HDR_BL_POS = 11;
	static constexpr std::size_t HDR_CALC_OFFSET = 18;

	out.clear();
	if (!out.reserve_noexcept(compute_buffer_size())) [[unlikely]] {
		return FF_SYS_ERR(BAD_ALLOC);
	}

	char *p = out.data();
	std::memcpy(p, HDR.data(), HDR.size());
	p += HDR.size();
	if ((p = m_Header.encode(p, includeMilliseconds)) == nullptr) {
		return FF_FIX_VALIDATION_ERR(COMPONENT_VALIDATION_FAILED, field_id::BeginString);
	}

	if (hasAllocID()) { WRITE_TAG3(fix43::tag_const::AllocID); std::memcpy(p, m_AllocID.data(), m_AllocID.size()); p += m_AllocID.size(); *p++ = fix43::serialize::SOH; }
	if (hasAllocTransType()) { WRITE_TAG3(fix43::tag_const::AllocTransType); *p++ = m_AllocTransType; *p++ = fix43::serialize::SOH; }
	if (hasAllocType()) { WRITE_TAG4(fix43::tag_const::AllocType); p += falconfix::itoa(m_AllocType, p); *p++ = fix43::serialize::SOH; }
	if (hasRefAllocID()) { WRITE_TAG3(fix43::tag_const::RefAllocID); std::memcpy(p, m_RefAllocID.data(), m_RefAllocID.size()); p += m_RefAllocID.size(); *p++ = fix43::serialize::SOH; }
	if (hasAllocLinkID()) { WRITE_TAG4(fix43::tag_const::AllocLinkID); std::memcpy(p, m_AllocLinkID.data(), m_AllocLinkID.size()); p += m_AllocLinkID.size(); *p++ = fix43::serialize::SOH; }
	if (hasAllocLinkType()) { WRITE_TAG4(fix43::tag_const::AllocLinkType); p += falconfix::itoa(m_AllocLinkType, p); *p++ = fix43::serialize::SOH; }
	if (hasBookingRefID()) { WRITE_TAG4(fix43::tag_const::BookingRefID); std::memcpy(p, m_BookingRefID.data(), m_BookingRefID.size()); p += m_BookingRefID.size(); *p++ = fix43::serialize::SOH; }
	if (!m_NoOrdersGroup.empty()) {
		WRITE_TAG3(fix43::tag_const::NoOrders);
		p += falconfix::itoa(static_cast<int64_t>(m_NoOrdersGroup.size()), p);
		*p++ = fix43::serialize::SOH;
		for (const auto &entry : m_NoOrdersGroup) {
			p = entry.encode(p, includeMilliseconds);
		}
	}
	if (!m_NoExecsGroup.empty()) {
		WRITE_TAG4(fix43::tag_const::NoExecs);
		p += falconfix::itoa(static_cast<int64_t>(m_NoExecsGroup.size()), p);
		*p++ = fix43::serialize::SOH;
		for (const auto &entry : m_NoExecsGroup) {
			p = entry.encode(p, includeMilliseconds);
		}
	}
	if (hasSide()) { WRITE_TAG3(fix43::tag_const::Side); *p++ = m_Side; *p++ = fix43::serialize::SOH; }
	if ((p = m_Instrument.encode(p, includeMilliseconds)) == nullptr) {
		return FF_FIX_VALIDATION_ERR(COMPONENT_VALIDATION_FAILED, 0);
	}
	if (hasQuantity()) { WRITE_TAG3(fix43::tag_const::Quantity); p += falconfix::dtoa(m_Quantity, p); *p++ = fix43::serialize::SOH; }
	if (hasLastMkt()) { WRITE_TAG3(fix43::tag_const::LastMkt); std::memcpy(p, m_LastMkt.data(), m_LastMkt.size()); p += m_LastMkt.size(); *p++ = fix43::serialize::SOH; }
	if (hasTradeOriginationDate()) { WRITE_TAG4(fix43::tag_const::TradeOriginationDate); std::memcpy(p, m_TradeOriginationDate.data(), m_TradeOriginationDate.size()); p += m_TradeOriginationDate.size(); *p++ = fix43::serialize::SOH; }
	if (hasTradingSessionID()) { WRITE_TAG4(fix43::tag_const::TradingSessionID); std::memcpy(p, m_TradingSessionID.data(), m_TradingSessionID.size()); p += m_TradingSessionID.size(); *p++ = fix43::serialize::SOH; }
	if (hasTradingSessionSubID()) { WRITE_TAG4(fix43::tag_const::TradingSessionSubID); std::memcpy(p, m_TradingSessionSubID.data(), m_TradingSessionSubID.size()); p += m_TradingSessionSubID.size(); *p++ = fix43::serialize::SOH; }
	if (hasPriceType()) { WRITE_TAG4(fix43::tag_const::PriceType); p += falconfix::itoa(m_PriceType, p); *p++ = fix43::serialize::SOH; }
	if (hasAvgPx()) { WRITE_TAG2(fix43::tag_const::AvgPx); p += falconfix::dtoa(m_AvgPx, p); *p++ = fix43::serialize::SOH; }
	if (hasCurrency()) { WRITE_TAG3(fix43::tag_const::Currency); std::memcpy(p, m_Currency.data(), m_Currency.size()); p += m_Currency.size(); *p++ = fix43::serialize::SOH; }
	if (hasAvgPrxPrecision()) { WRITE_TAG3(fix43::tag_const::AvgPrxPrecision); p += falconfix::itoa(m_AvgPrxPrecision, p); *p++ = fix43::serialize::SOH; }
	if ((p = m_Parties.encode(p, includeMilliseconds)) == nullptr) {
		return FF_FIX_VALIDATION_ERR(COMPONENT_VALIDATION_FAILED, 0);
	}
	if (hasTradeDate()) { WRITE_TAG3(fix43::tag_const::TradeDate); p += fix43::datetime::format_UTCDateOnly(m_TradeDate, p); *p++ = fix43::serialize::SOH; }
	if (hasTransactTime()) { WRITE_TAG3(fix43::tag_const::TransactTime); p += fix43::datetime::format_UTCTimestamp_compact(m_TransactTime, p, includeMilliseconds); *p++ = fix43::serialize::SOH; }
	if (hasSettlmntTyp()) { WRITE_TAG3(fix43::tag_const::SettlmntTyp); *p++ = m_SettlmntTyp; *p++ = fix43::serialize::SOH; }
	if (hasFutSettDate()) { WRITE_TAG3(fix43::tag_const::FutSettDate); p += fix43::datetime::format_UTCDateOnly(m_FutSettDate, p); *p++ = fix43::serialize::SOH; }
	if (hasGrossTradeAmt()) { WRITE_TAG4(fix43::tag_const::GrossTradeAmt); p += falconfix::dtoa(m_GrossTradeAmt, p); *p++ = fix43::serialize::SOH; }
	if (hasConcession()) { WRITE_TAG4(fix43::tag_const::Concession); p += falconfix::dtoa(m_Concession, p); *p++ = fix43::serialize::SOH; }
	if (hasTotalTakedown()) { WRITE_TAG4(fix43::tag_const::TotalTakedown); p += falconfix::dtoa(m_TotalTakedown, p); *p++ = fix43::serialize::SOH; }
	if (hasNetMoney()) { WRITE_TAG4(fix43::tag_const::NetMoney); p += falconfix::dtoa(m_NetMoney, p); *p++ = fix43::serialize::SOH; }
	if (hasPositionEffect()) { WRITE_TAG3(fix43::tag_const::PositionEffect); *p++ = m_PositionEffect; *p++ = fix43::serialize::SOH; }
	if (hasText()) { WRITE_TAG3(fix43::tag_const::Text); std::memcpy(p, m_Text.data(), m_Text.size()); p += m_Text.size(); *p++ = fix43::serialize::SOH; }
	if (hasEncodedTextLen()) { WRITE_TAG4(fix43::tag_const::EncodedTextLen); p += falconfix::itoa(m_EncodedTextLen, p); *p++ = fix43::serialize::SOH; }
	if (hasEncodedText()) { WRITE_TAG4(fix43::tag_const::EncodedText); std::memcpy(p, m_EncodedText.data(), m_EncodedText.size()); p += m_EncodedText.size(); *p++ = fix43::serialize::SOH; }
	if (hasNumDaysInterest()) { WRITE_TAG4(fix43::tag_const::NumDaysInterest); p += falconfix::itoa(m_NumDaysInterest, p); *p++ = fix43::serialize::SOH; }
	if (hasAccruedInterestRate()) { WRITE_TAG4(fix43::tag_const::AccruedInterestRate); p += falconfix::dtoa(m_AccruedInterestRate, p); *p++ = fix43::serialize::SOH; }
	if (hasTotalAccruedInterestAmt()) { WRITE_TAG4(fix43::tag_const::TotalAccruedInterestAmt); p += falconfix::dtoa(m_TotalAccruedInterestAmt, p); *p++ = fix43::serialize::SOH; }
	if (hasLegalConfirm()) { WRITE_TAG4(fix43::tag_const::LegalConfirm); *p++ = m_LegalConfirm ? 'Y' : 'N'; *p++ = fix43::serialize::SOH; }
	if (!m_NoAllocsGroup.empty()) {
		WRITE_TAG3(fix43::tag_const::NoAllocs);
		p += falconfix::itoa(static_cast<int64_t>(m_NoAllocsGroup.size()), p);
		*p++ = fix43::serialize::SOH;
		for (const auto &entry : m_NoAllocsGroup) {
			p = entry.encode(p, includeMilliseconds);
		}
	}

	if ((p = m_Trailer.encode(p, includeMilliseconds)) == nullptr) {
		return FF_FIX_VALIDATION_ERR(COMPONENT_VALIDATION_FAILED, field_id::SignatureLength);
	}

	const std::size_t msg_len_no_checksum = static_cast<std::size_t>(p - out.data());
	const std::size_t body_len = msg_len_no_checksum - HDR_CALC_OFFSET;

	char *digits = out.data() + HDR_BL_POS;
	digits[0] = '0' + ((body_len / 100000) % 10);
	digits[1] = '0' + ((body_len / 10000 ) % 10);
	digits[2] = '0' + ((body_len / 1000  ) % 10);
	digits[3] = '0' + ((body_len / 100   ) % 10);
	digits[4] = '0' + ((body_len / 10    ) % 10);
	digits[5] = '0' +  (body_len           % 10);

	std::uint32_t cksum = 0;
	for (const char *it = out.data(); it != out.data() + msg_len_no_checksum; ++it) {
		cksum += static_cast<unsigned char>(*it);
	}
	cksum &= 0xFF;

	*p++ = '1'; *p++ = '0'; *p++ = '=';
	*p++ = char('0' + (cksum / 100));
	*p++ = char('0' + ((cksum / 10) % 10));
	*p++ = char('0' + (cksum % 10));
	*p++ = fix43::serialize::SOH;
	out.commit(static_cast<std::size_t>(p - out.data()));
	return FF_OK();
}

bool Allocation::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::AllocID: setAllocID({begin, len}); return true;
	case field_id::AllocTransType: setAllocTransType(fix43::parser::parse_char(begin, end)); return true;
	case field_id::AllocType: setAllocType(falconfix::atoi(begin, end)); return true;
	case field_id::RefAllocID: setRefAllocID({begin, len}); return true;
	case field_id::AllocLinkID: setAllocLinkID({begin, len}); return true;
	case field_id::AllocLinkType: setAllocLinkType(falconfix::atoi(begin, end)); return true;
	case field_id::BookingRefID: setBookingRefID({begin, len}); return true;
	case field_id::Side: setSide(fix43::parser::parse_char(begin, end)); return true;
	case field_id::Quantity: setQuantity(fix43::parser::parse_double(begin, end)); return true;
	case field_id::LastMkt: setLastMkt({begin, len}); return true;
	case field_id::TradeOriginationDate: setTradeOriginationDate({begin, len}); return true;
	case field_id::TradingSessionID: setTradingSessionID({begin, len}); return true;
	case field_id::TradingSessionSubID: setTradingSessionSubID({begin, len}); return true;
	case field_id::PriceType: setPriceType(falconfix::atoi(begin, end)); return true;
	case field_id::AvgPx: setAvgPx(fix43::parser::parse_double(begin, end)); return true;
	case field_id::Currency: setCurrency({begin, len}); return true;
	case field_id::AvgPrxPrecision: setAvgPrxPrecision(falconfix::atoi(begin, end)); return true;
	case field_id::TradeDate: setTradeDate(fix43::parser::parse_date32(begin, end)); return true;
	case field_id::TransactTime: setTransactTime(falconfix::atoi(begin, end)); return true;
	case field_id::SettlmntTyp: setSettlmntTyp(fix43::parser::parse_char(begin, end)); return true;
	case field_id::FutSettDate: setFutSettDate(fix43::parser::parse_date32(begin, end)); return true;
	case field_id::GrossTradeAmt: setGrossTradeAmt(fix43::parser::parse_double(begin, end)); return true;
	case field_id::Concession: setConcession(fix43::parser::parse_double(begin, end)); return true;
	case field_id::TotalTakedown: setTotalTakedown(fix43::parser::parse_double(begin, end)); return true;
	case field_id::NetMoney: setNetMoney(fix43::parser::parse_double(begin, end)); return true;
	case field_id::PositionEffect: setPositionEffect(fix43::parser::parse_char(begin, end)); return true;
	case field_id::Text: setText({begin, len}); return true;
	case field_id::EncodedTextLen: setEncodedTextLen(falconfix::atoi(begin, end)); return true;
	case field_id::EncodedText: setEncodedText({begin, len}); return true;
	case field_id::NumDaysInterest: setNumDaysInterest(falconfix::atoi(begin, end)); return true;
	case field_id::AccruedInterestRate: setAccruedInterestRate(fix43::parser::parse_double(begin, end)); return true;
	case field_id::TotalAccruedInterestAmt: setTotalAccruedInterestAmt(fix43::parser::parse_double(begin, end)); return true;
	case field_id::LegalConfirm: setLegalConfirm(fix43::parser::parse_bool(begin, end)); return true;
	default: return false;
	}
}

} // namespace fix43::messages
