// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: a162b11d2446f674

#include <FIX4.4/components/ContraGrp.h>

#include <cstring>

#include <FIX4.4/utils/macros.h>
#include <FIX4.4/utils/parser.h>
#include <FIX4.4/utils/serializer.h>
#include <FIX4.4/utils/tag_constants.h>
#include <FIX4.4/utils/datetime.h>
#include <utils/string_utils.h>

namespace fix44::components {

void ContraGrp::NoContraBrokers::reset() noexcept {
	m_ContraBroker = fields::ContraBroker_NULL;
	m_ContraTrader = fields::ContraTrader_NULL;
	m_ContraTradeQty = fields::NULL_QTY;
	m_ContraTradeTime = fields::NULL_UTCTIMESTAMP;
	m_ContraLegRefID = fields::ContraLegRefID_NULL;
	m_presence = 0;
}

bool ContraGrp::NoContraBrokers::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool ContraGrp::NoContraBrokers::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (consumed && tag == field_id::ContraBroker) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix44::serialize::SOH) { ++p; }
		if (p >= end) { return false; }
		const char *valueEnd = p;
		++p;
		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			break;
		}
		consumed = true;
	}
	return consumed;
}

char *ContraGrp::NoContraBrokers::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasContraBroker()) { WRITE_TAG4(fix44::tag_const::ContraBroker); std::memcpy(p, m_ContraBroker.data(), m_ContraBroker.size()); p += m_ContraBroker.size(); *p++ = fix44::serialize::SOH; }
	if (hasContraTrader()) { WRITE_TAG4(fix44::tag_const::ContraTrader); std::memcpy(p, m_ContraTrader.data(), m_ContraTrader.size()); p += m_ContraTrader.size(); *p++ = fix44::serialize::SOH; }
	if (hasContraTradeQty()) { WRITE_TAG4(fix44::tag_const::ContraTradeQty); p += falconfix::dtoa(m_ContraTradeQty, p); *p++ = fix44::serialize::SOH; }
	if (hasContraTradeTime()) { WRITE_TAG4(fix44::tag_const::ContraTradeTime); p += fix44::datetime::format_UTCTimestamp_compact(m_ContraTradeTime, p, includeMilliseconds); *p++ = fix44::serialize::SOH; }
	if (hasContraLegRefID()) { WRITE_TAG4(fix44::tag_const::ContraLegRefID); std::memcpy(p, m_ContraLegRefID.data(), m_ContraLegRefID.size()); p += m_ContraLegRefID.size(); *p++ = fix44::serialize::SOH; }
	return p;
}

bool ContraGrp::NoContraBrokers::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::ContraBroker: setContraBroker({begin, len}); return true;
	case field_id::ContraTrader: setContraTrader({begin, len}); return true;
	case field_id::ContraTradeQty: setContraTradeQty(fix44::parser::parse_double(begin, end)); return true;
	case field_id::ContraTradeTime: setContraTradeTime(falconfix::atoi(begin, end)); return true;
	case field_id::ContraLegRefID: setContraLegRefID({begin, len}); return true;
	default: return false;
	}
}

void ContraGrp::reset() noexcept {
	m_NoContraBrokersGroup.clear();
	m_presence = 0;
}

bool ContraGrp::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	for (const auto &entry : m_NoContraBrokersGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

bool ContraGrp::decode(const char *&p, const char *end) noexcept {
	return decode(p, end, 0, false);
}

bool ContraGrp::decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (stop_on_repetition && consumed && tag == stop_tag) {
			p = tag_start;
			break;
		}
		switch (tag) {
		case field_id::NoContraBrokers: {
			++p;
			const char *valueBegin = p;
			while (p < end && *p != fix44::serialize::SOH) { ++p; }
			if (p >= end) { return false; }
			const char *valueEnd = p;
			++p;
			const int64_t count_i64 = falconfix::atoi(valueBegin, valueEnd);
			if (count_i64 < 0) { return false; }
			const std::size_t count = static_cast<std::size_t>(count_i64);
			m_NoContraBrokersGroup.clear();
			m_NoContraBrokersGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoContraBrokersGroup.emplace_back();
				if (!m_NoContraBrokersGroup.back().decode(p, end)) { return false; }
			}
			consumed = true;
			continue;
		}
		default:
			p = tag_start;
			return consumed;
		}
	}
	return consumed;
}

char *ContraGrp::encode(char *p, bool includeMilliseconds) const noexcept {
	if (!m_NoContraBrokersGroup.empty()) {
		WRITE_TAG4(fix44::tag_const::NoContraBrokers);
		p += falconfix::itoa(static_cast<int64_t>(m_NoContraBrokersGroup.size()), p);
		*p++ = fix44::serialize::SOH;
		for (const auto &entry : m_NoContraBrokersGroup) {
			if ((p = entry.encode(p, includeMilliseconds)) == nullptr) { return nullptr; }
		}
	}
	return p;
}

bool ContraGrp::setField(int32_t, const char *, const char *) noexcept {
	return false;
}

} // namespace fix44::components
