// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 4f1b773ec8d7f6d1

#include <FIX4.4/components/InstrmtGrp.h>

#include <cstring>

#include <FIX4.4/utils/macros.h>
#include <FIX4.4/utils/parser.h>
#include <FIX4.4/utils/serializer.h>
#include <FIX4.4/utils/tag_constants.h>
#include <FIX4.4/utils/datetime.h>
#include <utils/string_utils.h>

namespace fix44::components {

void InstrmtGrp::NoRelatedSym::reset() noexcept {
	m_Instrument.reset();
	m_presence = 0;
}

bool InstrmtGrp::NoRelatedSym::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}

	return (!m_Instrument.hasAnySet() || m_Instrument.checkRequired());
}

bool InstrmtGrp::NoRelatedSym::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (consumed && tag == field_id::Symbol) {
			p = tag_start;
			break;
		}
		switch (tag) {
		case field_id::Symbol:
			p = tag_start;
			if (!m_Instrument.decode(p, end, field_id::Symbol, true)) { return false; }
			consumed = true;
			continue;
		default:
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix44::serialize::SOH) { ++p; }
		if (p >= end) { return false; }
		const char *valueEnd = p;
		++p;
		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			break;
		}
		consumed = true;
	}
	return consumed;
}

char *InstrmtGrp::NoRelatedSym::encode(char *p, bool includeMilliseconds) const noexcept {
	if ((p = m_Instrument.encode(p, includeMilliseconds)) == nullptr) { return nullptr; }
	return p;
}

bool InstrmtGrp::NoRelatedSym::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	default: return false;
	}
}

void InstrmtGrp::reset() noexcept {
	m_NoRelatedSymGroup.clear();
	m_presence = 0;
}

bool InstrmtGrp::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	for (const auto &entry : m_NoRelatedSymGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

bool InstrmtGrp::decode(const char *&p, const char *end) noexcept {
	return decode(p, end, 0, false);
}

bool InstrmtGrp::decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (stop_on_repetition && consumed && tag == stop_tag) {
			p = tag_start;
			break;
		}
		switch (tag) {
		case field_id::NoRelatedSym: {
			++p;
			const char *valueBegin = p;
			while (p < end && *p != fix44::serialize::SOH) { ++p; }
			if (p >= end) { return false; }
			const char *valueEnd = p;
			++p;
			const int64_t count_i64 = falconfix::atoi(valueBegin, valueEnd);
			if (count_i64 < 0) { return false; }
			const std::size_t count = static_cast<std::size_t>(count_i64);
			m_NoRelatedSymGroup.clear();
			m_NoRelatedSymGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoRelatedSymGroup.emplace_back();
				if (!m_NoRelatedSymGroup.back().decode(p, end)) { return false; }
			}
			consumed = true;
			continue;
		}
		default:
			p = tag_start;
			return consumed;
		}
	}
	return consumed;
}

char *InstrmtGrp::encode(char *p, bool includeMilliseconds) const noexcept {
	if (!m_NoRelatedSymGroup.empty()) {
		WRITE_TAG4(fix44::tag_const::NoRelatedSym);
		p += falconfix::itoa(static_cast<int64_t>(m_NoRelatedSymGroup.size()), p);
		*p++ = fix44::serialize::SOH;
		for (const auto &entry : m_NoRelatedSymGroup) {
			if ((p = entry.encode(p, includeMilliseconds)) == nullptr) { return nullptr; }
		}
	}
	return p;
}

bool InstrmtGrp::setField(int32_t, const char *, const char *) noexcept {
	return false;
}

} // namespace fix44::components
