// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 01e5ef2281648f1e

#include <FIX4.4/components/PositionAmountData.h>

#include <cstring>

#include <FIX4.4/utils/macros.h>
#include <FIX4.4/utils/parser.h>
#include <FIX4.4/utils/serializer.h>
#include <FIX4.4/utils/tag_constants.h>
#include <FIX4.4/utils/datetime.h>
#include <utils/string_utils.h>

namespace fix44::components {

void PositionAmountData::NoPosAmt::reset() noexcept {
	m_PosAmtType = fields::PosAmtType_NULL;
	m_PosAmt = fields::NULL_AMT;
	m_presence = 0;
}

bool PositionAmountData::NoPosAmt::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool PositionAmountData::NoPosAmt::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (consumed && tag == field_id::PosAmtType) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix44::serialize::SOH) { ++p; }
		if (p >= end) { return false; }
		const char *valueEnd = p;
		++p;
		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			break;
		}
		consumed = true;
	}
	return consumed;
}

char *PositionAmountData::NoPosAmt::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasPosAmtType()) { WRITE_TAG4(fix44::tag_const::PosAmtType); std::memcpy(p, m_PosAmtType.data(), m_PosAmtType.size()); p += m_PosAmtType.size(); *p++ = fix44::serialize::SOH; }
	if (hasPosAmt()) { WRITE_TAG4(fix44::tag_const::PosAmt); p += falconfix::dtoa(m_PosAmt, p); *p++ = fix44::serialize::SOH; }
	return p;
}

bool PositionAmountData::NoPosAmt::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::PosAmtType: setPosAmtType({begin, len}); return true;
	case field_id::PosAmt: setPosAmt(fix44::parser::parse_double(begin, end)); return true;
	default: return false;
	}
}

void PositionAmountData::reset() noexcept {
	m_NoPosAmtGroup.clear();
	m_presence = 0;
}

bool PositionAmountData::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	for (const auto &entry : m_NoPosAmtGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

bool PositionAmountData::decode(const char *&p, const char *end) noexcept {
	return decode(p, end, 0, false);
}

bool PositionAmountData::decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (stop_on_repetition && consumed && tag == stop_tag) {
			p = tag_start;
			break;
		}
		switch (tag) {
		case field_id::NoPosAmt: {
			++p;
			const char *valueBegin = p;
			while (p < end && *p != fix44::serialize::SOH) { ++p; }
			if (p >= end) { return false; }
			const char *valueEnd = p;
			++p;
			const int64_t count_i64 = falconfix::atoi(valueBegin, valueEnd);
			if (count_i64 < 0) { return false; }
			const std::size_t count = static_cast<std::size_t>(count_i64);
			m_NoPosAmtGroup.clear();
			m_NoPosAmtGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoPosAmtGroup.emplace_back();
				if (!m_NoPosAmtGroup.back().decode(p, end)) { return false; }
			}
			consumed = true;
			continue;
		}
		default:
			p = tag_start;
			return consumed;
		}
	}
	return consumed;
}

char *PositionAmountData::encode(char *p, bool includeMilliseconds) const noexcept {
	if (!m_NoPosAmtGroup.empty()) {
		WRITE_TAG4(fix44::tag_const::NoPosAmt);
		p += falconfix::itoa(static_cast<int64_t>(m_NoPosAmtGroup.size()), p);
		*p++ = fix44::serialize::SOH;
		for (const auto &entry : m_NoPosAmtGroup) {
			if ((p = entry.encode(p, includeMilliseconds)) == nullptr) { return nullptr; }
		}
	}
	return p;
}

bool PositionAmountData::setField(int32_t, const char *, const char *) noexcept {
	return false;
}

} // namespace fix44::components
