// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: f36789ec36830d06

#include <FIX4.4/components/QuotQualGrp.h>

#include <cstring>

#include <FIX4.4/utils/macros.h>
#include <FIX4.4/utils/parser.h>
#include <FIX4.4/utils/serializer.h>
#include <FIX4.4/utils/tag_constants.h>
#include <FIX4.4/utils/datetime.h>
#include <utils/string_utils.h>

namespace fix44::components {

void QuotQualGrp::NoQuoteQualifiers::reset() noexcept {
	m_QuoteQualifier = fields::NULL_CHAR;
	m_presence = 0;
}

bool QuotQualGrp::NoQuoteQualifiers::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool QuotQualGrp::NoQuoteQualifiers::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (consumed && tag == field_id::QuoteQualifier) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix44::serialize::SOH) { ++p; }
		if (p >= end) { return false; }
		const char *valueEnd = p;
		++p;
		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			break;
		}
		consumed = true;
	}
	return consumed;
}

char *QuotQualGrp::NoQuoteQualifiers::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasQuoteQualifier()) { WRITE_TAG4(fix44::tag_const::QuoteQualifier); *p++ = m_QuoteQualifier; *p++ = fix44::serialize::SOH; }
	return p;
}

bool QuotQualGrp::NoQuoteQualifiers::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::QuoteQualifier: setQuoteQualifier(fix44::parser::parse_char(begin, end)); return true;
	default: return false;
	}
}

void QuotQualGrp::reset() noexcept {
	m_NoQuoteQualifiersGroup.clear();
	m_presence = 0;
}

bool QuotQualGrp::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	for (const auto &entry : m_NoQuoteQualifiersGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

bool QuotQualGrp::decode(const char *&p, const char *end) noexcept {
	return decode(p, end, 0, false);
}

bool QuotQualGrp::decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (stop_on_repetition && consumed && tag == stop_tag) {
			p = tag_start;
			break;
		}
		switch (tag) {
		case field_id::NoQuoteQualifiers: {
			++p;
			const char *valueBegin = p;
			while (p < end && *p != fix44::serialize::SOH) { ++p; }
			if (p >= end) { return false; }
			const char *valueEnd = p;
			++p;
			const int64_t count_i64 = falconfix::atoi(valueBegin, valueEnd);
			if (count_i64 < 0) { return false; }
			const std::size_t count = static_cast<std::size_t>(count_i64);
			m_NoQuoteQualifiersGroup.clear();
			m_NoQuoteQualifiersGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoQuoteQualifiersGroup.emplace_back();
				if (!m_NoQuoteQualifiersGroup.back().decode(p, end)) { return false; }
			}
			consumed = true;
			continue;
		}
		default:
			p = tag_start;
			return consumed;
		}
	}
	return consumed;
}

char *QuotQualGrp::encode(char *p, bool includeMilliseconds) const noexcept {
	if (!m_NoQuoteQualifiersGroup.empty()) {
		WRITE_TAG4(fix44::tag_const::NoQuoteQualifiers);
		p += falconfix::itoa(static_cast<int64_t>(m_NoQuoteQualifiersGroup.size()), p);
		*p++ = fix44::serialize::SOH;
		for (const auto &entry : m_NoQuoteQualifiersGroup) {
			if ((p = entry.encode(p, includeMilliseconds)) == nullptr) { return nullptr; }
		}
	}
	return p;
}

bool QuotQualGrp::setField(int32_t, const char *, const char *) noexcept {
	return false;
}

} // namespace fix44::components
