// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: cf6d1b0e86685688

#include <FIX4.4/components/TrdRegTimestamps.h>

#include <cstring>

#include <FIX4.4/utils/macros.h>
#include <FIX4.4/utils/parser.h>
#include <FIX4.4/utils/serializer.h>
#include <FIX4.4/utils/tag_constants.h>
#include <FIX4.4/utils/datetime.h>
#include <utils/string_utils.h>

namespace fix44::components {

void TrdRegTimestamps::NoTrdRegTimestamps::reset() noexcept {
	m_TrdRegTimestamp = fields::NULL_UTCTIMESTAMP;
	m_TrdRegTimestampType = fields::NULL_INT;
	m_TrdRegTimestampOrigin = fields::TrdRegTimestampOrigin_NULL;
	m_presence = 0;
}

bool TrdRegTimestamps::NoTrdRegTimestamps::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	return true;
}

bool TrdRegTimestamps::NoTrdRegTimestamps::decode(const char *&p, const char *end) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (consumed && tag == field_id::TrdRegTimestamp) {
			p = tag_start;
			break;
		}
		++p;
		const char *valueBegin = p;
		while (p < end && *p != fix44::serialize::SOH) { ++p; }
		if (p >= end) { return false; }
		const char *valueEnd = p;
		++p;
		if (!setField(tag, valueBegin, valueEnd)) {
			p = tag_start;
			break;
		}
		consumed = true;
	}
	return consumed;
}

char *TrdRegTimestamps::NoTrdRegTimestamps::encode(char *p, bool includeMilliseconds) const noexcept {
	if (hasTrdRegTimestamp()) { WRITE_TAG4(fix44::tag_const::TrdRegTimestamp); p += fix44::datetime::format_UTCTimestamp_compact(m_TrdRegTimestamp, p, includeMilliseconds); *p++ = fix44::serialize::SOH; }
	if (hasTrdRegTimestampType()) { WRITE_TAG4(fix44::tag_const::TrdRegTimestampType); p += falconfix::itoa(m_TrdRegTimestampType, p); *p++ = fix44::serialize::SOH; }
	if (hasTrdRegTimestampOrigin()) { WRITE_TAG4(fix44::tag_const::TrdRegTimestampOrigin); std::memcpy(p, m_TrdRegTimestampOrigin.data(), m_TrdRegTimestampOrigin.size()); p += m_TrdRegTimestampOrigin.size(); *p++ = fix44::serialize::SOH; }
	return p;
}

bool TrdRegTimestamps::NoTrdRegTimestamps::setField(int32_t tag, const char *begin, const char *end) noexcept {
	const std::size_t len = static_cast<std::size_t>(end - begin);

	switch (tag) {
	case field_id::TrdRegTimestamp: setTrdRegTimestamp(falconfix::atoi(begin, end)); return true;
	case field_id::TrdRegTimestampType: setTrdRegTimestampType(falconfix::atoi(begin, end)); return true;
	case field_id::TrdRegTimestampOrigin: setTrdRegTimestampOrigin({begin, len}); return true;
	default: return false;
	}
}

void TrdRegTimestamps::reset() noexcept {
	m_NoTrdRegTimestampsGroup.clear();
	m_presence = 0;
}

bool TrdRegTimestamps::checkRequired() const noexcept {
	if ((m_presence & REQUIRED) != REQUIRED) {
		return false;
	}
	for (const auto &entry : m_NoTrdRegTimestampsGroup) {
		if (!entry.checkRequired()) {
			return false;
		}
	}
	return true;
}

bool TrdRegTimestamps::decode(const char *&p, const char *end) noexcept {
	return decode(p, end, 0, false);
}

bool TrdRegTimestamps::decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept {
	bool consumed = false;
	while (p < end) {
		const char *tag_start = p;
		int32_t tag = 0;
		while (p < end && *p != '=') {
			const unsigned d = static_cast<unsigned>(*p - '0');
			if (d > 9) { return false; }
			tag = tag * 10 + static_cast<int32_t>(d);
			++p;
		}
		if (p >= end) { return false; }
		if (stop_on_repetition && consumed && tag == stop_tag) {
			p = tag_start;
			break;
		}
		switch (tag) {
		case field_id::NoTrdRegTimestamps: {
			++p;
			const char *valueBegin = p;
			while (p < end && *p != fix44::serialize::SOH) { ++p; }
			if (p >= end) { return false; }
			const char *valueEnd = p;
			++p;
			const int64_t count_i64 = falconfix::atoi(valueBegin, valueEnd);
			if (count_i64 < 0) { return false; }
			const std::size_t count = static_cast<std::size_t>(count_i64);
			m_NoTrdRegTimestampsGroup.clear();
			m_NoTrdRegTimestampsGroup.reserve(count);
			for (std::size_t i = 0; i < count; ++i) {
				m_NoTrdRegTimestampsGroup.emplace_back();
				if (!m_NoTrdRegTimestampsGroup.back().decode(p, end)) { return false; }
			}
			consumed = true;
			continue;
		}
		default:
			p = tag_start;
			return consumed;
		}
	}
	return consumed;
}

char *TrdRegTimestamps::encode(char *p, bool includeMilliseconds) const noexcept {
	if (!m_NoTrdRegTimestampsGroup.empty()) {
		WRITE_TAG4(fix44::tag_const::NoTrdRegTimestamps);
		p += falconfix::itoa(static_cast<int64_t>(m_NoTrdRegTimestampsGroup.size()), p);
		*p++ = fix44::serialize::SOH;
		for (const auto &entry : m_NoTrdRegTimestampsGroup) {
			if ((p = entry.encode(p, includeMilliseconds)) == nullptr) { return nullptr; }
		}
	}
	return p;
}

bool TrdRegTimestamps::setField(int32_t, const char *, const char *) noexcept {
	return false;
}

} // namespace fix44::components
