# -*- coding: utf-8 -*-

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo

"""
generator_engine.py
-------------------------------------------------------
Generate engine headers for version-specific protocol/session helpers.
"""

from pathlib import Path

from code.common import (
    open_generated_file,
    write_autogen_header,
    namespace_from_spec,
    normalize_version_string,
)
from code.generator_enums import safe_enum_name


def _build_context(spec: dict):
    ns = namespace_from_spec(spec)
    version = spec.get("fix_version") or spec.get("version")
    if not version:
        raise ValueError("spec is missing FIX version (expected 'fix_version' or 'version')")
    include_root = normalize_version_string(version)
    msgtype_members = {}
    session_reject_members = set()
    for field in spec.get("fields", []):
        if field.get("name") == "MsgType":
            for idx, value in enumerate(field.get("values", [])):
                enum_value = value.get("enum")
                if not enum_value:
                    continue
                msgtype_members[enum_value] = safe_enum_name(value.get("description"), idx)
        elif field.get("name") == "SessionRejectReason":
            for idx, value in enumerate(field.get("values", [])):
                session_reject_members.add(safe_enum_name(value.get("description"), idx))
    return ns, include_root, msgtype_members, session_reject_members


def _pick_session_reject_member(session_reject_members: set[str], *candidates: str) -> str:
    for candidate in candidates:
        if candidate in session_reject_members:
            return candidate
    if session_reject_members:
        return sorted(session_reject_members)[0]
    raise ValueError("SessionRejectReason enum is missing from spec")


def _protocol_version_number(include_root: str) -> int:
    if not include_root.startswith("FIX"):
        raise ValueError(f"unsupported FIX version format: {include_root}")
    parts = include_root[3:].split(".")
    if len(parts) != 2 or not all(part.isdigit() for part in parts):
        raise ValueError(f"unsupported FIX version format: {include_root}")
    return int(parts[0]) * 10 + int(parts[1])


def _protocol_version_enum(include_root: str) -> str:
    mapping = {
        "FIX4.0": "FIX40",
        "FIX4.1": "FIX41",
        "FIX4.2": "FIX42",
        "FIX4.3": "FIX43",
        "FIX4.4": "FIX44",
        "FIX5.0": "FIX50",
        "FIX5.0SP1": "FIX50SP1",
        "FIX5.0SP2": "FIX50SP2",
        "FIXT1.1": "FIXT11",
    }
    try:
        return mapping[include_root]
    except KeyError as exc:
        raise ValueError(f"unsupported FIX version format: {include_root}") from exc


def _write_protocol_header(out_path: Path, ns: str, include_root: str):
    protocol_version = _protocol_version_enum(include_root)

    with open_generated_file(out_path, encoding="utf-8") as fh:
        write_autogen_header(fh, f"{include_root} generated protocol constants")
        fh.write("#pragma once\n\n")
        fh.write("#include <string_view>\n\n")
        fh.write("#include <app/fix_message_ref.h>\n\n")
        fh.write(f"namespace {ns}::engine {{\n")
        fh.write("class Session;\n")
        fh.write("}\n\n")
        fh.write(f"namespace {ns} {{\n\n")
        fh.write("struct Protocol {\n")
        fh.write(f"\tstatic constexpr falconfix::ProtocolVersion VERSION = falconfix::ProtocolVersion::{protocol_version};\n")
        fh.write(f"\tstatic constexpr std::string_view BEGIN_STRING = \"{include_root}\";\n\n")
        fh.write(f"\tusing SessionType = {ns}::engine::Session;\n")
        fh.write("};\n\n")
        fh.write(f"}} // namespace {ns}\n")


def _write_session_header(out_path: Path, ns: str, include_root: str, session_reject_members: set[str]):
    protocol_version = _protocol_version_enum(include_root)
    invalid_tag_number = _pick_session_reject_member(session_reject_members, "INVALID_TAG_NUMBER")
    value_is_incorrect = _pick_session_reject_member(session_reject_members, "VALUE_IS_INCORRECT")
    tag_not_defined = _pick_session_reject_member(session_reject_members, "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE")
    duplicate_tag = _pick_session_reject_member(
        session_reject_members,
        "TAG_APPEARS_MORE_THAN_ONCE",
        "TAG_SPECIFIED_WITHOUT_A_VALUE",
        "UNDEFINED_TAG",
    )
    incorrect_data_format = _pick_session_reject_member(
        session_reject_members,
        "INCORRECT_DATA_FORMAT_FOR_VALUE",
        "VALUE_IS_INCORRECT",
    )
    other = _pick_session_reject_member(
        session_reject_members,
        "OTHER",
        "VALUE_IS_INCORRECT",
        "INVALID_TAG_NUMBER",
    )
    invalid_msg_type = _pick_session_reject_member(
        session_reject_members,
        "INVALID_MSGTYPE",
        "INVALID_MSG_TYPE",
    )
    required_tag_missing = _pick_session_reject_member(session_reject_members, "REQUIRED_TAG_MISSING")
    repeating_group_error = _pick_session_reject_member(
        session_reject_members,
        "INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP",
        "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE",
        "VALUE_IS_INCORRECT",
    )

    with open_generated_file(out_path, encoding="utf-8") as fh:
        write_autogen_header(fh, f"{include_root} generated session")
        fh.write("#pragma once\n\n")
        fh.write("#include <cassert>\n")
        fh.write("#include <memory>\n")
        fh.write("#include <mutex>\n")
        fh.write("#include <string>\n")
        fh.write("#include <string_view>\n\n")
        fh.write("#include <app/fix_application.h>\n")
        fh.write("#include <connection/i_connection.h>\n")
        fh.write("#include <logger/message_log.h>\n")
        fh.write("#include <session/session_base.h>\n")
        fh.write("#include <session/session_schedule.h>\n")
        fh.write("#include <session/session_settings.h>\n")
        fh.write("#include <session/session_state.h>\n")
        fh.write("#include <store/message_store.h>\n")
        fh.write("#include <store/null_message_store.h>\n")
        fh.write("#include <utils/fast_buffer.h>\n")
        fh.write("#include <utils/tick_clock.h>\n")
        fh.write("#include <utils/error_codes.h>\n\n")
        fh.write(f"#include <{include_root}/engine/outbound_prepare.h>\n")
        fh.write(f"#include <{include_root}/engine/tcp_frame_view.h>\n")
        fh.write(f"#include <{include_root}/messages/Heartbeat.h>\n")
        fh.write(f"#include <{include_root}/messages/Logon.h>\n")
        fh.write(f"#include <{include_root}/messages/Logout.h>\n")
        fh.write(f"#include <{include_root}/messages/Reject.h>\n")
        fh.write(f"#include <{include_root}/messages/BusinessMessageReject.h>\n")
        fh.write(f"#include <{include_root}/messages/ResendRequest.h>\n")
        fh.write(f"#include <{include_root}/messages/SequenceReset.h>\n")
        fh.write(f"#include <{include_root}/messages/TestRequest.h>\n\n")
        fh.write(f"namespace {ns}::engine {{\n\n")
        fh.write("enum class SeqNumState : uint8_t {\n")
        fh.write("    Expected,\n")
        fh.write("    Gap,\n")
        fh.write("    PossDupOld,\n")
        fh.write("    InvalidOld\n")
        fh.write("};\n\n")
        fh.write("[[nodiscard]] inline static SeqNumState classifySeqNum(int64_t msgSeqNum,\n")
        fh.write("                                                int64_t expectedSeqNum,\n")
        fh.write("                                                bool possDup) noexcept {\n")
        fh.write("    if (msgSeqNum == expectedSeqNum) { return SeqNumState::Expected; }\n")
        fh.write("    if (msgSeqNum > expectedSeqNum) {  return SeqNumState::Gap; }\n")
        fh.write("    return possDup ? SeqNumState::PossDupOld : SeqNumState::InvalidOld;\n")
        fh.write("}\n\n")
        fh.write(f"[[nodiscard]] inline static {ns}::enums::SessionRejectReason toSessionRejectReason(const FFStatus &rc) noexcept {{\n")
        fh.write("    namespace code = falconfix::errors::code;\n\n")
        fh.write("    switch (rc.code) {\n")
        fh.write("    case code::fix::parse::UNKNOWN_FIELD_ID:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{invalid_tag_number};\n\n")
        fh.write("    case code::fix::parse::INVALID_FIELD_VALUE:\n")
        fh.write("    case code::fix::validation::INVALID_FIELD_VALUE:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{value_is_incorrect};\n\n")
        fh.write("    case code::fix::parse::UNEXPECTED_FIELD:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{tag_not_defined};\n\n")
        fh.write("    case code::fix::parse::OUT_OF_RANGE:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{value_is_incorrect};\n\n")
        fh.write("    case code::fix::parse::DUPLICATE_TAG:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{duplicate_tag};\n\n")
        fh.write("    case code::fix::parse::MALFORMED_TAG:\n")
        fh.write("    case code::fix::parse::MISSING_EQUALS:\n")
        fh.write("    case code::fix::parse::MISSING_SOH:\n")
        fh.write("    case code::fix::parse::DECODE_FAILED:\n")
        fh.write("    case code::fix::parse::INVALID_LENGTH:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{incorrect_data_format};\n\n")
        fh.write("    case code::fix::parse::INVALID_CHECKSUM:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{other};\n\n")
        fh.write("    case code::fix::parse::INVALID_MESSAGE_TYPE:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{invalid_msg_type};\n\n")
        fh.write("    case code::fix::validation::MISSING_REQUIRED:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{required_tag_missing};\n\n")
        fh.write("    case code::fix::validation::REQUIRED_GROUP_EMPTY:\n")
        fh.write("    case code::fix::validation::GROUP_COUNT_MISMATCH:\n")
        fh.write("    case code::fix::validation::COMPONENT_VALIDATION_FAILED:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{repeating_group_error};\n\n")
        fh.write("    default:\n")
        fh.write(f"        return {ns}::enums::SessionRejectReason::{other};\n")
        fh.write("    }\n")
        fh.write("}\n\n")
        fh.write("class Session final : public falconfix::SessionBase {\n")
        fh.write("\tfalconfix::SessionID m_sid;\n")
        fh.write("\tfalconfix::FIXApplication &m_app;\n")
        fh.write("\tfalconfix::SessionConfig m_cfg;\n")
        fh.write("\tfalconfix::IConnection *m_connection{nullptr};\n")
        fh.write("\tstd::unique_ptr<falconfix::MessageLog> m_log;\n")
        fh.write("\tstd::unique_ptr<falconfix::MessageStore> m_store;\n")
        fh.write("\tfalconfix::SessionState m_state;\n")
        fh.write("\tfalconfix::FastBuffer m_out;\n")
        fh.write("\tfalconfix::FastBuffer m_in;\n")
        fh.write("\tstd::recursive_mutex m_mutex;\n\n")
        fh.write("\tstd::string m_sidText;\n\n")
        fh.write("public:\n")
        fh.write("\tSession(falconfix::FIXApplication &app,\n")
        fh.write("\t        const falconfix::SessionConfig &cfg,\n")
        fh.write("\t        std::unique_ptr<falconfix::MessageLog> log,\n")
        fh.write("\t        std::unique_ptr<falconfix::MessageStore> store);\n\n")
        fh.write("\tconst falconfix::SessionID &sessionID() const noexcept override { return m_sid;\t}\n")
        fh.write(f"\tfalconfix::ProtocolVersion protocolVersion() const noexcept override {{ return falconfix::ProtocolVersion::{protocol_version}; }}\n")
        fh.write("\tvoid bindConnection(falconfix::IConnection &connection) noexcept override { m_connection = &connection;\t}\n")
        fh.write("\t[[nodiscard]] falconfix::IConnection &connection() noexcept {\n")
        fh.write("\t\tassert(m_connection != nullptr);\n")
        fh.write("\t\treturn *m_connection;\n")
        fh.write("\t}\n\t\n")
        fh.write("\n")
        fh.write("\ttemplate<typename Msg>\n")
        fh.write("\tFFStatus send(Msg &msg) noexcept {\n")
        fh.write("\t\tstd::lock_guard<std::recursive_mutex> lock(m_mutex);\n\n")
        fh.write("\t\tconst int64_t seqNum = m_store->nextSenderSeqNum();\n\n")
        fh.write(f"\t\tFFStatus rc = {ns}::engine::prepareOutbound(msg, seqNum, m_sid);\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\tfalconfix::FIXMessageRef ref{\n")
        fh.write("\t\t\t.ptr = &msg,\n")
        fh.write("\t\t\t.msgType = Msg::MSGTYPE,\n")
        fh.write("\t\t\t.protocol = Msg::PROTOCOL\n")
        fh.write("\t\t};\n\n")
        fh.write("\t\trc = Msg::IS_ADMIN ? m_app.toAdmin(ref, m_sid) : m_app.toApp(ref, m_sid);\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\trc = msg.toString(m_out, m_cfg.connection.millisecondsInTimeStamp);\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\trc = connection().write(m_out.data(), m_out.size());\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\trc = m_store->storeOutgoing(seqNum, Msg::MSGTYPE, Msg::IS_ADMIN, {m_out.data(), m_out.size()});\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\tm_state.lastSentMs = falconfix::TickClock::getTickCount();\n\n")
        fh.write("\t\tm_log->outgoing(m_sidText, {m_out.data(), m_out.size()});\n\n")
        fh.write("\t\tm_store->incrNextSenderSeqNum();\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write("\tFFStatus doLogout(std::string_view reason = {}) noexcept override;\n")
        fh.write(f"\tFFStatus sendReject(int64_t refSeqNum, int32_t refTagID, std::string_view text, {ns}::enums::SessionRejectReason reason) noexcept;\n\n")
        fh.write("private:\n")
        fh.write("\tFFStatus onReceive(const char *data, std::size_t size) noexcept override;\n")
        fh.write("\tFFStatus onConnected() noexcept override;\n")
        fh.write("\tFFStatus onDisconnected() noexcept override;\n")
        fh.write("\tFFStatus onTimer() noexcept override;\n\n")
        fh.write("\tFFStatus sendLogon() noexcept;\n")
        fh.write("\tFFStatus sendLogout(std::string_view reason) noexcept;\n")
        fh.write("\tFFStatus sendHeartbeat() noexcept;\n")
        fh.write("\tFFStatus sendTestRequest() noexcept;\n\n")
        fh.write("\tFFStatus sendResendRequest(int64_t beginSeqNo, int64_t endSeqNo) noexcept;\n")
        fh.write("\tFFStatus sendSequenceResetGapFill(int64_t msgSeqNum, int64_t newSeqNo) noexcept;\n")
        fh.write("\tFFStatus sendBusinessReject(int64_t refSeqNum, std::string_view refMsgType, int32_t reason, std::string_view text) noexcept;\n")
        fh.write("\tFFStatus resendApplicationMessage(const falconfix::StoredMessageView &stored) noexcept;\n")
        fh.write("\tstatic bool buildPossDupReplay(std::string_view raw, std::string &out);\n\t\n")
        fh.write("\tFFStatus validateSessionIdentity(std::string_view beginString,\n")
        fh.write("\t                                 std::string_view senderCompID,\n")
        fh.write("\t                                 std::string_view targetCompID) noexcept;\n")
        fh.write("\tFFStatus validateSendingTime(int64_t sendingTimeMs) noexcept;\n")
        fh.write("\t[[nodiscard]] bool isDisconnected() const noexcept override { return m_state.status == falconfix::SessionStatus::Disconnected; }\n")
        fh.write("\t[[nodiscard]] bool isWithinSchedule(int64_t nowsecs = 0) const noexcept override;\n")
        fh.write("public:\n")
        fh.write(f"\tFFStatus handleLogonReceived(const {ns}::messages::Logon &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleLogoutReceived(const {ns}::messages::Logout &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleHeartbeatReceived(const {ns}::messages::Heartbeat &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleTestRequestReceived(const {ns}::messages::TestRequest &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleResendRequestReceived(const {ns}::messages::ResendRequest &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleRejectReceived(const {ns}::messages::Reject &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleBusinessMessageRejectReceived(const {ns}::messages::BusinessMessageReject &msg) noexcept;\n")
        fh.write(f"\tFFStatus handleSequenceResetReceived(const {ns}::messages::SequenceReset &msg) noexcept;\n")
        fh.write("\n#ifdef FALCONFIX_ENABLE_TEST_API\n")
        fh.write("\tFFStatus validateSessionIdentityForTest(std::string_view beginString,\n")
        fh.write("\t                                        std::string_view senderCompID,\n")
        fh.write("\t                                        std::string_view targetCompID) noexcept override;\n")
        fh.write("\tFFStatus validateSendingTimeForTest(int64_t sendingTimeMs) noexcept override;\n")
        fh.write("\tvoid setScheduleForTest(int64_t start, int64_t end) noexcept;\n\n")
        fh.write("\tvoid setNextSenderSeqNumForTest(int64_t seqNum) noexcept override;\n")
        fh.write("\tvoid setNextTargetSeqNumForTest(int64_t seqNum) noexcept override;\n")
        fh.write("\tint64_t nextSenderSeqNumForTest() const noexcept override;\n")
        fh.write("\tint64_t nextTargetSeqNumForTest() const noexcept override;\n")
        fh.write("\tvoid setAwaitingTestResponseForTest(bool awaiting, uint64_t testRequestID) noexcept override;\n")
        fh.write("\tbool awaitingTestResponseForTest() const noexcept override;\n")
        fh.write("\tuint64_t testRequestIDForTest() const noexcept override;\n")
        fh.write("#endif\n")
        fh.write("};\n\n")
        fh.write("std::unique_ptr<falconfix::SessionBase>\n")
        fh.write("makeSession(falconfix::FIXApplication &app,\n")
        fh.write("            const falconfix::SessionConfig &cfg,\n")
        fh.write("            std::unique_ptr<falconfix::MessageLog> log,\n")
        fh.write("            std::unique_ptr<falconfix::MessageStore> store);\n\n")
        fh.write(f"}} // namespace {ns}::engine\n")


def _write_session_cpp(out_path: Path, ns: str, include_root: str):
    with open_generated_file(out_path, encoding="utf-8") as fh:
        write_autogen_header(fh, f"{include_root} generated session implementation")
        fh.write(f"#include <{include_root}/engine/session.h>\n\n")
        fh.write("#include <utility>\n")
        fh.write("#include <vector>\n\n")
        fh.write(f"#include <{include_root}/engine/inbound_dispatch.h>\n")
        fh.write(f"#include <{include_root}/engine/tcp_frame_view.h>\n")
        fh.write(f"#include <{include_root}/utils/datetime.h>\n")
        fh.write(f"#include <{include_root}/utils/macros.h>\n")
        fh.write(f"#include <{include_root}/utils/serializer.h>\n")
        fh.write(f"#include <{include_root}/utils/tag_constants.h>\n\n")
        fh.write(f"namespace {ns}::engine {{\n\n")
        fh.write("Session::Session(falconfix::FIXApplication &app,\n")
        fh.write("                 const falconfix::SessionConfig &cfg,\n")
        fh.write("                 std::unique_ptr<falconfix::MessageLog> log,\n")
        fh.write("                 std::unique_ptr<falconfix::MessageStore> store)\n")
        fh.write("    : m_sid(cfg.sessionID),\n")
        fh.write("      m_app(app),\n")
        fh.write("      m_cfg(cfg),\n")
        fh.write("      m_log(std::move(log)),\n")
        fh.write("      m_store(std::move(store)) {\n")
        fh.write("\tm_sidText = m_sid.toString();\n\n")
        fh.write("\tif (!m_log) {\n")
        fh.write("\t\tm_log = std::make_unique<falconfix::NullMessageLog>();\n")
        fh.write("\t}\n")
        fh.write("\tif (!m_store) {\n")
        fh.write("\t\tm_store = std::make_unique<falconfix::NullMessageStore>();\n")
        fh.write("\t}\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::doLogout(std::string_view reason) noexcept {\n")
        fh.write("    std::lock_guard<std::recursive_mutex> lock(m_mutex);\n\n")
        fh.write("    if (m_state.closing() ||\n")
        fh.write("        m_state.status == falconfix::SessionStatus::Disconnected) {\n")
        fh.write("        return FF_OK();\n")
        fh.write("    }\n\n")
        fh.write("    if (m_state.awaitingResend) {\n")
        fh.write("        m_state.status = falconfix::SessionStatus::Closing;\n")
        fh.write("        return FF_OK();\n")
        fh.write("    }\n\n")
        fh.write("    return sendLogout(reason);\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::onReceive(const char *data, std::size_t size) noexcept {\n")
        fh.write("    std::lock_guard<std::recursive_mutex> lock(m_mutex);\n\n")
        fh.write("    if (m_state.status == falconfix::SessionStatus::Disconnected) {\n")
        fh.write("        return FF_OK();\n")
        fh.write("    }\n\n")
        fh.write("    if (!data && size > 0) [[unlikely]] {\n")
        fh.write("        return FF_FIX_PARSE_ERR(INVALID_LENGTH, 0);\n")
        fh.write("    }\n\n")
        fh.write("    const bool hasPending = !m_in.empty();\n")
        fh.write("    if (hasPending || size == 0) {\n")
        fh.write("        if (size > 0) {\n")
        fh.write("            if (!m_in.reserve_noexcept(m_in.size() + size)) [[unlikely]] {\n")
        fh.write("                return FF_SYS_ERR(OUT_OF_MEMORY);\n")
        fh.write("            }\n")
        fh.write("            m_in.append(data, size);\n")
        fh.write("        }\n")
        fh.write("        data = m_in.data();\n")
        fh.write("        size = m_in.size();\n")
        fh.write("    }\n\n")
        fh.write("    const bool usingPending = !m_in.empty();\n")
        fh.write("    const char *cursor = data;\n")
        fh.write("    const char *end = data + size;\n")
        fh.write("    const char *bufferBegin = cursor;\n\n")
        fh.write("    while (cursor < end) {\n")
        fh.write("        TCPFrameView frame;\n\n")
        fh.write("        FFStatus rc = parseTCPFrame(cursor, static_cast<std::size_t>(end - cursor), frame);\n")
        fh.write("        if (isIncompleteTCPFrame(rc)) [[unlikely]] {\n")
        fh.write("            if (usingPending) {\n")
        fh.write("                const std::size_t processed = static_cast<std::size_t>(cursor - bufferBegin);\n")
        fh.write("                if (processed > 0) {\n")
        fh.write("                    m_in.consume(processed);\n")
        fh.write("                }\n")
        fh.write("            }\n")
        fh.write("            else {\n")
        fh.write("                const std::size_t remaining = static_cast<std::size_t>(end - cursor);\n")
        fh.write("                if (!m_in.reserve_noexcept(remaining)) [[unlikely]] {\n")
        fh.write("                    return FF_SYS_ERR(OUT_OF_MEMORY);\n")
        fh.write("                }\n")
        fh.write("                m_in.append(cursor, remaining);\n")
        fh.write("            }\n")
        fh.write("\n")
        fh.write("            return FF_OK();\n")
        fh.write("        }\n")
        fh.write("        if (!rc.ok()) [[unlikely]] {\n")
        fh.write("            if (usingPending) {\n")
        fh.write("                m_in.clear();\n")
        fh.write("            }\n")
        fh.write("            m_log->event(m_sidText, falconfix::errors::format_error(rc));\n")
        fh.write("\n")
        fh.write("            if (frame.msgSeqNum > 0) {\n")
        fh.write("                (void)sendReject(\n")
        fh.write("                    frame.msgSeqNum,\n")
        fh.write("                    rc.tag,\n")
        fh.write("                    falconfix::errors::format_error(rc),\n")
        fh.write("                    toSessionRejectReason(rc)\n")
        fh.write("                );\n")
        fh.write("            }\n")
        fh.write("\n")
        fh.write("            return rc;\n")
        fh.write("        }\n\n")
        fh.write("        rc = validateSessionIdentity(\n")
        fh.write("            frame.beginString,\n")
        fh.write("            frame.senderCompID,\n")
        fh.write("            frame.targetCompID\n")
        fh.write("        );\n")
        fh.write("        if (!rc.ok()) [[unlikely]] {\n")
        fh.write("            m_log->event(m_sidText, falconfix::errors::format_error(rc));\n")
        fh.write("            return rc;\n")
        fh.write("        }\n\n")
        fh.write("        if (m_cfg.connection.validateSendingTime) {\n")
        fh.write("            rc = validateSendingTime(frame.sendingTimeMs);\n")
        fh.write("            if (!rc.ok()) [[unlikely]] {\n")
        fh.write("                m_log->event(m_sidText, falconfix::errors::format_error(rc));\n")
        fh.write("                (void)sendReject(\n")
        fh.write("                    frame.msgSeqNum, \n")
        fh.write("                    rc.tag, \n")
        fh.write("                    falconfix::errors::format_error(rc),\n")
        fh.write("                    toSessionRejectReason(rc)\n")
        fh.write("                );\n")
        fh.write("                return rc;\n")
        fh.write("            }\n")
        fh.write("        }\n\n")
        fh.write("        m_log->incoming(m_sidText, {frame.begin, static_cast<std::size_t>(frame.end - frame.begin)});\n")
        fh.write("        m_state.lastReceivedMs = falconfix::TickClock::getTickCount();\n\n")
        fh.write("        const int64_t expectedSeqNum = m_store->nextTargetSeqNum();\n\n")
        fh.write("\t\tauto ss = classifySeqNum(frame.msgSeqNum, expectedSeqNum, frame.possDup);\n")
        fh.write("        switch (ss) {\n")
        fh.write("        case SeqNumState::Expected:\n")
        fh.write("            break;\n\n")
        fh.write("        case SeqNumState::Gap:\n")
        fh.write("            if (m_cfg.connection.enableResendRequest && !m_state.awaitingResend) {\n")
        fh.write("                m_state.awaitingResend = true;\n\n")
        fh.write("                rc = sendResendRequest(expectedSeqNum, frame.msgSeqNum);\n")
        fh.write("                if (!rc.ok()) [[unlikely]] {\n")
        fh.write("                    return rc;\n")
        fh.write("                }\n\n")
        fh.write("                m_log->event(m_sidText, \"sequence gap detected\");\n")
        fh.write("            }\n\n")
        fh.write("            return FF_FIX_SESSION_ERR(RESEND_REQUIRED, static_cast<int32_t>(frame.msgSeqNum));\n\n")
        fh.write("        case SeqNumState::PossDupOld:\n")
        fh.write("            m_log->event(m_sidText, \"old possdup message received\");\n")
        fh.write("            break;\n\n")
        fh.write("        case SeqNumState::InvalidOld:\n")
        fh.write("            return FF_FIX_SESSION_ERR(SEQUENCE_GAP, static_cast<int32_t>(frame.msgSeqNum));\n")
        fh.write("        }\n\n")
        fh.write(f"        rc = dispatchInbound(*this, m_app, m_sid, frame);\n")
        fh.write("        if (!rc.ok()) [[unlikely]] {\n")
        fh.write("            m_log->event(m_sidText, falconfix::errors::format_error(rc));\n")
        fh.write("            if (frame.msgSeqNum > 0 &&\n")
        fh.write("                (rc.domain == falconfix::errors::Domain::fix_parse ||\n")
        fh.write("                 rc.domain == falconfix::errors::Domain::fix_validation)) {\n")
        fh.write("                (void)sendReject(\n")
        fh.write("                    frame.msgSeqNum,\n")
        fh.write("                    rc.tag,\n")
        fh.write("                    falconfix::errors::format_error(rc),\n")
        fh.write("                    toSessionRejectReason(rc)\n")
        fh.write("                );\n")
        fh.write("            }\n")
        fh.write("            return rc;\n")
        fh.write("        }\n\n")
        fh.write("        if (m_state.status == falconfix::SessionStatus::Disconnected &&\n")
        fh.write("            (m_cfg.connection.resetOnLogout ||\n")
        fh.write("             m_cfg.connection.resetOnDisconnect ||\n")
        fh.write("             m_cfg.schedule.resetSeqNumsDaily)) {\n")
        fh.write("            return FF_OK();\n")
        fh.write("        }\n\n")
        fh.write("        rc = m_store->storeIncoming(\n")
        fh.write("            frame.msgSeqNum,\n")
        fh.write("            {frame.begin, static_cast<std::size_t>(frame.end - frame.begin)}\n")
        fh.write("        );\n")
        fh.write("        if (!rc.ok()) [[unlikely]] {\n")
        fh.write("            return rc;\n")
        fh.write("        }\n\n")
        fh.write(f"        if (frame.msgTypeEnum != {ns}::enums::MsgType::SEQUENCE_RESET) {{\n")
        fh.write("            m_store->incrNextTargetSeqNum();\n")
        fh.write("        }\n\n")
        fh.write("        if (m_state.awaitingResend && m_store->nextTargetSeqNum() > frame.msgSeqNum) {\n")
        fh.write("            m_state.awaitingResend = false;\n\n")
        fh.write("            if (m_state.status == falconfix::SessionStatus::Closing) {\n")
        fh.write("                return sendLogout(\"engine shutdown\");\n")
        fh.write("            }\n")
        fh.write("        }\n\n")
        fh.write("        if (usingPending) {\n")
        fh.write("            const std::size_t processed = static_cast<std::size_t>(frame.end - m_in.data());\n")
        fh.write("            m_in.consume(processed);\n")
        fh.write("            cursor = m_in.data();\n")
        fh.write("            end = cursor + m_in.size();\n")
        fh.write("            bufferBegin = cursor;\n")
        fh.write("        }\n")
        fh.write("        else {\n")
        fh.write("            cursor = frame.end;\n")
        fh.write("        }\n")
        fh.write("    }\n\n")
        fh.write("    if (usingPending) {\n")
        fh.write("        m_in.clear();\n")
        fh.write("    }\n\n")
        fh.write("    return FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::onConnected() noexcept {\n")
        fh.write("\tstd::lock_guard<std::recursive_mutex> lock(m_mutex);\n\n")
        fh.write("\tif (m_state.status != falconfix::SessionStatus::Disconnected) {\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.status = falconfix::SessionStatus::Connected;\n")
        fh.write("\tm_in.clear();\n")
        fh.write("\tm_log->event(m_sidText, \"connected\");\n\n")
        fh.write("\treturn sendLogon();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::onDisconnected() noexcept {\n")
        fh.write("\tstd::lock_guard<std::recursive_mutex> lock(m_mutex);\n\n")
        fh.write("\tconst bool wasSessionActive = \n")
        fh.write("\t\tm_state.status != falconfix::SessionStatus::Disconnected &&\n")
        fh.write("\t\t(m_state.loggedOn() || m_state.sentLogout || m_state.receivedLogout);\n")
        fh.write("\tconst bool shouldResetSeqNums =\n")
        fh.write("\t\tm_state.resetSeqNumsOnDisconnect ||\n")
        fh.write("\t\t(wasSessionActive && (\n")
        fh.write("\t\t\t((m_state.sentLogout || m_state.receivedLogout) && m_cfg.connection.resetOnLogout) ||\n")
        fh.write("\t\t\t(!(m_state.sentLogout || m_state.receivedLogout) && m_cfg.connection.resetOnDisconnect)\n")
        fh.write("\t\t));\n")
        fh.write("\tm_state.status = falconfix::SessionStatus::Disconnected;\n")
        fh.write("\tm_log->event(m_sidText, \"disconnected\");\n\n")
        fh.write("\tm_state.sentLogon = false;\n")
        fh.write("\tm_state.receivedLogon = false;\n")
        fh.write("\tm_state.sentLogout = false;\n")
        fh.write("\tm_state.receivedLogout = false;\n")
        fh.write("\tm_state.awaitingResend = false;\n")
        fh.write("\tm_state.awaitingTestResponse = false;\n")
        fh.write("\tm_state.testRequestSentMs = 0;\n")
        fh.write("\tm_state.testRequestID = 0;\n\n")
        fh.write("\tm_in.clear();\n\n")
        fh.write("\tif (wasSessionActive) {\n")
        fh.write("\t\tm_app.onLogout(m_sid);\n")
        fh.write("\t}\n\n")
        fh.write("\tif (shouldResetSeqNums) {\n")
        fh.write("        m_store->reset();\n")
        fh.write("        m_state.resetSeqNumsOnDisconnect = false;\n\n")
        fh.write("        m_log->event(m_sidText, \"sequence numbers reset\");\n")
        fh.write("    }\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::onTimer() noexcept {\n")
        fh.write("\tstd::unique_lock<std::recursive_mutex> lock(m_mutex);\n\n")
        fh.write("\tif (m_state.closing() || !m_state.loggedOn() || m_cfg.connection.disableHeartbeat) {\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write("\tif (!isWithinSchedule()) {\n")
        fh.write("\t\tm_log->event(m_sidText, \"session schedule ended\");\n")
        fh.write("\t\tm_state.resetSeqNumsOnDisconnect = m_cfg.schedule.resetSeqNumsDaily;\n")
        fh.write("\t\t(void)doLogout(\"session closed\");\n\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write("\tconst uint64_t now = falconfix::TickClock::getTickCount();\n")
        fh.write("\tconst uint64_t hb = m_cfg.connection.heartBtIntMs;\n")
        fh.write("\tconst uint64_t hbWithMargin = hb + static_cast<uint64_t>(hb / 2);\n\n")
        fh.write("\tif (m_state.awaitingTestResponse) {\n")
        fh.write("\t\tif (now - m_state.testRequestSentMs >= hb) {\n")
        fh.write("\t\t\tm_log->event(m_sidText, \"test request timeout\");\n\n")
        fh.write("\t\t\tm_state.awaitingTestResponse = false;\n")
        fh.write("\t\t\tm_state.status = falconfix::SessionStatus::Disconnected;\n")
        fh.write("\t\t\tlock.unlock();\n")
        fh.write("\t\t\tconnection().close();\n\n")
        fh.write("\t\t\treturn FF_FIX_SESSION_ERR(TEST_REQUEST_TIMEOUT, 0);\n")
        fh.write("\t\t}\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write("\tif (now - m_state.lastReceivedMs >= hbWithMargin) {\n")
        fh.write("\t\treturn sendTestRequest();\n")
        fh.write("\t}\n\n")
        fh.write("\tif (now - m_state.lastSentMs >= hb) {\n")
        fh.write("\t\treturn sendHeartbeat();\n")
        fh.write("\t}\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendLogon() noexcept {\n")
        fh.write(f"\t{ns}::messages::Logon msg;\n\n")
        fh.write("\tif (m_cfg.connection.resetOnLogon) {\n")
        fh.write("\t\tm_store->reset();\n")
        fh.write("\t\tmsg.setResetSeqNumFlag(true);\n")
        fh.write("\t}\n\n")
        fh.write("\tmsg.setEncryptMethod(0);\n")
        fh.write(f"\tmsg.setHeartBtInt(static_cast<{ns}::types::INT>(m_cfg.connection.heartBtIntMs / 1000ULL));\n\n")
        fh.write("\tFFStatus rc = send(msg);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.sentLogon = true;\n")
        fh.write("\tm_state.status = falconfix::SessionStatus::LogonSent;\n")
        fh.write("\tm_log->event(m_sidText, \"logon sent\");\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendLogout(std::string_view reason) noexcept {\n")
        fh.write("\tif (m_state.closing() || m_state.status == falconfix::SessionStatus::Disconnected) {\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write(f"\t{ns}::messages::Logout msg;\n\n")
        fh.write("\tif (!reason.empty()) {\n")
        fh.write("\t\tmsg.setText(reason);\n")
        fh.write("\t}\n\n")
        fh.write("\tFFStatus rc = send(msg);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.sentLogout = true;\n")
        fh.write("\tm_state.status = falconfix::SessionStatus::LogoutSent;\n")
        fh.write("\tm_log->event(m_sidText, \"logout sent\");\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendHeartbeat() noexcept {\n")
        fh.write(f"\t{ns}::messages::Heartbeat msg;\n")
        fh.write("\treturn send(msg);\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendTestRequest() noexcept {\n")
        fh.write(f"\t{ns}::messages::TestRequest msg;\n\n")
        fh.write("\t++m_state.testRequestID;\n\n")
        fh.write("\tchar buf[16];\n")
        fh.write("\tconst std::size_t n = falconfix::itoa(m_state.testRequestID, buf);\n\n")
        fh.write(f"\t{ns}::types::STRING<32> id;\n")
        fh.write("\tid.assign(buf, n);\n\n")
        fh.write("\tmsg.setTestReqID(id);\n\n")
        fh.write("\tFFStatus rc = send(msg);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.awaitingTestResponse = true;\n")
        fh.write("\tm_state.testRequestSentMs = falconfix::TickClock::getTickCount();\n\n")
        fh.write("\tm_log->event(m_sidText, \"test request sent\");\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendResendRequest(int64_t beginSeqNo, int64_t endSeqNo) noexcept {\n")
        fh.write(f"\t{ns}::messages::ResendRequest msg;\n\n")
        fh.write("\tmsg.setBeginSeqNo(beginSeqNo);\n")
        fh.write("\tmsg.setEndSeqNo(endSeqNo);\n\n")
        fh.write("\tFFStatus rc = send(msg);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\tm_log->event(m_sidText, \"resend request sent\");\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendSequenceResetGapFill(int64_t msgSeqNum, int64_t newSeqNo) noexcept {\n")
        fh.write(f"\t{ns}::messages::SequenceReset msg;\n\n")
        fh.write("\tmsg.getRefHeader().setMsgSeqNum(msgSeqNum);\n\n")
        fh.write("\tmsg.setGapFillFlag(true);\n")
        fh.write("\tmsg.setNewSeqNo(newSeqNo);\n\n")
        fh.write("\tFFStatus rc = prepareOutboundWithoutSeqOverride(msg, m_sid);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\trc = msg.toString(m_out, m_cfg.connection.millisecondsInTimeStamp);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\trc = connection().write(m_out.data(), m_out.size());\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\treturn rc;\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.lastSentMs = falconfix::TickClock::getTickCount();\n\n")
        fh.write("    m_log->outgoing(m_sidText, {m_out.data(), m_out.size()});\n")
        fh.write("    m_log->event(m_sidText, \"sequence reset gap-fill sent\");\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendReject(int64_t refSeqNum,\n")
        fh.write("                             int32_t refTagID,\n")
        fh.write("                             std::string_view text,\n")
        fh.write(f"                             {ns}::enums::SessionRejectReason reason) noexcept {{\n")
        fh.write(f"    {ns}::messages::Reject msg;\n\n")
        fh.write(f"    msg.setRefSeqNum(static_cast<{ns}::types::INT>(refSeqNum));\n\n")
        fh.write(f"    msg.setSessionRejectReason(static_cast<{ns}::types::INT>(reason));\n\n")
        fh.write("    if (refTagID > 0) {\n")
        fh.write(f"        msg.setRefTagID(static_cast<{ns}::types::INT>(refTagID));\n")
        fh.write("    }\n\n")
        fh.write("    if (!text.empty()) {\n")
        fh.write("        msg.setText(text);\n")
        fh.write("    }\n\n")
        fh.write("    return send(msg);\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::sendBusinessReject(int64_t refSeqNum,\n")
        fh.write("                                     std::string_view refMsgType,\n")
        fh.write("                                     int32_t reason,\n")
        fh.write("                                     std::string_view text) noexcept {\n")
        fh.write(f"    {ns}::messages::BusinessMessageReject msg;\n\n")
        fh.write(f"    msg.setRefSeqNum(static_cast<{ns}::types::INT>(refSeqNum));\n\n")
        fh.write("    msg.setRefMsgType(refMsgType);\n")
        fh.write(f"    msg.setBusinessRejectReason(static_cast<{ns}::types::INT>(reason));\n")
        fh.write("    if (!text.empty()) {\n")
        fh.write("        msg.setText(text);\n")
        fh.write("    }\n\n")
        fh.write("    return send(msg);\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::resendApplicationMessage(const falconfix::StoredMessageView &stored) noexcept {\n")
        fh.write("    std::string replay;\n\n")
        fh.write("    if (!buildPossDupReplay(stored.raw, replay)) [[unlikely]] {\n")
        fh.write("        return sendSequenceResetGapFill(stored.seqNum, stored.seqNum + 1);\n")
        fh.write("    }\n\n")
        fh.write("    FFStatus rc = connection().write(replay.data(), replay.size());\n")
        fh.write("    if (!rc.ok()) [[unlikely]] {\n")
        fh.write("        return rc;\n")
        fh.write("    }\n\n")
        fh.write("    m_log->outgoing(m_sidText, replay);\n")
        fh.write("    return FF_OK();\n")
        fh.write("}\n\n")
        fh.write("/*static */\n")
        fh.write("bool Session::buildPossDupReplay(std::string_view raw, std::string &out) {\n")
        fh.write(f"    constexpr char SOH = {ns}::serialize::SOH;\n\n")
        fh.write("    out.clear();\n")
        fh.write("    out.reserve(raw.size() + 96);\n\n")
        fh.write("    uint32_t checksum = 0;\n\n")
        fh.write("    auto appendChar = [&](char c) {\n")
        fh.write("        out.push_back(c);\n")
        fh.write("        checksum += static_cast<unsigned char>(c);\n")
        fh.write("    };\n\n")
        fh.write("    auto appendView = [&](std::string_view v) {\n")
        fh.write("        out.append(v.data(), v.size());\n\n")
        fh.write("        for (unsigned char c : v) {\n")
        fh.write("            checksum += c;\n")
        fh.write("        }\n")
        fh.write("    };\n\n")
        fh.write("    auto appendRaw = [&](const char *data, std::size_t size) {\n")
        fh.write("        out.append(data, size);\n\n")
        fh.write("        for (std::size_t i = 0; i < size; ++i) {\n")
        fh.write("            checksum += static_cast<unsigned char>(data[i]);\n")
        fh.write("        }\n")
        fh.write("    };\n\n")
        fh.write("    std::size_t bodyLengthValuePos = std::string::npos;\n")
        fh.write("    std::size_t bodyStartPos = std::string::npos;\n")
        fh.write("    std::size_t possDupInsertPos = std::string::npos;\n\n")
        fh.write("    std::string_view sendingTime{};\n\n")
        fh.write("    std::size_t pos = 0;\n\n")
        fh.write("    while (pos < raw.size()) {\n")
        fh.write("        const std::size_t fieldEnd = raw.find(SOH, pos);\n")
        fh.write("        if (fieldEnd == std::string_view::npos) [[unlikely]] {\n")
        fh.write("            return false;\n")
        fh.write("        }\n\n")
        fh.write("        const std::size_t eq = raw.find('=', pos);\n")
        fh.write("        if (eq == std::string_view::npos || eq > fieldEnd) [[unlikely]] {\n")
        fh.write("            return false;\n")
        fh.write("        }\n\n")
        fh.write("        int32_t tag = 0;\n\n")
        fh.write("        for (std::size_t i = pos; i < eq; ++i) {\n")
        fh.write("            const unsigned d = static_cast<unsigned>(raw[i] - '0');\n\n")
        fh.write("            if (d > 9) [[unlikely]] {\n")
        fh.write("                return false;\n")
        fh.write("            }\n\n")
        fh.write("            tag = (tag * 10) + static_cast<int32_t>(d);\n")
        fh.write("        }\n\n")
        fh.write("        switch (tag) {\n\n")
        fh.write(f"            case {ns}::field_id::CheckSum:\n")
        fh.write("                pos = raw.size();\n")
        fh.write("                continue;\n\n")
        fh.write(f"            case {ns}::field_id::BodyLength: {{\n")
        fh.write("                appendView(raw.substr(pos, eq - pos + 1));\n\n")
        fh.write("                bodyLengthValuePos = out.size();\n\n")
        fh.write("                appendView(\"000000\");\n")
        fh.write("                appendChar(SOH);\n\n")
        fh.write("                bodyStartPos = out.size();\n\n")
        fh.write("                pos = fieldEnd + 1;\n")
        fh.write("                continue;\n")
        fh.write("            }\n\n")
        fh.write(f"            case {ns}::field_id::SendingTime:\n")
        fh.write("                sendingTime = raw.substr(eq + 1, fieldEnd - eq - 1);\n")
        fh.write("                break;\n\n")
        fh.write("            default:\n")
        fh.write("                break;\n")
        fh.write("        }\n\n")
        fh.write("        appendRaw(raw.data() + pos, fieldEnd - pos + 1);\n\n")
        fh.write("        switch (tag) {\n\n")
        fh.write(f"            case {ns}::field_id::MsgType: {{\n")
        fh.write("                possDupInsertPos = out.size();\n\n")
        fh.write("                char tmp[16];\n")
        fh.write("                char *p = tmp;\n\n")
        fh.write(f"                WRITE_TAG3({ns}::tag_const::PossDupFlag); // 43=\n")
        fh.write("                *p++ = 'Y';\n")
        fh.write("                *p++ = SOH;\n\n")
        fh.write("                appendRaw(tmp, static_cast<std::size_t>(p - tmp));\n")
        fh.write("                break;\n")
        fh.write("            }\n\n")
        fh.write("            default:\n")
        fh.write("                break;\n")
        fh.write("        }\n\n")
        fh.write("        pos = fieldEnd + 1;\n")
        fh.write("    }\n\n")
        fh.write("    if (bodyLengthValuePos == std::string::npos ||\n")
        fh.write("        bodyStartPos == std::string::npos ||\n")
        fh.write("        possDupInsertPos == std::string::npos) [[unlikely]] {\n")
        fh.write("        return false;\n")
        fh.write("    }\n\n")
        fh.write("    if (!sendingTime.empty()) {\n")
        fh.write("        char tmp[64];\n")
        fh.write("        char *p = tmp;\n\n")
        fh.write(f"        WRITE_TAG4({ns}::tag_const::OrigSendingTime); // 122=\n\n")
        fh.write("        std::memcpy(p, sendingTime.data(), sendingTime.size());\n")
        fh.write("        p += sendingTime.size();\n\n")
        fh.write("        *p++ = SOH;\n\n")
        fh.write("        const std::size_t insertSize =\n")
        fh.write("            static_cast<std::size_t>(p - tmp);\n\n")
        fh.write("        out.insert(possDupInsertPos + 5, tmp, insertSize);\n\n")
        fh.write("        checksum = 0;\n\n")
        fh.write("        for (unsigned char c : out) {\n")
        fh.write("            checksum += c;\n")
        fh.write("        }\n")
        fh.write("    }\n\n")
        fh.write("    const std::size_t bodyLength = out.size() - bodyStartPos;\n\n")
        fh.write("    char *digits = out.data() + bodyLengthValuePos;\n\n")
        fh.write("    for (int i = 0; i < 6; ++i) {\n")
        fh.write("        checksum -= static_cast<unsigned char>(digits[i]);\n")
        fh.write("    }\n\n")
        fh.write("    digits[0] = char('0' + ((bodyLength / 100000) % 10));\n")
        fh.write("    digits[1] = char('0' + ((bodyLength / 10000) % 10));\n")
        fh.write("    digits[2] = char('0' + ((bodyLength / 1000) % 10));\n")
        fh.write("    digits[3] = char('0' + ((bodyLength / 100) % 10));\n")
        fh.write("    digits[4] = char('0' + ((bodyLength / 10) % 10));\n")
        fh.write("    digits[5] = char('0' + (bodyLength % 10));\n\n")
        fh.write("    for (int i = 0; i < 6; ++i) {\n")
        fh.write("        checksum += static_cast<unsigned char>(digits[i]);\n")
        fh.write("    }\n\n")
        fh.write("    checksum %= 256;\n\n")
        fh.write("    appendChar('1');\n")
        fh.write("    appendChar('0');\n")
        fh.write("    appendChar('=');\n")
        fh.write("    appendChar(char('0' + (checksum / 100)));\n")
        fh.write("    appendChar(char('0' + ((checksum / 10) % 10)));\n")
        fh.write("    appendChar(char('0' + (checksum % 10)));\n")
        fh.write("    appendChar(SOH);\n\n")
        fh.write("    return true;\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::validateSessionIdentity(std::string_view beginString,\n")
        fh.write("                                          std::string_view senderCompID,\n")
        fh.write("                                          std::string_view targetCompID) noexcept {\n")
        fh.write("    if (beginString != m_sid.beginString()) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_SESSION_ERR(SESSION_REJECT, {ns}::field_id::BeginString);\n")
        fh.write("    }\n\n")
        fh.write("    if (senderCompID != m_sid.targetCompID()) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_SESSION_ERR(SESSION_REJECT, {ns}::field_id::SenderCompID);\n")
        fh.write("    }\n\n")
        fh.write("    if (targetCompID != m_sid.senderCompID()) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_SESSION_ERR(SESSION_REJECT, {ns}::field_id::TargetCompID);\n")
        fh.write("    }\n\n")
        fh.write("    return FF_OK();\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::validateSendingTime(int64_t sendingTimeMs) noexcept {\n")
        fh.write("    if (sendingTimeMs <= 0) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_SESSION_ERR(SESSION_REJECT, {ns}::field_id::SendingTime);\n")
        fh.write("    }\n\n")
        fh.write(f"    const uint64_t nowMs = {ns}::datetime::detail::now_epoch_ms();\n")
        fh.write("    const auto diff = nowMs > static_cast<uint64_t>(sendingTimeMs)\n")
        fh.write("        ? nowMs - static_cast<uint64_t>(sendingTimeMs)\n")
        fh.write("        : static_cast<uint64_t>(sendingTimeMs) - nowMs;\n\n")
        fh.write("    if (diff > m_cfg.connection.maxLatencyMs) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_SESSION_ERR(SESSION_REJECT, {ns}::field_id::SendingTime);\n")
        fh.write("    }\n\n")
        fh.write("    return FF_OK();\n")
        fh.write("}\n\n")
        fh.write("bool Session::isWithinSchedule(int64_t nowsecs /*=0*/) const noexcept {\n")
        fh.write("    const auto &schedule = m_cfg.schedule;\n")
        fh.write("    if (!schedule.enabled) {\n")
        fh.write("        return true;\n")
        fh.write("    }\n\n")
        fh.write("    if (nowsecs == 0) {\n")
        fh.write("        return falconfix::session_schedule::isWithinScheduleNow(schedule);\n")
        fh.write("    }\n\n")
        fh.write("    return falconfix::session_schedule::isWithinScheduleAtSeconds(schedule, nowsecs);\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleLogonReceived(const {ns}::messages::Logon &msg) noexcept {{\n")
        fh.write("\tif (m_state.receivedLogon || m_state.loggedOn()) {\n")
        fh.write("\t\tm_log->event(m_sidText, \"duplicate logon received\");\n\n")
        fh.write("\t\tFFStatus rc = sendLogout(\"duplicate logon\");\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\tconnection().close();\n")
        fh.write("\t\treturn FF_FIX_SESSION_ERR(LOGON_FAILED, 0);\n")
        fh.write("\t}\n\n")
        fh.write("\tif (msg.getEncryptMethod() != 0) {\n")
        fh.write("\t\tm_log->event(m_sidText, \"invalid EncryptMethod received\");\n\n")
        fh.write("\t\tFFStatus rc = sendLogout(\"invalid EncryptMethod\");\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write(f"\t\treturn FF_FIX_SESSION_ERR(LOGON_FAILED, {ns}::field_id::EncryptMethod);\n")
        fh.write("\t}\n\n")
        fh.write("\tif (msg.getHeartBtInt() <= 0) {\n")
        fh.write("\t\tm_log->event(m_sidText, \"invalid HeartBtInt received\");\n\n")
        fh.write("\t\tFFStatus rc = sendLogout(\"invalid HeartBtInt\");\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n\n")
        fh.write(f"\t\treturn FF_FIX_SESSION_ERR(LOGON_FAILED, {ns}::field_id::HeartBtInt);\n")
        fh.write("\t}\n\n")
        fh.write("\tif (msg.hasResetSeqNumFlag() && msg.getResetSeqNumFlag()) {\n")
        fh.write("\t\tconst int64_t senderSeq = m_store->nextSenderSeqNum();\n")
        fh.write("\t\tm_store->reset();\n")
        fh.write("\t\tm_store->setNextSenderSeqNum(senderSeq);\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.receivedLogon = true;\n\n")
        fh.write("\tif (!m_state.sentLogon) {\n")
        fh.write("\t\tFFStatus rc = sendLogon();\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n")
        fh.write("\t}\n")
        fh.write("\tm_state.status = falconfix::SessionStatus::LoggedOn;\n\n")
        fh.write("\tm_log->event(m_sidText, \"logon received\");\n")
        fh.write("\tm_app.onLogon(m_sid);\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleLogoutReceived(const {ns}::messages::Logout &msg) noexcept {{\n")
        fh.write("\t(void)msg;\n\n")
        fh.write("\tm_state.receivedLogout = true;\n")
        fh.write("\tif (!m_state.sentLogout) {\n")
        fh.write("\t\tFFStatus rc = sendLogout({});\n")
        fh.write("\t\tif (!rc.ok()) [[unlikely]] {\n")
        fh.write("\t\t\treturn rc;\n")
        fh.write("\t\t}\n")
        fh.write("\t}\n\n")
        fh.write("\tm_state.status = falconfix::SessionStatus::Closing;\n\n")
        fh.write("\tif (m_cfg.connection.connectionType == falconfix::ConnectionType::Initiator) {\n")
        fh.write("\t\tconnection().close();\n")
        fh.write("\t\treturn onDisconnected();\n")
        fh.write("\t}\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleHeartbeatReceived(const {ns}::messages::Heartbeat &msg) noexcept {{\n")
        fh.write("\tif (m_state.awaitingTestResponse) {\n")
        fh.write("\t\tif (!msg.hasTestReqID()) {\n")
        fh.write("\t\t\tm_log->event(m_sidText, \"heartbeat missing TestReqID while awaiting test response\");\n")
        fh.write("\t\t\treturn FF_OK();\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\tchar buf[16];\n")
        fh.write("\t\tconst std::size_t n = falconfix::itoa(m_state.testRequestID, buf);\n")
        fh.write("\t\tstd::string_view expectedId(buf, n);\n")
        fh.write("\t\tif (msg.getTestReqID().view() != expectedId) {\n")
        fh.write("\t\t\tm_log->event(m_sidText, \"heartbeat TestReqID mismatch\");\n")
        fh.write("\t\t\treturn FF_OK();\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\tm_state.awaitingTestResponse = false;\n")
        fh.write("\t\tm_log->event(m_sidText, \"test request answered\");\n")
        fh.write("\t}\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleTestRequestReceived(const {ns}::messages::TestRequest &msg) noexcept {{\n")
        fh.write("\tm_log->event(m_sidText, \"test request received\");\n\n")
        fh.write("\tif (m_state.sentLogout || m_state.receivedLogout || m_cfg.connection.ignoreTestRequest) {\n")
        fh.write("\t\treturn FF_OK();\n")
        fh.write("\t}\n\n")
        fh.write(f"\t{ns}::messages::Heartbeat hb;\n")
        fh.write("\tif (msg.hasTestReqID()) {\n")
        fh.write("\t\thb.setTestReqID(msg.getTestReqID());\n")
        fh.write("\t}\n\n")
        fh.write("\treturn send(hb);\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleResendRequestReceived(const {ns}::messages::ResendRequest &msg) noexcept {{\n")
        fh.write("    m_log->event(m_sidText, \"resend request received\");\n\n")
        fh.write("    const int64_t beginSeqNum = msg.getBeginSeqNo();\n\n")
        fh.write("    int64_t endSeqNum = msg.getEndSeqNo();\n")
        fh.write("    if (endSeqNum == 0) {\n")
        fh.write("        endSeqNum = m_store->nextSenderSeqNum() - 1;\n")
        fh.write("    }\n\n")
        fh.write("    std::vector<falconfix::StoredMessageView> messages;\n\n")
        fh.write("    FFStatus rc = m_store->getOutgoing(beginSeqNum, endSeqNum, messages);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] {\n")
        fh.write("        return sendSequenceResetGapFill(beginSeqNum, endSeqNum + 1);\n")
        fh.write("    }\n\n")
        fh.write("    int64_t expectedSeqNum = beginSeqNum;\n")
        fh.write("    int64_t gapFillBegin = 0;\n\n")
        fh.write("    auto flushGapFill = [&]() noexcept -> FFStatus {\n")
        fh.write("        if (gapFillBegin == 0) {\n")
        fh.write("            return FF_OK();\n")
        fh.write("        }\n\n")
        fh.write("        FFStatus gapRc = sendSequenceResetGapFill(gapFillBegin, expectedSeqNum);\n")
        fh.write("        gapFillBegin = 0;\n")
        fh.write("        return gapRc;\n")
        fh.write("    };\n\n")
        fh.write("    for (const auto &stored : messages) {\n")
        fh.write("        while (expectedSeqNum < stored.seqNum) {\n")
        fh.write("            if (gapFillBegin == 0) {\n")
        fh.write("                gapFillBegin = expectedSeqNum;\n")
        fh.write("            }\n\n")
        fh.write("            ++expectedSeqNum;\n")
        fh.write("        }\n\n")
        fh.write("        if (stored.admin) {\n")
        fh.write("            if (gapFillBegin == 0) {\n")
        fh.write("                gapFillBegin = stored.seqNum;\n")
        fh.write("            }\n\n")
        fh.write("            expectedSeqNum = stored.seqNum + 1;\n")
        fh.write("            continue;\n")
        fh.write("        }\n\n")
        fh.write("        rc = flushGapFill();\n")
        fh.write("        if (!rc.ok()) [[unlikely]] {\n")
        fh.write("            return rc;\n")
        fh.write("        }\n\n")
        fh.write("        rc = resendApplicationMessage(stored);\n")
        fh.write("        if (!rc.ok()) [[unlikely]] {\n")
        fh.write("            return rc;\n")
        fh.write("        }\n\n")
        fh.write("        expectedSeqNum = stored.seqNum + 1;\n")
        fh.write("    }\n\n")
        fh.write("    while (expectedSeqNum <= endSeqNum) {\n")
        fh.write("        if (gapFillBegin == 0) {\n")
        fh.write("            gapFillBegin = expectedSeqNum;\n")
        fh.write("        }\n\n")
        fh.write("        ++expectedSeqNum;\n")
        fh.write("    }\n\n")
        fh.write("    return flushGapFill();\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleRejectReceived(const {ns}::messages::Reject &msg) noexcept {{\n")
        fh.write("\tm_log->event(m_sidText, \"reject received\");\n\n")
        fh.write("\tif (msg.hasText()) {\n")
        fh.write("\t\tm_log->event(m_sidText, msg.getText().view());\n")
        fh.write("\t}\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleBusinessMessageRejectReceived(const {ns}::messages::BusinessMessageReject &msg) noexcept {{\n")
        fh.write("\tm_log->event(m_sidText, \"business reject received\");\n\n")
        fh.write("\tif (msg.hasRefMsgType()) {\n")
        fh.write("\t\tm_log->event(m_sidText, msg.getRefMsgType().view());\n")
        fh.write("\t}\n\n")
        fh.write("\tif (msg.hasText()) {\n")
        fh.write("\t\tm_log->event(m_sidText, msg.getText().view());\n")
        fh.write("\t}\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"FFStatus Session::handleSequenceResetReceived(const {ns}::messages::SequenceReset &msg) noexcept {{\n")
        fh.write("\tm_log->event(m_sidText, \"sequence reset received\");\n\n")
        fh.write(f"\tif (!msg.hasNewSeqNo()) [[unlikely]] {{\n")
        fh.write(f"\t\treturn FF_FIX_SESSION_ERR(SEQUENCE_RESET_FAILED, {ns}::field_id::NewSeqNo);\n")
        fh.write("\t}\n\n")
        fh.write("\tconst int64_t newSeqNo = msg.getNewSeqNo();\n")
        fh.write("\tconst int64_t expectedSeqNum = m_store->nextTargetSeqNum();\n\n")
        fh.write("\tif (newSeqNo <= expectedSeqNum) [[unlikely]] {\n")
        fh.write("\t\treturn FF_FIX_SESSION_ERR(SEQUENCE_GAP, static_cast<int32_t>(newSeqNo));\n")
        fh.write("\t}\n\n")
        fh.write("\tm_store->setNextTargetSeqNum(newSeqNo);\n\n")
        fh.write("\tm_log->event(m_sidText, \"sequence numbers advanced by gap fill\");\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("std::unique_ptr<falconfix::SessionBase>\n")
        fh.write("makeSession(falconfix::FIXApplication &app,\n")
        fh.write("            const falconfix::SessionConfig &cfg,\n")
        fh.write("            std::unique_ptr<falconfix::MessageLog> log,\n")
        fh.write("            std::unique_ptr<falconfix::MessageStore> store) {\n")
        fh.write(f"\treturn std::make_unique<{ns}::engine::Session>(\n")
        fh.write("\t\tapp,\n")
        fh.write("\t\tcfg,\n")
        fh.write("\t\tstd::move(log),\n")
        fh.write("\t\tstd::move(store)\n")
        fh.write("\t);\n")
        fh.write("}\n\n")
        fh.write("#ifdef FALCONFIX_ENABLE_TEST_API\n")
        fh.write("FFStatus Session::validateSessionIdentityForTest(std::string_view beginString,\n")
        fh.write("                                                 std::string_view senderCompID,\n")
        fh.write("                                                 std::string_view targetCompID) noexcept {\n")
        fh.write("\treturn validateSessionIdentity(beginString, senderCompID, targetCompID);\n")
        fh.write("}\n\n")
        fh.write("FFStatus Session::validateSendingTimeForTest(int64_t sendingTimeMs) noexcept {\n")
        fh.write("\treturn validateSendingTime(sendingTimeMs);\n")
        fh.write("}\n\n")
        fh.write("void Session::setScheduleForTest(int64_t start, int64_t end) noexcept {\n")
        fh.write("\tm_cfg.schedule.startSeconds = start;\n")
        fh.write("\tm_cfg.schedule.endSeconds = end;\n")
        fh.write("\tm_cfg.schedule.enabled = true;\n")
        fh.write("}\n\n")
        fh.write("void Session::setNextSenderSeqNumForTest(int64_t seqNum) noexcept {\n")
        fh.write("\tstd::lock_guard<std::recursive_mutex> lock(m_mutex);\n")
        fh.write("\tm_store->setNextSenderSeqNum(seqNum);\n")
        fh.write("}\n\n")
        fh.write("void Session::setNextTargetSeqNumForTest(int64_t seqNum) noexcept {\n")
        fh.write("\tstd::lock_guard<std::recursive_mutex> lock(m_mutex);\n")
        fh.write("\tm_store->setNextTargetSeqNum(seqNum);\n")
        fh.write("}\n\n")
        fh.write("int64_t Session::nextSenderSeqNumForTest() const noexcept {\n")
        fh.write("\treturn m_store->nextSenderSeqNum();\n")
        fh.write("}\n\n")
        fh.write("int64_t Session::nextTargetSeqNumForTest() const noexcept {\n")
        fh.write("\treturn m_store->nextTargetSeqNum();\n")
        fh.write("}\n")
        fh.write("\n")
        fh.write("void Session::setAwaitingTestResponseForTest(bool awaiting, uint64_t testRequestID) noexcept {\n")
        fh.write("\tstd::lock_guard<std::recursive_mutex> lock(m_mutex);\n")
        fh.write("\tm_state.awaitingTestResponse = awaiting;\n")
        fh.write("\tm_state.testRequestID = testRequestID;\n")
        fh.write("}\n\n")
        fh.write("bool Session::awaitingTestResponseForTest() const noexcept {\n")
        fh.write("\treturn m_state.awaitingTestResponse;\n")
        fh.write("}\n\n")
        fh.write("uint64_t Session::testRequestIDForTest() const noexcept {\n")
        fh.write("\treturn m_state.testRequestID;\n")
        fh.write("}\n")
        fh.write("#endif\n\n")
        fh.write(f"}} // namespace {ns}::engine\n")


def _write_outbound_prepare_header(out_path: Path, ns: str, include_root: str):
    with open_generated_file(out_path, encoding="utf-8") as fh:
        write_autogen_header(fh, f"{include_root} generated outbound prepare helpers")
        fh.write("#pragma once\n\n")
        fh.write("#include <utils/error_codes.h>\n")
        fh.write("#include <session/session_id.h>\n")
        fh.write(f"#include <{include_root}/utils/datetime.h>\n\n")
        fh.write(f"namespace {ns}::engine {{\n\n")
        fh.write("template<typename Msg>\n")
        fh.write("inline FFStatus prepareOutbound(Msg &msg, int64_t seqNum, const falconfix::SessionID &sid) noexcept {\n")
        fh.write("\tauto &header = msg.getRefHeader();\n\n")
        fh.write("\theader.setBeginString(sid.beginString());\n")
        fh.write("\theader.setSenderCompID(sid.senderCompID());\n")
        fh.write("\theader.setTargetCompID(sid.targetCompID());\n")
        fh.write("\theader.setMsgSeqNum(seqNum);\n")
        fh.write(f"\theader.setSendingTime({ns}::datetime::now_UTCTimestamp());\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("template<typename Msg>\n")
        fh.write("inline FFStatus prepareOutboundWithoutSeqOverride(Msg &msg, const falconfix::SessionID &sid) noexcept {\n")
        fh.write("\tauto &header = msg.getRefHeader();\n\n")
        fh.write("\theader.setBeginString(sid.beginString());\n")
        fh.write("\theader.setSenderCompID(sid.senderCompID());\n")
        fh.write("\theader.setTargetCompID(sid.targetCompID());\n")
        fh.write(f"\theader.setSendingTime({ns}::datetime::now_UTCTimestamp());\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"}} // namespace {ns}::engine\n")


def _write_tcp_frame_view_header(out_path: Path, ns: str, include_root: str):
    with open_generated_file(out_path, encoding="utf-8") as fh:
        write_autogen_header(fh, f"{include_root} generated tcp frame view")
        fh.write("#pragma once\n\n")
        fh.write("#include <cstddef>\n")
        fh.write("#include <cstdint>\n")
        fh.write("#include <string_view>\n\n")
        fh.write("#include <utils/error_codes.h>\n")
        fh.write("#include <utils/string_utils.h>\n")
        fh.write(f"#include <{include_root}/core/field_id.h>\n")
        fh.write(f"#include <{include_root}/core/enums.h>\n")
        fh.write(f"#include <{include_root}/utils/parser.h>\n\n")
        fh.write(f"namespace {ns}::engine {{\n\n")
        fh.write("struct TCPFrameView {\n")
        fh.write("\tconst char *begin{nullptr};\n")
        fh.write("\tconst char *end{nullptr};\n\n")
        fh.write("\tstd::string_view beginString{};\n")
        fh.write("\tstd::string_view msgType{};\n")
        fh.write(f"\t{ns}::enums::MsgType msgTypeEnum{{{ns}::enums::MsgType::UNKNOWN}};\n\n")
        fh.write("\tstd::string_view senderCompID{};\n")
        fh.write("\tstd::string_view targetCompID{};\n\n")
        fh.write("\tint32_t bodyLength{0};\n")
        fh.write("\tint64_t msgSeqNum{0};\n\n")
        fh.write("\tint64_t sendingTimeMs{0};\n\n")
        fh.write("\tconst char *bodyBegin{nullptr};\n")
        fh.write("\tconst char *bodyEnd{nullptr};\n\n")
        fh.write("\tbool possDup{false};\n")
        fh.write("\tbool possResend{false};\n")
        fh.write("};\n\n")
        fh.write("[[nodiscard]] inline bool isIncompleteTCPFrame(const FFStatus &rc) noexcept {\n")
        fh.write("\treturn rc.domain == falconfix::errors::Domain::socket &&\n")
        fh.write("\t       rc.code == falconfix::errors::code::socket::BUFFER_UNDERFLOW;\n")
        fh.write("}\n\n")
        fh.write("inline FFStatus readFrameTag(const char *&p, const char *end, int32_t &tag) noexcept {\n")
        fh.write("\ttag = 0;\n\n")
        fh.write("\tif (p >= end) [[unlikely]] {\n")
        fh.write("\t\treturn FF_FIX_PARSE_ERR(INVALID_LENGTH, 0);\n")
        fh.write("\t}\n\n")
        fh.write("\twhile (p < end && *p != '=') {\n")
        fh.write("\t\tconst unsigned d = static_cast<unsigned>(*p - '0');\n")
        fh.write("\t\tif (d > 9) [[unlikely]] {\n")
        fh.write("\t\t\treturn FF_FIX_PARSE_ERR(MALFORMED_TAG, 0);\n")
        fh.write("\t\t}\n\n")
        fh.write("\t\ttag = tag * 10 + static_cast<int32_t>(d);\n")
        fh.write("\t\t++p;\n")
        fh.write("\t}\n\n")
        fh.write("\tif (p >= end || *p != '=') [[unlikely]] {\n")
        fh.write("\t\treturn FF_FIX_PARSE_ERR(MISSING_EQUALS, tag);\n")
        fh.write("\t}\n\n")
        fh.write("\t++p;\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("inline FFStatus readFrameValue(const char *&p, const char *end, const char *&begin, const char *&valueEnd, int32_t tag) noexcept {\n")
        fh.write("\tbegin = p;\n\n")
        fh.write("\twhile (p < end && *p != '\\x01') ++p;\n\n")
        fh.write("\tif (p >= end) [[unlikely]] {\n")
        fh.write("\t\treturn FF_FIX_PARSE_ERR(MISSING_SOH, tag);\n")
        fh.write("\t}\n\n")
        fh.write("\tvalueEnd = p;\n")
        fh.write("\t++p;\n\n")
        fh.write("\treturn FF_OK();\n")
        fh.write("}\n\n")
        fh.write("inline FFStatus parseTCPFrame(const char *data,\n")
        fh.write("                              std::size_t size,\n")
        fh.write("                              TCPFrameView &out) noexcept {\n")
        fh.write("    out = {};\n\n")
        fh.write("    if (!data) [[unlikely]] {\n")
        fh.write("        return FF_FIX_PARSE_ERR(INVALID_LENGTH, 0);\n")
        fh.write("    }\n\n")
        fh.write("    if (size < 20) [[unlikely]] {\n")
        fh.write("        return FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n")
        fh.write("    }\n\n")
        fh.write("    const char *p = data;\n")
        fh.write("    const char *end = data + size;\n\n")
        fh.write("    out.begin = data;\n\n")
        fh.write("    int32_t tag = 0;\n")
        fh.write("    const char *valueBegin = nullptr;\n")
        fh.write("    const char *valueEnd = nullptr;\n\n")
        fh.write("    FFStatus rc = readFrameTag(p, end, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] {\n")
        fh.write("        return rc.code == falconfix::errors::code::fix::parse::MALFORMED_TAG ? rc : FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n")
        fh.write("    }\n\n")
        fh.write(f"    if (tag != {ns}::field_id::BeginString) [[unlikely]] {{\n")
        fh.write(f"        return FF_FIX_VALIDATION_ERR(MISSING_REQUIRED, {ns}::field_id::BeginString);\n")
        fh.write("    }\n\n")
        fh.write("    rc = readFrameValue(p, end, valueBegin, valueEnd, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] return FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n\n")
        fh.write("    out.beginString = {valueBegin, static_cast<std::size_t>(valueEnd - valueBegin)};\n\n")
        fh.write("    rc = readFrameTag(p, end, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] {\n")
        fh.write("        return rc.code == falconfix::errors::code::fix::parse::MALFORMED_TAG ? rc : FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n")
        fh.write("    }\n\n")
        fh.write(f"    if (tag != {ns}::field_id::BodyLength) [[unlikely]] {{\n")
        fh.write(f"        return FF_FIX_VALIDATION_ERR(MISSING_REQUIRED, {ns}::field_id::BodyLength);\n")
        fh.write("    }\n\n")
        fh.write("    rc = readFrameValue(p, end, valueBegin, valueEnd, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] return FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n\n")
        fh.write("    out.bodyLength = falconfix::atoi(valueBegin, valueEnd);\n")
        fh.write("    if (out.bodyLength <= 0) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_PARSE_ERR(INVALID_FIELD_VALUE, {ns}::field_id::BodyLength);\n")
        fh.write("    }\n\n")
        fh.write("    out.bodyBegin = p;\n")
        fh.write("    out.bodyEnd = p + out.bodyLength;\n\n")
        fh.write("    if (out.bodyEnd > end) [[unlikely]] {\n")
        fh.write("        return FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n")
        fh.write("    }\n\n")
        fh.write("    rc = readFrameTag(p, out.bodyEnd, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write(f"    if (tag != {ns}::field_id::MsgType) [[unlikely]] {{\n")
        fh.write(f"        return FF_FIX_VALIDATION_ERR(MISSING_REQUIRED, {ns}::field_id::MsgType);\n")
        fh.write("    }\n\n")
        fh.write("    rc = readFrameValue(p, out.bodyEnd, valueBegin, valueEnd, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write("    out.msgType = {valueBegin, static_cast<std::size_t>(valueEnd - valueBegin)};\n\n")
        fh.write(f"    (void){ns}::enums::parse_MsgType(valueBegin, valueEnd, out.msgTypeEnum);\n\n")
        fh.write("    while (p < out.bodyEnd) {\n")
        fh.write("        rc = readFrameTag(p, out.bodyEnd, tag);\n")
        fh.write("        if (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write("        rc = readFrameValue(p, out.bodyEnd, valueBegin, valueEnd, tag);\n")
        fh.write("        if (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write("        switch (tag) {\n")
        fh.write(f"        case {ns}::field_id::SenderCompID:\n")
        fh.write("            out.senderCompID = {valueBegin, static_cast<std::size_t>(valueEnd - valueBegin)};\n")
        fh.write("            break;\n\n")
        fh.write(f"        case {ns}::field_id::TargetCompID:\n")
        fh.write("            out.targetCompID = {valueBegin, static_cast<std::size_t>(valueEnd - valueBegin)};\n")
        fh.write("            break;\n\n")
        fh.write(f"        case {ns}::field_id::MsgSeqNum:\n")
        fh.write("            out.msgSeqNum = falconfix::atoi(valueBegin, valueEnd);\n")
        fh.write("            break;\n\n")
        fh.write(f"        case {ns}::field_id::SendingTime:\n")
        fh.write(f"            out.sendingTimeMs = {ns}::parser::parse_timestamp64(valueBegin, valueEnd);\n")
        fh.write("            if (out.sendingTimeMs <= 0) [[unlikely]] {\n")
        fh.write(f"                return FF_FIX_PARSE_ERR(DECODE_FAILED, {ns}::field_id::SendingTime);\n")
        fh.write("            }\n")
        fh.write("            break;\n\n")
        fh.write(f"        case {ns}::field_id::PossDupFlag:\n")
        fh.write("            out.possDup = valueBegin < valueEnd && *valueBegin == 'Y';\n")
        fh.write("            break;\n\n")
        fh.write(f"        case {ns}::field_id::PossResend:\n")
        fh.write("            out.possResend = valueBegin < valueEnd && *valueBegin == 'Y';\n")
        fh.write("            break;\n\n")
        fh.write("        default:\n")
        fh.write("            break;\n")
        fh.write("        }\n")
        fh.write("    }\n\n")
        fh.write("    if (out.senderCompID.empty()) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_VALIDATION_ERR(MISSING_REQUIRED, {ns}::field_id::SenderCompID);\n")
        fh.write("    }\n\n")
        fh.write("    if (out.targetCompID.empty()) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_VALIDATION_ERR(MISSING_REQUIRED, {ns}::field_id::TargetCompID);\n")
        fh.write("    }\n\n")
        fh.write("    if (out.msgSeqNum <= 0) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_VALIDATION_ERR(MISSING_REQUIRED, {ns}::field_id::MsgSeqNum);\n")
        fh.write("    }\n\n")
        fh.write("    p = out.bodyEnd;\n\n")
        fh.write("    rc = readFrameTag(p, end, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] {\n")
        fh.write("        return rc.code == falconfix::errors::code::fix::parse::MALFORMED_TAG ? rc : FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n")
        fh.write("    }\n\n")
        fh.write(f"    if (tag != {ns}::field_id::CheckSum) [[unlikely]] {{\n")
        fh.write(f"        return FF_FIX_PARSE_ERR(INVALID_CHECKSUM, {ns}::field_id::CheckSum);\n")
        fh.write("    }\n\n")
        fh.write("    rc = readFrameValue(p, end, valueBegin, valueEnd, tag);\n")
        fh.write("    if (!rc.ok()) [[unlikely]] return FF_SOCKET_ERR(BUFFER_UNDERFLOW);\n\n")
        fh.write("    if ((valueEnd - valueBegin) != 3) [[unlikely]] {\n")
        fh.write(f"        return FF_FIX_PARSE_ERR(INVALID_CHECKSUM, {ns}::field_id::CheckSum);\n")
        fh.write("    }\n\n")
        fh.write("    out.end = p;\n")
        fh.write("    return FF_OK();\n")
        fh.write("}\n\n")
        fh.write(f"}} // namespace {ns}::engine\n")


def _write_inbound_dispatch_header(
    out_path: Path,
    ns: str,
    include_root: str,
    spec: dict,
    msgtype_members: dict[str, str],
    session_reject_members: set[str],
):
    messages = spec.get("messages", [])
    invalid_msg_type = _pick_session_reject_member(
        session_reject_members,
        "INVALID_MSGTYPE",
        "INVALID_MSG_TYPE",
    )

    with open_generated_file(out_path, encoding="utf-8") as fh:
        write_autogen_header(fh, f"{include_root} generated inbound dispatch helpers")
        fh.write("#pragma once\n\n")
        fh.write("#include <app/fix_application.h>\n")
        fh.write("#include <utils/error_codes.h>\n\n")
        fh.write(f"#include <{include_root}/core/enums.h>\n")
        fh.write(f"#include <{include_root}/core/field_id.h>\n")
        fh.write(f"#include <{include_root}/engine/protocol.h>\n")
        fh.write(f"#include <{include_root}/engine/tcp_frame_view.h>\n\n")
        fh.write(f"#include <{include_root}/utils/all_messages.h>\n\n")
        fh.write(f"namespace {ns}::engine {{\n\n")
        fh.write("template<typename Msg>\n")
        fh.write("using MessageHandler = FFStatus (Session::*)(const Msg &) noexcept;\n\n")
        fh.write("template<typename Msg>\n")
        fh.write("inline FFStatus dispatchTyped(falconfix::FIXApplication &app,\n")
        fh.write("                              const falconfix::SessionID &sid,\n")
        fh.write("                              const TCPFrameView &frame) noexcept {\n")
        fh.write("\tMsg msg;\n\n")
        fh.write("\tconst char *p = frame.begin;\n")
        fh.write("\tFFStatus rc = msg.setString(p, frame.end);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write("\tfalconfix::FIXMessageRef ref{\n")
        fh.write("\t\t.ptr = &msg,\n")
        fh.write("\t\t.msgType = Msg::MSGTYPE,\n")
        fh.write(f"\t\t.protocol = {ns}::Protocol::VERSION,\n")
        fh.write("\t\t.possDup = frame.possDup,\n")
        fh.write("\t\t.possResend = frame.possResend\n")
        fh.write("\t};\n\n")
        fh.write("\tif constexpr (Msg::IS_ADMIN) {\n")
        fh.write("\t\treturn app.fromAdmin(ref, sid);\n")
        fh.write("\t}\n")
        fh.write("\telse {\n")
        fh.write("\t\treturn app.fromApp(ref, sid);\n")
        fh.write("\t}\n")
        fh.write("}\n\n")
        fh.write("template<typename SessionT, typename Msg>\n")
        fh.write("inline FFStatus dispatchTypedSession(SessionT &session,\n")
        fh.write("                                   FFStatus (SessionT::*handler)(const Msg &) noexcept,\n")
        fh.write("                                   falconfix::FIXApplication &app,\n")
        fh.write("                                   const falconfix::SessionID &sid,\n")
        fh.write("                                   const TCPFrameView &frame) noexcept {\n")
        fh.write("\tMsg msg;\n\n")
        fh.write("\tconst char *p = frame.begin;\n")
        fh.write("\tFFStatus rc = msg.setString(p, frame.end);\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write("\tfalconfix::FIXMessageRef ref{\n")
        fh.write("\t\t.ptr = &msg,\n")
        fh.write("\t\t.msgType = Msg::MSGTYPE,\n")
        fh.write(f"\t\t.protocol = {ns}::Protocol::VERSION\n")
        fh.write("\t};\n\n")
        fh.write("\tif constexpr (Msg::IS_ADMIN) {\n")
        fh.write("\t\trc = app.fromAdmin(ref, sid);\n")
        fh.write("\t}\n")
        fh.write("\telse {\n")
        fh.write("\t\trc = app.fromApp(ref, sid);\n")
        fh.write("\t}\n")
        fh.write("\tif (!rc.ok()) [[unlikely]] return rc;\n\n")
        fh.write("\treturn (session.*handler)(msg);\n")
        fh.write("}\n\n")
        fh.write("template<typename SessionT>\n")
        fh.write("inline FFStatus dispatchInbound(SessionT &session,\n")
        fh.write("                               falconfix::FIXApplication &app,\n")
        fh.write("                               const falconfix::SessionID &sid,\n")
        fh.write("                               const TCPFrameView &frame) noexcept {\n")
        fh.write(f"\tusing namespace {ns}::enums;\n")
        fh.write(f"\tusing namespace {ns}::messages;\n\n")
        fh.write("\tswitch (frame.msgTypeEnum) {\n")
        for msg in messages:
            msg_name = msg.get("name")
            msg_type = msg.get("msgtype")
            member = msgtype_members.get(msg_type)
            if not msg_name or not member:
                continue
            admin_handler = {
                "Heartbeat": "handleHeartbeatReceived",
                "TestRequest": "handleTestRequestReceived",
                "ResendRequest": "handleResendRequestReceived",
                "Reject": "handleRejectReceived",
                "BusinessMessageReject": "handleBusinessMessageRejectReceived",
                "SequenceReset": "handleSequenceResetReceived",
                "Logout": "handleLogoutReceived",
                "Logon": "handleLogonReceived",
            }.get(msg_name)
            if admin_handler:
                fh.write(f"\tcase MsgType::{member}: return dispatchTypedSession(session, &SessionT::{admin_handler}, app, sid, frame);\n")
            else:
                fh.write(f"\tcase MsgType::{member}: return dispatchTyped<{msg_name}>(app, sid, frame);\n")
        fh.write("\tdefault:\n")
        fh.write(f"\t\treturn session.sendReject(\n")
        fh.write("\t\t\tframe.msgSeqNum,\n")
        fh.write(f"\t\t\t{ns}::field_id::MsgType,\n")
        fh.write("\t\t\t\"unsupported message type\",\n")
        fh.write(f"\t\t\t{ns}::enums::SessionRejectReason::{invalid_msg_type}\n")
        fh.write("\t\t);\n")
        fh.write("\t}\n")
        fh.write("}\n\n")
        fh.write(f"}} // namespace {ns}::engine\n")


def generate(engine_dir: Path, spec: dict):
    engine_dir.mkdir(parents=True, exist_ok=True)
    ns, include_root, msgtype_members, session_reject_members = _build_context(spec)
    cpp_engine_dir = engine_dir.parents[2] / "cpp" / include_root / "engine"
    cpp_engine_dir.mkdir(parents=True, exist_ok=True)
    _write_protocol_header(engine_dir / "protocol.h", ns, include_root)
    _write_session_header(engine_dir / "session.h", ns, include_root, session_reject_members)
    _write_session_cpp(cpp_engine_dir / "session.cpp", ns, include_root)
    _write_inbound_dispatch_header(
        engine_dir / "inbound_dispatch.h",
        ns,
        include_root,
        spec,
        msgtype_members,
        session_reject_members,
    )
    _write_outbound_prepare_header(engine_dir / "outbound_prepare.h", ns, include_root)
    _write_tcp_frame_view_header(engine_dir / "tcp_frame_view.h", ns, include_root)
    print(f"[ok] Generated engine files in {engine_dir} and {cpp_engine_dir}")
