// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 6d39a981899ab600

#pragma once

#include <cstdint>
#include <cstddef>
#include <cstring>

#ifdef _WIN32
#pragma push_macro("ABSOLUTE")
#pragma push_macro("PERCENTAGE")
#pragma push_macro("PER_UNIT")
#pragma push_macro("CORRECTION")
#pragma push_macro("ERROR")
#pragma push_macro("DELETE")
#pragma push_macro("constant")
#undef ABSOLUTE
#undef PERCENTAGE
#undef PER_UNIT
#undef CORRECTION
#undef ERROR
#undef DELETE
#undef constant
#endif

namespace fix42 {
namespace enums {

enum class AdvSide : char {
	BUY                                      = 'B',
	SELL                                     = 'S',
	TRADE                                    = 'T',
	CROSS                                    = 'X',
};

enum class AdvTransType : uint8_t {
	CANCEL,
	NEW,
	REPLACE,
};

[[nodiscard]] constexpr const char *to_cstr(AdvTransType v) noexcept {
	switch (v) {
		case AdvTransType::CANCEL                          : return "C";
		case AdvTransType::NEW                             : return "N";
		case AdvTransType::REPLACE                         : return "R";
	}
	return "";
}

[[nodiscard]] inline bool parse_AdvTransType(const char *s, AdvTransType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "C") == 0) { out = AdvTransType::CANCEL; return true; }
	if (std::strcmp(s, "N") == 0) { out = AdvTransType::NEW; return true; }
	if (std::strcmp(s, "R") == 0) { out = AdvTransType::REPLACE; return true; }
	return false;
}

enum class CommType : char {
	PER_UNIT                                 = '1',
	PERCENT                                  = '2',
	ABSOLUTE                                 = '3',
};

enum class ExecInstBit : uint8_t {
	STAY_ON_OFFER_SIDE,
	NOT_HELD,
	WORK,
	GO_ALONG,
	OVER_THE_DAY,
	HELD,
	PARTICIPATE_DO_NOT_INITIATE,
	STRICT_SCALE,
	TRY_TO_SCALE,
	STAY_ON_BID_SIDE,
	NO_CROSS,
	OK_TO_CROSS,
	CALL_FIRST,
	PERCENT_OF_VOLUME,
	DO_NOT_INCREASE,
	DO_NOT_REDUCE,
	ALL_OR_NONE,
	INSTITUTIONS_ONLY,
	LAST_PEG,
	MID_PRICE_PEG,
	NON_NEGOTIABLE,
	OPENING_PEG,
	MARKET_PEG,
	PRIMARY_PEG,
	SUSPEND,
	FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER,
	CUSTOMER_DISPLAY_INSTRUCTION,
	NETTING,
	PEG_TO_VWAP,
};

using ExecInstMask = uint64_t;

constexpr ExecInstMask bit(ExecInstBit b) noexcept { return 1ull << (uint8_t)b; }
constexpr ExecInstMask set(ExecInstMask m, ExecInstBit b) noexcept { return m | bit(b); }
constexpr bool has(ExecInstMask m, ExecInstBit b) noexcept { return (m & bit(b)) != 0; }

[[nodiscard]] inline bool parse_ExecInst(const char *s, ExecInstMask &out) noexcept {
	out = 0;
	if (!s) return false;
	const char *p = s;
	while (*p) {
		if (*p == ' ') { ++p; continue; }
		switch (*p) {
			case '0': out |= bit(ExecInstBit::STAY_ON_OFFER_SIDE); break;
			case '1': out |= bit(ExecInstBit::NOT_HELD); break;
			case '2': out |= bit(ExecInstBit::WORK); break;
			case '3': out |= bit(ExecInstBit::GO_ALONG); break;
			case '4': out |= bit(ExecInstBit::OVER_THE_DAY); break;
			case '5': out |= bit(ExecInstBit::HELD); break;
			case '6': out |= bit(ExecInstBit::PARTICIPATE_DO_NOT_INITIATE); break;
			case '7': out |= bit(ExecInstBit::STRICT_SCALE); break;
			case '8': out |= bit(ExecInstBit::TRY_TO_SCALE); break;
			case '9': out |= bit(ExecInstBit::STAY_ON_BID_SIDE); break;
			case 'A': out |= bit(ExecInstBit::NO_CROSS); break;
			case 'B': out |= bit(ExecInstBit::OK_TO_CROSS); break;
			case 'C': out |= bit(ExecInstBit::CALL_FIRST); break;
			case 'D': out |= bit(ExecInstBit::PERCENT_OF_VOLUME); break;
			case 'E': out |= bit(ExecInstBit::DO_NOT_INCREASE); break;
			case 'F': out |= bit(ExecInstBit::DO_NOT_REDUCE); break;
			case 'G': out |= bit(ExecInstBit::ALL_OR_NONE); break;
			case 'I': out |= bit(ExecInstBit::INSTITUTIONS_ONLY); break;
			case 'L': out |= bit(ExecInstBit::LAST_PEG); break;
			case 'M': out |= bit(ExecInstBit::MID_PRICE_PEG); break;
			case 'N': out |= bit(ExecInstBit::NON_NEGOTIABLE); break;
			case 'O': out |= bit(ExecInstBit::OPENING_PEG); break;
			case 'P': out |= bit(ExecInstBit::MARKET_PEG); break;
			case 'R': out |= bit(ExecInstBit::PRIMARY_PEG); break;
			case 'S': out |= bit(ExecInstBit::SUSPEND); break;
			case 'T': out |= bit(ExecInstBit::FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER); break;
			case 'U': out |= bit(ExecInstBit::CUSTOMER_DISPLAY_INSTRUCTION); break;
			case 'V': out |= bit(ExecInstBit::NETTING); break;
			case 'W': out |= bit(ExecInstBit::PEG_TO_VWAP); break;
		}
		++p;
	}
	return true;
}

[[nodiscard]] inline const char *to_string_ExecInst(ExecInstMask m, char *buf, std::size_t cap) noexcept {
	std::size_t pos = 0;
	auto append = [&](const char *t){ std::size_t len=std::strlen(t); if(pos+len+1<cap){ std::memcpy(buf+pos,t,len); pos+=len; buf[pos++]=' '; } };
	if (has(m, ExecInstBit::STAY_ON_OFFER_SIDE)) append("0");
	if (has(m, ExecInstBit::NOT_HELD)) append("1");
	if (has(m, ExecInstBit::WORK)) append("2");
	if (has(m, ExecInstBit::GO_ALONG)) append("3");
	if (has(m, ExecInstBit::OVER_THE_DAY)) append("4");
	if (has(m, ExecInstBit::HELD)) append("5");
	if (has(m, ExecInstBit::PARTICIPATE_DO_NOT_INITIATE)) append("6");
	if (has(m, ExecInstBit::STRICT_SCALE)) append("7");
	if (has(m, ExecInstBit::TRY_TO_SCALE)) append("8");
	if (has(m, ExecInstBit::STAY_ON_BID_SIDE)) append("9");
	if (has(m, ExecInstBit::NO_CROSS)) append("A");
	if (has(m, ExecInstBit::OK_TO_CROSS)) append("B");
	if (has(m, ExecInstBit::CALL_FIRST)) append("C");
	if (has(m, ExecInstBit::PERCENT_OF_VOLUME)) append("D");
	if (has(m, ExecInstBit::DO_NOT_INCREASE)) append("E");
	if (has(m, ExecInstBit::DO_NOT_REDUCE)) append("F");
	if (has(m, ExecInstBit::ALL_OR_NONE)) append("G");
	if (has(m, ExecInstBit::INSTITUTIONS_ONLY)) append("I");
	if (has(m, ExecInstBit::LAST_PEG)) append("L");
	if (has(m, ExecInstBit::MID_PRICE_PEG)) append("M");
	if (has(m, ExecInstBit::NON_NEGOTIABLE)) append("N");
	if (has(m, ExecInstBit::OPENING_PEG)) append("O");
	if (has(m, ExecInstBit::MARKET_PEG)) append("P");
	if (has(m, ExecInstBit::PRIMARY_PEG)) append("R");
	if (has(m, ExecInstBit::SUSPEND)) append("S");
	if (has(m, ExecInstBit::FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER)) append("T");
	if (has(m, ExecInstBit::CUSTOMER_DISPLAY_INSTRUCTION)) append("U");
	if (has(m, ExecInstBit::NETTING)) append("V");
	if (has(m, ExecInstBit::PEG_TO_VWAP)) append("W");
	if (pos > 0) buf[pos-1] = '\0'; else if (cap > 0) buf[0] = '\0';
	return buf;
}

enum class ExecTransType : char {
	NEW                                      = '0',
	CANCEL                                   = '1',
	CORRECT                                  = '2',
	STATUS                                   = '3',
};

enum class HandlInst : char {
	AUTOMATED_EXECUTION_NO_INTERVENTION      = '1',
	AUTOMATED_EXECUTION_INTERVENTION_OK      = '2',
	MANUAL_ORDER                             = '3',
};

enum class IDSource : uint8_t {
	CUSIP,
	SEDOL,
	QUIK,
	ISIN_NUMBER,
	RIC_CODE,
	ISO_CURRENCY_CODE,
	ISO_COUNTRY_CODE,
	EXCHANGE_SYMBOL,
	CONSOLIDATED_TAPE_ASSOCIATION,
};

[[nodiscard]] constexpr const char *to_cstr(IDSource v) noexcept {
	switch (v) {
		case IDSource::CUSIP                           : return "1";
		case IDSource::SEDOL                           : return "2";
		case IDSource::QUIK                            : return "3";
		case IDSource::ISIN_NUMBER                     : return "4";
		case IDSource::RIC_CODE                        : return "5";
		case IDSource::ISO_CURRENCY_CODE               : return "6";
		case IDSource::ISO_COUNTRY_CODE                : return "7";
		case IDSource::EXCHANGE_SYMBOL                 : return "8";
		case IDSource::CONSOLIDATED_TAPE_ASSOCIATION   : return "9";
	}
	return "";
}

[[nodiscard]] inline bool parse_IDSource(const char *s, IDSource &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = IDSource::CUSIP; return true; }
	if (std::strcmp(s, "2") == 0) { out = IDSource::SEDOL; return true; }
	if (std::strcmp(s, "3") == 0) { out = IDSource::QUIK; return true; }
	if (std::strcmp(s, "4") == 0) { out = IDSource::ISIN_NUMBER; return true; }
	if (std::strcmp(s, "5") == 0) { out = IDSource::RIC_CODE; return true; }
	if (std::strcmp(s, "6") == 0) { out = IDSource::ISO_CURRENCY_CODE; return true; }
	if (std::strcmp(s, "7") == 0) { out = IDSource::ISO_COUNTRY_CODE; return true; }
	if (std::strcmp(s, "8") == 0) { out = IDSource::EXCHANGE_SYMBOL; return true; }
	if (std::strcmp(s, "9") == 0) { out = IDSource::CONSOLIDATED_TAPE_ASSOCIATION; return true; }
	return false;
}

enum class IOIQltyInd : char {
	HIGH                                     = 'H',
	LOW                                      = 'L',
	MEDIUM                                   = 'M',
};

enum class IOIShares : uint8_t {
	LARGE,
	MEDIUM,
	SMALL,
};

[[nodiscard]] constexpr const char *to_cstr(IOIShares v) noexcept {
	switch (v) {
		case IOIShares::LARGE                           : return "L";
		case IOIShares::MEDIUM                          : return "M";
		case IOIShares::SMALL                           : return "S";
	}
	return "";
}

[[nodiscard]] inline bool parse_IOIShares(const char *s, IOIShares &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "L") == 0) { out = IOIShares::LARGE; return true; }
	if (std::strcmp(s, "M") == 0) { out = IOIShares::MEDIUM; return true; }
	if (std::strcmp(s, "S") == 0) { out = IOIShares::SMALL; return true; }
	return false;
}

enum class IOITransType : char {
	CANCEL                                   = 'C',
	NEW                                      = 'N',
	REPLACE                                  = 'R',
};

enum class LastCapacity : char {
	AGENT                                    = '1',
	CROSS_AS_AGENT                           = '2',
	CROSS_AS_PRINCIPAL                       = '3',
	PRINCIPAL                                = '4',
};

enum class MsgType : uint8_t {
	HEARTBEAT,
	TEST_REQUEST,
	RESEND_REQUEST,
	REJECT,
	SEQUENCE_RESET,
	LOGOUT,
	IOI,
	ADVERTISEMENT,
	EXECUTION_REPORT,
	ORDER_CANCEL_REJECT,
	LOGON,
	NEWS,
	EMAIL,
	NEW_ORDER_SINGLE,
	NEW_ORDER_LIST,
	ORDER_CANCEL_REQUEST,
	ORDER_CANCEL_REPLACE_REQUEST,
	ORDER_STATUS_REQUEST,
	ALLOCATION_INSTRUCTION,
	LIST_CANCEL_REQUEST,
	LIST_EXECUTE,
	LIST_STATUS_REQUEST,
	LIST_STATUS,
	ALLOCATION_INSTRUCTION_ACK,
	DONT_KNOW_TRADE,
	QUOTE_REQUEST,
	QUOTE,
	SETTLEMENT_INSTRUCTIONS,
	MARKET_DATA_REQUEST,
	MARKET_DATA_SNAPSHOT_FULL_REFRESH,
	MARKET_DATA_INCREMENTAL_REFRESH,
	MARKET_DATA_REQUEST_REJECT,
	QUOTE_CANCEL,
	QUOTE_STATUS_REQUEST,
	MASS_QUOTE_ACKNOWLEDGEMENT,
	SECURITY_DEFINITION_REQUEST,
	SECURITY_DEFINITION,
	SECURITY_STATUS_REQUEST,
	SECURITY_STATUS,
	TRADING_SESSION_STATUS_REQUEST,
	TRADING_SESSION_STATUS,
	MASS_QUOTE,
	BUSINESS_MESSAGE_REJECT,
	BID_REQUEST,
	BID_RESPONSE,
	LIST_STRIKE_PRICE,
	UNKNOWN = 255,
};

[[nodiscard]] constexpr const char *to_cstr(MsgType v) noexcept {
	switch (v) {
		case MsgType::HEARTBEAT                       : return "0";
		case MsgType::TEST_REQUEST                    : return "1";
		case MsgType::RESEND_REQUEST                  : return "2";
		case MsgType::REJECT                          : return "3";
		case MsgType::SEQUENCE_RESET                  : return "4";
		case MsgType::LOGOUT                          : return "5";
		case MsgType::IOI                             : return "6";
		case MsgType::ADVERTISEMENT                   : return "7";
		case MsgType::EXECUTION_REPORT                : return "8";
		case MsgType::ORDER_CANCEL_REJECT             : return "9";
		case MsgType::LOGON                           : return "A";
		case MsgType::NEWS                            : return "B";
		case MsgType::EMAIL                           : return "C";
		case MsgType::NEW_ORDER_SINGLE                : return "D";
		case MsgType::NEW_ORDER_LIST                  : return "E";
		case MsgType::ORDER_CANCEL_REQUEST            : return "F";
		case MsgType::ORDER_CANCEL_REPLACE_REQUEST    : return "G";
		case MsgType::ORDER_STATUS_REQUEST            : return "H";
		case MsgType::ALLOCATION_INSTRUCTION          : return "J";
		case MsgType::LIST_CANCEL_REQUEST             : return "K";
		case MsgType::LIST_EXECUTE                    : return "L";
		case MsgType::LIST_STATUS_REQUEST             : return "M";
		case MsgType::LIST_STATUS                     : return "N";
		case MsgType::ALLOCATION_INSTRUCTION_ACK      : return "P";
		case MsgType::DONT_KNOW_TRADE                 : return "Q";
		case MsgType::QUOTE_REQUEST                   : return "R";
		case MsgType::QUOTE                           : return "S";
		case MsgType::SETTLEMENT_INSTRUCTIONS         : return "T";
		case MsgType::MARKET_DATA_REQUEST             : return "V";
		case MsgType::MARKET_DATA_SNAPSHOT_FULL_REFRESH: return "W";
		case MsgType::MARKET_DATA_INCREMENTAL_REFRESH : return "X";
		case MsgType::MARKET_DATA_REQUEST_REJECT      : return "Y";
		case MsgType::QUOTE_CANCEL                    : return "Z";
		case MsgType::QUOTE_STATUS_REQUEST            : return "a";
		case MsgType::MASS_QUOTE_ACKNOWLEDGEMENT      : return "b";
		case MsgType::SECURITY_DEFINITION_REQUEST     : return "c";
		case MsgType::SECURITY_DEFINITION             : return "d";
		case MsgType::SECURITY_STATUS_REQUEST         : return "e";
		case MsgType::SECURITY_STATUS                 : return "f";
		case MsgType::TRADING_SESSION_STATUS_REQUEST  : return "g";
		case MsgType::TRADING_SESSION_STATUS          : return "h";
		case MsgType::MASS_QUOTE                      : return "i";
		case MsgType::BUSINESS_MESSAGE_REJECT         : return "j";
		case MsgType::BID_REQUEST                     : return "k";
		case MsgType::BID_RESPONSE                    : return "l";
		case MsgType::LIST_STRIKE_PRICE               : return "m";
		case MsgType::UNKNOWN                              : return "";
	}
	return "";
}

[[nodiscard]] inline bool parse_MsgType(const char *begin,
									   const char *end,
									   MsgType &out) noexcept {
	out = MsgType::UNKNOWN;

	if (!begin || !end || begin >= end) {
		return false;
	}

	const auto len = static_cast<std::size_t>(end - begin);

	switch (len) {
		case 1:
			switch (begin[0]) {
				case '0': out = MsgType::HEARTBEAT; return true;
				case '1': out = MsgType::TEST_REQUEST; return true;
				case '2': out = MsgType::RESEND_REQUEST; return true;
				case '3': out = MsgType::REJECT; return true;
				case '4': out = MsgType::SEQUENCE_RESET; return true;
				case '5': out = MsgType::LOGOUT; return true;
				case '6': out = MsgType::IOI; return true;
				case '7': out = MsgType::ADVERTISEMENT; return true;
				case '8': out = MsgType::EXECUTION_REPORT; return true;
				case '9': out = MsgType::ORDER_CANCEL_REJECT; return true;
				case 'A': out = MsgType::LOGON; return true;
				case 'B': out = MsgType::NEWS; return true;
				case 'C': out = MsgType::EMAIL; return true;
				case 'D': out = MsgType::NEW_ORDER_SINGLE; return true;
				case 'E': out = MsgType::NEW_ORDER_LIST; return true;
				case 'F': out = MsgType::ORDER_CANCEL_REQUEST; return true;
				case 'G': out = MsgType::ORDER_CANCEL_REPLACE_REQUEST; return true;
				case 'H': out = MsgType::ORDER_STATUS_REQUEST; return true;
				case 'J': out = MsgType::ALLOCATION_INSTRUCTION; return true;
				case 'K': out = MsgType::LIST_CANCEL_REQUEST; return true;
				case 'L': out = MsgType::LIST_EXECUTE; return true;
				case 'M': out = MsgType::LIST_STATUS_REQUEST; return true;
				case 'N': out = MsgType::LIST_STATUS; return true;
				case 'P': out = MsgType::ALLOCATION_INSTRUCTION_ACK; return true;
				case 'Q': out = MsgType::DONT_KNOW_TRADE; return true;
				case 'R': out = MsgType::QUOTE_REQUEST; return true;
				case 'S': out = MsgType::QUOTE; return true;
				case 'T': out = MsgType::SETTLEMENT_INSTRUCTIONS; return true;
				case 'V': out = MsgType::MARKET_DATA_REQUEST; return true;
				case 'W': out = MsgType::MARKET_DATA_SNAPSHOT_FULL_REFRESH; return true;
				case 'X': out = MsgType::MARKET_DATA_INCREMENTAL_REFRESH; return true;
				case 'Y': out = MsgType::MARKET_DATA_REQUEST_REJECT; return true;
				case 'Z': out = MsgType::QUOTE_CANCEL; return true;
				case 'a': out = MsgType::QUOTE_STATUS_REQUEST; return true;
				case 'b': out = MsgType::MASS_QUOTE_ACKNOWLEDGEMENT; return true;
				case 'c': out = MsgType::SECURITY_DEFINITION_REQUEST; return true;
				case 'd': out = MsgType::SECURITY_DEFINITION; return true;
				case 'e': out = MsgType::SECURITY_STATUS_REQUEST; return true;
				case 'f': out = MsgType::SECURITY_STATUS; return true;
				case 'g': out = MsgType::TRADING_SESSION_STATUS_REQUEST; return true;
				case 'h': out = MsgType::TRADING_SESSION_STATUS; return true;
				case 'i': out = MsgType::MASS_QUOTE; return true;
				case 'j': out = MsgType::BUSINESS_MESSAGE_REJECT; return true;
				case 'k': out = MsgType::BID_REQUEST; return true;
				case 'l': out = MsgType::BID_RESPONSE; return true;
				case 'm': out = MsgType::LIST_STRIKE_PRICE; return true;
				default: return false;
			}

		default:
			break;
	}

	return false;
}

enum class OrdStatus : char {
	NEW                                      = '0',
	PARTIALLY_FILLED                         = '1',
	FILLED                                   = '2',
	DONE_FOR_DAY                             = '3',
	CANCELED                                 = '4',
	REPLACED                                 = '5',
	PENDING_CANCEL                           = '6',
	STOPPED                                  = '7',
	REJECTED                                 = '8',
	SUSPENDED                                = '9',
	PENDING_NEW                              = 'A',
	CALCULATED                               = 'B',
	EXPIRED                                  = 'C',
	ACCEPTED_FOR_BIDDING                     = 'D',
	PENDING_REPLACE                          = 'E',
};

enum class OrdType : char {
	MARKET                                   = '1',
	LIMIT                                    = '2',
	STOP                                     = '3',
	STOP_LIMIT                               = '4',
	MARKET_ON_CLOSE                          = '5',
	WITH_OR_WITHOUT                          = '6',
	LIMIT_OR_BETTER                          = '7',
	LIMIT_WITH_OR_WITHOUT                    = '8',
	ON_BASIS                                 = '9',
	ON_CLOSE                                 = 'A',
	LIMIT_ON_CLOSE                           = 'B',
	FOREX_MARKET                             = 'C',
	PREVIOUSLY_QUOTED                        = 'D',
	PREVIOUSLY_INDICATED                     = 'E',
	FOREX_LIMIT                              = 'F',
	FOREX_SWAP                               = 'G',
	FOREX_PREVIOUSLY_QUOTED                  = 'H',
	FUNARI                                   = 'I',
	PEGGED                                   = 'P',
};

enum class Rule80A : char {
	AGENCY_SINGLE_ORDER                      = 'A',
	SHORT_EXEMPT_TRANSACTION_A_TYPE          = 'B',
	PROPRIETARY_NON_ALGO                     = 'C',
	PROGRAM_ORDER_MEMBER                     = 'D',
	SHORT_EXEMPT_TRANSACTION_FOR_PRINCIPAL   = 'E',
	SHORT_EXEMPT_TRANSACTION_W_TYPE          = 'F',
	SHORT_EXEMPT_TRANSACTION_I_TYPE          = 'H',
	INDIVIDUAL_INVESTOR                      = 'I',
	PROPRIETARY_ALGO                         = 'J',
	AGENCY_ALGO                              = 'K',
	SHORT_EXEMPT_TRANSACTION_MEMBER_AFFLIATED = 'L',
	PROGRAM_ORDER_OTHER_MEMBER               = 'M',
	AGENT_FOR_OTHER_MEMBER                   = 'N',
	PROPRIETARY_TRANSACTION_AFFILIATED       = 'O',
	PRINCIPAL                                = 'P',
	TRANSACTION_NON_MEMBER                   = 'R',
	SPECIALIST_TRADES                        = 'S',
	TRANSACTION_UNAFFILIATED_MEMBER          = 'T',
	AGENCY_INDEX_ARB                         = 'U',
	ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER = 'W',
	SHORT_EXEMPT_TRANSACTION_MEMBER_NOT_AFFLIATED = 'X',
	AGENCY_NON_ALGO                          = 'Y',
	SHORT_EXEMPT_TRANSACTION_NON_MEMBER      = 'Z',
};

enum class Side : char {
	BUY                                      = '1',
	SELL                                     = '2',
	BUY_MINUS                                = '3',
	SELL_PLUS                                = '4',
	SELL_SHORT                               = '5',
	SELL_SHORT_EXEMPT                        = '6',
	UNDISCLOSED                              = '7',
	CROSS                                    = '8',
	CROSS_SHORT                              = '9',
};

enum class TimeInForce : char {
	DAY                                      = '0',
	GOOD_TILL_CANCEL                         = '1',
	AT_THE_OPENING                           = '2',
	IMMEDIATE_OR_CANCEL                      = '3',
	FILL_OR_KILL                             = '4',
	GOOD_TILL_CROSSING                       = '5',
	GOOD_TILL_DATE                           = '6',
};

enum class Urgency : char {
	NORMAL                                   = '0',
	FLASH                                    = '1',
	BACKGROUND                               = '2',
};

enum class SettlmntTyp : char {
	REGULAR                                  = '0',
	CASH                                     = '1',
	NEXT_DAY                                 = '2',
	T_PLUS2                                  = '3',
	T_PLUS3                                  = '4',
	T_PLUS4                                  = '5',
	FUTURE                                   = '6',
	WHEN_AND_IF_ISSUED                       = '7',
	SELLERS_OPTION                           = '8',
	T_PLUS5                                  = '9',
};

enum class AllocTransType : char {
	NEW                                      = '0',
	REPLACE                                  = '1',
	CANCEL                                   = '2',
	PRELIMINARY                              = '3',
	CALCULATED                               = '4',
	CALCULATED_WITHOUT_PRELIMINARY           = '5',
};

enum class OpenClose : char {
	CLOSE                                    = 'C',
	OPEN                                     = 'O',
};

enum class ProcessCode : char {
	REGULAR                                  = '0',
	SOFT_DOLLAR                              = '1',
	STEP_IN                                  = '2',
	STEP_OUT                                 = '3',
	SOFT_DOLLAR_STEP_IN                      = '4',
	SOFT_DOLLAR_STEP_OUT                     = '5',
	PLAN_SPONSOR                             = '6',
};

enum class AllocStatus : uint8_t {
	ACCEPTED,
	BLOCK_LEVEL_REJECT,
	ACCOUNT_LEVEL_REJECT,
	RECEIVED,
};

[[nodiscard]] constexpr const char *to_cstr(AllocStatus v) noexcept {
	switch (v) {
		case AllocStatus::ACCEPTED                        : return "0";
		case AllocStatus::BLOCK_LEVEL_REJECT              : return "1";
		case AllocStatus::ACCOUNT_LEVEL_REJECT            : return "2";
		case AllocStatus::RECEIVED                        : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_AllocStatus(const char *s, AllocStatus &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = AllocStatus::ACCEPTED; return true; }
	if (std::strcmp(s, "1") == 0) { out = AllocStatus::BLOCK_LEVEL_REJECT; return true; }
	if (std::strcmp(s, "2") == 0) { out = AllocStatus::ACCOUNT_LEVEL_REJECT; return true; }
	if (std::strcmp(s, "3") == 0) { out = AllocStatus::RECEIVED; return true; }
	return false;
}

enum class AllocRejCode : uint8_t {
	UNKNOWN_ACCOUNT,
	INCORRECT_QUANTITY,
	INCORRECT_AVERAGEG_PRICE,
	UNKNOWN_EXECUTING_BROKER_MNEMONIC,
	COMMISSION_DIFFERENCE,
	UNKNOWN_ORDER_ID,
	UNKNOWN_LIST_ID,
	OTHER_SEE_TEXT,
};

[[nodiscard]] constexpr const char *to_cstr(AllocRejCode v) noexcept {
	switch (v) {
		case AllocRejCode::UNKNOWN_ACCOUNT                 : return "0";
		case AllocRejCode::INCORRECT_QUANTITY              : return "1";
		case AllocRejCode::INCORRECT_AVERAGEG_PRICE        : return "2";
		case AllocRejCode::UNKNOWN_EXECUTING_BROKER_MNEMONIC: return "3";
		case AllocRejCode::COMMISSION_DIFFERENCE           : return "4";
		case AllocRejCode::UNKNOWN_ORDER_ID                : return "5";
		case AllocRejCode::UNKNOWN_LIST_ID                 : return "6";
		case AllocRejCode::OTHER_SEE_TEXT                  : return "7";
	}
	return "";
}

[[nodiscard]] inline bool parse_AllocRejCode(const char *s, AllocRejCode &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = AllocRejCode::UNKNOWN_ACCOUNT; return true; }
	if (std::strcmp(s, "1") == 0) { out = AllocRejCode::INCORRECT_QUANTITY; return true; }
	if (std::strcmp(s, "2") == 0) { out = AllocRejCode::INCORRECT_AVERAGEG_PRICE; return true; }
	if (std::strcmp(s, "3") == 0) { out = AllocRejCode::UNKNOWN_EXECUTING_BROKER_MNEMONIC; return true; }
	if (std::strcmp(s, "4") == 0) { out = AllocRejCode::COMMISSION_DIFFERENCE; return true; }
	if (std::strcmp(s, "5") == 0) { out = AllocRejCode::UNKNOWN_ORDER_ID; return true; }
	if (std::strcmp(s, "6") == 0) { out = AllocRejCode::UNKNOWN_LIST_ID; return true; }
	if (std::strcmp(s, "7") == 0) { out = AllocRejCode::OTHER_SEE_TEXT; return true; }
	return false;
}

enum class EmailType : char {
	NEW                                      = '0',
	REPLY                                    = '1',
	ADMIN_REPLY                              = '2',
};

enum class EncryptMethod : uint8_t {
	NONE,
	PKCS,
	DES,
	PKCSDES,
	PGPDES,
	PGPDESMD5,
	PEM,
};

[[nodiscard]] constexpr const char *to_cstr(EncryptMethod v) noexcept {
	switch (v) {
		case EncryptMethod::NONE                            : return "0";
		case EncryptMethod::PKCS                            : return "1";
		case EncryptMethod::DES                             : return "2";
		case EncryptMethod::PKCSDES                         : return "3";
		case EncryptMethod::PGPDES                          : return "4";
		case EncryptMethod::PGPDESMD5                       : return "5";
		case EncryptMethod::PEM                             : return "6";
	}
	return "";
}

[[nodiscard]] inline bool parse_EncryptMethod(const char *s, EncryptMethod &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = EncryptMethod::NONE; return true; }
	if (std::strcmp(s, "1") == 0) { out = EncryptMethod::PKCS; return true; }
	if (std::strcmp(s, "2") == 0) { out = EncryptMethod::DES; return true; }
	if (std::strcmp(s, "3") == 0) { out = EncryptMethod::PKCSDES; return true; }
	if (std::strcmp(s, "4") == 0) { out = EncryptMethod::PGPDES; return true; }
	if (std::strcmp(s, "5") == 0) { out = EncryptMethod::PGPDESMD5; return true; }
	if (std::strcmp(s, "6") == 0) { out = EncryptMethod::PEM; return true; }
	return false;
}

enum class CxlRejReason : uint8_t {
	TOO_LATE_TO_CANCEL,
	UNKNOWN_ORDER,
	BROKER_CREDIT,
	ORDER_ALREADY_IN_PENDING_STATUS,
};

[[nodiscard]] constexpr const char *to_cstr(CxlRejReason v) noexcept {
	switch (v) {
		case CxlRejReason::TOO_LATE_TO_CANCEL              : return "0";
		case CxlRejReason::UNKNOWN_ORDER                   : return "1";
		case CxlRejReason::BROKER_CREDIT                   : return "2";
		case CxlRejReason::ORDER_ALREADY_IN_PENDING_STATUS : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_CxlRejReason(const char *s, CxlRejReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = CxlRejReason::TOO_LATE_TO_CANCEL; return true; }
	if (std::strcmp(s, "1") == 0) { out = CxlRejReason::UNKNOWN_ORDER; return true; }
	if (std::strcmp(s, "2") == 0) { out = CxlRejReason::BROKER_CREDIT; return true; }
	if (std::strcmp(s, "3") == 0) { out = CxlRejReason::ORDER_ALREADY_IN_PENDING_STATUS; return true; }
	return false;
}

enum class OrdRejReason : uint8_t {
	BROKER_CREDIT,
	UNKNOWN_SYMBOL,
	EXCHANGE_CLOSED,
	ORDER_EXCEEDS_LIMIT,
	TOO_LATE_TO_ENTER,
	UNKNOWN_ORDER,
	DUPLICATE_ORDER,
	DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER,
	STALE_ORDER,
};

[[nodiscard]] constexpr const char *to_cstr(OrdRejReason v) noexcept {
	switch (v) {
		case OrdRejReason::BROKER_CREDIT                   : return "0";
		case OrdRejReason::UNKNOWN_SYMBOL                  : return "1";
		case OrdRejReason::EXCHANGE_CLOSED                 : return "2";
		case OrdRejReason::ORDER_EXCEEDS_LIMIT             : return "3";
		case OrdRejReason::TOO_LATE_TO_ENTER               : return "4";
		case OrdRejReason::UNKNOWN_ORDER                   : return "5";
		case OrdRejReason::DUPLICATE_ORDER                 : return "6";
		case OrdRejReason::DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER: return "7";
		case OrdRejReason::STALE_ORDER                     : return "8";
	}
	return "";
}

[[nodiscard]] inline bool parse_OrdRejReason(const char *s, OrdRejReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = OrdRejReason::BROKER_CREDIT; return true; }
	if (std::strcmp(s, "1") == 0) { out = OrdRejReason::UNKNOWN_SYMBOL; return true; }
	if (std::strcmp(s, "2") == 0) { out = OrdRejReason::EXCHANGE_CLOSED; return true; }
	if (std::strcmp(s, "3") == 0) { out = OrdRejReason::ORDER_EXCEEDS_LIMIT; return true; }
	if (std::strcmp(s, "4") == 0) { out = OrdRejReason::TOO_LATE_TO_ENTER; return true; }
	if (std::strcmp(s, "5") == 0) { out = OrdRejReason::UNKNOWN_ORDER; return true; }
	if (std::strcmp(s, "6") == 0) { out = OrdRejReason::DUPLICATE_ORDER; return true; }
	if (std::strcmp(s, "7") == 0) { out = OrdRejReason::DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER; return true; }
	if (std::strcmp(s, "8") == 0) { out = OrdRejReason::STALE_ORDER; return true; }
	return false;
}

enum class IOIQualifier : char {
	ALL_OR_NONE                              = 'A',
	AT_THE_CLOSE                             = 'C',
	IN_TOUCH_WITH                            = 'I',
	LIMIT                                    = 'L',
	MORE_BEHIND                              = 'M',
	AT_THE_OPEN                              = 'O',
	TAKING_A_POSITION                        = 'P',
	AT_THE_MARKET                            = 'Q',
	READY_TO_TRADE                           = 'R',
	PORTFOLIO_SHOWN                          = 'S',
	THROUGH_THE_DAY                          = 'T',
	VERSUS                                   = 'V',
	INDICATION                               = 'W',
	CROSSING_OPPORTUNITY                     = 'X',
	AT_THE_MIDPOINT                          = 'Y',
	PRE_OPEN                                 = 'Z',
};

enum class DKReason : char {
	UNKNOWN_SYMBOL                           = 'A',
	WRONG_SIDE                               = 'B',
	QUANTITY_EXCEEDS_ORDER                   = 'C',
	NO_MATCHING_ORDER                        = 'D',
	PRICE_EXCEEDS_LIMIT                      = 'E',
	OTHER                                    = 'Z',
};

enum class MiscFeeType : char {
	REGULATORY                               = '1',
	TAX                                      = '2',
	LOCAL_COMMISSION                         = '3',
	EXCHANGE_FEES                            = '4',
	STAMP                                    = '5',
	LEVY                                     = '6',
	OTHER                                    = '7',
	MARKUP                                   = '8',
	CONSUMPTION_TAX                          = '9',
};

enum class ExecType : char {
	NEW                                      = '0',
	PARTIAL_FILL                             = '1',
	FILL                                     = '2',
	DONE_FOR_DAY                             = '3',
	CANCELED                                 = '4',
	REPLACED                                 = '5',
	PENDING_CANCEL                           = '6',
	STOPPED                                  = '7',
	REJECTED                                 = '8',
	SUSPENDED                                = '9',
	PENDING_NEW                              = 'A',
	CALCULATED                               = 'B',
	EXPIRED                                  = 'C',
	RESTATED                                 = 'D',
	PENDING_REPLACE                          = 'E',
};

enum class SettlInstMode : char {
	DEFAULT                                  = '0',
	STANDING_INSTRUCTIONS_PROVIDED           = '1',
	SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING   = '2',
	SPECIFIC_ALLOCATION_ACCOUNT_STANDING     = '3',
};

enum class SettlInstTransType : char {
	CANCEL                                   = 'C',
	NEW                                      = 'N',
	REPLACE                                  = 'R',
};

enum class SettlInstSource : char {
	BROKER_CREDIT                            = '1',
	INSTITUTION                              = '2',
};

enum class SettlLocation : uint8_t {
	CEDEL,
	DEPOSITORY_TRUST_COMPANY,
	EURO_CLEAR,
	FEDERAL_BOOK_ENTRY,
	LOCAL_MARKET_SETTLE_LOCATION,
	PHYSICAL,
	PARTICIPANT_TRUST_COMPANY,
};

[[nodiscard]] constexpr const char *to_cstr(SettlLocation v) noexcept {
	switch (v) {
		case SettlLocation::CEDEL                           : return "CED";
		case SettlLocation::DEPOSITORY_TRUST_COMPANY        : return "DTC";
		case SettlLocation::EURO_CLEAR                      : return "EUR";
		case SettlLocation::FEDERAL_BOOK_ENTRY              : return "FED";
		case SettlLocation::LOCAL_MARKET_SETTLE_LOCATION    : return "ISO Country Code";
		case SettlLocation::PHYSICAL                        : return "PNY";
		case SettlLocation::PARTICIPANT_TRUST_COMPANY       : return "PTC";
	}
	return "";
}

[[nodiscard]] inline bool parse_SettlLocation(const char *s, SettlLocation &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "CED") == 0) { out = SettlLocation::CEDEL; return true; }
	if (std::strcmp(s, "DTC") == 0) { out = SettlLocation::DEPOSITORY_TRUST_COMPANY; return true; }
	if (std::strcmp(s, "EUR") == 0) { out = SettlLocation::EURO_CLEAR; return true; }
	if (std::strcmp(s, "FED") == 0) { out = SettlLocation::FEDERAL_BOOK_ENTRY; return true; }
	if (std::strcmp(s, "ISO Country Code") == 0) { out = SettlLocation::LOCAL_MARKET_SETTLE_LOCATION; return true; }
	if (std::strcmp(s, "PNY") == 0) { out = SettlLocation::PHYSICAL; return true; }
	if (std::strcmp(s, "PTC") == 0) { out = SettlLocation::PARTICIPANT_TRUST_COMPANY; return true; }
	return false;
}

enum class SecurityType : uint8_t {
	WILDCARD,
	BANKERS_ACCEPTANCE,
	CONVERTIBLE_BOND,
	CERTIFICATE_OF_DEPOSIT,
	COLLATERALIZED_MORTGAGE_OBLIGATION,
	CORPORATE_BOND,
	COMMERCIAL_PAPER,
	CORPORATE_PRIVATE_PLACEMENT,
	COMMON_STOCK,
	FEDERAL_HOUSING_AUTHORITY,
	FEDERAL_HOME_LOAN,
	FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION,
	FOREIGN_EXCHANGE_CONTRACT,
	FUTURE,
	GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION,
	TREASURIES_AGENCY_DEBENTURE,
	IOETTE_MORTGAGE,
	MUTUAL_FUND,
	MORTGAGE_INTEREST_ONLY,
	MORTGAGE_PRINCIPAL_ONLY,
	MORTGAGE_PRIVATE_PLACEMENT,
	MISCELLANEOUS_PASS_THROUGH,
	MUNICIPAL_BOND,
	NO_SECURITY_TYPE,
	OPTION,
	PREFERRED_STOCK,
	REPURCHASE_AGREEMENT,
	REVERSE_REPURCHASE_AGREEMENT,
	STUDENT_LOAN_MARKETING_ASSOCIATION,
	TIME_DEPOSIT,
	US_TREASURY_BILL_OLD,
	WARRANT,
	CATS_TIGERS_AND_LIONS,
};

[[nodiscard]] constexpr const char *to_cstr(SecurityType v) noexcept {
	switch (v) {
		case SecurityType::WILDCARD                        : return "?";
		case SecurityType::BANKERS_ACCEPTANCE              : return "BA";
		case SecurityType::CONVERTIBLE_BOND                : return "CB";
		case SecurityType::CERTIFICATE_OF_DEPOSIT          : return "CD";
		case SecurityType::COLLATERALIZED_MORTGAGE_OBLIGATION: return "CMO";
		case SecurityType::CORPORATE_BOND                  : return "CORP";
		case SecurityType::COMMERCIAL_PAPER                : return "CP";
		case SecurityType::CORPORATE_PRIVATE_PLACEMENT     : return "CPP";
		case SecurityType::COMMON_STOCK                    : return "CS";
		case SecurityType::FEDERAL_HOUSING_AUTHORITY       : return "FHA";
		case SecurityType::FEDERAL_HOME_LOAN               : return "FHL";
		case SecurityType::FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION: return "FN";
		case SecurityType::FOREIGN_EXCHANGE_CONTRACT       : return "FOR";
		case SecurityType::FUTURE                          : return "FUT";
		case SecurityType::GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION: return "GN";
		case SecurityType::TREASURIES_AGENCY_DEBENTURE     : return "GOVT";
		case SecurityType::IOETTE_MORTGAGE                 : return "IET";
		case SecurityType::MUTUAL_FUND                     : return "MF";
		case SecurityType::MORTGAGE_INTEREST_ONLY          : return "MIO";
		case SecurityType::MORTGAGE_PRINCIPAL_ONLY         : return "MPO";
		case SecurityType::MORTGAGE_PRIVATE_PLACEMENT      : return "MPP";
		case SecurityType::MISCELLANEOUS_PASS_THROUGH      : return "MPT";
		case SecurityType::MUNICIPAL_BOND                  : return "MUNI";
		case SecurityType::NO_SECURITY_TYPE                : return "NONE";
		case SecurityType::OPTION                          : return "OPT";
		case SecurityType::PREFERRED_STOCK                 : return "PS";
		case SecurityType::REPURCHASE_AGREEMENT            : return "RP";
		case SecurityType::REVERSE_REPURCHASE_AGREEMENT    : return "RVRP";
		case SecurityType::STUDENT_LOAN_MARKETING_ASSOCIATION: return "SL";
		case SecurityType::TIME_DEPOSIT                    : return "TD";
		case SecurityType::US_TREASURY_BILL_OLD            : return "USTB";
		case SecurityType::WARRANT                         : return "WAR";
		case SecurityType::CATS_TIGERS_AND_LIONS           : return "ZOO";
	}
	return "";
}

[[nodiscard]] inline bool parse_SecurityType(const char *s, SecurityType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "?") == 0) { out = SecurityType::WILDCARD; return true; }
	if (std::strcmp(s, "BA") == 0) { out = SecurityType::BANKERS_ACCEPTANCE; return true; }
	if (std::strcmp(s, "CB") == 0) { out = SecurityType::CONVERTIBLE_BOND; return true; }
	if (std::strcmp(s, "CD") == 0) { out = SecurityType::CERTIFICATE_OF_DEPOSIT; return true; }
	if (std::strcmp(s, "CMO") == 0) { out = SecurityType::COLLATERALIZED_MORTGAGE_OBLIGATION; return true; }
	if (std::strcmp(s, "CORP") == 0) { out = SecurityType::CORPORATE_BOND; return true; }
	if (std::strcmp(s, "CP") == 0) { out = SecurityType::COMMERCIAL_PAPER; return true; }
	if (std::strcmp(s, "CPP") == 0) { out = SecurityType::CORPORATE_PRIVATE_PLACEMENT; return true; }
	if (std::strcmp(s, "CS") == 0) { out = SecurityType::COMMON_STOCK; return true; }
	if (std::strcmp(s, "FHA") == 0) { out = SecurityType::FEDERAL_HOUSING_AUTHORITY; return true; }
	if (std::strcmp(s, "FHL") == 0) { out = SecurityType::FEDERAL_HOME_LOAN; return true; }
	if (std::strcmp(s, "FN") == 0) { out = SecurityType::FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION; return true; }
	if (std::strcmp(s, "FOR") == 0) { out = SecurityType::FOREIGN_EXCHANGE_CONTRACT; return true; }
	if (std::strcmp(s, "FUT") == 0) { out = SecurityType::FUTURE; return true; }
	if (std::strcmp(s, "GN") == 0) { out = SecurityType::GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION; return true; }
	if (std::strcmp(s, "GOVT") == 0) { out = SecurityType::TREASURIES_AGENCY_DEBENTURE; return true; }
	if (std::strcmp(s, "IET") == 0) { out = SecurityType::IOETTE_MORTGAGE; return true; }
	if (std::strcmp(s, "MF") == 0) { out = SecurityType::MUTUAL_FUND; return true; }
	if (std::strcmp(s, "MIO") == 0) { out = SecurityType::MORTGAGE_INTEREST_ONLY; return true; }
	if (std::strcmp(s, "MPO") == 0) { out = SecurityType::MORTGAGE_PRINCIPAL_ONLY; return true; }
	if (std::strcmp(s, "MPP") == 0) { out = SecurityType::MORTGAGE_PRIVATE_PLACEMENT; return true; }
	if (std::strcmp(s, "MPT") == 0) { out = SecurityType::MISCELLANEOUS_PASS_THROUGH; return true; }
	if (std::strcmp(s, "MUNI") == 0) { out = SecurityType::MUNICIPAL_BOND; return true; }
	if (std::strcmp(s, "NONE") == 0) { out = SecurityType::NO_SECURITY_TYPE; return true; }
	if (std::strcmp(s, "OPT") == 0) { out = SecurityType::OPTION; return true; }
	if (std::strcmp(s, "PS") == 0) { out = SecurityType::PREFERRED_STOCK; return true; }
	if (std::strcmp(s, "RP") == 0) { out = SecurityType::REPURCHASE_AGREEMENT; return true; }
	if (std::strcmp(s, "RVRP") == 0) { out = SecurityType::REVERSE_REPURCHASE_AGREEMENT; return true; }
	if (std::strcmp(s, "SL") == 0) { out = SecurityType::STUDENT_LOAN_MARKETING_ASSOCIATION; return true; }
	if (std::strcmp(s, "TD") == 0) { out = SecurityType::TIME_DEPOSIT; return true; }
	if (std::strcmp(s, "USTB") == 0) { out = SecurityType::US_TREASURY_BILL_OLD; return true; }
	if (std::strcmp(s, "WAR") == 0) { out = SecurityType::WARRANT; return true; }
	if (std::strcmp(s, "ZOO") == 0) { out = SecurityType::CATS_TIGERS_AND_LIONS; return true; }
	return false;
}

enum class StandInstDbType : uint8_t {
	OTHER,
	DTCSID,
	THOMSON_ALERT,
	A_GLOBAL_CUSTODIAN,
};

[[nodiscard]] constexpr const char *to_cstr(StandInstDbType v) noexcept {
	switch (v) {
		case StandInstDbType::OTHER                           : return "0";
		case StandInstDbType::DTCSID                          : return "1";
		case StandInstDbType::THOMSON_ALERT                   : return "2";
		case StandInstDbType::A_GLOBAL_CUSTODIAN              : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_StandInstDbType(const char *s, StandInstDbType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = StandInstDbType::OTHER; return true; }
	if (std::strcmp(s, "1") == 0) { out = StandInstDbType::DTCSID; return true; }
	if (std::strcmp(s, "2") == 0) { out = StandInstDbType::THOMSON_ALERT; return true; }
	if (std::strcmp(s, "3") == 0) { out = StandInstDbType::A_GLOBAL_CUSTODIAN; return true; }
	return false;
}

enum class AllocLinkType : uint8_t {
	FX_NETTING,
	FX_SWAP,
};

[[nodiscard]] constexpr const char *to_cstr(AllocLinkType v) noexcept {
	switch (v) {
		case AllocLinkType::FX_NETTING                      : return "0";
		case AllocLinkType::FX_SWAP                         : return "1";
	}
	return "";
}

[[nodiscard]] inline bool parse_AllocLinkType(const char *s, AllocLinkType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = AllocLinkType::FX_NETTING; return true; }
	if (std::strcmp(s, "1") == 0) { out = AllocLinkType::FX_SWAP; return true; }
	return false;
}

enum class PutOrCall : uint8_t {
	PUT,
	CALL,
};

[[nodiscard]] constexpr const char *to_cstr(PutOrCall v) noexcept {
	switch (v) {
		case PutOrCall::PUT                             : return "0";
		case PutOrCall::CALL                            : return "1";
	}
	return "";
}

[[nodiscard]] inline bool parse_PutOrCall(const char *s, PutOrCall &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = PutOrCall::PUT; return true; }
	if (std::strcmp(s, "1") == 0) { out = PutOrCall::CALL; return true; }
	return false;
}

enum class CoveredOrUncovered : uint8_t {
	COVERED,
	UNCOVERED,
};

[[nodiscard]] constexpr const char *to_cstr(CoveredOrUncovered v) noexcept {
	switch (v) {
		case CoveredOrUncovered::COVERED                         : return "0";
		case CoveredOrUncovered::UNCOVERED                       : return "1";
	}
	return "";
}

[[nodiscard]] inline bool parse_CoveredOrUncovered(const char *s, CoveredOrUncovered &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = CoveredOrUncovered::COVERED; return true; }
	if (std::strcmp(s, "1") == 0) { out = CoveredOrUncovered::UNCOVERED; return true; }
	return false;
}

enum class CustomerOrFirm : uint8_t {
	CUSTOMER,
	FIRM,
};

[[nodiscard]] constexpr const char *to_cstr(CustomerOrFirm v) noexcept {
	switch (v) {
		case CustomerOrFirm::CUSTOMER                        : return "0";
		case CustomerOrFirm::FIRM                            : return "1";
	}
	return "";
}

[[nodiscard]] inline bool parse_CustomerOrFirm(const char *s, CustomerOrFirm &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = CustomerOrFirm::CUSTOMER; return true; }
	if (std::strcmp(s, "1") == 0) { out = CustomerOrFirm::FIRM; return true; }
	return false;
}

enum class AllocHandlInst : uint8_t {
	MATCH,
	FORWARD,
	FORWARD_AND_MATCH,
};

[[nodiscard]] constexpr const char *to_cstr(AllocHandlInst v) noexcept {
	switch (v) {
		case AllocHandlInst::MATCH                           : return "1";
		case AllocHandlInst::FORWARD                         : return "2";
		case AllocHandlInst::FORWARD_AND_MATCH               : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_AllocHandlInst(const char *s, AllocHandlInst &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = AllocHandlInst::MATCH; return true; }
	if (std::strcmp(s, "2") == 0) { out = AllocHandlInst::FORWARD; return true; }
	if (std::strcmp(s, "3") == 0) { out = AllocHandlInst::FORWARD_AND_MATCH; return true; }
	return false;
}

enum class RoutingType : uint8_t {
	TARGET_FIRM,
	TARGET_LIST,
	BLOCK_FIRM,
	BLOCK_LIST,
};

[[nodiscard]] constexpr const char *to_cstr(RoutingType v) noexcept {
	switch (v) {
		case RoutingType::TARGET_FIRM                     : return "1";
		case RoutingType::TARGET_LIST                     : return "2";
		case RoutingType::BLOCK_FIRM                      : return "3";
		case RoutingType::BLOCK_LIST                      : return "4";
	}
	return "";
}

[[nodiscard]] inline bool parse_RoutingType(const char *s, RoutingType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = RoutingType::TARGET_FIRM; return true; }
	if (std::strcmp(s, "2") == 0) { out = RoutingType::TARGET_LIST; return true; }
	if (std::strcmp(s, "3") == 0) { out = RoutingType::BLOCK_FIRM; return true; }
	if (std::strcmp(s, "4") == 0) { out = RoutingType::BLOCK_LIST; return true; }
	return false;
}

enum class Benchmark : char {
	CURVE                                    = '1',
	FIVE_YR                                  = '2',
	OLD5                                     = '3',
	TEN_YR                                   = '4',
	OLD10                                    = '5',
	THIRTY_YR                                = '6',
	OLD30                                    = '7',
	THREE_MOLIBOR                            = '8',
	SIX_MOLIBOR                              = '9',
};

enum class SubscriptionRequestType : char {
	SNAPSHOT                                 = '0',
	SNAPSHOT_AND_UPDATES                     = '1',
	DISABLE_PREVIOUS_SNAPSHOT                = '2',
};

enum class MDUpdateType : uint8_t {
	FULL_REFRESH,
	INCREMENTAL_REFRESH,
};

[[nodiscard]] constexpr const char *to_cstr(MDUpdateType v) noexcept {
	switch (v) {
		case MDUpdateType::FULL_REFRESH                    : return "0";
		case MDUpdateType::INCREMENTAL_REFRESH             : return "1";
	}
	return "";
}

[[nodiscard]] inline bool parse_MDUpdateType(const char *s, MDUpdateType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = MDUpdateType::FULL_REFRESH; return true; }
	if (std::strcmp(s, "1") == 0) { out = MDUpdateType::INCREMENTAL_REFRESH; return true; }
	return false;
}

enum class MDEntryType : char {
	BID                                      = '0',
	OFFER                                    = '1',
	TRADE                                    = '2',
	INDEX_VALUE                              = '3',
	OPENING_PRICE                            = '4',
	CLOSING_PRICE                            = '5',
	SETTLEMENT_PRICE                         = '6',
	TRADING_SESSION_HIGH_PRICE               = '7',
	TRADING_SESSION_LOW_PRICE                = '8',
	TRADING_SESSION_VWAP_PRICE               = '9',
};

enum class TickDirection : char {
	PLUS_TICK                                = '0',
	ZERO_PLUS_TICK                           = '1',
	MINUS_TICK                               = '2',
	ZERO_MINUS_TICK                          = '3',
};

enum class QuoteConditionBit : uint8_t {
	OPEN,
	CLOSED,
	EXCHANGE_BEST,
	CONSOLIDATED_BEST,
	LOCKED,
	CROSSED,
	DEPTH,
	FAST_TRADING,
	NON_FIRM,
};

using QuoteConditionMask = uint64_t;

constexpr QuoteConditionMask bit(QuoteConditionBit b) noexcept { return 1ull << (uint8_t)b; }
constexpr QuoteConditionMask set(QuoteConditionMask m, QuoteConditionBit b) noexcept { return m | bit(b); }
constexpr bool has(QuoteConditionMask m, QuoteConditionBit b) noexcept { return (m & bit(b)) != 0; }

[[nodiscard]] inline bool parse_QuoteCondition(const char *s, QuoteConditionMask &out) noexcept {
	out = 0;
	if (!s) return false;
	const char *p = s;
	while (*p) {
		if (*p == ' ') { ++p; continue; }
		switch (*p) {
			case 'A': out |= bit(QuoteConditionBit::OPEN); break;
			case 'B': out |= bit(QuoteConditionBit::CLOSED); break;
			case 'C': out |= bit(QuoteConditionBit::EXCHANGE_BEST); break;
			case 'D': out |= bit(QuoteConditionBit::CONSOLIDATED_BEST); break;
			case 'E': out |= bit(QuoteConditionBit::LOCKED); break;
			case 'F': out |= bit(QuoteConditionBit::CROSSED); break;
			case 'G': out |= bit(QuoteConditionBit::DEPTH); break;
			case 'H': out |= bit(QuoteConditionBit::FAST_TRADING); break;
			case 'I': out |= bit(QuoteConditionBit::NON_FIRM); break;
		}
		++p;
	}
	return true;
}

[[nodiscard]] inline const char *to_string_QuoteCondition(QuoteConditionMask m, char *buf, std::size_t cap) noexcept {
	std::size_t pos = 0;
	auto append = [&](const char *t){ std::size_t len=std::strlen(t); if(pos+len+1<cap){ std::memcpy(buf+pos,t,len); pos+=len; buf[pos++]=' '; } };
	if (has(m, QuoteConditionBit::OPEN)) append("A");
	if (has(m, QuoteConditionBit::CLOSED)) append("B");
	if (has(m, QuoteConditionBit::EXCHANGE_BEST)) append("C");
	if (has(m, QuoteConditionBit::CONSOLIDATED_BEST)) append("D");
	if (has(m, QuoteConditionBit::LOCKED)) append("E");
	if (has(m, QuoteConditionBit::CROSSED)) append("F");
	if (has(m, QuoteConditionBit::DEPTH)) append("G");
	if (has(m, QuoteConditionBit::FAST_TRADING)) append("H");
	if (has(m, QuoteConditionBit::NON_FIRM)) append("I");
	if (pos > 0) buf[pos-1] = '\0'; else if (cap > 0) buf[0] = '\0';
	return buf;
}

enum class TradeConditionBit : uint8_t {
	CASH,
	AVERAGE_PRICE_TRADE,
	CASH_TRADE,
	NEXT_DAY,
	OPENING,
	INTRADAY_TRADE_DETAIL,
	RULE127_TRADE,
	RULE155_TRADE,
	SOLD_LAST,
	NEXT_DAY_TRADE,
	OPENED,
	SELLER,
	SOLD,
	STOPPED_STOCK,
};

using TradeConditionMask = uint64_t;

constexpr TradeConditionMask bit(TradeConditionBit b) noexcept { return 1ull << (uint8_t)b; }
constexpr TradeConditionMask set(TradeConditionMask m, TradeConditionBit b) noexcept { return m | bit(b); }
constexpr bool has(TradeConditionMask m, TradeConditionBit b) noexcept { return (m & bit(b)) != 0; }

[[nodiscard]] inline bool parse_TradeCondition(const char *s, TradeConditionMask &out) noexcept {
	out = 0;
	if (!s) return false;
	const char *p = s;
	while (*p) {
		if (*p == ' ') { ++p; continue; }
		switch (*p) {
			case 'A': out |= bit(TradeConditionBit::CASH); break;
			case 'B': out |= bit(TradeConditionBit::AVERAGE_PRICE_TRADE); break;
			case 'C': out |= bit(TradeConditionBit::CASH_TRADE); break;
			case 'D': out |= bit(TradeConditionBit::NEXT_DAY); break;
			case 'E': out |= bit(TradeConditionBit::OPENING); break;
			case 'F': out |= bit(TradeConditionBit::INTRADAY_TRADE_DETAIL); break;
			case 'G': out |= bit(TradeConditionBit::RULE127_TRADE); break;
			case 'H': out |= bit(TradeConditionBit::RULE155_TRADE); break;
			case 'I': out |= bit(TradeConditionBit::SOLD_LAST); break;
			case 'J': out |= bit(TradeConditionBit::NEXT_DAY_TRADE); break;
			case 'K': out |= bit(TradeConditionBit::OPENED); break;
			case 'L': out |= bit(TradeConditionBit::SELLER); break;
			case 'M': out |= bit(TradeConditionBit::SOLD); break;
			case 'N': out |= bit(TradeConditionBit::STOPPED_STOCK); break;
		}
		++p;
	}
	return true;
}

[[nodiscard]] inline const char *to_string_TradeCondition(TradeConditionMask m, char *buf, std::size_t cap) noexcept {
	std::size_t pos = 0;
	auto append = [&](const char *t){ std::size_t len=std::strlen(t); if(pos+len+1<cap){ std::memcpy(buf+pos,t,len); pos+=len; buf[pos++]=' '; } };
	if (has(m, TradeConditionBit::CASH)) append("A");
	if (has(m, TradeConditionBit::AVERAGE_PRICE_TRADE)) append("B");
	if (has(m, TradeConditionBit::CASH_TRADE)) append("C");
	if (has(m, TradeConditionBit::NEXT_DAY)) append("D");
	if (has(m, TradeConditionBit::OPENING)) append("E");
	if (has(m, TradeConditionBit::INTRADAY_TRADE_DETAIL)) append("F");
	if (has(m, TradeConditionBit::RULE127_TRADE)) append("G");
	if (has(m, TradeConditionBit::RULE155_TRADE)) append("H");
	if (has(m, TradeConditionBit::SOLD_LAST)) append("I");
	if (has(m, TradeConditionBit::NEXT_DAY_TRADE)) append("J");
	if (has(m, TradeConditionBit::OPENED)) append("K");
	if (has(m, TradeConditionBit::SELLER)) append("L");
	if (has(m, TradeConditionBit::SOLD)) append("M");
	if (has(m, TradeConditionBit::STOPPED_STOCK)) append("N");
	if (pos > 0) buf[pos-1] = '\0'; else if (cap > 0) buf[0] = '\0';
	return buf;
}

enum class MDUpdateAction : char {
	NEW                                      = '0',
	CHANGE                                   = '1',
	DELETE                                   = '2',
};

enum class MDReqRejReason : char {
	UNKNOWN_SYMBOL                           = '0',
	DUPLICATE_MD_REQ_ID                      = '1',
	INSUFFICIENT_BANDWIDTH                   = '2',
	INSUFFICIENT_PERMISSIONS                 = '3',
	UNSUPPORTED_SUBSCRIPTION_REQUEST_TYPE    = '4',
	UNSUPPORTED_MARKET_DEPTH                 = '5',
	UNSUPPORTED_MD_UPDATE_TYPE               = '6',
	UNSUPPORTED_AGGREGATED_BOOK              = '7',
	UNSUPPORTED_MD_ENTRY_TYPE                = '8',
};

enum class DeleteReason : char {
	CANCELLATION                             = '0',
	ERROR                                    = '1',
};

enum class OpenCloseSettleFlag : char {
	DAILY_OPEN                               = '0',
	SESSION_OPEN                             = '1',
	DELIVERY_SETTLEMENT_ENTRY                = '2',
};

enum class FinancialStatus : char {
	BANKRUPT                                 = '1',
};

enum class CorporateAction : char {
	EX_DIVIDEND                              = 'A',
	EX_DISTRIBUTION                          = 'B',
	EX_RIGHTS                                = 'C',
	NEW                                      = 'D',
	EX_INTEREST                              = 'E',
};

enum class QuoteStatus : uint8_t {
	ACCEPTED,
	CANCEL_FOR_SYMBOL,
	CANCELED_FOR_SECURITY_TYPE,
	CANCELED_FOR_UNDERLYING,
	CANCELED_ALL,
	REJECTED,
};

[[nodiscard]] constexpr const char *to_cstr(QuoteStatus v) noexcept {
	switch (v) {
		case QuoteStatus::ACCEPTED                        : return "0";
		case QuoteStatus::CANCEL_FOR_SYMBOL               : return "1";
		case QuoteStatus::CANCELED_FOR_SECURITY_TYPE      : return "2";
		case QuoteStatus::CANCELED_FOR_UNDERLYING         : return "3";
		case QuoteStatus::CANCELED_ALL                    : return "4";
		case QuoteStatus::REJECTED                        : return "5";
	}
	return "";
}

[[nodiscard]] inline bool parse_QuoteStatus(const char *s, QuoteStatus &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = QuoteStatus::ACCEPTED; return true; }
	if (std::strcmp(s, "1") == 0) { out = QuoteStatus::CANCEL_FOR_SYMBOL; return true; }
	if (std::strcmp(s, "2") == 0) { out = QuoteStatus::CANCELED_FOR_SECURITY_TYPE; return true; }
	if (std::strcmp(s, "3") == 0) { out = QuoteStatus::CANCELED_FOR_UNDERLYING; return true; }
	if (std::strcmp(s, "4") == 0) { out = QuoteStatus::CANCELED_ALL; return true; }
	if (std::strcmp(s, "5") == 0) { out = QuoteStatus::REJECTED; return true; }
	return false;
}

enum class QuoteCancelType : uint8_t {
	CANCEL_FOR_ONE_OR_MORE_SECURITIES,
	CANCEL_FOR_SECURITY_TYPE,
	CANCEL_FOR_UNDERLYING_SECURITY,
	CANCEL_ALL_QUOTES,
};

[[nodiscard]] constexpr const char *to_cstr(QuoteCancelType v) noexcept {
	switch (v) {
		case QuoteCancelType::CANCEL_FOR_ONE_OR_MORE_SECURITIES: return "1";
		case QuoteCancelType::CANCEL_FOR_SECURITY_TYPE        : return "2";
		case QuoteCancelType::CANCEL_FOR_UNDERLYING_SECURITY  : return "3";
		case QuoteCancelType::CANCEL_ALL_QUOTES               : return "4";
	}
	return "";
}

[[nodiscard]] inline bool parse_QuoteCancelType(const char *s, QuoteCancelType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = QuoteCancelType::CANCEL_FOR_ONE_OR_MORE_SECURITIES; return true; }
	if (std::strcmp(s, "2") == 0) { out = QuoteCancelType::CANCEL_FOR_SECURITY_TYPE; return true; }
	if (std::strcmp(s, "3") == 0) { out = QuoteCancelType::CANCEL_FOR_UNDERLYING_SECURITY; return true; }
	if (std::strcmp(s, "4") == 0) { out = QuoteCancelType::CANCEL_ALL_QUOTES; return true; }
	return false;
}

enum class QuoteRejectReason : uint8_t {
	UNKNOWN_SYMBOL,
	EXCHANGE,
	QUOTE_REQUEST_EXCEEDS_LIMIT,
	TOO_LATE_TO_ENTER,
	UNKNOWN_QUOTE,
	DUPLICATE_QUOTE,
	INVALID_BID,
	INVALID_PRICE,
	NOT_AUTHORIZED_TO_QUOTE_SECURITY,
};

[[nodiscard]] constexpr const char *to_cstr(QuoteRejectReason v) noexcept {
	switch (v) {
		case QuoteRejectReason::UNKNOWN_SYMBOL                  : return "1";
		case QuoteRejectReason::EXCHANGE                        : return "2";
		case QuoteRejectReason::QUOTE_REQUEST_EXCEEDS_LIMIT     : return "3";
		case QuoteRejectReason::TOO_LATE_TO_ENTER               : return "4";
		case QuoteRejectReason::UNKNOWN_QUOTE                   : return "5";
		case QuoteRejectReason::DUPLICATE_QUOTE                 : return "6";
		case QuoteRejectReason::INVALID_BID                     : return "7";
		case QuoteRejectReason::INVALID_PRICE                   : return "8";
		case QuoteRejectReason::NOT_AUTHORIZED_TO_QUOTE_SECURITY: return "9";
	}
	return "";
}

[[nodiscard]] inline bool parse_QuoteRejectReason(const char *s, QuoteRejectReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = QuoteRejectReason::UNKNOWN_SYMBOL; return true; }
	if (std::strcmp(s, "2") == 0) { out = QuoteRejectReason::EXCHANGE; return true; }
	if (std::strcmp(s, "3") == 0) { out = QuoteRejectReason::QUOTE_REQUEST_EXCEEDS_LIMIT; return true; }
	if (std::strcmp(s, "4") == 0) { out = QuoteRejectReason::TOO_LATE_TO_ENTER; return true; }
	if (std::strcmp(s, "5") == 0) { out = QuoteRejectReason::UNKNOWN_QUOTE; return true; }
	if (std::strcmp(s, "6") == 0) { out = QuoteRejectReason::DUPLICATE_QUOTE; return true; }
	if (std::strcmp(s, "7") == 0) { out = QuoteRejectReason::INVALID_BID; return true; }
	if (std::strcmp(s, "8") == 0) { out = QuoteRejectReason::INVALID_PRICE; return true; }
	if (std::strcmp(s, "9") == 0) { out = QuoteRejectReason::NOT_AUTHORIZED_TO_QUOTE_SECURITY; return true; }
	return false;
}

enum class QuoteResponseLevel : uint8_t {
	NO_ACKNOWLEDGEMENT,
	ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES,
	ACKNOWLEDGE_EACH_QUOTE_MESSAGE,
};

[[nodiscard]] constexpr const char *to_cstr(QuoteResponseLevel v) noexcept {
	switch (v) {
		case QuoteResponseLevel::NO_ACKNOWLEDGEMENT              : return "0";
		case QuoteResponseLevel::ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES: return "1";
		case QuoteResponseLevel::ACKNOWLEDGE_EACH_QUOTE_MESSAGE  : return "2";
	}
	return "";
}

[[nodiscard]] inline bool parse_QuoteResponseLevel(const char *s, QuoteResponseLevel &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = QuoteResponseLevel::NO_ACKNOWLEDGEMENT; return true; }
	if (std::strcmp(s, "1") == 0) { out = QuoteResponseLevel::ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES; return true; }
	if (std::strcmp(s, "2") == 0) { out = QuoteResponseLevel::ACKNOWLEDGE_EACH_QUOTE_MESSAGE; return true; }
	return false;
}

enum class QuoteRequestType : uint8_t {
	MANUAL,
	AUTOMATIC,
};

[[nodiscard]] constexpr const char *to_cstr(QuoteRequestType v) noexcept {
	switch (v) {
		case QuoteRequestType::MANUAL                          : return "1";
		case QuoteRequestType::AUTOMATIC                       : return "2";
	}
	return "";
}

[[nodiscard]] inline bool parse_QuoteRequestType(const char *s, QuoteRequestType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = QuoteRequestType::MANUAL; return true; }
	if (std::strcmp(s, "2") == 0) { out = QuoteRequestType::AUTOMATIC; return true; }
	return false;
}

enum class SecurityRequestType : uint8_t {
	REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS,
	REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS,
	REQUEST_LIST_SECURITY_TYPES,
	REQUEST_LIST_SECURITIES,
};

[[nodiscard]] constexpr const char *to_cstr(SecurityRequestType v) noexcept {
	switch (v) {
		case SecurityRequestType::REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS: return "0";
		case SecurityRequestType::REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS: return "1";
		case SecurityRequestType::REQUEST_LIST_SECURITY_TYPES     : return "2";
		case SecurityRequestType::REQUEST_LIST_SECURITIES         : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_SecurityRequestType(const char *s, SecurityRequestType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = SecurityRequestType::REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS; return true; }
	if (std::strcmp(s, "1") == 0) { out = SecurityRequestType::REQUEST_SECURITY_IDENTITY_FOR_SPECIFICATIONS; return true; }
	if (std::strcmp(s, "2") == 0) { out = SecurityRequestType::REQUEST_LIST_SECURITY_TYPES; return true; }
	if (std::strcmp(s, "3") == 0) { out = SecurityRequestType::REQUEST_LIST_SECURITIES; return true; }
	return false;
}

enum class SecurityResponseType : uint8_t {
	ACCEPT_AS_IS,
	ACCEPT_WITH_REVISIONS,
	LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST,
	LIST_OF_SECURITIES_RETURNED_PER_REQUEST,
	REJECT_SECURITY_PROPOSAL,
	CANNOT_MATCH_SELECTION_CRITERIA,
};

[[nodiscard]] constexpr const char *to_cstr(SecurityResponseType v) noexcept {
	switch (v) {
		case SecurityResponseType::ACCEPT_AS_IS                    : return "1";
		case SecurityResponseType::ACCEPT_WITH_REVISIONS           : return "2";
		case SecurityResponseType::LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST: return "3";
		case SecurityResponseType::LIST_OF_SECURITIES_RETURNED_PER_REQUEST: return "4";
		case SecurityResponseType::REJECT_SECURITY_PROPOSAL        : return "5";
		case SecurityResponseType::CANNOT_MATCH_SELECTION_CRITERIA : return "6";
	}
	return "";
}

[[nodiscard]] inline bool parse_SecurityResponseType(const char *s, SecurityResponseType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = SecurityResponseType::ACCEPT_AS_IS; return true; }
	if (std::strcmp(s, "2") == 0) { out = SecurityResponseType::ACCEPT_WITH_REVISIONS; return true; }
	if (std::strcmp(s, "3") == 0) { out = SecurityResponseType::LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST; return true; }
	if (std::strcmp(s, "4") == 0) { out = SecurityResponseType::LIST_OF_SECURITIES_RETURNED_PER_REQUEST; return true; }
	if (std::strcmp(s, "5") == 0) { out = SecurityResponseType::REJECT_SECURITY_PROPOSAL; return true; }
	if (std::strcmp(s, "6") == 0) { out = SecurityResponseType::CANNOT_MATCH_SELECTION_CRITERIA; return true; }
	return false;
}

enum class SecurityTradingStatus : uint8_t {
	OPENING_DELAY,
	MARKET_ON_CLOSE_IMBALANCE_SELL,
	NO_MARKET_IMBALANCE,
	NO_MARKET_ON_CLOSE_IMBALANCE,
	ITS_PRE_OPENING,
	NEW_PRICE_INDICATION,
	TRADE_DISSEMINATION_TIME,
	READY_TO_TRADE,
	NOT_AVAILABLE_FOR_TRADING,
	NOT_TRADED_ON_THIS_MARKET,
	TRADING_HALT,
	UNKNOWN_OR_INVALID,
	RESUME,
	NO_OPEN,
	PRICE_INDICATION,
	TRADING_RANGE_INDICATION,
	MARKET_IMBALANCE_BUY,
	MARKET_IMBALANCE_SELL,
	MARKET_ON_CLOSE_IMBALANCE_BUY,
};

[[nodiscard]] constexpr const char *to_cstr(SecurityTradingStatus v) noexcept {
	switch (v) {
		case SecurityTradingStatus::OPENING_DELAY                   : return "1";
		case SecurityTradingStatus::MARKET_ON_CLOSE_IMBALANCE_SELL  : return "10";
		case SecurityTradingStatus::NO_MARKET_IMBALANCE             : return "12";
		case SecurityTradingStatus::NO_MARKET_ON_CLOSE_IMBALANCE    : return "13";
		case SecurityTradingStatus::ITS_PRE_OPENING                 : return "14";
		case SecurityTradingStatus::NEW_PRICE_INDICATION            : return "15";
		case SecurityTradingStatus::TRADE_DISSEMINATION_TIME        : return "16";
		case SecurityTradingStatus::READY_TO_TRADE                  : return "17";
		case SecurityTradingStatus::NOT_AVAILABLE_FOR_TRADING       : return "18";
		case SecurityTradingStatus::NOT_TRADED_ON_THIS_MARKET       : return "19";
		case SecurityTradingStatus::TRADING_HALT                    : return "2";
		case SecurityTradingStatus::UNKNOWN_OR_INVALID              : return "20";
		case SecurityTradingStatus::RESUME                          : return "3";
		case SecurityTradingStatus::NO_OPEN                         : return "4";
		case SecurityTradingStatus::PRICE_INDICATION                : return "5";
		case SecurityTradingStatus::TRADING_RANGE_INDICATION        : return "6";
		case SecurityTradingStatus::MARKET_IMBALANCE_BUY            : return "7";
		case SecurityTradingStatus::MARKET_IMBALANCE_SELL           : return "8";
		case SecurityTradingStatus::MARKET_ON_CLOSE_IMBALANCE_BUY   : return "9";
	}
	return "";
}

[[nodiscard]] inline bool parse_SecurityTradingStatus(const char *s, SecurityTradingStatus &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = SecurityTradingStatus::OPENING_DELAY; return true; }
	if (std::strcmp(s, "10") == 0) { out = SecurityTradingStatus::MARKET_ON_CLOSE_IMBALANCE_SELL; return true; }
	if (std::strcmp(s, "12") == 0) { out = SecurityTradingStatus::NO_MARKET_IMBALANCE; return true; }
	if (std::strcmp(s, "13") == 0) { out = SecurityTradingStatus::NO_MARKET_ON_CLOSE_IMBALANCE; return true; }
	if (std::strcmp(s, "14") == 0) { out = SecurityTradingStatus::ITS_PRE_OPENING; return true; }
	if (std::strcmp(s, "15") == 0) { out = SecurityTradingStatus::NEW_PRICE_INDICATION; return true; }
	if (std::strcmp(s, "16") == 0) { out = SecurityTradingStatus::TRADE_DISSEMINATION_TIME; return true; }
	if (std::strcmp(s, "17") == 0) { out = SecurityTradingStatus::READY_TO_TRADE; return true; }
	if (std::strcmp(s, "18") == 0) { out = SecurityTradingStatus::NOT_AVAILABLE_FOR_TRADING; return true; }
	if (std::strcmp(s, "19") == 0) { out = SecurityTradingStatus::NOT_TRADED_ON_THIS_MARKET; return true; }
	if (std::strcmp(s, "2") == 0) { out = SecurityTradingStatus::TRADING_HALT; return true; }
	if (std::strcmp(s, "20") == 0) { out = SecurityTradingStatus::UNKNOWN_OR_INVALID; return true; }
	if (std::strcmp(s, "3") == 0) { out = SecurityTradingStatus::RESUME; return true; }
	if (std::strcmp(s, "4") == 0) { out = SecurityTradingStatus::NO_OPEN; return true; }
	if (std::strcmp(s, "5") == 0) { out = SecurityTradingStatus::PRICE_INDICATION; return true; }
	if (std::strcmp(s, "6") == 0) { out = SecurityTradingStatus::TRADING_RANGE_INDICATION; return true; }
	if (std::strcmp(s, "7") == 0) { out = SecurityTradingStatus::MARKET_IMBALANCE_BUY; return true; }
	if (std::strcmp(s, "8") == 0) { out = SecurityTradingStatus::MARKET_IMBALANCE_SELL; return true; }
	if (std::strcmp(s, "9") == 0) { out = SecurityTradingStatus::MARKET_ON_CLOSE_IMBALANCE_BUY; return true; }
	return false;
}

enum class HaltReasonChar : char {
	NEWS_DISSEMINATION                       = 'D',
	ORDER_INFLUX                             = 'E',
	ORDER_IMBALANCE                          = 'I',
	ADDITIONAL_INFORMATION                   = 'M',
	NEWS_PENDING                             = 'P',
	EQUIPMENT_CHANGEOVER                     = 'X',
};

enum class Adjustment : uint8_t {
	CANCEL,
	ERROR,
	CORRECTION,
};

[[nodiscard]] constexpr const char *to_cstr(Adjustment v) noexcept {
	switch (v) {
		case Adjustment::CANCEL                          : return "1";
		case Adjustment::ERROR                           : return "2";
		case Adjustment::CORRECTION                      : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_Adjustment(const char *s, Adjustment &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = Adjustment::CANCEL; return true; }
	if (std::strcmp(s, "2") == 0) { out = Adjustment::ERROR; return true; }
	if (std::strcmp(s, "3") == 0) { out = Adjustment::CORRECTION; return true; }
	return false;
}

enum class TradSesMethod : uint8_t {
	ELECTRONIC,
	OPEN_OUTCRY,
	TWO_PARTY,
};

[[nodiscard]] constexpr const char *to_cstr(TradSesMethod v) noexcept {
	switch (v) {
		case TradSesMethod::ELECTRONIC                      : return "1";
		case TradSesMethod::OPEN_OUTCRY                     : return "2";
		case TradSesMethod::TWO_PARTY                       : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_TradSesMethod(const char *s, TradSesMethod &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = TradSesMethod::ELECTRONIC; return true; }
	if (std::strcmp(s, "2") == 0) { out = TradSesMethod::OPEN_OUTCRY; return true; }
	if (std::strcmp(s, "3") == 0) { out = TradSesMethod::TWO_PARTY; return true; }
	return false;
}

enum class TradSesMode : uint8_t {
	TESTING,
	SIMULATED,
	PRODUCTION,
};

[[nodiscard]] constexpr const char *to_cstr(TradSesMode v) noexcept {
	switch (v) {
		case TradSesMode::TESTING                         : return "1";
		case TradSesMode::SIMULATED                       : return "2";
		case TradSesMode::PRODUCTION                      : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_TradSesMode(const char *s, TradSesMode &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = TradSesMode::TESTING; return true; }
	if (std::strcmp(s, "2") == 0) { out = TradSesMode::SIMULATED; return true; }
	if (std::strcmp(s, "3") == 0) { out = TradSesMode::PRODUCTION; return true; }
	return false;
}

enum class TradSesStatus : uint8_t {
	HALTED,
	OPEN,
	CLOSED,
	PRE_OPEN,
	PRE_CLOSE,
};

[[nodiscard]] constexpr const char *to_cstr(TradSesStatus v) noexcept {
	switch (v) {
		case TradSesStatus::HALTED                          : return "1";
		case TradSesStatus::OPEN                            : return "2";
		case TradSesStatus::CLOSED                          : return "3";
		case TradSesStatus::PRE_OPEN                        : return "4";
		case TradSesStatus::PRE_CLOSE                       : return "5";
	}
	return "";
}

[[nodiscard]] inline bool parse_TradSesStatus(const char *s, TradSesStatus &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = TradSesStatus::HALTED; return true; }
	if (std::strcmp(s, "2") == 0) { out = TradSesStatus::OPEN; return true; }
	if (std::strcmp(s, "3") == 0) { out = TradSesStatus::CLOSED; return true; }
	if (std::strcmp(s, "4") == 0) { out = TradSesStatus::PRE_OPEN; return true; }
	if (std::strcmp(s, "5") == 0) { out = TradSesStatus::PRE_CLOSE; return true; }
	return false;
}

enum class MessageEncoding : uint8_t {
	EUCJP,
	ISO2022_JP,
	SHIFT_JIS,
	UTF8,
};

[[nodiscard]] constexpr const char *to_cstr(MessageEncoding v) noexcept {
	switch (v) {
		case MessageEncoding::EUCJP                           : return "EUC-JP";
		case MessageEncoding::ISO2022_JP                      : return "ISO-2022-JP";
		case MessageEncoding::SHIFT_JIS                       : return "Shift_JIS";
		case MessageEncoding::UTF8                            : return "UTF-8";
	}
	return "";
}

[[nodiscard]] inline bool parse_MessageEncoding(const char *s, MessageEncoding &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "EUC-JP") == 0) { out = MessageEncoding::EUCJP; return true; }
	if (std::strcmp(s, "ISO-2022-JP") == 0) { out = MessageEncoding::ISO2022_JP; return true; }
	if (std::strcmp(s, "Shift_JIS") == 0) { out = MessageEncoding::SHIFT_JIS; return true; }
	if (std::strcmp(s, "UTF-8") == 0) { out = MessageEncoding::UTF8; return true; }
	return false;
}

enum class QuoteEntryRejectReason : uint8_t {
	UNKNOWN_SYMBOL,
	EXCHANGE,
	QUOTE_EXCEEDS_LIMIT,
	TOO_LATE_TO_ENTER,
	UNKNOWN_QUOTE,
	DUPLICATE_QUOTE,
	INVALID_BID_ASK_SPREAD,
	INVALID_PRICE,
	NOT_AUTHORIZED_TO_QUOTE_SECURITY,
};

[[nodiscard]] constexpr const char *to_cstr(QuoteEntryRejectReason v) noexcept {
	switch (v) {
		case QuoteEntryRejectReason::UNKNOWN_SYMBOL                  : return "1";
		case QuoteEntryRejectReason::EXCHANGE                        : return "2";
		case QuoteEntryRejectReason::QUOTE_EXCEEDS_LIMIT             : return "3";
		case QuoteEntryRejectReason::TOO_LATE_TO_ENTER               : return "4";
		case QuoteEntryRejectReason::UNKNOWN_QUOTE                   : return "5";
		case QuoteEntryRejectReason::DUPLICATE_QUOTE                 : return "6";
		case QuoteEntryRejectReason::INVALID_BID_ASK_SPREAD          : return "7";
		case QuoteEntryRejectReason::INVALID_PRICE                   : return "8";
		case QuoteEntryRejectReason::NOT_AUTHORIZED_TO_QUOTE_SECURITY: return "9";
	}
	return "";
}

[[nodiscard]] inline bool parse_QuoteEntryRejectReason(const char *s, QuoteEntryRejectReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = QuoteEntryRejectReason::UNKNOWN_SYMBOL; return true; }
	if (std::strcmp(s, "2") == 0) { out = QuoteEntryRejectReason::EXCHANGE; return true; }
	if (std::strcmp(s, "3") == 0) { out = QuoteEntryRejectReason::QUOTE_EXCEEDS_LIMIT; return true; }
	if (std::strcmp(s, "4") == 0) { out = QuoteEntryRejectReason::TOO_LATE_TO_ENTER; return true; }
	if (std::strcmp(s, "5") == 0) { out = QuoteEntryRejectReason::UNKNOWN_QUOTE; return true; }
	if (std::strcmp(s, "6") == 0) { out = QuoteEntryRejectReason::DUPLICATE_QUOTE; return true; }
	if (std::strcmp(s, "7") == 0) { out = QuoteEntryRejectReason::INVALID_BID_ASK_SPREAD; return true; }
	if (std::strcmp(s, "8") == 0) { out = QuoteEntryRejectReason::INVALID_PRICE; return true; }
	if (std::strcmp(s, "9") == 0) { out = QuoteEntryRejectReason::NOT_AUTHORIZED_TO_QUOTE_SECURITY; return true; }
	return false;
}

enum class SessionRejectReason : uint8_t {
	INVALID_TAG_NUMBER,
	REQUIRED_TAG_MISSING,
	SENDING_TIME_ACCURACY_PROBLEM,
	INVALID_MSG_TYPE,
	TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE,
	UNDEFINED_TAG,
	TAG_SPECIFIED_WITHOUT_A_VALUE,
	VALUE_IS_INCORRECT,
	INCORRECT_DATA_FORMAT_FOR_VALUE,
	DECRYPTION_PROBLEM,
	SIGNATURE_PROBLEM,
	COMP_ID_PROBLEM,
};

[[nodiscard]] constexpr const char *to_cstr(SessionRejectReason v) noexcept {
	switch (v) {
		case SessionRejectReason::INVALID_TAG_NUMBER              : return "0";
		case SessionRejectReason::REQUIRED_TAG_MISSING            : return "1";
		case SessionRejectReason::SENDING_TIME_ACCURACY_PROBLEM   : return "10";
		case SessionRejectReason::INVALID_MSG_TYPE                : return "11";
		case SessionRejectReason::TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE: return "2";
		case SessionRejectReason::UNDEFINED_TAG                   : return "3";
		case SessionRejectReason::TAG_SPECIFIED_WITHOUT_A_VALUE   : return "4";
		case SessionRejectReason::VALUE_IS_INCORRECT              : return "5";
		case SessionRejectReason::INCORRECT_DATA_FORMAT_FOR_VALUE : return "6";
		case SessionRejectReason::DECRYPTION_PROBLEM              : return "7";
		case SessionRejectReason::SIGNATURE_PROBLEM               : return "8";
		case SessionRejectReason::COMP_ID_PROBLEM                 : return "9";
	}
	return "";
}

[[nodiscard]] inline bool parse_SessionRejectReason(const char *s, SessionRejectReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = SessionRejectReason::INVALID_TAG_NUMBER; return true; }
	if (std::strcmp(s, "1") == 0) { out = SessionRejectReason::REQUIRED_TAG_MISSING; return true; }
	if (std::strcmp(s, "10") == 0) { out = SessionRejectReason::SENDING_TIME_ACCURACY_PROBLEM; return true; }
	if (std::strcmp(s, "11") == 0) { out = SessionRejectReason::INVALID_MSG_TYPE; return true; }
	if (std::strcmp(s, "2") == 0) { out = SessionRejectReason::TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE; return true; }
	if (std::strcmp(s, "3") == 0) { out = SessionRejectReason::UNDEFINED_TAG; return true; }
	if (std::strcmp(s, "4") == 0) { out = SessionRejectReason::TAG_SPECIFIED_WITHOUT_A_VALUE; return true; }
	if (std::strcmp(s, "5") == 0) { out = SessionRejectReason::VALUE_IS_INCORRECT; return true; }
	if (std::strcmp(s, "6") == 0) { out = SessionRejectReason::INCORRECT_DATA_FORMAT_FOR_VALUE; return true; }
	if (std::strcmp(s, "7") == 0) { out = SessionRejectReason::DECRYPTION_PROBLEM; return true; }
	if (std::strcmp(s, "8") == 0) { out = SessionRejectReason::SIGNATURE_PROBLEM; return true; }
	if (std::strcmp(s, "9") == 0) { out = SessionRejectReason::COMP_ID_PROBLEM; return true; }
	return false;
}

enum class BidRequestTransType : char {
	CANCEL                                   = 'C',
	NEW                                      = 'N',
};

enum class ExecRestatementReason : uint8_t {
	GT_CORPORATE_ACTION,
	GT_RENEWAL,
	VERBAL_CHANGE,
	REPRICING_OF_ORDER,
	BROKER_OPTION,
	PARTIAL_DECLINE_OF_ORDER_QTY,
};

[[nodiscard]] constexpr const char *to_cstr(ExecRestatementReason v) noexcept {
	switch (v) {
		case ExecRestatementReason::GT_CORPORATE_ACTION             : return "0";
		case ExecRestatementReason::GT_RENEWAL                      : return "1";
		case ExecRestatementReason::VERBAL_CHANGE                   : return "2";
		case ExecRestatementReason::REPRICING_OF_ORDER              : return "3";
		case ExecRestatementReason::BROKER_OPTION                   : return "4";
		case ExecRestatementReason::PARTIAL_DECLINE_OF_ORDER_QTY    : return "5";
	}
	return "";
}

[[nodiscard]] inline bool parse_ExecRestatementReason(const char *s, ExecRestatementReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = ExecRestatementReason::GT_CORPORATE_ACTION; return true; }
	if (std::strcmp(s, "1") == 0) { out = ExecRestatementReason::GT_RENEWAL; return true; }
	if (std::strcmp(s, "2") == 0) { out = ExecRestatementReason::VERBAL_CHANGE; return true; }
	if (std::strcmp(s, "3") == 0) { out = ExecRestatementReason::REPRICING_OF_ORDER; return true; }
	if (std::strcmp(s, "4") == 0) { out = ExecRestatementReason::BROKER_OPTION; return true; }
	if (std::strcmp(s, "5") == 0) { out = ExecRestatementReason::PARTIAL_DECLINE_OF_ORDER_QTY; return true; }
	return false;
}

enum class BusinessRejectReason : uint8_t {
	OTHER,
	UNKNOWN_ID,
	UNKNOWN_SECURITY,
	UNSUPPORTED_MESSAGE_TYPE,
	APPLICATION_NOT_AVAILABLE,
	CONDITIONALLY_REQUIRED_FIELD_MISSING,
};

[[nodiscard]] constexpr const char *to_cstr(BusinessRejectReason v) noexcept {
	switch (v) {
		case BusinessRejectReason::OTHER                           : return "0";
		case BusinessRejectReason::UNKNOWN_ID                      : return "1";
		case BusinessRejectReason::UNKNOWN_SECURITY                : return "2";
		case BusinessRejectReason::UNSUPPORTED_MESSAGE_TYPE        : return "3";
		case BusinessRejectReason::APPLICATION_NOT_AVAILABLE       : return "4";
		case BusinessRejectReason::CONDITIONALLY_REQUIRED_FIELD_MISSING: return "5";
	}
	return "";
}

[[nodiscard]] inline bool parse_BusinessRejectReason(const char *s, BusinessRejectReason &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = BusinessRejectReason::OTHER; return true; }
	if (std::strcmp(s, "1") == 0) { out = BusinessRejectReason::UNKNOWN_ID; return true; }
	if (std::strcmp(s, "2") == 0) { out = BusinessRejectReason::UNKNOWN_SECURITY; return true; }
	if (std::strcmp(s, "3") == 0) { out = BusinessRejectReason::UNSUPPORTED_MESSAGE_TYPE; return true; }
	if (std::strcmp(s, "4") == 0) { out = BusinessRejectReason::APPLICATION_NOT_AVAILABLE; return true; }
	if (std::strcmp(s, "5") == 0) { out = BusinessRejectReason::CONDITIONALLY_REQUIRED_FIELD_MISSING; return true; }
	return false;
}

enum class MsgDirection : char {
	RECEIVE                                  = 'R',
	SEND                                     = 'S',
};

enum class DiscretionInst : char {
	RELATED_TO_DISPLAYED_PRICE               = '0',
	RELATED_TO_MARKET_PRICE                  = '1',
	RELATED_TO_PRIMARY_PRICE                 = '2',
	RELATED_TO_LOCAL_PRIMARY_PRICE           = '3',
	RELATED_TO_MIDPOINT_PRICE                = '4',
	RELATED_TO_LAST_TRADE_PRICE              = '5',
};

enum class LiquidityIndType : uint8_t {
	FIVE_DAY_MOVING_AVERAGE,
	TWENTY_DAY_MOVING_AVERAGE,
	NORMAL_MARKET_SIZE,
	OTHER,
};

[[nodiscard]] constexpr const char *to_cstr(LiquidityIndType v) noexcept {
	switch (v) {
		case LiquidityIndType::FIVE_DAY_MOVING_AVERAGE         : return "1";
		case LiquidityIndType::TWENTY_DAY_MOVING_AVERAGE       : return "2";
		case LiquidityIndType::NORMAL_MARKET_SIZE              : return "3";
		case LiquidityIndType::OTHER                           : return "4";
	}
	return "";
}

[[nodiscard]] inline bool parse_LiquidityIndType(const char *s, LiquidityIndType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = LiquidityIndType::FIVE_DAY_MOVING_AVERAGE; return true; }
	if (std::strcmp(s, "2") == 0) { out = LiquidityIndType::TWENTY_DAY_MOVING_AVERAGE; return true; }
	if (std::strcmp(s, "3") == 0) { out = LiquidityIndType::NORMAL_MARKET_SIZE; return true; }
	if (std::strcmp(s, "4") == 0) { out = LiquidityIndType::OTHER; return true; }
	return false;
}

enum class ProgRptReqs : uint8_t {
	BUY_SIDE_REQUESTS,
	SELL_SIDE_SENDS,
	REAL_TIME_EXECUTION_REPORTS,
};

[[nodiscard]] constexpr const char *to_cstr(ProgRptReqs v) noexcept {
	switch (v) {
		case ProgRptReqs::BUY_SIDE_REQUESTS               : return "1";
		case ProgRptReqs::SELL_SIDE_SENDS                 : return "2";
		case ProgRptReqs::REAL_TIME_EXECUTION_REPORTS     : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_ProgRptReqs(const char *s, ProgRptReqs &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = ProgRptReqs::BUY_SIDE_REQUESTS; return true; }
	if (std::strcmp(s, "2") == 0) { out = ProgRptReqs::SELL_SIDE_SENDS; return true; }
	if (std::strcmp(s, "3") == 0) { out = ProgRptReqs::REAL_TIME_EXECUTION_REPORTS; return true; }
	return false;
}

enum class IncTaxInd : uint8_t {
	NET,
	GROSS,
};

[[nodiscard]] constexpr const char *to_cstr(IncTaxInd v) noexcept {
	switch (v) {
		case IncTaxInd::NET                             : return "1";
		case IncTaxInd::GROSS                           : return "2";
	}
	return "";
}

[[nodiscard]] inline bool parse_IncTaxInd(const char *s, IncTaxInd &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = IncTaxInd::NET; return true; }
	if (std::strcmp(s, "2") == 0) { out = IncTaxInd::GROSS; return true; }
	return false;
}

enum class TradeType : char {
	AGENCY                                   = 'A',
	VWAP_GUARANTEE                           = 'G',
	GUARANTEED_CLOSE                         = 'J',
	RISK_TRADE                               = 'R',
};

enum class BasisPxType : char {
	CLOSING_PRICE_AT_MORNING_SESSION         = '2',
	CLOSING_PRICE                            = '3',
	CURRENT_PRICE                            = '4',
	SQ                                       = '5',
	VWAP_THROUGH_A_DAY                       = '6',
	VWAP_THROUGH_A_MORNING_SESSION           = '7',
	VWAP_THROUGH_AN_AFTERNOON_SESSION        = '8',
	VWAP_THROUGH_A_DAY_EXCEPT                = '9',
	VWAP_THROUGH_A_MORNING_SESSION_EXCEPT    = 'A',
	VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT = 'B',
	STRIKE                                   = 'C',
	OPEN                                     = 'D',
	OTHERS                                   = 'Z',
};

enum class PriceType : uint8_t {
	PERCENTAGE,
	PER_UNIT,
	FIXED_AMOUNT,
};

[[nodiscard]] constexpr const char *to_cstr(PriceType v) noexcept {
	switch (v) {
		case PriceType::PERCENTAGE                      : return "1";
		case PriceType::PER_UNIT                        : return "2";
		case PriceType::FIXED_AMOUNT                    : return "3";
	}
	return "";
}

[[nodiscard]] inline bool parse_PriceType(const char *s, PriceType &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = PriceType::PERCENTAGE; return true; }
	if (std::strcmp(s, "2") == 0) { out = PriceType::PER_UNIT; return true; }
	if (std::strcmp(s, "3") == 0) { out = PriceType::FIXED_AMOUNT; return true; }
	return false;
}

enum class GTBookingInst : uint8_t {
	BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION,
	ACCUMULATE_UNTIL_FILLED_OR_EXPIRED,
	ACCUMULATE_UNTIL_VERBALLLY_NOTIFIED_OTHERWISE,
};

[[nodiscard]] constexpr const char *to_cstr(GTBookingInst v) noexcept {
	switch (v) {
		case GTBookingInst::BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION: return "0";
		case GTBookingInst::ACCUMULATE_UNTIL_FILLED_OR_EXPIRED: return "1";
		case GTBookingInst::ACCUMULATE_UNTIL_VERBALLLY_NOTIFIED_OTHERWISE: return "2";
	}
	return "";
}

[[nodiscard]] inline bool parse_GTBookingInst(const char *s, GTBookingInst &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "0") == 0) { out = GTBookingInst::BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION; return true; }
	if (std::strcmp(s, "1") == 0) { out = GTBookingInst::ACCUMULATE_UNTIL_FILLED_OR_EXPIRED; return true; }
	if (std::strcmp(s, "2") == 0) { out = GTBookingInst::ACCUMULATE_UNTIL_VERBALLLY_NOTIFIED_OTHERWISE; return true; }
	return false;
}

enum class NetGrossInd : uint8_t {
	NET,
	GROSS,
};

[[nodiscard]] constexpr const char *to_cstr(NetGrossInd v) noexcept {
	switch (v) {
		case NetGrossInd::NET                             : return "1";
		case NetGrossInd::GROSS                           : return "2";
	}
	return "";
}

[[nodiscard]] inline bool parse_NetGrossInd(const char *s, NetGrossInd &out) noexcept {
	if (!s) return false;
	if (std::strcmp(s, "1") == 0) { out = NetGrossInd::NET; return true; }
	if (std::strcmp(s, "2") == 0) { out = NetGrossInd::GROSS; return true; }
	return false;
}

enum class ListExecInstType : char {
	IMMEDIATE                                = '1',
	WAIT_FOR_INSTRUCTION                     = '2',
};

enum class CxlRejResponseTo : char {
	ORDER_CANCEL_REQUEST                     = '1',
	ORDER_CANCEL                             = '2',
};

enum class MultiLegReportingType : char {
	SINGLE_SECURITY                          = '1',
	INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY   = '2',
	MULTI_LEG_SECURITY                       = '3',
};

} // namespace enums
} // namespace fix42

#ifdef _WIN32
// Restore Windows macros
#pragma pop_macro("constant")
#pragma pop_macro("DELETE")
#pragma pop_macro("ERROR")
#pragma pop_macro("CORRECTION")
#pragma pop_macro("PER_UNIT")
#pragma pop_macro("PERCENTAGE")
#pragma pop_macro("ABSOLUTE")
#endif
