# -*- coding: utf-8 -*-

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo

"""
writers.py - C++ Header and File Writing Utilities

Functions to generate headers, namespaces, macros, etc.
"""

import hashlib
import io
from pathlib import Path
from typing import TextIO, Optional, List

from .formatters import indent


_CONTENT_HASH_PLACEHOLDER = "__FALCONFIX_CONTENT_HASH__"
_CONTENT_HASH_LINE = f"ContentHash: {_CONTENT_HASH_PLACEHOLDER}"
_GENERATED_BY_LINE = "Generated by FalconFIX Generator"


def _finalize_generated_content(content: str) -> str:
    if _CONTENT_HASH_PLACEHOLDER not in content:
        return content

    content_without_hash = content.replace(_CONTENT_HASH_LINE, "ContentHash:", 1)
    digest = hashlib.sha256(content_without_hash.encode("utf-8")).hexdigest()[:16]
    return content.replace(_CONTENT_HASH_PLACEHOLDER, digest, 1)


class _GeneratedFileBuffer(io.StringIO):
    def __init__(self, path: Path, encoding: str = "utf-8"):
        super().__init__()
        self._path = Path(path)
        self._encoding = encoding

    def close(self) -> None:
        if not self.closed:
            final_content = _finalize_generated_content(self.getvalue())
            previous_content = None
            if self._path.exists():
                previous_content = self._path.read_text(encoding=self._encoding)

            if previous_content != final_content:
                self._path.parent.mkdir(parents=True, exist_ok=True)
                self._path.write_text(final_content, encoding=self._encoding)

        super().close()


class _GeneratedFileContext:
    def __init__(self, path: Path, encoding: str = "utf-8"):
        self._buffer = _GeneratedFileBuffer(path, encoding=encoding)

    def __enter__(self) -> TextIO:
        return self._buffer

    def __exit__(self, exc_type, exc, tb) -> bool:
        self._buffer.close()
        return False


def open_generated_file(path: Path, encoding: str = "utf-8") -> _GeneratedFileContext:
    return _GeneratedFileContext(path, encoding=encoding)


# ===== AUTOGENERATION HEADER =====

def write_autogen_header(
    f: TextIO,
    description: str = "Auto-generated FIX code",
) -> None:
    """
    Writes boilerplate header for auto-generated file.

    Args:
        f: File handle aberto para escrita
        description: Description of what the file is
    """
    _ = description
    write_generated_line_header(f)


def write_generated_line_header(
    f: TextIO,
    comment_prefix: str = "//",
    *description_lines: str,
) -> None:
    f.write(f"{comment_prefix} {_GENERATED_BY_LINE}\n")
    f.write(f"{comment_prefix} {_CONTENT_HASH_LINE}\n")
    for line in description_lines:
        f.write(f"{comment_prefix} {line}\n")
    f.write("\n")


# ===== NAMESPACE MANAGEMENT =====

def write_namespace_open(f: TextIO, namespace: str, indent_spaces: int = 0) -> None:
    """
    Escreve abertura de namespace.

    Args:
        f: File handle
        namespace: Nome do namespace (ex: "fix44")
        indent_spaces: Initial indentation

    Exemplo output:
        namespace fix44 {
    """
    prefix = " " * indent_spaces
    f.write(f"{prefix}namespace {namespace} {{\n\n")


def write_namespace_close(f: TextIO, namespace: str, indent_spaces: int = 0) -> None:
    """
    Escreve fechamento de namespace.

    Args:
        f: File handle
        namespace: Nome do namespace
        indent_spaces: Indentation

    Exemplo output:
        } // namespace fix44
    """
    prefix = " " * indent_spaces
    f.write(f"\n{prefix}}} // namespace {namespace}\n")


# ===== COMMON MACROS =====

def emit_common_macros(base_path: Path, namespace: str) -> None:
    """
    Gera arquivo macros.h com macros FIX usuais.

    Args:
        base_path: Directory where save (utils/)
        namespace: Namespace FIX
    """
    utils_dir = Path(base_path)
    utils_dir.mkdir(parents=True, exist_ok=True)

    macros_file = utils_dir / "macros.h"

    with open_generated_file(macros_file) as f:
        write_autogen_header(f, "FIX common macros")

        f.write("#pragma once\n\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("// Branch prediction hints — High-Frequency Trading optimizations\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("// DECLARE_FIELD\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("#ifndef DECLARE_FIELD\n")
        f.write("    #define DECLARE_FIELD(type, name, init) type name = init;\n")
        f.write("    #define DECLARE_STATIC_FIELD(type, name, init) static inline constexpr type name = init;\n")
        f.write("#endif\n\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("// PARSER - CONTEXT\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("#define ACTIVATE_CTX(obj) do {                                                          \\\n")
        f.write("    ctx_obj = &(obj);                                                                    \\\n")
        f.write("    ctx_fn  = [](void *o, int32_t tag, const char *b, const char *e) noexcept -> bool { \\\n")
        f.write("        return static_cast<decltype(&(obj))>(o)->setField(tag, b, e);                    \\\n")
        f.write("    };                                                                                  \\\n")
        f.write("} while(0)\n\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("// SERIALIZER\n")
        f.write("// ----------------------------------------------------------------------------- \n")
        f.write("#define WRITE_TAG1(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 1\n")
        f.write("#define WRITE_TAG2(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 2\n")
        f.write("#define WRITE_TAG3(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 3\n")
        f.write("#define WRITE_TAG4(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 4\n")
        f.write("#define WRITE_TAG5(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 5\n")
        f.write("#define WRITE_TAG6(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 6\n")
        f.write("#define WRITE_TAG7(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 7\n")
        f.write("#define WRITE_TAG8(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 8\n")
        f.write("#define WRITE_TAG9(tag)  *reinterpret_cast<uint32_t*>(p) = (tag); p += 9\n\n")

        write_namespace_open(f, namespace)

        f.write("} // namespace\n")
def emit_datetime_header(base_path: Path, namespace: str, include_root: str) -> None:
    """
    Generates datetime.h file with FIX date/time functions.

    Args:
        base_path: Directory where save (utils/)
        namespace: Namespace FIX
    """
    utils_dir = Path(base_path)
    utils_dir.mkdir(parents=True, exist_ok=True)

    datetime_file = utils_dir / "datetime.h"

    content = f"""#pragma once

#include <chrono>
#include <cstdint>
#include <ctime>
#include <cstring>

#include <{include_root}/core/types.h>

namespace {namespace}::datetime {{

using clock = std::chrono::system_clock;
using namespace {namespace}::types;

inline void write2(char *out, int32_t v) noexcept {{
    out[0] = static_cast<char>('0' + ((v / 10) % 10));
    out[1] = static_cast<char>('0' + (v % 10));
}}

inline void write3(char *out, int32_t v) noexcept {{
    out[0] = static_cast<char>('0' + ((v / 100) % 10));
    out[1] = static_cast<char>('0' + ((v / 10) % 10));
    out[2] = static_cast<char>('0' + (v % 10));
}}

inline void write4(char *out, int32_t v) noexcept {{
    out[0] = static_cast<char>('0' + ((v / 1000) % 10));
    out[1] = static_cast<char>('0' + ((v / 100) % 10));
    out[2] = static_cast<char>('0' + ((v / 10) % 10));
    out[3] = static_cast<char>('0' + (v % 10));
}}

inline void gmtime_utc(std::time_t t, std::tm &out) noexcept {{
#if defined(_WIN32)
    gmtime_s(&out, &t);
#else
    gmtime_r(&t, &out);
#endif
}}

namespace detail {{

struct UtcSecondCache {{
    int64_t cached_sec{{-1}};
    int64_t compact_base{{0}};       // YYYYMMDDHHMMSS000
    int32_t date{{0}};               // YYYYMMDD
    int32_t time_ms_base{{0}};       // ms since midnight, without current ms
    char compact_prefix[14]{{}};     // YYYYMMDDHHMMSS
    char fix_prefix[18]{{}};         // YYYYMMDD-HH:MM:SS.

    inline void update(int64_t sec) noexcept {{
        if (sec == cached_sec) return;

        cached_sec = sec;

        std::time_t t = static_cast<std::time_t>(sec);
        std::tm tm{{}};
        gmtime_utc(t, tm);

        const int32_t y = tm.tm_year + 1900;
        const int32_t mon = tm.tm_mon + 1;
        const int32_t d = tm.tm_mday;
        const int32_t h = tm.tm_hour;
        const int32_t m = tm.tm_min;
        const int32_t s = tm.tm_sec;

        date = y * 10000 + mon * 100 + d;
        time_ms_base = ((h * 60 + m) * 60 + s) * 1000;

        compact_base =
            static_cast<int64_t>(
                (((((static_cast<int64_t>(y) * 100 + mon) * 100 + d) * 100 + h) * 100 + m) * 100 + s)
            ) * 1000;

        write4(compact_prefix + 0, y);
        write2(compact_prefix + 4, mon);
        write2(compact_prefix + 6, d);
        write2(compact_prefix + 8, h);
        write2(compact_prefix + 10, m);
        write2(compact_prefix + 12, s);

        write4(fix_prefix + 0, y);
        write2(fix_prefix + 4, mon);
        write2(fix_prefix + 6, d);
        fix_prefix[8] = '-';
        write2(fix_prefix + 9, h);
        fix_prefix[11] = ':';
        write2(fix_prefix + 12, m);
        fix_prefix[14] = ':';
        write2(fix_prefix + 15, s);
        fix_prefix[17] = '.';
    }}
}};

inline UtcSecondCache &utc_cache_for(int64_t sec) noexcept {{
    thread_local UtcSecondCache cache{{}};
    cache.update(sec);
    return cache;
}}

inline int64_t now_epoch_ms() noexcept {{
    using namespace std::chrono;
    return duration_cast<milliseconds>(clock::now().time_since_epoch()).count();
}}

[[nodiscard]] inline int64_t seconds_since_midnight_utc() noexcept {{
    const int64_t epochMs = now_epoch_ms();
    const int64_t epochSec = epochMs / 1000;
    return epochSec % 86400;
}}

}} // namespace detail

[[nodiscard]] inline UTCTIMESTAMP now_UTCTimestamp() noexcept {{
    const int64_t epoch_ms = detail::now_epoch_ms();
    const int64_t sec = epoch_ms / 1000;
    const int32_t ms = static_cast<int32_t>(epoch_ms - sec * 1000);

    auto &cache = detail::utc_cache_for(sec);
    return static_cast<UTCTIMESTAMP>(cache.compact_base + ms);
}}

inline std::size_t now_UTCTimestampStr(char *out, bool includeMilliseconds = true) noexcept {{
    const int64_t epoch_ms = detail::now_epoch_ms();
    const int64_t sec = epoch_ms / 1000;
    const int32_t ms = static_cast<int32_t>(epoch_ms - sec * 1000);

    auto &cache = detail::utc_cache_for(sec);

    std::memcpy(out, cache.compact_prefix, 14);
    if (includeMilliseconds) {{
        write3(out + 14, ms);
        out[17] = '\\0';
        return 17;
    }}

    out[14] = '\\0';
    return 14;
}}

inline std::size_t now_FIXUTCTimestampStr(char *out, bool includeMilliseconds = true) noexcept {{
    const int64_t epoch_ms = detail::now_epoch_ms();
    const int64_t sec = epoch_ms / 1000;
    const int32_t ms = static_cast<int32_t>(epoch_ms - sec * 1000);

    auto &cache = detail::utc_cache_for(sec);

    if (includeMilliseconds) {{
        std::memcpy(out, cache.fix_prefix, 18);
        write3(out + 18, ms);
        out[21] = '\\0';
        return 21;
    }}

    std::memcpy(out, cache.fix_prefix, 17);
    out[17] = '\\0';
    return 17;
}}

[[nodiscard]] inline UTCDATEONLY now_UTCDateOnly() noexcept {{
    const int64_t epoch_ms = detail::now_epoch_ms();
    const int64_t sec = epoch_ms / 1000;
    return static_cast<UTCDATEONLY>(detail::utc_cache_for(sec).date);
}}

[[nodiscard]] inline UTCTIMEONLY now_UTCTimeOnly() noexcept {{
    const int64_t epoch_ms = detail::now_epoch_ms();
    const int64_t sec = epoch_ms / 1000;
    const int32_t ms = static_cast<int32_t>(epoch_ms - sec * 1000);

    auto &cache = detail::utc_cache_for(sec);
    return static_cast<UTCTIMEONLY>(cache.time_ms_base + ms);
}}

[[nodiscard]] inline LOCALMKTDATE now_LocalMktDate() noexcept {{
    return static_cast<LOCALMKTDATE>(now_UTCDateOnly());
}}

[[nodiscard]] inline std::size_t format_UTCTimestamp(UTCTIMESTAMP compact, char *out, bool includeMilliseconds = true) noexcept {{
    const int32_t ms = static_cast<int32_t>(compact % 1000);
    const int32_t sec = static_cast<int32_t>((compact / 1000) % 100);
    const int32_t min = static_cast<int32_t>((compact / 100000) % 100);
    const int32_t hour = static_cast<int32_t>((compact / 10000000) % 100);
    const int32_t day = static_cast<int32_t>((compact / 1000000000LL) % 100);
    const int32_t mon = static_cast<int32_t>((compact / 100000000000LL) % 100);
    const int32_t year = static_cast<int32_t>(compact / 10000000000000LL);

    write4(out + 0, year);
    write2(out + 4, mon);
    write2(out + 6, day);
    out[8] = '-';
    write2(out + 9, hour);
    out[11] = ':';
    write2(out + 12, min);
    out[14] = ':';
    write2(out + 15, sec);
    if (includeMilliseconds) {{
        out[17] = '.';
        write3(out + 18, ms);
        out[21] = '\\0';
        return 21;
    }}

    out[17] = '\\0';
    return 17;
}}

[[nodiscard]] inline std::size_t format_UTCTimestamp_compact(UTCTIMESTAMP compact, char *out, bool includeMilliseconds = true) noexcept {{
    const int32_t ms = static_cast<int32_t>(compact % 1000);
    const int32_t sec = static_cast<int32_t>((compact / 1000) % 100);
    const int32_t min = static_cast<int32_t>((compact / 100000) % 100);
    const int32_t hour = static_cast<int32_t>((compact / 10000000) % 100);
    const int32_t day = static_cast<int32_t>((compact / 1000000000LL) % 100);
    const int32_t mon = static_cast<int32_t>((compact / 100000000000LL) % 100);
    const int32_t year = static_cast<int32_t>(compact / 10000000000000LL);

    write4(out + 0, year);
    write2(out + 4, mon);
    write2(out + 6, day);
    write2(out + 8, hour);
    write2(out + 10, min);
    write2(out + 12, sec);
    if (includeMilliseconds) {{
        write3(out + 14, ms);
        out[17] = '\\0';
        return 17;
    }}

    out[14] = '\\0';
    return 14;
}}

[[nodiscard]] inline std::size_t format_UTCDateOnly(UTCDATEONLY yyyymmdd, char *out) noexcept {{
    const int32_t year = static_cast<int32_t>(yyyymmdd / 10000);
    const int32_t mon = static_cast<int32_t>((yyyymmdd / 100) % 100);
    const int32_t day = static_cast<int32_t>(yyyymmdd % 100);

    write4(out + 0, year);
    write2(out + 4, mon);
    write2(out + 6, day);
    out[8] = '\\0';
    return 8;
}}

[[nodiscard]] inline std::size_t format_UTCTimeOnly(UTCTIMEONLY ms_since_midnight, char *out) noexcept {{
    const int32_t h = static_cast<int32_t>(ms_since_midnight / 3600000);
    const int32_t m = static_cast<int32_t>((ms_since_midnight / 60000) % 60);
    const int32_t s = static_cast<int32_t>((ms_since_midnight / 1000) % 60);
    const int32_t ms = static_cast<int32_t>(ms_since_midnight % 1000);

    write2(out + 0, h);
    out[2] = ':';
    write2(out + 3, m);
    out[5] = ':';
    write2(out + 6, s);
    out[8] = '.';
    write3(out + 9, ms);
    out[12] = '\\0';
    return 12;
}}

[[nodiscard]] inline std::size_t format_LocalMktDate(LOCALMKTDATE yyyymmdd, char *out) noexcept {{
    return format_UTCDateOnly(static_cast<UTCDATEONLY>(yyyymmdd), out);
}}

}} // namespace {namespace}::datetime
"""

    with open_generated_file(datetime_file, encoding="utf-8") as f:
        write_autogen_header(f, "FIX date/time utilities")
        f.write(content)


# ===== CUSTOM WRITERS =====

def write_include_guard_open(f: TextIO, guard_name: str) -> None:
    """
    Escreve abertura de include guard.

    Args:
        f: File handle
        guard_name: Nome do guard (ex: FIX44_MESSAGE_H)

    Exemplo output:
        #ifndef FIX44_MESSAGE_H
        #define FIX44_MESSAGE_H
    """
    f.write(f"#ifndef {guard_name}\n")
    f.write(f"#define {guard_name}\n\n")


def write_include_guard_close(f: TextIO, guard_name: str) -> None:
    """
    Escreve fechamento de include guard.

    Args:
        f: File handle
        guard_name: Nome do guard

    Exemplo output:
        #endif // FIX44_MESSAGE_H
    """
    f.write(f"\n#endif // {guard_name}\n")


def write_include(f: TextIO, header: str, is_system: bool = False) -> None:
    """
    Escreve uma linha #include.

    Args:
        f: File handle
        header: Nome do header a incluir
        is_system: If True uses <>, otherwise uses ""
    """
    if is_system:
        f.write(f"#include <{header}>\n")
    else:
        f.write(f"#include \"{header}\"\n")
