// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 51eafff382985a5e

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/NestedParties2.h>
#include <FIX4.4/components/NstdPtys2SubGrp.h>
#include <FIX4.4/components/OrdAllocGrp.h>

namespace fix44::messages {

class ConfirmationRequest {
	static constexpr std::size_t P_ConfirmReqID                 = 0;
	static constexpr std::size_t P_ConfirmType                  = 1;
	static constexpr std::size_t P_AllocID                      = 2;
	static constexpr std::size_t P_SecondaryAllocID             = 3;
	static constexpr std::size_t P_IndividualAllocID            = 4;
	static constexpr std::size_t P_TransactTime                 = 5;
	static constexpr std::size_t P_AllocAccount                 = 6;
	static constexpr std::size_t P_AllocAcctIDSource            = 7;
	static constexpr std::size_t P_AllocAccountType             = 8;
	static constexpr std::size_t P_Text                         = 9;
	static constexpr std::size_t P_EncodedTextLen               = 10;
	static constexpr std::size_t P_EncodedText                  = 11;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1) |
		(1ULL << 5);
	static constexpr std::size_t MAX_ENCODE_SIZE = 377;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_ConfirmReqID{fields::ConfirmReqID_NULL};
	types::INT m_ConfirmType{fields::NULL_INT};
	components::OrdAllocGrp m_OrdAllocGrp{};
	types::STRING<32> m_AllocID{fields::AllocID_NULL};
	types::STRING<32> m_SecondaryAllocID{fields::SecondaryAllocID_NULL};
	types::STRING<32> m_IndividualAllocID{fields::IndividualAllocID_NULL};
	types::UTCTIMESTAMP m_TransactTime{fields::NULL_UTCTIMESTAMP};
	types::STRING<32> m_AllocAccount{fields::AllocAccount_NULL};
	types::INT m_AllocAcctIDSource{fields::NULL_INT};
	types::INT m_AllocAccountType{fields::NULL_INT};
	types::STRING<32> m_Text{fields::Text_NULL};
	types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedText{fields::EncodedText_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "BH";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_OrdAllocGrp.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getConfirmReqID() const noexcept { return m_ConfirmReqID; }
	const types::INT &getConfirmType() const noexcept { return m_ConfirmType; }
	components::OrdAllocGrp &getRefOrdAllocGrp() noexcept { return m_OrdAllocGrp; }
	const components::OrdAllocGrp &getRefOrdAllocGrp() const noexcept { return m_OrdAllocGrp; }
	const types::STRING<32> &getAllocID() const noexcept { return m_AllocID; }
	const types::STRING<32> &getSecondaryAllocID() const noexcept { return m_SecondaryAllocID; }
	const types::STRING<32> &getIndividualAllocID() const noexcept { return m_IndividualAllocID; }
	const types::UTCTIMESTAMP &getTransactTime() const noexcept { return m_TransactTime; }
	const types::STRING<32> &getAllocAccount() const noexcept { return m_AllocAccount; }
	const types::INT &getAllocAcctIDSource() const noexcept { return m_AllocAcctIDSource; }
	const types::INT &getAllocAccountType() const noexcept { return m_AllocAccountType; }
	const types::STRING<32> &getText() const noexcept { return m_Text; }
	const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
	const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }

	// mutators
	void setConfirmReqID(const types::STRING<32> &v) noexcept { m_ConfirmReqID = v; m_presence |= (1ULL << P_ConfirmReqID); }
	void setConfirmType(types::INT v) noexcept { m_ConfirmType = v; m_presence |= (1ULL << P_ConfirmType); }
	void setAllocID(const types::STRING<32> &v) noexcept { m_AllocID = v; m_presence |= (1ULL << P_AllocID); }
	void setSecondaryAllocID(const types::STRING<32> &v) noexcept { m_SecondaryAllocID = v; m_presence |= (1ULL << P_SecondaryAllocID); }
	void setIndividualAllocID(const types::STRING<32> &v) noexcept { m_IndividualAllocID = v; m_presence |= (1ULL << P_IndividualAllocID); }
	void setTransactTime(types::UTCTIMESTAMP v) noexcept { m_TransactTime = v; m_presence |= (1ULL << P_TransactTime); }
	void setAllocAccount(const types::STRING<32> &v) noexcept { m_AllocAccount = v; m_presence |= (1ULL << P_AllocAccount); }
	void setAllocAcctIDSource(types::INT v) noexcept { m_AllocAcctIDSource = v; m_presence |= (1ULL << P_AllocAcctIDSource); }
	void setAllocAccountType(types::INT v) noexcept { m_AllocAccountType = v; m_presence |= (1ULL << P_AllocAccountType); }
	void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
	void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
	void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_OrdAllocGrp.hasAnySet()) { return true; }
		return false;
	}
	bool hasConfirmReqID() const noexcept { return (m_presence & (1ULL << P_ConfirmReqID)) != 0; }
	bool hasConfirmType() const noexcept { return (m_presence & (1ULL << P_ConfirmType)) != 0; }
	bool hasAllocID() const noexcept { return (m_presence & (1ULL << P_AllocID)) != 0; }
	bool hasSecondaryAllocID() const noexcept { return (m_presence & (1ULL << P_SecondaryAllocID)) != 0; }
	bool hasIndividualAllocID() const noexcept { return (m_presence & (1ULL << P_IndividualAllocID)) != 0; }
	bool hasTransactTime() const noexcept { return (m_presence & (1ULL << P_TransactTime)) != 0; }
	bool hasAllocAccount() const noexcept { return (m_presence & (1ULL << P_AllocAccount)) != 0; }
	bool hasAllocAcctIDSource() const noexcept { return (m_presence & (1ULL << P_AllocAcctIDSource)) != 0; }
	bool hasAllocAccountType() const noexcept { return (m_presence & (1ULL << P_AllocAccountType)) != 0; }
	bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
	bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
	bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
};

} // namespace fix44::messages
