// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: dfa99375cd949092

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/OrdListStatGrp.h>

namespace fix44::messages {

class ListStatus {
	static constexpr std::size_t P_ListID                       = 0;
	static constexpr std::size_t P_ListStatusType               = 1;
	static constexpr std::size_t P_NoRpts                       = 2;
	static constexpr std::size_t P_ListOrderStatus              = 3;
	static constexpr std::size_t P_RptSeq                       = 4;
	static constexpr std::size_t P_ListStatusText               = 5;
	static constexpr std::size_t P_EncodedListStatusTextLen     = 6;
	static constexpr std::size_t P_EncodedListStatusText        = 7;
	static constexpr std::size_t P_TransactTime                 = 8;
	static constexpr std::size_t P_TotNoOrders                  = 9;
	static constexpr std::size_t P_LastFragment                 = 10;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1) |
		(1ULL << 2) |
		(1ULL << 3) |
		(1ULL << 4) |
		(1ULL << 9);
	static constexpr std::size_t MAX_ENCODE_SIZE = 284;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_ListID{fields::ListID_NULL};
	types::INT m_ListStatusType{fields::NULL_INT};
	types::INT m_NoRpts{fields::NULL_INT};
	types::INT m_ListOrderStatus{fields::NULL_INT};
	types::INT m_RptSeq{fields::NULL_INT};
	types::STRING<32> m_ListStatusText{fields::ListStatusText_NULL};
	types::LENGTH m_EncodedListStatusTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedListStatusText{fields::EncodedListStatusText_NULL};
	types::UTCTIMESTAMP m_TransactTime{fields::NULL_UTCTIMESTAMP};
	types::INT m_TotNoOrders{fields::NULL_INT};
	types::BOOLEAN m_LastFragment{fields::NULL_BOOLEAN};
	components::OrdListStatGrp m_OrdListStatGrp{};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "N";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_OrdListStatGrp.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getListID() const noexcept { return m_ListID; }
	const types::INT &getListStatusType() const noexcept { return m_ListStatusType; }
	const types::INT &getNoRpts() const noexcept { return m_NoRpts; }
	const types::INT &getListOrderStatus() const noexcept { return m_ListOrderStatus; }
	const types::INT &getRptSeq() const noexcept { return m_RptSeq; }
	const types::STRING<32> &getListStatusText() const noexcept { return m_ListStatusText; }
	const types::LENGTH &getEncodedListStatusTextLen() const noexcept { return m_EncodedListStatusTextLen; }
	const types::DATA<32> &getEncodedListStatusText() const noexcept { return m_EncodedListStatusText; }
	const types::UTCTIMESTAMP &getTransactTime() const noexcept { return m_TransactTime; }
	const types::INT &getTotNoOrders() const noexcept { return m_TotNoOrders; }
	const types::BOOLEAN &getLastFragment() const noexcept { return m_LastFragment; }
	components::OrdListStatGrp &getRefOrdListStatGrp() noexcept { return m_OrdListStatGrp; }
	const components::OrdListStatGrp &getRefOrdListStatGrp() const noexcept { return m_OrdListStatGrp; }

	// mutators
	void setListID(const types::STRING<32> &v) noexcept { m_ListID = v; m_presence |= (1ULL << P_ListID); }
	void setListStatusType(types::INT v) noexcept { m_ListStatusType = v; m_presence |= (1ULL << P_ListStatusType); }
	void setNoRpts(types::INT v) noexcept { m_NoRpts = v; m_presence |= (1ULL << P_NoRpts); }
	void setListOrderStatus(types::INT v) noexcept { m_ListOrderStatus = v; m_presence |= (1ULL << P_ListOrderStatus); }
	void setRptSeq(types::INT v) noexcept { m_RptSeq = v; m_presence |= (1ULL << P_RptSeq); }
	void setListStatusText(const types::STRING<32> &v) noexcept { m_ListStatusText = v; m_presence |= (1ULL << P_ListStatusText); }
	void setEncodedListStatusTextLen(types::LENGTH v) noexcept { m_EncodedListStatusTextLen = v; m_presence |= (1ULL << P_EncodedListStatusTextLen); }
	void setEncodedListStatusText(const types::DATA<32> &v) noexcept { m_EncodedListStatusText = v; m_presence |= (1ULL << P_EncodedListStatusText); }
	void setTransactTime(types::UTCTIMESTAMP v) noexcept { m_TransactTime = v; m_presence |= (1ULL << P_TransactTime); }
	void setTotNoOrders(types::INT v) noexcept { m_TotNoOrders = v; m_presence |= (1ULL << P_TotNoOrders); }
	void setLastFragment(types::BOOLEAN v) noexcept { m_LastFragment = v; m_presence |= (1ULL << P_LastFragment); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_OrdListStatGrp.hasAnySet()) { return true; }
		return false;
	}
	bool hasListID() const noexcept { return (m_presence & (1ULL << P_ListID)) != 0; }
	bool hasListStatusType() const noexcept { return (m_presence & (1ULL << P_ListStatusType)) != 0; }
	bool hasNoRpts() const noexcept { return (m_presence & (1ULL << P_NoRpts)) != 0; }
	bool hasListOrderStatus() const noexcept { return (m_presence & (1ULL << P_ListOrderStatus)) != 0; }
	bool hasRptSeq() const noexcept { return (m_presence & (1ULL << P_RptSeq)) != 0; }
	bool hasListStatusText() const noexcept { return (m_presence & (1ULL << P_ListStatusText)) != 0; }
	bool hasEncodedListStatusTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedListStatusTextLen)) != 0; }
	bool hasEncodedListStatusText() const noexcept { return (m_presence & (1ULL << P_EncodedListStatusText)) != 0; }
	bool hasTransactTime() const noexcept { return (m_presence & (1ULL << P_TransactTime)) != 0; }
	bool hasTotNoOrders() const noexcept { return (m_presence & (1ULL << P_TotNoOrders)) != 0; }
	bool hasLastFragment() const noexcept { return (m_presence & (1ULL << P_LastFragment)) != 0; }
};

} // namespace fix44::messages
