// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: ac1b09b010aa7311

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/EvntGrp.h>
#include <FIX4.4/components/InstrmtLegGrp.h>
#include <FIX4.4/components/Instrument.h>
#include <FIX4.4/components/InstrumentLeg.h>
#include <FIX4.4/components/LegSecAltIDGrp.h>
#include <FIX4.4/components/NestedParties.h>
#include <FIX4.4/components/NstdPtysSubGrp.h>
#include <FIX4.4/components/Parties.h>
#include <FIX4.4/components/PosUndInstrmtGrp.h>
#include <FIX4.4/components/PositionAmountData.h>
#include <FIX4.4/components/PositionQty.h>
#include <FIX4.4/components/PtysSubGrp.h>
#include <FIX4.4/components/SecAltIDGrp.h>
#include <FIX4.4/components/UndSecAltIDGrp.h>
#include <FIX4.4/components/UnderlyingInstrument.h>
#include <FIX4.4/components/UnderlyingStipulations.h>

namespace fix44::messages {

class PositionReport {
	static constexpr std::size_t P_PosMaintRptID                = 0;
	static constexpr std::size_t P_PosReqID                     = 1;
	static constexpr std::size_t P_PosReqType                   = 2;
	static constexpr std::size_t P_SubscriptionRequestType      = 3;
	static constexpr std::size_t P_TotalNumPosReports           = 4;
	static constexpr std::size_t P_UnsolicitedIndicator         = 5;
	static constexpr std::size_t P_PosReqResult                 = 6;
	static constexpr std::size_t P_ClearingBusinessDate         = 7;
	static constexpr std::size_t P_SettlSessID                  = 8;
	static constexpr std::size_t P_SettlSessSubID               = 9;
	static constexpr std::size_t P_Account                      = 10;
	static constexpr std::size_t P_AcctIDSource                 = 11;
	static constexpr std::size_t P_AccountType                  = 12;
	static constexpr std::size_t P_Currency                     = 13;
	static constexpr std::size_t P_SettlPrice                   = 14;
	static constexpr std::size_t P_SettlPriceType               = 15;
	static constexpr std::size_t P_PriorSettlPrice              = 16;
	static constexpr std::size_t P_RegistStatus                 = 17;
	static constexpr std::size_t P_DeliveryDate                 = 18;
	static constexpr std::size_t P_Text                         = 19;
	static constexpr std::size_t P_EncodedTextLen               = 20;
	static constexpr std::size_t P_EncodedText                  = 21;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 6) |
		(1ULL << 7) |
		(1ULL << 10) |
		(1ULL << 12) |
		(1ULL << 14) |
		(1ULL << 15) |
		(1ULL << 16);
	static constexpr std::size_t MAX_ENCODE_SIZE = 569;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_PosMaintRptID{fields::PosMaintRptID_NULL};
	types::STRING<32> m_PosReqID{fields::PosReqID_NULL};
	types::INT m_PosReqType{fields::NULL_INT};
	types::CHAR m_SubscriptionRequestType{fields::NULL_CHAR};
	types::INT m_TotalNumPosReports{fields::NULL_INT};
	types::BOOLEAN m_UnsolicitedIndicator{fields::NULL_BOOLEAN};
	types::INT m_PosReqResult{fields::NULL_INT};
	types::UTCDATEONLY m_ClearingBusinessDate{fields::NULL_LOCALMKTDATE};
	types::STRING<32> m_SettlSessID{fields::SettlSessID_NULL};
	types::STRING<32> m_SettlSessSubID{fields::SettlSessSubID_NULL};
	components::Parties m_Parties{};
	types::STRING<32> m_Account{fields::Account_NULL};
	types::INT m_AcctIDSource{fields::NULL_INT};
	types::INT m_AccountType{fields::NULL_INT};
	components::Instrument m_Instrument{};
	types::CURRENCY<32> m_Currency{fields::Currency_NULL};
	types::FLOAT m_SettlPrice{fields::NULL_PRICE};
	types::INT m_SettlPriceType{fields::NULL_INT};
	types::FLOAT m_PriorSettlPrice{fields::NULL_PRICE};
	components::InstrmtLegGrp m_InstrmtLegGrp{};
	components::PosUndInstrmtGrp m_PosUndInstrmtGrp{};
	components::PositionQty m_PositionQty{};
	components::PositionAmountData m_PositionAmountData{};
	types::CHAR m_RegistStatus{fields::NULL_CHAR};
	types::UTCDATEONLY m_DeliveryDate{fields::NULL_LOCALMKTDATE};
	types::STRING<32> m_Text{fields::Text_NULL};
	types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedText{fields::EncodedText_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "AP";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_Parties.compute_buffer_size();
		total += m_Instrument.compute_buffer_size();
		total += m_InstrmtLegGrp.compute_buffer_size();
		total += m_PosUndInstrmtGrp.compute_buffer_size();
		total += m_PositionQty.compute_buffer_size();
		total += m_PositionAmountData.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getPosMaintRptID() const noexcept { return m_PosMaintRptID; }
	const types::STRING<32> &getPosReqID() const noexcept { return m_PosReqID; }
	const types::INT &getPosReqType() const noexcept { return m_PosReqType; }
	const types::CHAR &getSubscriptionRequestType() const noexcept { return m_SubscriptionRequestType; }
	const types::INT &getTotalNumPosReports() const noexcept { return m_TotalNumPosReports; }
	const types::BOOLEAN &getUnsolicitedIndicator() const noexcept { return m_UnsolicitedIndicator; }
	const types::INT &getPosReqResult() const noexcept { return m_PosReqResult; }
	const types::UTCDATEONLY &getClearingBusinessDate() const noexcept { return m_ClearingBusinessDate; }
	const types::STRING<32> &getSettlSessID() const noexcept { return m_SettlSessID; }
	const types::STRING<32> &getSettlSessSubID() const noexcept { return m_SettlSessSubID; }
	components::Parties &getRefParties() noexcept { return m_Parties; }
	const components::Parties &getRefParties() const noexcept { return m_Parties; }
	const types::STRING<32> &getAccount() const noexcept { return m_Account; }
	const types::INT &getAcctIDSource() const noexcept { return m_AcctIDSource; }
	const types::INT &getAccountType() const noexcept { return m_AccountType; }
	components::Instrument &getRefInstrument() noexcept { return m_Instrument; }
	const components::Instrument &getRefInstrument() const noexcept { return m_Instrument; }
	const types::CURRENCY<32> &getCurrency() const noexcept { return m_Currency; }
	const types::FLOAT &getSettlPrice() const noexcept { return m_SettlPrice; }
	const types::INT &getSettlPriceType() const noexcept { return m_SettlPriceType; }
	const types::FLOAT &getPriorSettlPrice() const noexcept { return m_PriorSettlPrice; }
	components::InstrmtLegGrp &getRefInstrmtLegGrp() noexcept { return m_InstrmtLegGrp; }
	const components::InstrmtLegGrp &getRefInstrmtLegGrp() const noexcept { return m_InstrmtLegGrp; }
	components::PosUndInstrmtGrp &getRefPosUndInstrmtGrp() noexcept { return m_PosUndInstrmtGrp; }
	const components::PosUndInstrmtGrp &getRefPosUndInstrmtGrp() const noexcept { return m_PosUndInstrmtGrp; }
	components::PositionQty &getRefPositionQty() noexcept { return m_PositionQty; }
	const components::PositionQty &getRefPositionQty() const noexcept { return m_PositionQty; }
	components::PositionAmountData &getRefPositionAmountData() noexcept { return m_PositionAmountData; }
	const components::PositionAmountData &getRefPositionAmountData() const noexcept { return m_PositionAmountData; }
	const types::CHAR &getRegistStatus() const noexcept { return m_RegistStatus; }
	const types::UTCDATEONLY &getDeliveryDate() const noexcept { return m_DeliveryDate; }
	const types::STRING<32> &getText() const noexcept { return m_Text; }
	const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
	const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }

	// mutators
	void setPosMaintRptID(const types::STRING<32> &v) noexcept { m_PosMaintRptID = v; m_presence |= (1ULL << P_PosMaintRptID); }
	void setPosReqID(const types::STRING<32> &v) noexcept { m_PosReqID = v; m_presence |= (1ULL << P_PosReqID); }
	void setPosReqType(types::INT v) noexcept { m_PosReqType = v; m_presence |= (1ULL << P_PosReqType); }
	void setSubscriptionRequestType(types::CHAR v) noexcept { m_SubscriptionRequestType = v; m_presence |= (1ULL << P_SubscriptionRequestType); }
	void setTotalNumPosReports(types::INT v) noexcept { m_TotalNumPosReports = v; m_presence |= (1ULL << P_TotalNumPosReports); }
	void setUnsolicitedIndicator(types::BOOLEAN v) noexcept { m_UnsolicitedIndicator = v; m_presence |= (1ULL << P_UnsolicitedIndicator); }
	void setPosReqResult(types::INT v) noexcept { m_PosReqResult = v; m_presence |= (1ULL << P_PosReqResult); }
	void setClearingBusinessDate(types::UTCDATEONLY v) noexcept { m_ClearingBusinessDate = v; m_presence |= (1ULL << P_ClearingBusinessDate); }
	void setSettlSessID(const types::STRING<32> &v) noexcept { m_SettlSessID = v; m_presence |= (1ULL << P_SettlSessID); }
	void setSettlSessSubID(const types::STRING<32> &v) noexcept { m_SettlSessSubID = v; m_presence |= (1ULL << P_SettlSessSubID); }
	void setAccount(const types::STRING<32> &v) noexcept { m_Account = v; m_presence |= (1ULL << P_Account); }
	void setAcctIDSource(types::INT v) noexcept { m_AcctIDSource = v; m_presence |= (1ULL << P_AcctIDSource); }
	void setAccountType(types::INT v) noexcept { m_AccountType = v; m_presence |= (1ULL << P_AccountType); }
	void setCurrency(const types::CURRENCY<32> &v) noexcept { m_Currency = v; m_presence |= (1ULL << P_Currency); }
	void setSettlPrice(types::FLOAT v) noexcept { m_SettlPrice = v; m_presence |= (1ULL << P_SettlPrice); }
	void setSettlPriceType(types::INT v) noexcept { m_SettlPriceType = v; m_presence |= (1ULL << P_SettlPriceType); }
	void setPriorSettlPrice(types::FLOAT v) noexcept { m_PriorSettlPrice = v; m_presence |= (1ULL << P_PriorSettlPrice); }
	void setRegistStatus(types::CHAR v) noexcept { m_RegistStatus = v; m_presence |= (1ULL << P_RegistStatus); }
	void setDeliveryDate(types::UTCDATEONLY v) noexcept { m_DeliveryDate = v; m_presence |= (1ULL << P_DeliveryDate); }
	void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
	void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
	void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Parties.hasAnySet()) { return true; }
		if (m_Instrument.hasAnySet()) { return true; }
		if (m_InstrmtLegGrp.hasAnySet()) { return true; }
		if (m_PosUndInstrmtGrp.hasAnySet()) { return true; }
		if (m_PositionQty.hasAnySet()) { return true; }
		if (m_PositionAmountData.hasAnySet()) { return true; }
		return false;
	}
	bool hasPosMaintRptID() const noexcept { return (m_presence & (1ULL << P_PosMaintRptID)) != 0; }
	bool hasPosReqID() const noexcept { return (m_presence & (1ULL << P_PosReqID)) != 0; }
	bool hasPosReqType() const noexcept { return (m_presence & (1ULL << P_PosReqType)) != 0; }
	bool hasSubscriptionRequestType() const noexcept { return (m_presence & (1ULL << P_SubscriptionRequestType)) != 0; }
	bool hasTotalNumPosReports() const noexcept { return (m_presence & (1ULL << P_TotalNumPosReports)) != 0; }
	bool hasUnsolicitedIndicator() const noexcept { return (m_presence & (1ULL << P_UnsolicitedIndicator)) != 0; }
	bool hasPosReqResult() const noexcept { return (m_presence & (1ULL << P_PosReqResult)) != 0; }
	bool hasClearingBusinessDate() const noexcept { return (m_presence & (1ULL << P_ClearingBusinessDate)) != 0; }
	bool hasSettlSessID() const noexcept { return (m_presence & (1ULL << P_SettlSessID)) != 0; }
	bool hasSettlSessSubID() const noexcept { return (m_presence & (1ULL << P_SettlSessSubID)) != 0; }
	bool hasAccount() const noexcept { return (m_presence & (1ULL << P_Account)) != 0; }
	bool hasAcctIDSource() const noexcept { return (m_presence & (1ULL << P_AcctIDSource)) != 0; }
	bool hasAccountType() const noexcept { return (m_presence & (1ULL << P_AccountType)) != 0; }
	bool hasCurrency() const noexcept { return (m_presence & (1ULL << P_Currency)) != 0; }
	bool hasSettlPrice() const noexcept { return (m_presence & (1ULL << P_SettlPrice)) != 0; }
	bool hasSettlPriceType() const noexcept { return (m_presence & (1ULL << P_SettlPriceType)) != 0; }
	bool hasPriorSettlPrice() const noexcept { return (m_presence & (1ULL << P_PriorSettlPrice)) != 0; }
	bool hasRegistStatus() const noexcept { return (m_presence & (1ULL << P_RegistStatus)) != 0; }
	bool hasDeliveryDate() const noexcept { return (m_presence & (1ULL << P_DeliveryDate)) != 0; }
	bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
	bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
	bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
};

} // namespace fix44::messages
