// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 26452f7de99726b3

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/EvntGrp.h>
#include <FIX4.4/components/FinancingDetails.h>
#include <FIX4.4/components/Instrument.h>
#include <FIX4.4/components/InstrumentLeg.h>
#include <FIX4.4/components/LegBenchmarkCurveData.h>
#include <FIX4.4/components/LegSecAltIDGrp.h>
#include <FIX4.4/components/LegStipulations.h>
#include <FIX4.4/components/NestedParties.h>
#include <FIX4.4/components/NstdPtysSubGrp.h>
#include <FIX4.4/components/OrderQtyData.h>
#include <FIX4.4/components/Parties.h>
#include <FIX4.4/components/PtysSubGrp.h>
#include <FIX4.4/components/QuotQualGrp.h>
#include <FIX4.4/components/QuotReqGrp.h>
#include <FIX4.4/components/QuotReqLegsGrp.h>
#include <FIX4.4/components/SecAltIDGrp.h>
#include <FIX4.4/components/SpreadOrBenchmarkCurveData.h>
#include <FIX4.4/components/Stipulations.h>
#include <FIX4.4/components/UndInstrmtGrp.h>
#include <FIX4.4/components/UndSecAltIDGrp.h>
#include <FIX4.4/components/UnderlyingInstrument.h>
#include <FIX4.4/components/UnderlyingStipulations.h>
#include <FIX4.4/components/YieldData.h>

namespace fix44::messages {

class QuoteRequest {
	static constexpr std::size_t P_QuoteReqID                   = 0;
	static constexpr std::size_t P_RFQReqID                     = 1;
	static constexpr std::size_t P_ClOrdID                      = 2;
	static constexpr std::size_t P_OrderCapacity                = 3;
	static constexpr std::size_t P_Text                         = 4;
	static constexpr std::size_t P_EncodedTextLen               = 5;
	static constexpr std::size_t P_EncodedText                  = 6;

	static constexpr uint64_t REQUIRED = (1ULL << 0);
	static constexpr std::size_t MAX_ENCODE_SIZE = 214;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_QuoteReqID{fields::QuoteReqID_NULL};
	types::STRING<32> m_RFQReqID{fields::RFQReqID_NULL};
	types::STRING<32> m_ClOrdID{fields::ClOrdID_NULL};
	types::CHAR m_OrderCapacity{fields::NULL_CHAR};
	components::QuotReqGrp m_QuotReqGrp{};
	types::STRING<32> m_Text{fields::Text_NULL};
	types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedText{fields::EncodedText_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "R";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_QuotReqGrp.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getQuoteReqID() const noexcept { return m_QuoteReqID; }
	const types::STRING<32> &getRFQReqID() const noexcept { return m_RFQReqID; }
	const types::STRING<32> &getClOrdID() const noexcept { return m_ClOrdID; }
	const types::CHAR &getOrderCapacity() const noexcept { return m_OrderCapacity; }
	components::QuotReqGrp &getRefQuotReqGrp() noexcept { return m_QuotReqGrp; }
	const components::QuotReqGrp &getRefQuotReqGrp() const noexcept { return m_QuotReqGrp; }
	const types::STRING<32> &getText() const noexcept { return m_Text; }
	const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
	const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }

	// mutators
	void setQuoteReqID(const types::STRING<32> &v) noexcept { m_QuoteReqID = v; m_presence |= (1ULL << P_QuoteReqID); }
	void setRFQReqID(const types::STRING<32> &v) noexcept { m_RFQReqID = v; m_presence |= (1ULL << P_RFQReqID); }
	void setClOrdID(const types::STRING<32> &v) noexcept { m_ClOrdID = v; m_presence |= (1ULL << P_ClOrdID); }
	void setOrderCapacity(types::CHAR v) noexcept { m_OrderCapacity = v; m_presence |= (1ULL << P_OrderCapacity); }
	void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
	void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
	void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_QuotReqGrp.hasAnySet()) { return true; }
		return false;
	}
	bool hasQuoteReqID() const noexcept { return (m_presence & (1ULL << P_QuoteReqID)) != 0; }
	bool hasRFQReqID() const noexcept { return (m_presence & (1ULL << P_RFQReqID)) != 0; }
	bool hasClOrdID() const noexcept { return (m_presence & (1ULL << P_ClOrdID)) != 0; }
	bool hasOrderCapacity() const noexcept { return (m_presence & (1ULL << P_OrderCapacity)) != 0; }
	bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
	bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
	bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
};

} // namespace fix44::messages
