// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 11dafcae2e183f34

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/NestedParties.h>
#include <FIX4.4/components/NstdPtysSubGrp.h>
#include <FIX4.4/components/Parties.h>
#include <FIX4.4/components/PtysSubGrp.h>
#include <FIX4.4/components/RgstDistInstGrp.h>
#include <FIX4.4/components/RgstDtlsGrp.h>

namespace fix44::messages {

class RegistrationInstructions {
	static constexpr std::size_t P_RegistID                     = 0;
	static constexpr std::size_t P_RegistTransType              = 1;
	static constexpr std::size_t P_RegistRefID                  = 2;
	static constexpr std::size_t P_ClOrdID                      = 3;
	static constexpr std::size_t P_Account                      = 4;
	static constexpr std::size_t P_AcctIDSource                 = 5;
	static constexpr std::size_t P_RegistAcctType               = 6;
	static constexpr std::size_t P_TaxAdvantageType             = 7;
	static constexpr std::size_t P_OwnershipType                = 8;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1) |
		(1ULL << 2);
	static constexpr std::size_t MAX_ENCODE_SIZE = 244;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_RegistID{fields::RegistID_NULL};
	types::CHAR m_RegistTransType{fields::NULL_CHAR};
	types::STRING<32> m_RegistRefID{fields::RegistRefID_NULL};
	types::STRING<32> m_ClOrdID{fields::ClOrdID_NULL};
	components::Parties m_Parties{};
	types::STRING<32> m_Account{fields::Account_NULL};
	types::INT m_AcctIDSource{fields::NULL_INT};
	types::STRING<32> m_RegistAcctType{fields::RegistAcctType_NULL};
	types::INT m_TaxAdvantageType{fields::NULL_INT};
	types::CHAR m_OwnershipType{fields::NULL_CHAR};
	components::RgstDtlsGrp m_RgstDtlsGrp{};
	components::RgstDistInstGrp m_RgstDistInstGrp{};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "o";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_Parties.compute_buffer_size();
		total += m_RgstDtlsGrp.compute_buffer_size();
		total += m_RgstDistInstGrp.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getRegistID() const noexcept { return m_RegistID; }
	const types::CHAR &getRegistTransType() const noexcept { return m_RegistTransType; }
	const types::STRING<32> &getRegistRefID() const noexcept { return m_RegistRefID; }
	const types::STRING<32> &getClOrdID() const noexcept { return m_ClOrdID; }
	components::Parties &getRefParties() noexcept { return m_Parties; }
	const components::Parties &getRefParties() const noexcept { return m_Parties; }
	const types::STRING<32> &getAccount() const noexcept { return m_Account; }
	const types::INT &getAcctIDSource() const noexcept { return m_AcctIDSource; }
	const types::STRING<32> &getRegistAcctType() const noexcept { return m_RegistAcctType; }
	const types::INT &getTaxAdvantageType() const noexcept { return m_TaxAdvantageType; }
	const types::CHAR &getOwnershipType() const noexcept { return m_OwnershipType; }
	components::RgstDtlsGrp &getRefRgstDtlsGrp() noexcept { return m_RgstDtlsGrp; }
	const components::RgstDtlsGrp &getRefRgstDtlsGrp() const noexcept { return m_RgstDtlsGrp; }
	components::RgstDistInstGrp &getRefRgstDistInstGrp() noexcept { return m_RgstDistInstGrp; }
	const components::RgstDistInstGrp &getRefRgstDistInstGrp() const noexcept { return m_RgstDistInstGrp; }

	// mutators
	void setRegistID(const types::STRING<32> &v) noexcept { m_RegistID = v; m_presence |= (1ULL << P_RegistID); }
	void setRegistTransType(types::CHAR v) noexcept { m_RegistTransType = v; m_presence |= (1ULL << P_RegistTransType); }
	void setRegistRefID(const types::STRING<32> &v) noexcept { m_RegistRefID = v; m_presence |= (1ULL << P_RegistRefID); }
	void setClOrdID(const types::STRING<32> &v) noexcept { m_ClOrdID = v; m_presence |= (1ULL << P_ClOrdID); }
	void setAccount(const types::STRING<32> &v) noexcept { m_Account = v; m_presence |= (1ULL << P_Account); }
	void setAcctIDSource(types::INT v) noexcept { m_AcctIDSource = v; m_presence |= (1ULL << P_AcctIDSource); }
	void setRegistAcctType(const types::STRING<32> &v) noexcept { m_RegistAcctType = v; m_presence |= (1ULL << P_RegistAcctType); }
	void setTaxAdvantageType(types::INT v) noexcept { m_TaxAdvantageType = v; m_presence |= (1ULL << P_TaxAdvantageType); }
	void setOwnershipType(types::CHAR v) noexcept { m_OwnershipType = v; m_presence |= (1ULL << P_OwnershipType); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Parties.hasAnySet()) { return true; }
		if (m_RgstDtlsGrp.hasAnySet()) { return true; }
		if (m_RgstDistInstGrp.hasAnySet()) { return true; }
		return false;
	}
	bool hasRegistID() const noexcept { return (m_presence & (1ULL << P_RegistID)) != 0; }
	bool hasRegistTransType() const noexcept { return (m_presence & (1ULL << P_RegistTransType)) != 0; }
	bool hasRegistRefID() const noexcept { return (m_presence & (1ULL << P_RegistRefID)) != 0; }
	bool hasClOrdID() const noexcept { return (m_presence & (1ULL << P_ClOrdID)) != 0; }
	bool hasAccount() const noexcept { return (m_presence & (1ULL << P_Account)) != 0; }
	bool hasAcctIDSource() const noexcept { return (m_presence & (1ULL << P_AcctIDSource)) != 0; }
	bool hasRegistAcctType() const noexcept { return (m_presence & (1ULL << P_RegistAcctType)) != 0; }
	bool hasTaxAdvantageType() const noexcept { return (m_presence & (1ULL << P_TaxAdvantageType)) != 0; }
	bool hasOwnershipType() const noexcept { return (m_presence & (1ULL << P_OwnershipType)) != 0; }
};

} // namespace fix44::messages
