// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: f7067ad21c9c905d

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/DlvyInstGrp.h>
#include <FIX4.4/components/Parties.h>
#include <FIX4.4/components/PtysSubGrp.h>
#include <FIX4.4/components/SettlInstGrp.h>
#include <FIX4.4/components/SettlInstructionsData.h>
#include <FIX4.4/components/SettlParties.h>
#include <FIX4.4/components/SettlPtysSubGrp.h>

namespace fix44::messages {

class SettlementInstructions {
	static constexpr std::size_t P_SettlInstMsgID               = 0;
	static constexpr std::size_t P_SettlInstReqID               = 1;
	static constexpr std::size_t P_SettlInstMode                = 2;
	static constexpr std::size_t P_SettlInstReqRejCode          = 3;
	static constexpr std::size_t P_Text                         = 4;
	static constexpr std::size_t P_EncodedTextLen               = 5;
	static constexpr std::size_t P_EncodedText                  = 6;
	static constexpr std::size_t P_ClOrdID                      = 7;
	static constexpr std::size_t P_TransactTime                 = 8;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 2) |
		(1ULL << 8);
	static constexpr std::size_t MAX_ENCODE_SIZE = 260;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_SettlInstMsgID{fields::SettlInstMsgID_NULL};
	types::STRING<32> m_SettlInstReqID{fields::SettlInstReqID_NULL};
	types::CHAR m_SettlInstMode{fields::NULL_CHAR};
	types::INT m_SettlInstReqRejCode{fields::NULL_INT};
	types::STRING<32> m_Text{fields::Text_NULL};
	types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedText{fields::EncodedText_NULL};
	types::STRING<32> m_ClOrdID{fields::ClOrdID_NULL};
	types::UTCTIMESTAMP m_TransactTime{fields::NULL_UTCTIMESTAMP};
	components::SettlInstGrp m_SettlInstGrp{};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "T";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_SettlInstGrp.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getSettlInstMsgID() const noexcept { return m_SettlInstMsgID; }
	const types::STRING<32> &getSettlInstReqID() const noexcept { return m_SettlInstReqID; }
	const types::CHAR &getSettlInstMode() const noexcept { return m_SettlInstMode; }
	const types::INT &getSettlInstReqRejCode() const noexcept { return m_SettlInstReqRejCode; }
	const types::STRING<32> &getText() const noexcept { return m_Text; }
	const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
	const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }
	const types::STRING<32> &getClOrdID() const noexcept { return m_ClOrdID; }
	const types::UTCTIMESTAMP &getTransactTime() const noexcept { return m_TransactTime; }
	components::SettlInstGrp &getRefSettlInstGrp() noexcept { return m_SettlInstGrp; }
	const components::SettlInstGrp &getRefSettlInstGrp() const noexcept { return m_SettlInstGrp; }

	// mutators
	void setSettlInstMsgID(const types::STRING<32> &v) noexcept { m_SettlInstMsgID = v; m_presence |= (1ULL << P_SettlInstMsgID); }
	void setSettlInstReqID(const types::STRING<32> &v) noexcept { m_SettlInstReqID = v; m_presence |= (1ULL << P_SettlInstReqID); }
	void setSettlInstMode(types::CHAR v) noexcept { m_SettlInstMode = v; m_presence |= (1ULL << P_SettlInstMode); }
	void setSettlInstReqRejCode(types::INT v) noexcept { m_SettlInstReqRejCode = v; m_presence |= (1ULL << P_SettlInstReqRejCode); }
	void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
	void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
	void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }
	void setClOrdID(const types::STRING<32> &v) noexcept { m_ClOrdID = v; m_presence |= (1ULL << P_ClOrdID); }
	void setTransactTime(types::UTCTIMESTAMP v) noexcept { m_TransactTime = v; m_presence |= (1ULL << P_TransactTime); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_SettlInstGrp.hasAnySet()) { return true; }
		return false;
	}
	bool hasSettlInstMsgID() const noexcept { return (m_presence & (1ULL << P_SettlInstMsgID)) != 0; }
	bool hasSettlInstReqID() const noexcept { return (m_presence & (1ULL << P_SettlInstReqID)) != 0; }
	bool hasSettlInstMode() const noexcept { return (m_presence & (1ULL << P_SettlInstMode)) != 0; }
	bool hasSettlInstReqRejCode() const noexcept { return (m_presence & (1ULL << P_SettlInstReqRejCode)) != 0; }
	bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
	bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
	bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
	bool hasClOrdID() const noexcept { return (m_presence & (1ULL << P_ClOrdID)) != 0; }
	bool hasTransactTime() const noexcept { return (m_presence & (1ULL << P_TransactTime)) != 0; }
};

} // namespace fix44::messages
