// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 7d12110daba0aedb

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

#include <FIX4.4/components/Parties.h>
#include <FIX4.4/components/PtysSubGrp.h>

namespace fix44::messages {

class SettlementInstructionRequest {
	static constexpr std::size_t P_SettlInstReqID               = 0;
	static constexpr std::size_t P_TransactTime                 = 1;
	static constexpr std::size_t P_AllocAccount                 = 2;
	static constexpr std::size_t P_AllocAcctIDSource            = 3;
	static constexpr std::size_t P_Side                         = 4;
	static constexpr std::size_t P_Product                      = 5;
	static constexpr std::size_t P_SecurityType                 = 6;
	static constexpr std::size_t P_CFICode                      = 7;
	static constexpr std::size_t P_EffectiveTime                = 8;
	static constexpr std::size_t P_ExpireTime                   = 9;
	static constexpr std::size_t P_LastUpdateTime               = 10;
	static constexpr std::size_t P_StandInstDbType              = 11;
	static constexpr std::size_t P_StandInstDbName              = 12;
	static constexpr std::size_t P_StandInstDbID                = 13;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1);
	static constexpr std::size_t MAX_ENCODE_SIZE = 388;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_SettlInstReqID{fields::SettlInstReqID_NULL};
	types::UTCTIMESTAMP m_TransactTime{fields::NULL_UTCTIMESTAMP};
	components::Parties m_Parties{};
	types::STRING<32> m_AllocAccount{fields::AllocAccount_NULL};
	types::INT m_AllocAcctIDSource{fields::NULL_INT};
	types::CHAR m_Side{fields::NULL_CHAR};
	types::INT m_Product{fields::NULL_INT};
	types::STRING<32> m_SecurityType{fields::SecurityType_NULL};
	types::STRING<32> m_CFICode{fields::CFICode_NULL};
	types::UTCTIMESTAMP m_EffectiveTime{fields::NULL_UTCTIMESTAMP};
	types::UTCTIMESTAMP m_ExpireTime{fields::NULL_UTCTIMESTAMP};
	types::UTCTIMESTAMP m_LastUpdateTime{fields::NULL_UTCTIMESTAMP};
	types::INT m_StandInstDbType{fields::NULL_INT};
	types::STRING<32> m_StandInstDbName{fields::StandInstDbName_NULL};
	types::STRING<32> m_StandInstDbID{fields::StandInstDbID_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "AV";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_Parties.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getSettlInstReqID() const noexcept { return m_SettlInstReqID; }
	const types::UTCTIMESTAMP &getTransactTime() const noexcept { return m_TransactTime; }
	components::Parties &getRefParties() noexcept { return m_Parties; }
	const components::Parties &getRefParties() const noexcept { return m_Parties; }
	const types::STRING<32> &getAllocAccount() const noexcept { return m_AllocAccount; }
	const types::INT &getAllocAcctIDSource() const noexcept { return m_AllocAcctIDSource; }
	const types::CHAR &getSide() const noexcept { return m_Side; }
	const types::INT &getProduct() const noexcept { return m_Product; }
	const types::STRING<32> &getSecurityType() const noexcept { return m_SecurityType; }
	const types::STRING<32> &getCFICode() const noexcept { return m_CFICode; }
	const types::UTCTIMESTAMP &getEffectiveTime() const noexcept { return m_EffectiveTime; }
	const types::UTCTIMESTAMP &getExpireTime() const noexcept { return m_ExpireTime; }
	const types::UTCTIMESTAMP &getLastUpdateTime() const noexcept { return m_LastUpdateTime; }
	const types::INT &getStandInstDbType() const noexcept { return m_StandInstDbType; }
	const types::STRING<32> &getStandInstDbName() const noexcept { return m_StandInstDbName; }
	const types::STRING<32> &getStandInstDbID() const noexcept { return m_StandInstDbID; }

	// mutators
	void setSettlInstReqID(const types::STRING<32> &v) noexcept { m_SettlInstReqID = v; m_presence |= (1ULL << P_SettlInstReqID); }
	void setTransactTime(types::UTCTIMESTAMP v) noexcept { m_TransactTime = v; m_presence |= (1ULL << P_TransactTime); }
	void setAllocAccount(const types::STRING<32> &v) noexcept { m_AllocAccount = v; m_presence |= (1ULL << P_AllocAccount); }
	void setAllocAcctIDSource(types::INT v) noexcept { m_AllocAcctIDSource = v; m_presence |= (1ULL << P_AllocAcctIDSource); }
	void setSide(types::CHAR v) noexcept { m_Side = v; m_presence |= (1ULL << P_Side); }
	void setProduct(types::INT v) noexcept { m_Product = v; m_presence |= (1ULL << P_Product); }
	void setSecurityType(const types::STRING<32> &v) noexcept { m_SecurityType = v; m_presence |= (1ULL << P_SecurityType); }
	void setCFICode(const types::STRING<32> &v) noexcept { m_CFICode = v; m_presence |= (1ULL << P_CFICode); }
	void setEffectiveTime(types::UTCTIMESTAMP v) noexcept { m_EffectiveTime = v; m_presence |= (1ULL << P_EffectiveTime); }
	void setExpireTime(types::UTCTIMESTAMP v) noexcept { m_ExpireTime = v; m_presence |= (1ULL << P_ExpireTime); }
	void setLastUpdateTime(types::UTCTIMESTAMP v) noexcept { m_LastUpdateTime = v; m_presence |= (1ULL << P_LastUpdateTime); }
	void setStandInstDbType(types::INT v) noexcept { m_StandInstDbType = v; m_presence |= (1ULL << P_StandInstDbType); }
	void setStandInstDbName(const types::STRING<32> &v) noexcept { m_StandInstDbName = v; m_presence |= (1ULL << P_StandInstDbName); }
	void setStandInstDbID(const types::STRING<32> &v) noexcept { m_StandInstDbID = v; m_presence |= (1ULL << P_StandInstDbID); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Parties.hasAnySet()) { return true; }
		return false;
	}
	bool hasSettlInstReqID() const noexcept { return (m_presence & (1ULL << P_SettlInstReqID)) != 0; }
	bool hasTransactTime() const noexcept { return (m_presence & (1ULL << P_TransactTime)) != 0; }
	bool hasAllocAccount() const noexcept { return (m_presence & (1ULL << P_AllocAccount)) != 0; }
	bool hasAllocAcctIDSource() const noexcept { return (m_presence & (1ULL << P_AllocAcctIDSource)) != 0; }
	bool hasSide() const noexcept { return (m_presence & (1ULL << P_Side)) != 0; }
	bool hasProduct() const noexcept { return (m_presence & (1ULL << P_Product)) != 0; }
	bool hasSecurityType() const noexcept { return (m_presence & (1ULL << P_SecurityType)) != 0; }
	bool hasCFICode() const noexcept { return (m_presence & (1ULL << P_CFICode)) != 0; }
	bool hasEffectiveTime() const noexcept { return (m_presence & (1ULL << P_EffectiveTime)) != 0; }
	bool hasExpireTime() const noexcept { return (m_presence & (1ULL << P_ExpireTime)) != 0; }
	bool hasLastUpdateTime() const noexcept { return (m_presence & (1ULL << P_LastUpdateTime)) != 0; }
	bool hasStandInstDbType() const noexcept { return (m_presence & (1ULL << P_StandInstDbType)) != 0; }
	bool hasStandInstDbName() const noexcept { return (m_presence & (1ULL << P_StandInstDbName)) != 0; }
	bool hasStandInstDbID() const noexcept { return (m_presence & (1ULL << P_StandInstDbID)) != 0; }
};

} // namespace fix44::messages
