// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 2e991402e3255e50

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.4/core/types.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/engine/protocol.h>
#include <FIX4.4/messages/Header.h>
#include <FIX4.4/messages/Trailer.h>

namespace fix44::messages {

class UserRequest {
	static constexpr std::size_t P_UserRequestID                = 0;
	static constexpr std::size_t P_UserRequestType              = 1;
	static constexpr std::size_t P_Username                     = 2;
	static constexpr std::size_t P_Password                     = 3;
	static constexpr std::size_t P_NewPassword                  = 4;
	static constexpr std::size_t P_RawDataLength                = 5;
	static constexpr std::size_t P_RawData                      = 6;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1) |
		(1ULL << 2);
	static constexpr std::size_t MAX_ENCODE_SIZE = 233;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_UserRequestID{fields::UserRequestID_NULL};
	types::INT m_UserRequestType{fields::NULL_INT};
	types::STRING<32> m_Username{fields::Username_NULL};
	types::STRING<32> m_Password{fields::Password_NULL};
	types::STRING<32> m_NewPassword{fields::NewPassword_NULL};
	types::LENGTH m_RawDataLength{fields::NULL_LENGTH};
	types::DATA<32> m_RawData{fields::RawData_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix44::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "BE";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getUserRequestID() const noexcept { return m_UserRequestID; }
	const types::INT &getUserRequestType() const noexcept { return m_UserRequestType; }
	const types::STRING<32> &getUsername() const noexcept { return m_Username; }
	const types::STRING<32> &getPassword() const noexcept { return m_Password; }
	const types::STRING<32> &getNewPassword() const noexcept { return m_NewPassword; }
	const types::LENGTH &getRawDataLength() const noexcept { return m_RawDataLength; }
	const types::DATA<32> &getRawData() const noexcept { return m_RawData; }

	// mutators
	void setUserRequestID(const types::STRING<32> &v) noexcept { m_UserRequestID = v; m_presence |= (1ULL << P_UserRequestID); }
	void setUserRequestType(types::INT v) noexcept { m_UserRequestType = v; m_presence |= (1ULL << P_UserRequestType); }
	void setUsername(const types::STRING<32> &v) noexcept { m_Username = v; m_presence |= (1ULL << P_Username); }
	void setPassword(const types::STRING<32> &v) noexcept { m_Password = v; m_presence |= (1ULL << P_Password); }
	void setNewPassword(const types::STRING<32> &v) noexcept { m_NewPassword = v; m_presence |= (1ULL << P_NewPassword); }
	void setRawDataLength(types::LENGTH v) noexcept { m_RawDataLength = v; m_presence |= (1ULL << P_RawDataLength); }
	void setRawData(const types::DATA<32> &v) noexcept { m_RawData = v; m_presence |= (1ULL << P_RawData); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		return false;
	}
	bool hasUserRequestID() const noexcept { return (m_presence & (1ULL << P_UserRequestID)) != 0; }
	bool hasUserRequestType() const noexcept { return (m_presence & (1ULL << P_UserRequestType)) != 0; }
	bool hasUsername() const noexcept { return (m_presence & (1ULL << P_Username)) != 0; }
	bool hasPassword() const noexcept { return (m_presence & (1ULL << P_Password)) != 0; }
	bool hasNewPassword() const noexcept { return (m_presence & (1ULL << P_NewPassword)) != 0; }
	bool hasRawDataLength() const noexcept { return (m_presence & (1ULL << P_RawDataLength)) != 0; }
	bool hasRawData() const noexcept { return (m_presence & (1ULL << P_RawData)) != 0; }
};

} // namespace fix44::messages
