// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: aa343ab43397aa13

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <FIX4.3/core/types.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/field_id.h>
#include <FIX4.3/engine/protocol.h>
#include <FIX4.3/messages/Header.h>
#include <FIX4.3/messages/Trailer.h>

#include <FIX4.3/components/Instrument.h>
#include <FIX4.3/components/OrderQtyData.h>

namespace fix43::messages {

class DontKnowTrade {
	static constexpr std::size_t P_OrderID                      = 0;
	static constexpr std::size_t P_ExecID                       = 1;
	static constexpr std::size_t P_DKReason                     = 2;
	static constexpr std::size_t P_Side                         = 3;
	static constexpr std::size_t P_LastQty                      = 4;
	static constexpr std::size_t P_LastPx                       = 5;
	static constexpr std::size_t P_Text                         = 6;
	static constexpr std::size_t P_EncodedTextLen               = 7;
	static constexpr std::size_t P_EncodedText                  = 8;

	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1) |
		(1ULL << 2) |
		(1ULL << 3);
	static constexpr std::size_t MAX_ENCODE_SIZE = 237;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_OrderID{fields::OrderID_NULL};
	types::STRING<32> m_ExecID{fields::ExecID_NULL};
	types::CHAR m_DKReason{fields::NULL_CHAR};
	components::Instrument m_Instrument{};
	types::CHAR m_Side{fields::NULL_CHAR};
	components::OrderQtyData m_OrderQtyData{};
	types::FLOAT m_LastQty{fields::NULL_QTY};
	types::FLOAT m_LastPx{fields::NULL_PRICE};
	types::STRING<32> m_Text{fields::Text_NULL};
	types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedText{fields::EncodedText_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix43::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "Q";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		total += m_Instrument.compute_buffer_size();
		total += m_OrderQtyData.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getOrderID() const noexcept { return m_OrderID; }
	const types::STRING<32> &getExecID() const noexcept { return m_ExecID; }
	const types::CHAR &getDKReason() const noexcept { return m_DKReason; }
	components::Instrument &getRefInstrument() noexcept { return m_Instrument; }
	const components::Instrument &getRefInstrument() const noexcept { return m_Instrument; }
	const types::CHAR &getSide() const noexcept { return m_Side; }
	components::OrderQtyData &getRefOrderQtyData() noexcept { return m_OrderQtyData; }
	const components::OrderQtyData &getRefOrderQtyData() const noexcept { return m_OrderQtyData; }
	const types::FLOAT &getLastQty() const noexcept { return m_LastQty; }
	const types::FLOAT &getLastPx() const noexcept { return m_LastPx; }
	const types::STRING<32> &getText() const noexcept { return m_Text; }
	const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
	const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }

	// mutators
	void setOrderID(const types::STRING<32> &v) noexcept { m_OrderID = v; m_presence |= (1ULL << P_OrderID); }
	void setExecID(const types::STRING<32> &v) noexcept { m_ExecID = v; m_presence |= (1ULL << P_ExecID); }
	void setDKReason(types::CHAR v) noexcept { m_DKReason = v; m_presence |= (1ULL << P_DKReason); }
	void setSide(types::CHAR v) noexcept { m_Side = v; m_presence |= (1ULL << P_Side); }
	void setLastQty(types::FLOAT v) noexcept { m_LastQty = v; m_presence |= (1ULL << P_LastQty); }
	void setLastPx(types::FLOAT v) noexcept { m_LastPx = v; m_presence |= (1ULL << P_LastPx); }
	void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
	void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
	void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Instrument.hasAnySet()) { return true; }
		if (m_OrderQtyData.hasAnySet()) { return true; }
		return false;
	}
	bool hasOrderID() const noexcept { return (m_presence & (1ULL << P_OrderID)) != 0; }
	bool hasExecID() const noexcept { return (m_presence & (1ULL << P_ExecID)) != 0; }
	bool hasDKReason() const noexcept { return (m_presence & (1ULL << P_DKReason)) != 0; }
	bool hasSide() const noexcept { return (m_presence & (1ULL << P_Side)) != 0; }
	bool hasLastQty() const noexcept { return (m_presence & (1ULL << P_LastQty)) != 0; }
	bool hasLastPx() const noexcept { return (m_presence & (1ULL << P_LastPx)) != 0; }
	bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
	bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
	bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
};

} // namespace fix43::messages
