// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 3dfc7eb1ef9b7fec

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <utility>
#include <vector>
#include <FIX4.3/core/types.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/field_id.h>
#include <FIX4.3/engine/protocol.h>
#include <FIX4.3/messages/Header.h>
#include <FIX4.3/messages/Trailer.h>

#include <FIX4.3/components/Instrument.h>
#include <FIX4.3/components/UnderlyingInstrument.h>

namespace fix43::messages {

class OrderMassCancelReport {
	static constexpr std::size_t P_ClOrdID                      = 0;
	static constexpr std::size_t P_SecondaryClOrdID             = 1;
	static constexpr std::size_t P_OrderID                      = 2;
	static constexpr std::size_t P_SecondaryOrderID             = 3;
	static constexpr std::size_t P_MassCancelRequestType        = 4;
	static constexpr std::size_t P_MassCancelResponse           = 5;
	static constexpr std::size_t P_MassCancelRejectReason       = 6;
	static constexpr std::size_t P_TotalAffectedOrders          = 7;
	static constexpr std::size_t P_TradingSessionID             = 8;
	static constexpr std::size_t P_TradingSessionSubID          = 9;
	static constexpr std::size_t P_Side                         = 10;
	static constexpr std::size_t P_TransactTime                 = 11;
	static constexpr std::size_t P_Text                         = 12;
	static constexpr std::size_t P_EncodedTextLen               = 13;
	static constexpr std::size_t P_EncodedText                  = 14;

	struct NoAffectedOrders {
		static constexpr std::size_t P_OrigClOrdID                  = 0;
		static constexpr std::size_t P_AffectedOrderID              = 1;
		static constexpr std::size_t P_AffectedSecondaryOrderID     = 2;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 110;

		types::STRING<32> m_OrigClOrdID{fields::OrigClOrdID_NULL};
		types::STRING<32> m_AffectedOrderID{fields::AffectedOrderID_NULL};
		types::STRING<32> m_AffectedSecondaryOrderID{fields::AffectedSecondaryOrderID_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::STRING<32> &getOrigClOrdID() const noexcept { return m_OrigClOrdID; }
		const types::STRING<32> &getAffectedOrderID() const noexcept { return m_AffectedOrderID; }
		const types::STRING<32> &getAffectedSecondaryOrderID() const noexcept { return m_AffectedSecondaryOrderID; }

		// mutators
		void setOrigClOrdID(const types::STRING<32> &v) noexcept { m_OrigClOrdID = v; m_presence |= (1ULL << P_OrigClOrdID); }
		void setAffectedOrderID(const types::STRING<32> &v) noexcept { m_AffectedOrderID = v; m_presence |= (1ULL << P_AffectedOrderID); }
		void setAffectedSecondaryOrderID(const types::STRING<32> &v) noexcept { m_AffectedSecondaryOrderID = v; m_presence |= (1ULL << P_AffectedSecondaryOrderID); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasOrigClOrdID() const noexcept { return (m_presence & (1ULL << P_OrigClOrdID)) != 0; }
		bool hasAffectedOrderID() const noexcept { return (m_presence & (1ULL << P_AffectedOrderID)) != 0; }
		bool hasAffectedSecondaryOrderID() const noexcept { return (m_presence & (1ULL << P_AffectedSecondaryOrderID)) != 0; }
	};


	static constexpr uint64_t REQUIRED =
		(1ULL << 2) |
		(1ULL << 4) |
		(1ULL << 5);
	static constexpr std::size_t MAX_ENCODE_SIZE = 387;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_ClOrdID{fields::ClOrdID_NULL};
	types::STRING<32> m_SecondaryClOrdID{fields::SecondaryClOrdID_NULL};
	types::STRING<32> m_OrderID{fields::OrderID_NULL};
	types::STRING<32> m_SecondaryOrderID{fields::SecondaryOrderID_NULL};
	types::CHAR m_MassCancelRequestType{fields::NULL_CHAR};
	types::CHAR m_MassCancelResponse{fields::NULL_CHAR};
	types::CHAR m_MassCancelRejectReason{fields::NULL_CHAR};
	types::INT m_TotalAffectedOrders{fields::NULL_INT};
	std::vector<NoAffectedOrders> m_NoAffectedOrdersGroup{};
	types::STRING<32> m_TradingSessionID{fields::TradingSessionID_NULL};
	types::STRING<32> m_TradingSessionSubID{fields::TradingSessionSubID_NULL};
	components::Instrument m_Instrument{};
	components::UnderlyingInstrument m_UnderlyingInstrument{};
	types::CHAR m_Side{fields::NULL_CHAR};
	types::UTCTIMESTAMP m_TransactTime{fields::NULL_UTCTIMESTAMP};
	types::STRING<32> m_Text{fields::Text_NULL};
	types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
	types::DATA<32> m_EncodedText{fields::EncodedText_NULL};

	uint64_t m_presence{0};

public:
	using Protocol = fix43::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "r";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		for (const auto &entry : m_NoAffectedOrdersGroup) { total += entry.compute_buffer_size(); }
		total += m_Instrument.compute_buffer_size();
		total += m_UnderlyingInstrument.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getClOrdID() const noexcept { return m_ClOrdID; }
	const types::STRING<32> &getSecondaryClOrdID() const noexcept { return m_SecondaryClOrdID; }
	const types::STRING<32> &getOrderID() const noexcept { return m_OrderID; }
	const types::STRING<32> &getSecondaryOrderID() const noexcept { return m_SecondaryOrderID; }
	const types::CHAR &getMassCancelRequestType() const noexcept { return m_MassCancelRequestType; }
	const types::CHAR &getMassCancelResponse() const noexcept { return m_MassCancelResponse; }
	const types::CHAR &getMassCancelRejectReason() const noexcept { return m_MassCancelRejectReason; }
	const types::INT &getTotalAffectedOrders() const noexcept { return m_TotalAffectedOrders; }
	std::vector<NoAffectedOrders> &getRefNoAffectedOrdersGroup() noexcept { return m_NoAffectedOrdersGroup; }
	const std::vector<NoAffectedOrders> &getRefNoAffectedOrdersGroup() const noexcept { return m_NoAffectedOrdersGroup; }
	const types::STRING<32> &getTradingSessionID() const noexcept { return m_TradingSessionID; }
	const types::STRING<32> &getTradingSessionSubID() const noexcept { return m_TradingSessionSubID; }
	components::Instrument &getRefInstrument() noexcept { return m_Instrument; }
	const components::Instrument &getRefInstrument() const noexcept { return m_Instrument; }
	components::UnderlyingInstrument &getRefUnderlyingInstrument() noexcept { return m_UnderlyingInstrument; }
	const components::UnderlyingInstrument &getRefUnderlyingInstrument() const noexcept { return m_UnderlyingInstrument; }
	const types::CHAR &getSide() const noexcept { return m_Side; }
	const types::UTCTIMESTAMP &getTransactTime() const noexcept { return m_TransactTime; }
	const types::STRING<32> &getText() const noexcept { return m_Text; }
	const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
	const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }

	// mutators
	void setClOrdID(const types::STRING<32> &v) noexcept { m_ClOrdID = v; m_presence |= (1ULL << P_ClOrdID); }
	void setSecondaryClOrdID(const types::STRING<32> &v) noexcept { m_SecondaryClOrdID = v; m_presence |= (1ULL << P_SecondaryClOrdID); }
	void setOrderID(const types::STRING<32> &v) noexcept { m_OrderID = v; m_presence |= (1ULL << P_OrderID); }
	void setSecondaryOrderID(const types::STRING<32> &v) noexcept { m_SecondaryOrderID = v; m_presence |= (1ULL << P_SecondaryOrderID); }
	void setMassCancelRequestType(types::CHAR v) noexcept { m_MassCancelRequestType = v; m_presence |= (1ULL << P_MassCancelRequestType); }
	void setMassCancelResponse(types::CHAR v) noexcept { m_MassCancelResponse = v; m_presence |= (1ULL << P_MassCancelResponse); }
	void setMassCancelRejectReason(types::CHAR v) noexcept { m_MassCancelRejectReason = v; m_presence |= (1ULL << P_MassCancelRejectReason); }
	void setTotalAffectedOrders(types::INT v) noexcept { m_TotalAffectedOrders = v; m_presence |= (1ULL << P_TotalAffectedOrders); }
	void addNoAffectedOrdersGroup(const NoAffectedOrders &item) { m_NoAffectedOrdersGroup.push_back(item); }
	void addNoAffectedOrdersGroup(NoAffectedOrders &&item) noexcept { m_NoAffectedOrdersGroup.push_back(std::move(item)); }
	void setTradingSessionID(const types::STRING<32> &v) noexcept { m_TradingSessionID = v; m_presence |= (1ULL << P_TradingSessionID); }
	void setTradingSessionSubID(const types::STRING<32> &v) noexcept { m_TradingSessionSubID = v; m_presence |= (1ULL << P_TradingSessionSubID); }
	void setSide(types::CHAR v) noexcept { m_Side = v; m_presence |= (1ULL << P_Side); }
	void setTransactTime(types::UTCTIMESTAMP v) noexcept { m_TransactTime = v; m_presence |= (1ULL << P_TransactTime); }
	void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
	void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
	void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Instrument.hasAnySet()) { return true; }
		if (m_UnderlyingInstrument.hasAnySet()) { return true; }
		if (!m_NoAffectedOrdersGroup.empty()) { return true; }
		return false;
	}
	bool hasClOrdID() const noexcept { return (m_presence & (1ULL << P_ClOrdID)) != 0; }
	bool hasSecondaryClOrdID() const noexcept { return (m_presence & (1ULL << P_SecondaryClOrdID)) != 0; }
	bool hasOrderID() const noexcept { return (m_presence & (1ULL << P_OrderID)) != 0; }
	bool hasSecondaryOrderID() const noexcept { return (m_presence & (1ULL << P_SecondaryOrderID)) != 0; }
	bool hasMassCancelRequestType() const noexcept { return (m_presence & (1ULL << P_MassCancelRequestType)) != 0; }
	bool hasMassCancelResponse() const noexcept { return (m_presence & (1ULL << P_MassCancelResponse)) != 0; }
	bool hasMassCancelRejectReason() const noexcept { return (m_presence & (1ULL << P_MassCancelRejectReason)) != 0; }
	bool hasTotalAffectedOrders() const noexcept { return (m_presence & (1ULL << P_TotalAffectedOrders)) != 0; }
	bool hasNoAffectedOrders() const noexcept { return !m_NoAffectedOrdersGroup.empty(); }
	bool hasTradingSessionID() const noexcept { return (m_presence & (1ULL << P_TradingSessionID)) != 0; }
	bool hasTradingSessionSubID() const noexcept { return (m_presence & (1ULL << P_TradingSessionSubID)) != 0; }
	bool hasSide() const noexcept { return (m_presence & (1ULL << P_Side)) != 0; }
	bool hasTransactTime() const noexcept { return (m_presence & (1ULL << P_TransactTime)) != 0; }
	bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
	bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
	bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
};

} // namespace fix43::messages
