// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 99bde0c792405e1d

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <utility>
#include <vector>
#include <FIX4.3/core/types.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/field_id.h>
#include <FIX4.3/engine/protocol.h>
#include <FIX4.3/messages/Header.h>
#include <FIX4.3/messages/Trailer.h>

#include <FIX4.3/components/Instrument.h>
#include <FIX4.3/components/Parties.h>

namespace fix43::messages {

class QuoteCancel {
	static constexpr std::size_t P_QuoteReqID                   = 0;
	static constexpr std::size_t P_QuoteID                      = 1;
	static constexpr std::size_t P_QuoteCancelType              = 2;
	static constexpr std::size_t P_QuoteResponseLevel           = 3;
	static constexpr std::size_t P_Account                      = 4;
	static constexpr std::size_t P_AccountType                  = 5;
	static constexpr std::size_t P_TradingSessionID             = 6;
	static constexpr std::size_t P_TradingSessionSubID          = 7;

	struct NoQuoteEntries {

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 32;

		components::Instrument m_Instrument{};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_Instrument.compute_buffer_size();
		}

		// accessors
		components::Instrument &getRefInstrument() noexcept { return m_Instrument; }
		const components::Instrument &getRefInstrument() const noexcept { return m_Instrument; }

		// mutators

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_Instrument.hasAnySet()) { return true; }
			return false;
		}
	};


	static constexpr uint64_t REQUIRED =
		(1ULL << 1) |
		(1ULL << 2);
	static constexpr std::size_t MAX_ENCODE_SIZE = 258;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_QuoteReqID{fields::QuoteReqID_NULL};
	types::STRING<32> m_QuoteID{fields::QuoteID_NULL};
	types::INT m_QuoteCancelType{fields::NULL_INT};
	types::INT m_QuoteResponseLevel{fields::NULL_INT};
	components::Parties m_Parties{};
	types::STRING<32> m_Account{fields::Account_NULL};
	types::INT m_AccountType{fields::NULL_INT};
	types::STRING<32> m_TradingSessionID{fields::TradingSessionID_NULL};
	types::STRING<32> m_TradingSessionSubID{fields::TradingSessionSubID_NULL};
	std::vector<NoQuoteEntries> m_NoQuoteEntriesGroup{};

	uint64_t m_presence{0};

public:
	using Protocol = fix43::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "Z";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		for (const auto &entry : m_NoQuoteEntriesGroup) { total += entry.compute_buffer_size(); }
		total += m_Parties.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getQuoteReqID() const noexcept { return m_QuoteReqID; }
	const types::STRING<32> &getQuoteID() const noexcept { return m_QuoteID; }
	const types::INT &getQuoteCancelType() const noexcept { return m_QuoteCancelType; }
	const types::INT &getQuoteResponseLevel() const noexcept { return m_QuoteResponseLevel; }
	components::Parties &getRefParties() noexcept { return m_Parties; }
	const components::Parties &getRefParties() const noexcept { return m_Parties; }
	const types::STRING<32> &getAccount() const noexcept { return m_Account; }
	const types::INT &getAccountType() const noexcept { return m_AccountType; }
	const types::STRING<32> &getTradingSessionID() const noexcept { return m_TradingSessionID; }
	const types::STRING<32> &getTradingSessionSubID() const noexcept { return m_TradingSessionSubID; }
	std::vector<NoQuoteEntries> &getRefNoQuoteEntriesGroup() noexcept { return m_NoQuoteEntriesGroup; }
	const std::vector<NoQuoteEntries> &getRefNoQuoteEntriesGroup() const noexcept { return m_NoQuoteEntriesGroup; }

	// mutators
	void setQuoteReqID(const types::STRING<32> &v) noexcept { m_QuoteReqID = v; m_presence |= (1ULL << P_QuoteReqID); }
	void setQuoteID(const types::STRING<32> &v) noexcept { m_QuoteID = v; m_presence |= (1ULL << P_QuoteID); }
	void setQuoteCancelType(types::INT v) noexcept { m_QuoteCancelType = v; m_presence |= (1ULL << P_QuoteCancelType); }
	void setQuoteResponseLevel(types::INT v) noexcept { m_QuoteResponseLevel = v; m_presence |= (1ULL << P_QuoteResponseLevel); }
	void setAccount(const types::STRING<32> &v) noexcept { m_Account = v; m_presence |= (1ULL << P_Account); }
	void setAccountType(types::INT v) noexcept { m_AccountType = v; m_presence |= (1ULL << P_AccountType); }
	void setTradingSessionID(const types::STRING<32> &v) noexcept { m_TradingSessionID = v; m_presence |= (1ULL << P_TradingSessionID); }
	void setTradingSessionSubID(const types::STRING<32> &v) noexcept { m_TradingSessionSubID = v; m_presence |= (1ULL << P_TradingSessionSubID); }
	void addNoQuoteEntriesGroup(const NoQuoteEntries &item) { m_NoQuoteEntriesGroup.push_back(item); }
	void addNoQuoteEntriesGroup(NoQuoteEntries &&item) noexcept { m_NoQuoteEntriesGroup.push_back(std::move(item)); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Parties.hasAnySet()) { return true; }
		if (!m_NoQuoteEntriesGroup.empty()) { return true; }
		return false;
	}
	bool hasQuoteReqID() const noexcept { return (m_presence & (1ULL << P_QuoteReqID)) != 0; }
	bool hasQuoteID() const noexcept { return (m_presence & (1ULL << P_QuoteID)) != 0; }
	bool hasQuoteCancelType() const noexcept { return (m_presence & (1ULL << P_QuoteCancelType)) != 0; }
	bool hasQuoteResponseLevel() const noexcept { return (m_presence & (1ULL << P_QuoteResponseLevel)) != 0; }
	bool hasAccount() const noexcept { return (m_presence & (1ULL << P_Account)) != 0; }
	bool hasAccountType() const noexcept { return (m_presence & (1ULL << P_AccountType)) != 0; }
	bool hasTradingSessionID() const noexcept { return (m_presence & (1ULL << P_TradingSessionID)) != 0; }
	bool hasTradingSessionSubID() const noexcept { return (m_presence & (1ULL << P_TradingSessionSubID)) != 0; }
	bool hasNoQuoteEntries() const noexcept { return !m_NoQuoteEntriesGroup.empty(); }
};

} // namespace fix43::messages
