// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 1582b81e81ea2f42

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <utility>
#include <vector>
#include <FIX4.3/core/types.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/field_id.h>
#include <FIX4.3/engine/protocol.h>
#include <FIX4.3/messages/Header.h>
#include <FIX4.3/messages/Trailer.h>

#include <FIX4.3/components/NestedParties.h>
#include <FIX4.3/components/Parties.h>

namespace fix43::messages {

class RegistrationInstructions {
	static constexpr std::size_t P_RegistID                     = 0;
	static constexpr std::size_t P_RegistTransType              = 1;
	static constexpr std::size_t P_RegistRefID                  = 2;
	static constexpr std::size_t P_ClOrdID                      = 3;
	static constexpr std::size_t P_Account                      = 4;
	static constexpr std::size_t P_RegistAcctType               = 5;
	static constexpr std::size_t P_TaxAdvantageType             = 6;
	static constexpr std::size_t P_OwnershipType                = 7;

	struct NoRegistDtls {
		static constexpr std::size_t P_RegistDetls                  = 0;
		static constexpr std::size_t P_RegistEmail                  = 1;
		static constexpr std::size_t P_MailingDtls                  = 2;
		static constexpr std::size_t P_MailingInst                  = 3;
		static constexpr std::size_t P_OwnerType                    = 4;
		static constexpr std::size_t P_DateOfBirth                  = 5;
		static constexpr std::size_t P_InvestorCountryOfResidence   = 6;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 223;

		types::STRING<32> m_RegistDetls{fields::RegistDetls_NULL};
		types::STRING<32> m_RegistEmail{fields::RegistEmail_NULL};
		types::STRING<32> m_MailingDtls{fields::MailingDtls_NULL};
		types::STRING<32> m_MailingInst{fields::MailingInst_NULL};
		components::NestedParties m_NestedParties{};
		types::INT m_OwnerType{fields::NULL_INT};
		types::UTCDATEONLY m_DateOfBirth{fields::NULL_LOCALMKTDATE};
		types::COUNTRY<32> m_InvestorCountryOfResidence{fields::InvestorCountryOfResidence_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_NestedParties.compute_buffer_size();
		}

		// accessors
		const types::STRING<32> &getRegistDetls() const noexcept { return m_RegistDetls; }
		const types::STRING<32> &getRegistEmail() const noexcept { return m_RegistEmail; }
		const types::STRING<32> &getMailingDtls() const noexcept { return m_MailingDtls; }
		const types::STRING<32> &getMailingInst() const noexcept { return m_MailingInst; }
		components::NestedParties &getRefNestedParties() noexcept { return m_NestedParties; }
		const components::NestedParties &getRefNestedParties() const noexcept { return m_NestedParties; }
		const types::INT &getOwnerType() const noexcept { return m_OwnerType; }
		const types::UTCDATEONLY &getDateOfBirth() const noexcept { return m_DateOfBirth; }
		const types::COUNTRY<32> &getInvestorCountryOfResidence() const noexcept { return m_InvestorCountryOfResidence; }

		// mutators
		void setRegistDetls(const types::STRING<32> &v) noexcept { m_RegistDetls = v; m_presence |= (1ULL << P_RegistDetls); }
		void setRegistEmail(const types::STRING<32> &v) noexcept { m_RegistEmail = v; m_presence |= (1ULL << P_RegistEmail); }
		void setMailingDtls(const types::STRING<32> &v) noexcept { m_MailingDtls = v; m_presence |= (1ULL << P_MailingDtls); }
		void setMailingInst(const types::STRING<32> &v) noexcept { m_MailingInst = v; m_presence |= (1ULL << P_MailingInst); }
		void setOwnerType(types::INT v) noexcept { m_OwnerType = v; m_presence |= (1ULL << P_OwnerType); }
		void setDateOfBirth(types::UTCDATEONLY v) noexcept { m_DateOfBirth = v; m_presence |= (1ULL << P_DateOfBirth); }
		void setInvestorCountryOfResidence(const types::COUNTRY<32> &v) noexcept { m_InvestorCountryOfResidence = v; m_presence |= (1ULL << P_InvestorCountryOfResidence); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_NestedParties.hasAnySet()) { return true; }
			return false;
		}
		bool hasRegistDetls() const noexcept { return (m_presence & (1ULL << P_RegistDetls)) != 0; }
		bool hasRegistEmail() const noexcept { return (m_presence & (1ULL << P_RegistEmail)) != 0; }
		bool hasMailingDtls() const noexcept { return (m_presence & (1ULL << P_MailingDtls)) != 0; }
		bool hasMailingInst() const noexcept { return (m_presence & (1ULL << P_MailingInst)) != 0; }
		bool hasOwnerType() const noexcept { return (m_presence & (1ULL << P_OwnerType)) != 0; }
		bool hasDateOfBirth() const noexcept { return (m_presence & (1ULL << P_DateOfBirth)) != 0; }
		bool hasInvestorCountryOfResidence() const noexcept { return (m_presence & (1ULL << P_InvestorCountryOfResidence)) != 0; }
	};

	struct NoDistribInsts {
		static constexpr std::size_t P_DistribPaymentMethod         = 0;
		static constexpr std::size_t P_DistribPercentage            = 1;
		static constexpr std::size_t P_CashDistribCurr              = 2;
		static constexpr std::size_t P_CashDistribAgentName         = 3;
		static constexpr std::size_t P_CashDistribAgentCode         = 4;
		static constexpr std::size_t P_CashDistribAgentAcctNumber   = 5;
		static constexpr std::size_t P_CashDistribPayRef            = 6;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 239;

		types::INT m_DistribPaymentMethod{fields::NULL_INT};
		types::FLOAT m_DistribPercentage{fields::NULL_PERCENTAGE};
		types::CURRENCY<32> m_CashDistribCurr{fields::CashDistribCurr_NULL};
		types::STRING<32> m_CashDistribAgentName{fields::CashDistribAgentName_NULL};
		types::STRING<32> m_CashDistribAgentCode{fields::CashDistribAgentCode_NULL};
		types::STRING<32> m_CashDistribAgentAcctNumber{fields::CashDistribAgentAcctNumber_NULL};
		types::STRING<32> m_CashDistribPayRef{fields::CashDistribPayRef_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::INT &getDistribPaymentMethod() const noexcept { return m_DistribPaymentMethod; }
		const types::FLOAT &getDistribPercentage() const noexcept { return m_DistribPercentage; }
		const types::CURRENCY<32> &getCashDistribCurr() const noexcept { return m_CashDistribCurr; }
		const types::STRING<32> &getCashDistribAgentName() const noexcept { return m_CashDistribAgentName; }
		const types::STRING<32> &getCashDistribAgentCode() const noexcept { return m_CashDistribAgentCode; }
		const types::STRING<32> &getCashDistribAgentAcctNumber() const noexcept { return m_CashDistribAgentAcctNumber; }
		const types::STRING<32> &getCashDistribPayRef() const noexcept { return m_CashDistribPayRef; }

		// mutators
		void setDistribPaymentMethod(types::INT v) noexcept { m_DistribPaymentMethod = v; m_presence |= (1ULL << P_DistribPaymentMethod); }
		void setDistribPercentage(types::FLOAT v) noexcept { m_DistribPercentage = v; m_presence |= (1ULL << P_DistribPercentage); }
		void setCashDistribCurr(const types::CURRENCY<32> &v) noexcept { m_CashDistribCurr = v; m_presence |= (1ULL << P_CashDistribCurr); }
		void setCashDistribAgentName(const types::STRING<32> &v) noexcept { m_CashDistribAgentName = v; m_presence |= (1ULL << P_CashDistribAgentName); }
		void setCashDistribAgentCode(const types::STRING<32> &v) noexcept { m_CashDistribAgentCode = v; m_presence |= (1ULL << P_CashDistribAgentCode); }
		void setCashDistribAgentAcctNumber(const types::STRING<32> &v) noexcept { m_CashDistribAgentAcctNumber = v; m_presence |= (1ULL << P_CashDistribAgentAcctNumber); }
		void setCashDistribPayRef(const types::STRING<32> &v) noexcept { m_CashDistribPayRef = v; m_presence |= (1ULL << P_CashDistribPayRef); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasDistribPaymentMethod() const noexcept { return (m_presence & (1ULL << P_DistribPaymentMethod)) != 0; }
		bool hasDistribPercentage() const noexcept { return (m_presence & (1ULL << P_DistribPercentage)) != 0; }
		bool hasCashDistribCurr() const noexcept { return (m_presence & (1ULL << P_CashDistribCurr)) != 0; }
		bool hasCashDistribAgentName() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentName)) != 0; }
		bool hasCashDistribAgentCode() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentCode)) != 0; }
		bool hasCashDistribAgentAcctNumber() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentAcctNumber)) != 0; }
		bool hasCashDistribPayRef() const noexcept { return (m_presence & (1ULL << P_CashDistribPayRef)) != 0; }
	};


	static constexpr uint64_t REQUIRED =
		(1ULL << 0) |
		(1ULL << 1) |
		(1ULL << 2);
	static constexpr std::size_t MAX_ENCODE_SIZE = 219;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_RegistID{fields::RegistID_NULL};
	types::CHAR m_RegistTransType{fields::NULL_CHAR};
	types::STRING<32> m_RegistRefID{fields::RegistRefID_NULL};
	types::STRING<32> m_ClOrdID{fields::ClOrdID_NULL};
	components::Parties m_Parties{};
	types::STRING<32> m_Account{fields::Account_NULL};
	types::STRING<32> m_RegistAcctType{fields::RegistAcctType_NULL};
	types::INT m_TaxAdvantageType{fields::NULL_INT};
	types::CHAR m_OwnershipType{fields::NULL_CHAR};
	std::vector<NoRegistDtls> m_NoRegistDtlsGroup{};
	std::vector<NoDistribInsts> m_NoDistribInstsGroup{};

	uint64_t m_presence{0};

public:
	using Protocol = fix43::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "o";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		for (const auto &entry : m_NoRegistDtlsGroup) { total += entry.compute_buffer_size(); }
		for (const auto &entry : m_NoDistribInstsGroup) { total += entry.compute_buffer_size(); }
		total += m_Parties.compute_buffer_size();
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getRegistID() const noexcept { return m_RegistID; }
	const types::CHAR &getRegistTransType() const noexcept { return m_RegistTransType; }
	const types::STRING<32> &getRegistRefID() const noexcept { return m_RegistRefID; }
	const types::STRING<32> &getClOrdID() const noexcept { return m_ClOrdID; }
	components::Parties &getRefParties() noexcept { return m_Parties; }
	const components::Parties &getRefParties() const noexcept { return m_Parties; }
	const types::STRING<32> &getAccount() const noexcept { return m_Account; }
	const types::STRING<32> &getRegistAcctType() const noexcept { return m_RegistAcctType; }
	const types::INT &getTaxAdvantageType() const noexcept { return m_TaxAdvantageType; }
	const types::CHAR &getOwnershipType() const noexcept { return m_OwnershipType; }
	std::vector<NoRegistDtls> &getRefNoRegistDtlsGroup() noexcept { return m_NoRegistDtlsGroup; }
	const std::vector<NoRegistDtls> &getRefNoRegistDtlsGroup() const noexcept { return m_NoRegistDtlsGroup; }
	std::vector<NoDistribInsts> &getRefNoDistribInstsGroup() noexcept { return m_NoDistribInstsGroup; }
	const std::vector<NoDistribInsts> &getRefNoDistribInstsGroup() const noexcept { return m_NoDistribInstsGroup; }

	// mutators
	void setRegistID(const types::STRING<32> &v) noexcept { m_RegistID = v; m_presence |= (1ULL << P_RegistID); }
	void setRegistTransType(types::CHAR v) noexcept { m_RegistTransType = v; m_presence |= (1ULL << P_RegistTransType); }
	void setRegistRefID(const types::STRING<32> &v) noexcept { m_RegistRefID = v; m_presence |= (1ULL << P_RegistRefID); }
	void setClOrdID(const types::STRING<32> &v) noexcept { m_ClOrdID = v; m_presence |= (1ULL << P_ClOrdID); }
	void setAccount(const types::STRING<32> &v) noexcept { m_Account = v; m_presence |= (1ULL << P_Account); }
	void setRegistAcctType(const types::STRING<32> &v) noexcept { m_RegistAcctType = v; m_presence |= (1ULL << P_RegistAcctType); }
	void setTaxAdvantageType(types::INT v) noexcept { m_TaxAdvantageType = v; m_presence |= (1ULL << P_TaxAdvantageType); }
	void setOwnershipType(types::CHAR v) noexcept { m_OwnershipType = v; m_presence |= (1ULL << P_OwnershipType); }
	void addNoRegistDtlsGroup(const NoRegistDtls &item) { m_NoRegistDtlsGroup.push_back(item); }
	void addNoRegistDtlsGroup(NoRegistDtls &&item) noexcept { m_NoRegistDtlsGroup.push_back(std::move(item)); }
	void addNoDistribInstsGroup(const NoDistribInsts &item) { m_NoDistribInstsGroup.push_back(item); }
	void addNoDistribInstsGroup(NoDistribInsts &&item) noexcept { m_NoDistribInstsGroup.push_back(std::move(item)); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_Parties.hasAnySet()) { return true; }
		if (!m_NoRegistDtlsGroup.empty()) { return true; }
		if (!m_NoDistribInstsGroup.empty()) { return true; }
		return false;
	}
	bool hasRegistID() const noexcept { return (m_presence & (1ULL << P_RegistID)) != 0; }
	bool hasRegistTransType() const noexcept { return (m_presence & (1ULL << P_RegistTransType)) != 0; }
	bool hasRegistRefID() const noexcept { return (m_presence & (1ULL << P_RegistRefID)) != 0; }
	bool hasClOrdID() const noexcept { return (m_presence & (1ULL << P_ClOrdID)) != 0; }
	bool hasAccount() const noexcept { return (m_presence & (1ULL << P_Account)) != 0; }
	bool hasRegistAcctType() const noexcept { return (m_presence & (1ULL << P_RegistAcctType)) != 0; }
	bool hasTaxAdvantageType() const noexcept { return (m_presence & (1ULL << P_TaxAdvantageType)) != 0; }
	bool hasOwnershipType() const noexcept { return (m_presence & (1ULL << P_OwnershipType)) != 0; }
	bool hasNoRegistDtls() const noexcept { return !m_NoRegistDtlsGroup.empty(); }
	bool hasNoDistribInsts() const noexcept { return !m_NoDistribInstsGroup.empty(); }
};

} // namespace fix43::messages
