// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Auto-generated FIX code. Do not edit by hand.

// Generated by FalconFIX Generator
// ContentHash: daa97398dbf79cdf

#pragma once

#include <array>
#include <cstdint>
#include <string_view>
#include <utils/fast_buffer.h>
#include <utils/error_codes.h>
#include <utility>
#include <vector>
#include <FIX4.3/core/types.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/field_id.h>
#include <FIX4.3/engine/protocol.h>
#include <FIX4.3/messages/Header.h>
#include <FIX4.3/messages/Trailer.h>

#include <FIX4.3/components/Instrument.h>

namespace fix43::messages {

class RFQRequest {
	static constexpr std::size_t P_RFQReqID                     = 0;
	static constexpr std::size_t P_SubscriptionRequestType      = 1;

	struct NoRelatedSym {
		static constexpr std::size_t P_PrevClosePx                  = 0;
		static constexpr std::size_t P_QuoteRequestType             = 1;
		static constexpr std::size_t P_QuoteType                    = 2;
		static constexpr std::size_t P_TradingSessionID             = 3;
		static constexpr std::size_t P_TradingSessionSubID          = 4;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 153;

		components::Instrument m_Instrument{};
		types::FLOAT m_PrevClosePx{fields::NULL_PRICE};
		types::INT m_QuoteRequestType{fields::NULL_INT};
		types::INT m_QuoteType{fields::NULL_INT};
		types::STRING<32> m_TradingSessionID{fields::TradingSessionID_NULL};
		types::STRING<32> m_TradingSessionSubID{fields::TradingSessionSubID_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_Instrument.compute_buffer_size();
		}

		// accessors
		components::Instrument &getRefInstrument() noexcept { return m_Instrument; }
		const components::Instrument &getRefInstrument() const noexcept { return m_Instrument; }
		const types::FLOAT &getPrevClosePx() const noexcept { return m_PrevClosePx; }
		const types::INT &getQuoteRequestType() const noexcept { return m_QuoteRequestType; }
		const types::INT &getQuoteType() const noexcept { return m_QuoteType; }
		const types::STRING<32> &getTradingSessionID() const noexcept { return m_TradingSessionID; }
		const types::STRING<32> &getTradingSessionSubID() const noexcept { return m_TradingSessionSubID; }

		// mutators
		void setPrevClosePx(types::FLOAT v) noexcept { m_PrevClosePx = v; m_presence |= (1ULL << P_PrevClosePx); }
		void setQuoteRequestType(types::INT v) noexcept { m_QuoteRequestType = v; m_presence |= (1ULL << P_QuoteRequestType); }
		void setQuoteType(types::INT v) noexcept { m_QuoteType = v; m_presence |= (1ULL << P_QuoteType); }
		void setTradingSessionID(const types::STRING<32> &v) noexcept { m_TradingSessionID = v; m_presence |= (1ULL << P_TradingSessionID); }
		void setTradingSessionSubID(const types::STRING<32> &v) noexcept { m_TradingSessionSubID = v; m_presence |= (1ULL << P_TradingSessionSubID); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_Instrument.hasAnySet()) { return true; }
			return false;
		}
		bool hasPrevClosePx() const noexcept { return (m_presence & (1ULL << P_PrevClosePx)) != 0; }
		bool hasQuoteRequestType() const noexcept { return (m_presence & (1ULL << P_QuoteRequestType)) != 0; }
		bool hasQuoteType() const noexcept { return (m_presence & (1ULL << P_QuoteType)) != 0; }
		bool hasTradingSessionID() const noexcept { return (m_presence & (1ULL << P_TradingSessionID)) != 0; }
		bool hasTradingSessionSubID() const noexcept { return (m_presence & (1ULL << P_TradingSessionSubID)) != 0; }
	};


	static constexpr uint64_t REQUIRED = (1ULL << 0);
	static constexpr std::size_t MAX_ENCODE_SIZE = 43;

	Header m_Header{};
	Trailer m_Trailer{};

	types::STRING<32> m_RFQReqID{fields::RFQReqID_NULL};
	std::vector<NoRelatedSym> m_NoRelatedSymGroup{};
	types::CHAR m_SubscriptionRequestType{fields::NULL_CHAR};

	uint64_t m_presence{0};

public:
	using Protocol = fix43::Protocol;
	static constexpr falconfix::ProtocolVersion PROTOCOL = Protocol::VERSION;
	static constexpr std::string_view MSGTYPE = "AH";
	static constexpr bool IS_ADMIN = false;

	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	FFStatus setString(const char *&p, const char *end) noexcept;
	FFStatus setString(std::string_view sv) noexcept {
		const char *p = sv.data();
		const char *end = p + sv.size();
		return setString(p, end);
	}

	// encode
	FFStatus toString(falconfix::FastBuffer &out, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE
			+ m_Header.compute_buffer_size()
			+ m_Trailer.compute_buffer_size();
		for (const auto &entry : m_NoRelatedSymGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	Header &getRefHeader() noexcept { return m_Header; }
	const Header &getRefHeader() const noexcept { return m_Header; }
	Trailer &getRefTrailer() noexcept { return m_Trailer; }
	const Trailer &getRefTrailer() const noexcept { return m_Trailer; }

	const types::STRING<32> &getRFQReqID() const noexcept { return m_RFQReqID; }
	std::vector<NoRelatedSym> &getRefNoRelatedSymGroup() noexcept { return m_NoRelatedSymGroup; }
	const std::vector<NoRelatedSym> &getRefNoRelatedSymGroup() const noexcept { return m_NoRelatedSymGroup; }
	const types::CHAR &getSubscriptionRequestType() const noexcept { return m_SubscriptionRequestType; }

	// mutators
	void setRFQReqID(const types::STRING<32> &v) noexcept { m_RFQReqID = v; m_presence |= (1ULL << P_RFQReqID); }
	void addNoRelatedSymGroup(const NoRelatedSym &item) { m_NoRelatedSymGroup.push_back(item); }
	void addNoRelatedSymGroup(NoRelatedSym &&item) noexcept { m_NoRelatedSymGroup.push_back(std::move(item)); }
	void setSubscriptionRequestType(types::CHAR v) noexcept { m_SubscriptionRequestType = v; m_presence |= (1ULL << P_SubscriptionRequestType); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoRelatedSymGroup.empty()) { return true; }
		return false;
	}
	bool hasRFQReqID() const noexcept { return (m_presence & (1ULL << P_RFQReqID)) != 0; }
	bool hasNoRelatedSym() const noexcept { return !m_NoRelatedSymGroup.empty(); }
	bool hasSubscriptionRequestType() const noexcept { return (m_presence & (1ULL << P_SubscriptionRequestType)) != 0; }
};

} // namespace fix43::messages
