// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 0df6b3d277573c22

#pragma once

#include <fix_messages.h>

namespace fix42::samples {

inline fix42::messages::Heartbeat createHeartbeat() noexcept {
	fix42::messages::Heartbeat msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000057");
	msg.setField(35, "0");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(112, "REQID_1");
	msg.setField(10, "013");
	return msg;
}

inline fix42::messages::TestRequest createTestRequest() noexcept {
	fix42::messages::TestRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000057");
	msg.setField(35, "1");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(112, "REQID_1");
	msg.setField(10, "014");
	return msg;
}

inline fix42::messages::ResendRequest createResendRequest() noexcept {
	fix42::messages::ResendRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000054");
	msg.setField(35, "2");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(7, "1");
	msg.setField(16, "1");
	msg.setField(10, "177");
	return msg;
}

inline fix42::messages::Reject createReject() noexcept {
	fix42::messages::Reject msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000099");
	msg.setField(35, "3");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(45, "1");
	msg.setField(371, "1");
	msg.setField(372, "VAL_372");
	msg.setField(373, "1");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "063");
	return msg;
}

inline fix42::messages::SequenceReset createSequenceReset() noexcept {
	fix42::messages::SequenceReset msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000056");
	msg.setField(35, "4");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(123, "Y");
	msg.setField(36, "1");
	msg.setField(10, "062");
	return msg;
}

inline fix42::messages::Logout createLogout() noexcept {
	fix42::messages::Logout msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000070");
	msg.setField(35, "5");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "144");
	return msg;
}

inline fix42::messages::IOI createIOI() noexcept {
	fix42::messages::IOI msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000408");
	msg.setField(35, "6");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(23, "VAL_23");
	msg.setField(28, "1");
	msg.setField(26, "VAL_26");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(27, "VAL_27");
	msg.setField(44, "35.5");
	msg.setField(15, "DOL");
	msg.setField(62, "20250101000000000");
	msg.setField(25, "1");
	msg.setField(130, "Y");
	msg.setField(199, "1");
	auto &vec_NoIOIQualifiers = msg.getRefNoIOIQualifiersGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoIOIQualifiers = vec_NoIOIQualifiers.emplace_back();
		g_NoIOIQualifiers.setField(104, "1");
	}
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(60, "20250101000000000");
	msg.setField(149, "VAL_149");
	msg.setField(215, "1");
	auto &vec_NoRoutingIDs = msg.getRefNoRoutingIDsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRoutingIDs = vec_NoRoutingIDs.emplace_back();
		g_NoRoutingIDs.setField(216, "1");
		g_NoRoutingIDs.setField(217, "VAL_217");
	}
	msg.setField(218, "1");
	msg.setField(219, "1");
	msg.setField(10, "179");
	return msg;
}

inline fix42::messages::Advertisement createAdvertisement() noexcept {
	fix42::messages::Advertisement msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000355");
	msg.setField(35, "7");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(2, "VAL_2");
	msg.setField(5, "VAL_5");
	msg.setField(3, "VAL_3");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(4, "1");
	msg.setField(53, "100");
	msg.setField(44, "35.5");
	msg.setField(15, "DOL");
	msg.setField(75, "20250101");
	msg.setField(60, "20250101000000000");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(149, "VAL_149");
	msg.setField(30, "NYSE");
	msg.setField(336, "VAL_336");
	msg.setField(10, "163");
	return msg;
}

inline fix42::messages::ExecutionReport createExecutionReport() noexcept {
	fix42::messages::ExecutionReport msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000890");
	msg.setField(35, "8");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(37, "VAL_37");
	msg.setField(198, "VAL_198");
	msg.setField(11, "CLORDID_123");
	msg.setField(41, "VAL_41");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(382, "1");
	auto &vec_NoContraBrokers = msg.getRefNoContraBrokersGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoContraBrokers = vec_NoContraBrokers.emplace_back();
		g_NoContraBrokers.setField(375, "VAL_375");
		g_NoContraBrokers.setField(337, "VAL_337");
		g_NoContraBrokers.setField(437, "100");
		g_NoContraBrokers.setField(438, "20250101000000000");
	}
	msg.setField(66, "VAL_66");
	msg.setField(17, "VAL_17");
	msg.setField(20, "1");
	msg.setField(19, "VAL_19");
	msg.setField(150, "1");
	msg.setField(39, "1");
	msg.setField(103, "1");
	msg.setField(378, "1");
	msg.setField(1, "VAL_1");
	msg.setField(63, "1");
	msg.setField(64, "20250101");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(38, "100");
	msg.setField(152, "100");
	msg.setField(40, "1");
	msg.setField(44, "35.5");
	msg.setField(99, "35.5");
	msg.setField(211, "1");
	msg.setField(388, "1");
	msg.setField(389, "1");
	msg.setField(15, "DOL");
	msg.setField(376, "VAL_376");
	msg.setField(377, "Y");
	msg.setField(59, "1");
	msg.setField(168, "20250101000000000");
	msg.setField(432, "20250101");
	msg.setField(126, "20250101000000000");
	msg.setField(18, "0");
	msg.setField(47, "1");
	msg.setField(32, "100");
	msg.setField(31, "35.5");
	msg.setField(194, "35.5");
	msg.setField(195, "1");
	msg.setField(30, "NYSE");
	msg.setField(336, "VAL_336");
	msg.setField(29, "1");
	msg.setField(151, "100");
	msg.setField(14, "100");
	msg.setField(6, "35.5");
	msg.setField(424, "100");
	msg.setField(425, "100");
	msg.setField(426, "35.5");
	msg.setField(427, "1");
	msg.setField(75, "20250101");
	msg.setField(60, "20250101000000000");
	msg.setField(113, "Y");
	msg.setField(12, "100");
	msg.setField(13, "1");
	msg.setField(381, "100");
	msg.setField(119, "100");
	msg.setField(120, "DOL");
	msg.setField(155, "100");
	msg.setField(156, "1");
	msg.setField(21, "1");
	msg.setField(110, "100");
	msg.setField(111, "100");
	msg.setField(77, "1");
	msg.setField(210, "100");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(193, "20250101");
	msg.setField(192, "100");
	msg.setField(439, "VAL_439");
	msg.setField(440, "VAL_440");
	msg.setField(442, "1");
	msg.setField(10, "242");
	return msg;
}

inline fix42::messages::OrderCancelReject createOrderCancelReject() noexcept {
	fix42::messages::OrderCancelReject msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000195");
	msg.setField(35, "9");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(37, "VAL_37");
	msg.setField(198, "VAL_198");
	msg.setField(11, "CLORDID_123");
	msg.setField(41, "VAL_41");
	msg.setField(39, "1");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(66, "VAL_66");
	msg.setField(1, "VAL_1");
	msg.setField(60, "20250101000000000");
	msg.setField(434, "1");
	msg.setField(102, "1");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "162");
	return msg;
}

inline fix42::messages::Logon createLogon() noexcept {
	fix42::messages::Logon msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000105");
	msg.setField(35, "A");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(98, "1");
	msg.setField(108, "1");
	msg.setField(95, "1");
	msg.setField(96, "DATA");
	msg.setField(141, "Y");
	msg.setField(383, "1");
	msg.setField(384, "1");
	auto &vec_NoMsgTypes = msg.getRefNoMsgTypesGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoMsgTypes = vec_NoMsgTypes.emplace_back();
		g_NoMsgTypes.setField(372, "VAL_372");
		g_NoMsgTypes.setField(385, "1");
	}
	msg.setField(10, "220");
	return msg;
}

inline fix42::messages::News createNews() noexcept {
	fix42::messages::News msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000353");
	msg.setField(35, "B");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(42, "20250101000000000");
	msg.setField(61, "1");
	msg.setField(148, "VAL_148");
	msg.setField(358, "1");
	msg.setField(359, "DATA");
	msg.setField(215, "1");
	auto &vec_NoRoutingIDs = msg.getRefNoRoutingIDsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRoutingIDs = vec_NoRoutingIDs.emplace_back();
		g_NoRoutingIDs.setField(216, "1");
		g_NoRoutingIDs.setField(217, "VAL_217");
	}
	msg.setField(146, "1");
	auto &vec_NoRelatedSym = msg.getRefNoRelatedSymGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRelatedSym = vec_NoRelatedSym.emplace_back();
		g_NoRelatedSym.setField(46, "VAL_46");
		g_NoRelatedSym.setField(65, "VAL_65");
		g_NoRelatedSym.setField(48, "VAL_48");
		g_NoRelatedSym.setField(22, "VAL_22");
		g_NoRelatedSym.setField(167, "VAL_167");
		g_NoRelatedSym.setField(200, "122035");
		g_NoRelatedSym.setField(205, "15");
		g_NoRelatedSym.setField(201, "1");
		g_NoRelatedSym.setField(202, "35.5");
		g_NoRelatedSym.setField(206, "1");
		g_NoRelatedSym.setField(231, "100");
		g_NoRelatedSym.setField(223, "100");
		g_NoRelatedSym.setField(207, "NYSE");
		g_NoRelatedSym.setField(106, "VAL_106");
		g_NoRelatedSym.setField(348, "1");
		g_NoRelatedSym.setField(349, "DATA");
		g_NoRelatedSym.setField(107, "VAL_107");
		g_NoRelatedSym.setField(350, "1");
		g_NoRelatedSym.setField(351, "DATA");
	}
	msg.setField(33, "1");
	auto &vec_LinesOfText = msg.getRefLinesOfTextGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_LinesOfText = vec_LinesOfText.emplace_back();
		g_LinesOfText.setField(58, "VAL_58");
		g_LinesOfText.setField(354, "1");
		g_LinesOfText.setField(355, "DATA");
	}
	msg.setField(149, "VAL_149");
	msg.setField(95, "1");
	msg.setField(96, "DATA");
	msg.setField(10, "059");
	return msg;
}

inline fix42::messages::Email createEmail() noexcept {
	fix42::messages::Email msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000378");
	msg.setField(35, "C");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(164, "VAL_164");
	msg.setField(94, "1");
	msg.setField(42, "20250101000000000");
	msg.setField(147, "VAL_147");
	msg.setField(356, "1");
	msg.setField(357, "DATA");
	msg.setField(215, "1");
	auto &vec_NoRoutingIDs = msg.getRefNoRoutingIDsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRoutingIDs = vec_NoRoutingIDs.emplace_back();
		g_NoRoutingIDs.setField(216, "1");
		g_NoRoutingIDs.setField(217, "VAL_217");
	}
	msg.setField(146, "1");
	auto &vec_NoRelatedSym = msg.getRefNoRelatedSymGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRelatedSym = vec_NoRelatedSym.emplace_back();
		g_NoRelatedSym.setField(46, "VAL_46");
		g_NoRelatedSym.setField(65, "VAL_65");
		g_NoRelatedSym.setField(48, "VAL_48");
		g_NoRelatedSym.setField(22, "VAL_22");
		g_NoRelatedSym.setField(167, "VAL_167");
		g_NoRelatedSym.setField(200, "122035");
		g_NoRelatedSym.setField(205, "15");
		g_NoRelatedSym.setField(201, "1");
		g_NoRelatedSym.setField(202, "35.5");
		g_NoRelatedSym.setField(206, "1");
		g_NoRelatedSym.setField(231, "100");
		g_NoRelatedSym.setField(223, "100");
		g_NoRelatedSym.setField(207, "NYSE");
		g_NoRelatedSym.setField(106, "VAL_106");
		g_NoRelatedSym.setField(348, "1");
		g_NoRelatedSym.setField(349, "DATA");
		g_NoRelatedSym.setField(107, "VAL_107");
		g_NoRelatedSym.setField(350, "1");
		g_NoRelatedSym.setField(351, "DATA");
	}
	msg.setField(37, "VAL_37");
	msg.setField(11, "CLORDID_123");
	msg.setField(33, "1");
	auto &vec_LinesOfText = msg.getRefLinesOfTextGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_LinesOfText = vec_LinesOfText.emplace_back();
		g_LinesOfText.setField(58, "VAL_58");
		g_LinesOfText.setField(354, "1");
		g_LinesOfText.setField(355, "DATA");
	}
	msg.setField(95, "1");
	msg.setField(96, "DATA");
	msg.setField(10, "039");
	return msg;
}

inline fix42::messages::NewOrderSingle createNewOrderSingle() noexcept {
	fix42::messages::NewOrderSingle msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000693");
	msg.setField(35, "D");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(11, "CLORDID_123");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(1, "VAL_1");
	msg.setField(78, "1");
	auto &vec_NoAllocs = msg.getRefNoAllocsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoAllocs = vec_NoAllocs.emplace_back();
		g_NoAllocs.setField(79, "VAL_79");
		g_NoAllocs.setField(80, "100");
	}
	msg.setField(63, "1");
	msg.setField(64, "20250101");
	msg.setField(21, "1");
	msg.setField(18, "0");
	msg.setField(110, "100");
	msg.setField(111, "100");
	msg.setField(100, "NYSE");
	msg.setField(386, "1");
	auto &vec_NoTradingSessions = msg.getRefNoTradingSessionsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoTradingSessions = vec_NoTradingSessions.emplace_back();
		g_NoTradingSessions.setField(336, "VAL_336");
	}
	msg.setField(81, "1");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(140, "35.5");
	msg.setField(54, "1");
	msg.setField(114, "Y");
	msg.setField(60, "20250101000000000");
	msg.setField(38, "100");
	msg.setField(152, "100");
	msg.setField(40, "1");
	msg.setField(44, "35.5");
	msg.setField(99, "35.5");
	msg.setField(15, "DOL");
	msg.setField(376, "VAL_376");
	msg.setField(377, "Y");
	msg.setField(23, "VAL_23");
	msg.setField(117, "VAL_117");
	msg.setField(59, "1");
	msg.setField(168, "20250101000000000");
	msg.setField(432, "20250101");
	msg.setField(126, "20250101000000000");
	msg.setField(427, "1");
	msg.setField(12, "100");
	msg.setField(13, "1");
	msg.setField(47, "1");
	msg.setField(121, "Y");
	msg.setField(120, "DOL");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(193, "20250101");
	msg.setField(192, "100");
	msg.setField(77, "1");
	msg.setField(203, "1");
	msg.setField(204, "1");
	msg.setField(210, "100");
	msg.setField(211, "1");
	msg.setField(388, "1");
	msg.setField(389, "1");
	msg.setField(439, "VAL_439");
	msg.setField(440, "VAL_440");
	msg.setField(10, "036");
	return msg;
}

inline fix42::messages::NewOrderList createNewOrderList() noexcept {
	fix42::messages::NewOrderList msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000803");
	msg.setField(35, "E");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(66, "VAL_66");
	msg.setField(390, "VAL_390");
	msg.setField(391, "VAL_391");
	msg.setField(414, "1");
	msg.setField(394, "1");
	msg.setField(415, "1");
	msg.setField(433, "1");
	msg.setField(69, "VAL_69");
	msg.setField(352, "1");
	msg.setField(353, "DATA");
	msg.setField(68, "1");
	msg.setField(73, "1");
	auto &vec_NoOrders = msg.getRefNoOrdersGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoOrders = vec_NoOrders.emplace_back();
		g_NoOrders.setField(11, "CLORDID_123");
		g_NoOrders.setField(67, "1");
		g_NoOrders.setField(160, "1");
		g_NoOrders.setField(109, "VAL_109");
		g_NoOrders.setField(76, "VAL_76");
		g_NoOrders.setField(1, "VAL_1");
		g_NoOrders.setField(78, "1");
		auto &vec_NoAllocs = g_NoOrders.getRefNoAllocsGroup();
		for (int i = 0; i < 1; ++i) {
			auto &g_NoAllocs = vec_NoAllocs.emplace_back();
			g_NoAllocs.setField(79, "VAL_79");
			g_NoAllocs.setField(80, "100");
		}
	}
	msg.setField(63, "1");
	msg.setField(64, "20250101");
	msg.setField(21, "1");
	msg.setField(18, "0");
	msg.setField(110, "100");
	msg.setField(111, "100");
	msg.setField(100, "NYSE");
	msg.setField(81, "1");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(140, "35.5");
	msg.setField(54, "1");
	msg.setField(401, "1");
	msg.setField(114, "Y");
	msg.setField(60, "20250101000000000");
	msg.setField(38, "100");
	msg.setField(152, "100");
	msg.setField(40, "1");
	msg.setField(44, "35.5");
	msg.setField(99, "35.5");
	msg.setField(15, "DOL");
	msg.setField(376, "VAL_376");
	msg.setField(377, "Y");
	msg.setField(23, "VAL_23");
	msg.setField(117, "VAL_117");
	msg.setField(59, "1");
	msg.setField(168, "20250101000000000");
	msg.setField(432, "20250101");
	msg.setField(126, "20250101000000000");
	msg.setField(427, "1");
	msg.setField(12, "100");
	msg.setField(13, "1");
	msg.setField(47, "1");
	msg.setField(121, "Y");
	msg.setField(120, "DOL");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(193, "20250101");
	msg.setField(192, "100");
	msg.setField(77, "1");
	msg.setField(203, "1");
	msg.setField(204, "1");
	msg.setField(210, "100");
	msg.setField(211, "1");
	msg.setField(388, "1");
	msg.setField(389, "1");
	msg.setField(439, "VAL_439");
	msg.setField(440, "VAL_440");
	msg.setField(386, "1");
	msg.setField(336, "VAL_336");
	msg.setField(10, "007");
	return msg;
}

inline fix42::messages::OrderCancelRequest createOrderCancelRequest() noexcept {
	fix42::messages::OrderCancelRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000374");
	msg.setField(35, "F");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(41, "VAL_41");
	msg.setField(37, "VAL_37");
	msg.setField(11, "CLORDID_123");
	msg.setField(66, "VAL_66");
	msg.setField(1, "VAL_1");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(60, "20250101000000000");
	msg.setField(38, "100");
	msg.setField(152, "100");
	msg.setField(376, "VAL_376");
	msg.setField(377, "Y");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "149");
	return msg;
}

inline fix42::messages::OrderCancelReplaceRequest createOrderCancelReplaceRequest() noexcept {
	fix42::messages::OrderCancelReplaceRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000687");
	msg.setField(35, "G");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(37, "VAL_37");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(41, "VAL_41");
	msg.setField(11, "CLORDID_123");
	msg.setField(66, "VAL_66");
	msg.setField(1, "VAL_1");
	msg.setField(78, "1");
	auto &vec_NoAllocs = msg.getRefNoAllocsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoAllocs = vec_NoAllocs.emplace_back();
		g_NoAllocs.setField(79, "VAL_79");
		g_NoAllocs.setField(80, "100");
	}
	msg.setField(63, "1");
	msg.setField(64, "20250101");
	msg.setField(21, "1");
	msg.setField(18, "0");
	msg.setField(110, "100");
	msg.setField(111, "100");
	msg.setField(100, "NYSE");
	msg.setField(386, "1");
	auto &vec_NoTradingSessions = msg.getRefNoTradingSessionsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoTradingSessions = vec_NoTradingSessions.emplace_back();
		g_NoTradingSessions.setField(336, "VAL_336");
	}
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(60, "20250101000000000");
	msg.setField(38, "100");
	msg.setField(152, "100");
	msg.setField(40, "1");
	msg.setField(44, "35.5");
	msg.setField(99, "35.5");
	msg.setField(211, "1");
	msg.setField(388, "1");
	msg.setField(389, "1");
	msg.setField(376, "VAL_376");
	msg.setField(377, "Y");
	msg.setField(15, "DOL");
	msg.setField(59, "1");
	msg.setField(168, "20250101000000000");
	msg.setField(432, "20250101");
	msg.setField(126, "20250101000000000");
	msg.setField(427, "1");
	msg.setField(12, "100");
	msg.setField(13, "1");
	msg.setField(47, "1");
	msg.setField(121, "Y");
	msg.setField(120, "DOL");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(193, "20250101");
	msg.setField(192, "100");
	msg.setField(77, "1");
	msg.setField(203, "1");
	msg.setField(204, "1");
	msg.setField(210, "100");
	msg.setField(114, "Y");
	msg.setField(439, "VAL_439");
	msg.setField(440, "VAL_440");
	msg.setField(10, "174");
	return msg;
}

inline fix42::messages::OrderStatusRequest createOrderStatusRequest() noexcept {
	fix42::messages::OrderStatusRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000275");
	msg.setField(35, "H");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(37, "VAL_37");
	msg.setField(11, "CLORDID_123");
	msg.setField(109, "VAL_109");
	msg.setField(1, "VAL_1");
	msg.setField(76, "VAL_76");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(10, "035");
	return msg;
}

inline fix42::messages::Allocation createAllocation() noexcept {
	fix42::messages::Allocation msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000727");
	msg.setField(35, "J");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(70, "VAL_70");
	msg.setField(71, "1");
	msg.setField(72, "VAL_72");
	msg.setField(196, "VAL_196");
	msg.setField(197, "1");
	msg.setField(73, "1");
	auto &vec_NoOrders = msg.getRefNoOrdersGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoOrders = vec_NoOrders.emplace_back();
		g_NoOrders.setField(11, "CLORDID_123");
		g_NoOrders.setField(37, "VAL_37");
		g_NoOrders.setField(198, "VAL_198");
		g_NoOrders.setField(66, "VAL_66");
		g_NoOrders.setField(105, "VAL_105");
	}
	msg.setField(124, "1");
	auto &vec_NoExecs = msg.getRefNoExecsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoExecs = vec_NoExecs.emplace_back();
		g_NoExecs.setField(32, "100");
		g_NoExecs.setField(17, "VAL_17");
		g_NoExecs.setField(31, "35.5");
		g_NoExecs.setField(29, "1");
	}
	msg.setField(54, "1");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(53, "100");
	msg.setField(30, "NYSE");
	msg.setField(336, "VAL_336");
	msg.setField(6, "35.5");
	msg.setField(15, "DOL");
	msg.setField(74, "1");
	msg.setField(75, "20250101");
	msg.setField(60, "20250101000000000");
	msg.setField(63, "1");
	msg.setField(64, "20250101");
	msg.setField(381, "100");
	msg.setField(118, "100");
	msg.setField(77, "1");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(157, "1");
	msg.setField(158, "100");
	msg.setField(78, "1");
	auto &vec_NoAllocs = msg.getRefNoAllocsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoAllocs = vec_NoAllocs.emplace_back();
		g_NoAllocs.setField(79, "VAL_79");
		g_NoAllocs.setField(366, "35.5");
		g_NoAllocs.setField(80, "100");
		g_NoAllocs.setField(81, "1");
		g_NoAllocs.setField(92, "VAL_92");
		g_NoAllocs.setField(208, "Y");
		g_NoAllocs.setField(209, "1");
		g_NoAllocs.setField(161, "VAL_161");
		g_NoAllocs.setField(360, "1");
		g_NoAllocs.setField(361, "DATA");
		g_NoAllocs.setField(76, "VAL_76");
		g_NoAllocs.setField(109, "VAL_109");
		g_NoAllocs.setField(12, "100");
		g_NoAllocs.setField(13, "1");
		g_NoAllocs.setField(153, "35.5");
		g_NoAllocs.setField(154, "100");
		g_NoAllocs.setField(119, "100");
		g_NoAllocs.setField(120, "DOL");
		g_NoAllocs.setField(155, "100");
		g_NoAllocs.setField(156, "1");
		g_NoAllocs.setField(159, "100");
		g_NoAllocs.setField(160, "1");
		g_NoAllocs.setField(136, "1");
		auto &vec_NoMiscFees = g_NoAllocs.getRefNoMiscFeesGroup();
		for (int i = 0; i < 1; ++i) {
			auto &g_NoMiscFees = vec_NoMiscFees.emplace_back();
			g_NoMiscFees.setField(137, "100");
			g_NoMiscFees.setField(138, "DOL");
			g_NoMiscFees.setField(139, "1");
		}
	}
	msg.setField(10, "135");
	return msg;
}

inline fix42::messages::ListCancelRequest createListCancelRequest() noexcept {
	fix42::messages::ListCancelRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000101");
	msg.setField(35, "K");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(66, "VAL_66");
	msg.setField(60, "20250101000000000");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "216");
	return msg;
}

inline fix42::messages::ListExecute createListExecute() noexcept {
	fix42::messages::ListExecute msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000125");
	msg.setField(35, "L");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(66, "VAL_66");
	msg.setField(391, "VAL_391");
	msg.setField(390, "VAL_390");
	msg.setField(60, "20250101000000000");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "081");
	return msg;
}

inline fix42::messages::ListStatusRequest createListStatusRequest() noexcept {
	fix42::messages::ListStatusRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000080");
	msg.setField(35, "M");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(66, "VAL_66");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "001");
	return msg;
}

inline fix42::messages::ListStatus createListStatus() noexcept {
	fix42::messages::ListStatus msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000215");
	msg.setField(35, "N");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(66, "VAL_66");
	msg.setField(429, "1");
	msg.setField(82, "1");
	msg.setField(431, "1");
	msg.setField(83, "1");
	msg.setField(444, "VAL_444");
	msg.setField(445, "1");
	msg.setField(446, "DATA");
	msg.setField(60, "20250101000000000");
	msg.setField(68, "1");
	msg.setField(73, "1");
	auto &vec_NoOrders = msg.getRefNoOrdersGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoOrders = vec_NoOrders.emplace_back();
		g_NoOrders.setField(11, "CLORDID_123");
		g_NoOrders.setField(14, "100");
		g_NoOrders.setField(39, "1");
		g_NoOrders.setField(151, "100");
		g_NoOrders.setField(84, "100");
		g_NoOrders.setField(6, "35.5");
		g_NoOrders.setField(103, "1");
		g_NoOrders.setField(58, "VAL_58");
		g_NoOrders.setField(354, "1");
		g_NoOrders.setField(355, "DATA");
	}
	msg.setField(10, "161");
	return msg;
}

inline fix42::messages::AllocationInstructionAck createAllocationInstructionAck() noexcept {
	fix42::messages::AllocationInstructionAck msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000145");
	msg.setField(35, "P");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(70, "VAL_70");
	msg.setField(75, "20250101");
	msg.setField(60, "20250101000000000");
	msg.setField(87, "1");
	msg.setField(88, "1");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "219");
	return msg;
}

inline fix42::messages::DontKnowTrade createDontKnowTrade() noexcept {
	fix42::messages::DontKnowTrade msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000301");
	msg.setField(35, "Q");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(37, "VAL_37");
	msg.setField(17, "VAL_17");
	msg.setField(127, "1");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(38, "100");
	msg.setField(152, "100");
	msg.setField(32, "100");
	msg.setField(31, "35.5");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "145");
	return msg;
}

inline fix42::messages::QuoteRequest createQuoteRequest() noexcept {
	fix42::messages::QuoteRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000360");
	msg.setField(35, "R");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(131, "VAL_131");
	msg.setField(146, "1");
	auto &vec_NoRelatedSym = msg.getRefNoRelatedSymGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRelatedSym = vec_NoRelatedSym.emplace_back();
		g_NoRelatedSym.setField(55, "VAL_55");
		g_NoRelatedSym.setField(65, "VAL_65");
		g_NoRelatedSym.setField(48, "VAL_48");
		g_NoRelatedSym.setField(22, "VAL_22");
		g_NoRelatedSym.setField(167, "VAL_167");
		g_NoRelatedSym.setField(200, "122035");
		g_NoRelatedSym.setField(205, "15");
		g_NoRelatedSym.setField(201, "1");
		g_NoRelatedSym.setField(202, "35.5");
		g_NoRelatedSym.setField(206, "1");
		g_NoRelatedSym.setField(231, "100");
		g_NoRelatedSym.setField(223, "100");
		g_NoRelatedSym.setField(207, "NYSE");
		g_NoRelatedSym.setField(106, "VAL_106");
		g_NoRelatedSym.setField(348, "1");
		g_NoRelatedSym.setField(349, "DATA");
		g_NoRelatedSym.setField(107, "VAL_107");
		g_NoRelatedSym.setField(350, "1");
		g_NoRelatedSym.setField(351, "DATA");
		g_NoRelatedSym.setField(140, "35.5");
		g_NoRelatedSym.setField(303, "1");
		g_NoRelatedSym.setField(336, "VAL_336");
		g_NoRelatedSym.setField(54, "1");
		g_NoRelatedSym.setField(38, "100");
		g_NoRelatedSym.setField(64, "20250101");
		g_NoRelatedSym.setField(40, "1");
		g_NoRelatedSym.setField(193, "20250101");
		g_NoRelatedSym.setField(192, "100");
		g_NoRelatedSym.setField(126, "20250101000000000");
		g_NoRelatedSym.setField(60, "20250101000000000");
		g_NoRelatedSym.setField(15, "DOL");
	}
	msg.setField(10, "226");
	return msg;
}

inline fix42::messages::Quote createQuote() noexcept {
	fix42::messages::Quote msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000408");
	msg.setField(35, "S");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(131, "VAL_131");
	msg.setField(117, "VAL_117");
	msg.setField(301, "1");
	msg.setField(336, "VAL_336");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(132, "35.5");
	msg.setField(133, "35.5");
	msg.setField(134, "100");
	msg.setField(135, "100");
	msg.setField(62, "20250101000000000");
	msg.setField(188, "35.5");
	msg.setField(190, "35.5");
	msg.setField(189, "1");
	msg.setField(191, "1");
	msg.setField(60, "20250101000000000");
	msg.setField(64, "20250101");
	msg.setField(40, "1");
	msg.setField(193, "20250101");
	msg.setField(192, "100");
	msg.setField(15, "DOL");
	msg.setField(10, "033");
	return msg;
}

inline fix42::messages::SettlementInstructions createSettlementInstructions() noexcept {
	fix42::messages::SettlementInstructions msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000449");
	msg.setField(35, "T");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(162, "VAL_162");
	msg.setField(163, "1");
	msg.setField(214, "VAL_214");
	msg.setField(160, "1");
	msg.setField(165, "1");
	msg.setField(79, "VAL_79");
	msg.setField(166, "VAL_166");
	msg.setField(75, "20250101");
	msg.setField(70, "VAL_70");
	msg.setField(30, "NYSE");
	msg.setField(336, "VAL_336");
	msg.setField(54, "1");
	msg.setField(167, "VAL_167");
	msg.setField(168, "20250101000000000");
	msg.setField(60, "20250101000000000");
	msg.setField(109, "VAL_109");
	msg.setField(76, "VAL_76");
	msg.setField(169, "1");
	msg.setField(170, "VAL_170");
	msg.setField(171, "VAL_171");
	msg.setField(172, "1");
	msg.setField(173, "VAL_173");
	msg.setField(174, "VAL_174");
	msg.setField(175, "VAL_175");
	msg.setField(176, "VAL_176");
	msg.setField(177, "VAL_177");
	msg.setField(178, "VAL_178");
	msg.setField(179, "VAL_179");
	msg.setField(180, "VAL_180");
	msg.setField(181, "VAL_181");
	msg.setField(182, "VAL_182");
	msg.setField(183, "VAL_183");
	msg.setField(184, "VAL_184");
	msg.setField(185, "VAL_185");
	msg.setField(186, "VAL_186");
	msg.setField(187, "VAL_187");
	msg.setField(10, "013");
	return msg;
}

inline fix42::messages::MarketDataRequest createMarketDataRequest() noexcept {
	fix42::messages::MarketDataRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000281");
	msg.setField(35, "V");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(262, "VAL_262");
	msg.setField(263, "1");
	msg.setField(264, "1");
	msg.setField(265, "1");
	msg.setField(266, "Y");
	msg.setField(267, "1");
	auto &vec_NoMDEntryTypes = msg.getRefNoMDEntryTypesGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoMDEntryTypes = vec_NoMDEntryTypes.emplace_back();
		g_NoMDEntryTypes.setField(269, "1");
	}
	msg.setField(146, "1");
	auto &vec_NoRelatedSym = msg.getRefNoRelatedSymGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRelatedSym = vec_NoRelatedSym.emplace_back();
		g_NoRelatedSym.setField(55, "VAL_55");
		g_NoRelatedSym.setField(65, "VAL_65");
		g_NoRelatedSym.setField(48, "VAL_48");
		g_NoRelatedSym.setField(22, "VAL_22");
		g_NoRelatedSym.setField(167, "VAL_167");
		g_NoRelatedSym.setField(200, "122035");
		g_NoRelatedSym.setField(205, "15");
		g_NoRelatedSym.setField(201, "1");
		g_NoRelatedSym.setField(202, "35.5");
		g_NoRelatedSym.setField(206, "1");
		g_NoRelatedSym.setField(231, "100");
		g_NoRelatedSym.setField(223, "100");
		g_NoRelatedSym.setField(207, "NYSE");
		g_NoRelatedSym.setField(106, "VAL_106");
		g_NoRelatedSym.setField(348, "1");
		g_NoRelatedSym.setField(349, "DATA");
		g_NoRelatedSym.setField(107, "VAL_107");
		g_NoRelatedSym.setField(350, "1");
		g_NoRelatedSym.setField(351, "DATA");
		g_NoRelatedSym.setField(336, "VAL_336");
	}
	msg.setField(10, "102");
	return msg;
}

inline fix42::messages::MarketDataSnapshotFullRefresh createMarketDataSnapshotFullRefresh() noexcept {
	fix42::messages::MarketDataSnapshotFullRefresh msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000536");
	msg.setField(35, "W");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(262, "VAL_262");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(291, "1");
	msg.setField(292, "1");
	msg.setField(387, "100");
	msg.setField(268, "1");
	auto &vec_NoMDEntries = msg.getRefNoMDEntriesGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoMDEntries = vec_NoMDEntries.emplace_back();
		g_NoMDEntries.setField(269, "1");
		g_NoMDEntries.setField(270, "35.5");
		g_NoMDEntries.setField(15, "DOL");
		g_NoMDEntries.setField(271, "100");
		g_NoMDEntries.setField(272, "20250101");
		g_NoMDEntries.setField(273, "10:00:00.000");
		g_NoMDEntries.setField(274, "1");
		g_NoMDEntries.setField(275, "NYSE");
		g_NoMDEntries.setField(336, "VAL_336");
		g_NoMDEntries.setField(276, "0");
		g_NoMDEntries.setField(277, "0");
		g_NoMDEntries.setField(282, "VAL_282");
		g_NoMDEntries.setField(283, "VAL_283");
		g_NoMDEntries.setField(284, "VAL_284");
		g_NoMDEntries.setField(286, "1");
		g_NoMDEntries.setField(59, "1");
		g_NoMDEntries.setField(432, "20250101");
		g_NoMDEntries.setField(126, "20250101000000000");
		g_NoMDEntries.setField(110, "100");
		g_NoMDEntries.setField(18, "0");
		g_NoMDEntries.setField(287, "1");
		g_NoMDEntries.setField(37, "VAL_37");
		g_NoMDEntries.setField(299, "VAL_299");
		g_NoMDEntries.setField(288, "VAL_288");
		g_NoMDEntries.setField(289, "VAL_289");
		g_NoMDEntries.setField(346, "1");
		g_NoMDEntries.setField(290, "1");
		g_NoMDEntries.setField(58, "VAL_58");
		g_NoMDEntries.setField(354, "1");
		g_NoMDEntries.setField(355, "DATA");
	}
	msg.setField(10, "224");
	return msg;
}

inline fix42::messages::MarketDataIncrementalRefresh createMarketDataIncrementalRefresh() noexcept {
	fix42::messages::MarketDataIncrementalRefresh msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000572");
	msg.setField(35, "X");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(262, "VAL_262");
	msg.setField(268, "1");
	auto &vec_NoMDEntries = msg.getRefNoMDEntriesGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoMDEntries = vec_NoMDEntries.emplace_back();
		g_NoMDEntries.setField(279, "1");
		g_NoMDEntries.setField(285, "1");
		g_NoMDEntries.setField(269, "1");
		g_NoMDEntries.setField(278, "VAL_278");
		g_NoMDEntries.setField(280, "VAL_280");
		g_NoMDEntries.setField(55, "VAL_55");
		g_NoMDEntries.setField(65, "VAL_65");
		g_NoMDEntries.setField(48, "VAL_48");
		g_NoMDEntries.setField(22, "VAL_22");
		g_NoMDEntries.setField(167, "VAL_167");
		g_NoMDEntries.setField(200, "122035");
		g_NoMDEntries.setField(205, "15");
		g_NoMDEntries.setField(201, "1");
		g_NoMDEntries.setField(202, "35.5");
		g_NoMDEntries.setField(206, "1");
		g_NoMDEntries.setField(231, "100");
		g_NoMDEntries.setField(223, "100");
		g_NoMDEntries.setField(207, "NYSE");
		g_NoMDEntries.setField(106, "VAL_106");
		g_NoMDEntries.setField(348, "1");
		g_NoMDEntries.setField(349, "DATA");
		g_NoMDEntries.setField(107, "VAL_107");
		g_NoMDEntries.setField(350, "1");
		g_NoMDEntries.setField(351, "DATA");
		g_NoMDEntries.setField(291, "1");
		g_NoMDEntries.setField(292, "1");
		g_NoMDEntries.setField(270, "35.5");
		g_NoMDEntries.setField(15, "DOL");
		g_NoMDEntries.setField(271, "100");
		g_NoMDEntries.setField(272, "20250101");
		g_NoMDEntries.setField(273, "10:00:00.000");
		g_NoMDEntries.setField(274, "1");
		g_NoMDEntries.setField(275, "NYSE");
		g_NoMDEntries.setField(336, "VAL_336");
		g_NoMDEntries.setField(276, "0");
		g_NoMDEntries.setField(277, "0");
		g_NoMDEntries.setField(282, "VAL_282");
		g_NoMDEntries.setField(283, "VAL_283");
		g_NoMDEntries.setField(284, "VAL_284");
		g_NoMDEntries.setField(286, "1");
		g_NoMDEntries.setField(59, "1");
		g_NoMDEntries.setField(432, "20250101");
		g_NoMDEntries.setField(126, "20250101000000000");
		g_NoMDEntries.setField(110, "100");
		g_NoMDEntries.setField(18, "0");
		g_NoMDEntries.setField(287, "1");
		g_NoMDEntries.setField(37, "VAL_37");
		g_NoMDEntries.setField(299, "VAL_299");
		g_NoMDEntries.setField(288, "VAL_288");
		g_NoMDEntries.setField(289, "VAL_289");
		g_NoMDEntries.setField(346, "1");
		g_NoMDEntries.setField(290, "1");
		g_NoMDEntries.setField(387, "100");
		g_NoMDEntries.setField(58, "VAL_58");
		g_NoMDEntries.setField(354, "1");
		g_NoMDEntries.setField(355, "DATA");
	}
	msg.setField(10, "118");
	return msg;
}

inline fix42::messages::MarketDataRequestReject createMarketDataRequestReject() noexcept {
	fix42::messages::MarketDataRequestReject msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000088");
	msg.setField(35, "Y");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(262, "VAL_262");
	msg.setField(281, "1");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "123");
	return msg;
}

inline fix42::messages::QuoteCancel createQuoteCancel() noexcept {
	fix42::messages::QuoteCancel msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000281");
	msg.setField(35, "Z");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(131, "VAL_131");
	msg.setField(117, "VAL_117");
	msg.setField(298, "1");
	msg.setField(301, "1");
	msg.setField(336, "VAL_336");
	msg.setField(295, "1");
	auto &vec_NoQuoteEntries = msg.getRefNoQuoteEntriesGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoQuoteEntries = vec_NoQuoteEntries.emplace_back();
		g_NoQuoteEntries.setField(55, "VAL_55");
		g_NoQuoteEntries.setField(65, "VAL_65");
		g_NoQuoteEntries.setField(48, "VAL_48");
		g_NoQuoteEntries.setField(22, "VAL_22");
		g_NoQuoteEntries.setField(167, "VAL_167");
		g_NoQuoteEntries.setField(200, "122035");
		g_NoQuoteEntries.setField(205, "15");
		g_NoQuoteEntries.setField(201, "1");
		g_NoQuoteEntries.setField(202, "35.5");
		g_NoQuoteEntries.setField(206, "1");
		g_NoQuoteEntries.setField(231, "100");
		g_NoQuoteEntries.setField(223, "100");
		g_NoQuoteEntries.setField(207, "NYSE");
		g_NoQuoteEntries.setField(106, "VAL_106");
		g_NoQuoteEntries.setField(348, "1");
		g_NoQuoteEntries.setField(349, "DATA");
		g_NoQuoteEntries.setField(107, "VAL_107");
		g_NoQuoteEntries.setField(350, "1");
		g_NoQuoteEntries.setField(351, "DATA");
		g_NoQuoteEntries.setField(311, "VAL_311");
	}
	msg.setField(10, "098");
	return msg;
}

inline fix42::messages::QuoteStatusRequest createQuoteStatusRequest() noexcept {
	fix42::messages::QuoteStatusRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000244");
	msg.setField(35, "a");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(117, "VAL_117");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(54, "1");
	msg.setField(336, "VAL_336");
	msg.setField(10, "200");
	return msg;
}

inline fix42::messages::QuoteAcknowledgement createQuoteAcknowledgement() noexcept {
	fix42::messages::QuoteAcknowledgement msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000505");
	msg.setField(35, "b");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(131, "VAL_131");
	msg.setField(117, "VAL_117");
	msg.setField(297, "1");
	msg.setField(300, "1");
	msg.setField(301, "1");
	msg.setField(336, "VAL_336");
	msg.setField(58, "VAL_58");
	msg.setField(296, "1");
	auto &vec_NoQuoteSets = msg.getRefNoQuoteSetsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoQuoteSets = vec_NoQuoteSets.emplace_back();
		g_NoQuoteSets.setField(302, "VAL_302");
		g_NoQuoteSets.setField(311, "VAL_311");
		g_NoQuoteSets.setField(312, "VAL_312");
		g_NoQuoteSets.setField(309, "VAL_309");
		g_NoQuoteSets.setField(305, "VAL_305");
		g_NoQuoteSets.setField(310, "VAL_310");
		g_NoQuoteSets.setField(313, "122035");
		g_NoQuoteSets.setField(314, "15");
		g_NoQuoteSets.setField(315, "1");
		g_NoQuoteSets.setField(316, "35.5");
		g_NoQuoteSets.setField(317, "1");
		g_NoQuoteSets.setField(436, "100");
		g_NoQuoteSets.setField(435, "100");
		g_NoQuoteSets.setField(308, "NYSE");
		g_NoQuoteSets.setField(306, "VAL_306");
		g_NoQuoteSets.setField(362, "1");
		g_NoQuoteSets.setField(363, "DATA");
		g_NoQuoteSets.setField(307, "VAL_307");
		g_NoQuoteSets.setField(364, "1");
		g_NoQuoteSets.setField(365, "DATA");
		g_NoQuoteSets.setField(304, "1");
		g_NoQuoteSets.setField(295, "1");
		auto &vec_NoQuoteEntries = g_NoQuoteSets.getRefNoQuoteEntriesGroup();
		for (int i = 0; i < 1; ++i) {
			auto &g_NoQuoteEntries = vec_NoQuoteEntries.emplace_back();
			g_NoQuoteEntries.setField(299, "VAL_299");
			g_NoQuoteEntries.setField(55, "VAL_55");
			g_NoQuoteEntries.setField(65, "VAL_65");
			g_NoQuoteEntries.setField(48, "VAL_48");
			g_NoQuoteEntries.setField(22, "VAL_22");
			g_NoQuoteEntries.setField(167, "VAL_167");
			g_NoQuoteEntries.setField(200, "122035");
			g_NoQuoteEntries.setField(205, "15");
			g_NoQuoteEntries.setField(201, "1");
			g_NoQuoteEntries.setField(202, "35.5");
			g_NoQuoteEntries.setField(206, "1");
			g_NoQuoteEntries.setField(231, "100");
			g_NoQuoteEntries.setField(223, "100");
			g_NoQuoteEntries.setField(207, "NYSE");
			g_NoQuoteEntries.setField(106, "VAL_106");
			g_NoQuoteEntries.setField(348, "1");
			g_NoQuoteEntries.setField(349, "DATA");
			g_NoQuoteEntries.setField(107, "VAL_107");
			g_NoQuoteEntries.setField(350, "1");
			g_NoQuoteEntries.setField(351, "DATA");
			g_NoQuoteEntries.setField(368, "1");
		}
	}
	msg.setField(10, "096");
	return msg;
}

inline fix42::messages::SecurityDefinitionRequest createSecurityDefinitionRequest() noexcept {
	fix42::messages::SecurityDefinitionRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000482");
	msg.setField(35, "c");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(320, "VAL_320");
	msg.setField(321, "1");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(15, "DOL");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(336, "VAL_336");
	msg.setField(146, "1");
	auto &vec_NoRelatedSym = msg.getRefNoRelatedSymGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRelatedSym = vec_NoRelatedSym.emplace_back();
		g_NoRelatedSym.setField(311, "VAL_311");
		g_NoRelatedSym.setField(312, "VAL_312");
		g_NoRelatedSym.setField(309, "VAL_309");
		g_NoRelatedSym.setField(305, "VAL_305");
		g_NoRelatedSym.setField(310, "VAL_310");
		g_NoRelatedSym.setField(313, "122035");
		g_NoRelatedSym.setField(314, "15");
		g_NoRelatedSym.setField(315, "1");
		g_NoRelatedSym.setField(316, "35.5");
		g_NoRelatedSym.setField(317, "1");
		g_NoRelatedSym.setField(436, "100");
		g_NoRelatedSym.setField(435, "100");
		g_NoRelatedSym.setField(308, "NYSE");
		g_NoRelatedSym.setField(306, "VAL_306");
		g_NoRelatedSym.setField(362, "1");
		g_NoRelatedSym.setField(363, "DATA");
		g_NoRelatedSym.setField(307, "VAL_307");
		g_NoRelatedSym.setField(364, "1");
		g_NoRelatedSym.setField(365, "DATA");
		g_NoRelatedSym.setField(319, "100");
		g_NoRelatedSym.setField(54, "1");
		g_NoRelatedSym.setField(318, "DOL");
	}
	msg.setField(10, "133");
	return msg;
}

inline fix42::messages::SecurityDefinition createSecurityDefinition() noexcept {
	fix42::messages::SecurityDefinition msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000500");
	msg.setField(35, "d");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(320, "VAL_320");
	msg.setField(322, "VAL_322");
	msg.setField(323, "1");
	msg.setField(393, "1");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(15, "DOL");
	msg.setField(336, "VAL_336");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(146, "1");
	auto &vec_NoRelatedSym = msg.getRefNoRelatedSymGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoRelatedSym = vec_NoRelatedSym.emplace_back();
		g_NoRelatedSym.setField(311, "VAL_311");
		g_NoRelatedSym.setField(312, "VAL_312");
		g_NoRelatedSym.setField(309, "VAL_309");
		g_NoRelatedSym.setField(305, "VAL_305");
		g_NoRelatedSym.setField(310, "VAL_310");
		g_NoRelatedSym.setField(313, "122035");
		g_NoRelatedSym.setField(314, "15");
		g_NoRelatedSym.setField(315, "1");
		g_NoRelatedSym.setField(316, "35.5");
		g_NoRelatedSym.setField(317, "1");
		g_NoRelatedSym.setField(436, "100");
		g_NoRelatedSym.setField(435, "100");
		g_NoRelatedSym.setField(308, "NYSE");
		g_NoRelatedSym.setField(306, "VAL_306");
		g_NoRelatedSym.setField(362, "1");
		g_NoRelatedSym.setField(363, "DATA");
		g_NoRelatedSym.setField(307, "VAL_307");
		g_NoRelatedSym.setField(364, "1");
		g_NoRelatedSym.setField(365, "DATA");
		g_NoRelatedSym.setField(319, "100");
		g_NoRelatedSym.setField(54, "1");
		g_NoRelatedSym.setField(318, "DOL");
	}
	msg.setField(10, "059");
	return msg;
}

inline fix42::messages::SecurityStatusRequest createSecurityStatusRequest() noexcept {
	fix42::messages::SecurityStatusRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000252");
	msg.setField(35, "e");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(324, "VAL_324");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(15, "DOL");
	msg.setField(263, "1");
	msg.setField(336, "VAL_336");
	msg.setField(10, "128");
	return msg;
}

inline fix42::messages::SecurityStatus createSecurityStatus() noexcept {
	fix42::messages::SecurityStatus msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000357");
	msg.setField(35, "f");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(324, "VAL_324");
	msg.setField(55, "VAL_55");
	msg.setField(65, "VAL_65");
	msg.setField(48, "VAL_48");
	msg.setField(22, "VAL_22");
	msg.setField(167, "VAL_167");
	msg.setField(200, "122035");
	msg.setField(205, "15");
	msg.setField(201, "1");
	msg.setField(202, "35.5");
	msg.setField(206, "1");
	msg.setField(231, "100");
	msg.setField(223, "100");
	msg.setField(207, "NYSE");
	msg.setField(106, "VAL_106");
	msg.setField(348, "1");
	msg.setField(349, "DATA");
	msg.setField(107, "VAL_107");
	msg.setField(350, "1");
	msg.setField(351, "DATA");
	msg.setField(15, "DOL");
	msg.setField(336, "VAL_336");
	msg.setField(325, "Y");
	msg.setField(326, "1");
	msg.setField(291, "1");
	msg.setField(292, "1");
	msg.setField(327, "1");
	msg.setField(328, "Y");
	msg.setField(329, "Y");
	msg.setField(330, "100");
	msg.setField(331, "100");
	msg.setField(332, "35.5");
	msg.setField(333, "35.5");
	msg.setField(31, "35.5");
	msg.setField(60, "20250101000000000");
	msg.setField(334, "1");
	msg.setField(10, "166");
	return msg;
}

inline fix42::messages::TradingSessionStatusRequest createTradingSessionStatusRequest() noexcept {
	fix42::messages::TradingSessionStatusRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000087");
	msg.setField(35, "g");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(335, "VAL_335");
	msg.setField(336, "VAL_336");
	msg.setField(338, "1");
	msg.setField(339, "1");
	msg.setField(263, "1");
	msg.setField(10, "003");
	return msg;
}

inline fix42::messages::TradingSessionStatus createTradingSessionStatus() noexcept {
	fix42::messages::TradingSessionStatus msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000236");
	msg.setField(35, "h");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(335, "VAL_335");
	msg.setField(336, "VAL_336");
	msg.setField(338, "1");
	msg.setField(339, "1");
	msg.setField(325, "Y");
	msg.setField(340, "1");
	msg.setField(341, "20250101000000000");
	msg.setField(342, "20250101000000000");
	msg.setField(343, "20250101000000000");
	msg.setField(344, "20250101000000000");
	msg.setField(345, "20250101000000000");
	msg.setField(387, "100");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "087");
	return msg;
}

inline fix42::messages::MassQuote createMassQuote() noexcept {
	fix42::messages::MassQuote msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000666");
	msg.setField(35, "i");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(131, "VAL_131");
	msg.setField(117, "VAL_117");
	msg.setField(301, "1");
	msg.setField(293, "100");
	msg.setField(294, "100");
	msg.setField(296, "1");
	auto &vec_NoQuoteSets = msg.getRefNoQuoteSetsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoQuoteSets = vec_NoQuoteSets.emplace_back();
		g_NoQuoteSets.setField(302, "VAL_302");
		g_NoQuoteSets.setField(311, "VAL_311");
		g_NoQuoteSets.setField(312, "VAL_312");
		g_NoQuoteSets.setField(309, "VAL_309");
		g_NoQuoteSets.setField(305, "VAL_305");
		g_NoQuoteSets.setField(310, "VAL_310");
		g_NoQuoteSets.setField(313, "122035");
		g_NoQuoteSets.setField(314, "15");
		g_NoQuoteSets.setField(315, "1");
		g_NoQuoteSets.setField(316, "35.5");
		g_NoQuoteSets.setField(317, "1");
		g_NoQuoteSets.setField(436, "100");
		g_NoQuoteSets.setField(435, "100");
		g_NoQuoteSets.setField(308, "NYSE");
		g_NoQuoteSets.setField(306, "VAL_306");
		g_NoQuoteSets.setField(362, "1");
		g_NoQuoteSets.setField(363, "DATA");
		g_NoQuoteSets.setField(307, "VAL_307");
		g_NoQuoteSets.setField(364, "1");
		g_NoQuoteSets.setField(365, "DATA");
		g_NoQuoteSets.setField(367, "20250101000000000");
		g_NoQuoteSets.setField(304, "1");
		g_NoQuoteSets.setField(295, "1");
		auto &vec_NoQuoteEntries = g_NoQuoteSets.getRefNoQuoteEntriesGroup();
		for (int i = 0; i < 1; ++i) {
			auto &g_NoQuoteEntries = vec_NoQuoteEntries.emplace_back();
			g_NoQuoteEntries.setField(299, "VAL_299");
			g_NoQuoteEntries.setField(55, "VAL_55");
			g_NoQuoteEntries.setField(65, "VAL_65");
			g_NoQuoteEntries.setField(48, "VAL_48");
			g_NoQuoteEntries.setField(22, "VAL_22");
			g_NoQuoteEntries.setField(167, "VAL_167");
			g_NoQuoteEntries.setField(200, "122035");
			g_NoQuoteEntries.setField(205, "15");
			g_NoQuoteEntries.setField(201, "1");
			g_NoQuoteEntries.setField(202, "35.5");
			g_NoQuoteEntries.setField(206, "1");
			g_NoQuoteEntries.setField(231, "100");
			g_NoQuoteEntries.setField(223, "100");
			g_NoQuoteEntries.setField(207, "NYSE");
			g_NoQuoteEntries.setField(106, "VAL_106");
			g_NoQuoteEntries.setField(348, "1");
			g_NoQuoteEntries.setField(349, "DATA");
			g_NoQuoteEntries.setField(107, "VAL_107");
			g_NoQuoteEntries.setField(350, "1");
			g_NoQuoteEntries.setField(351, "DATA");
			g_NoQuoteEntries.setField(132, "35.5");
			g_NoQuoteEntries.setField(133, "35.5");
			g_NoQuoteEntries.setField(134, "100");
			g_NoQuoteEntries.setField(135, "100");
			g_NoQuoteEntries.setField(62, "20250101000000000");
			g_NoQuoteEntries.setField(188, "35.5");
			g_NoQuoteEntries.setField(190, "35.5");
			g_NoQuoteEntries.setField(189, "1");
			g_NoQuoteEntries.setField(191, "1");
			g_NoQuoteEntries.setField(60, "20250101000000000");
			g_NoQuoteEntries.setField(336, "VAL_336");
			g_NoQuoteEntries.setField(64, "20250101");
			g_NoQuoteEntries.setField(40, "1");
			g_NoQuoteEntries.setField(193, "20250101");
			g_NoQuoteEntries.setField(192, "100");
			g_NoQuoteEntries.setField(15, "DOL");
		}
	}
	msg.setField(10, "118");
	return msg;
}

inline fix42::messages::BusinessMessageReject createBusinessMessageReject() noexcept {
	fix42::messages::BusinessMessageReject msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000105");
	msg.setField(35, "j");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(45, "1");
	msg.setField(372, "VAL_372");
	msg.setField(379, "VAL_379");
	msg.setField(380, "1");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "036");
	return msg;
}

inline fix42::messages::BidRequest createBidRequest() noexcept {
	fix42::messages::BidRequest msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000421");
	msg.setField(35, "k");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(390, "VAL_390");
	msg.setField(391, "VAL_391");
	msg.setField(374, "1");
	msg.setField(392, "VAL_392");
	msg.setField(393, "1");
	msg.setField(394, "1");
	msg.setField(395, "1");
	msg.setField(15, "DOL");
	msg.setField(396, "100");
	msg.setField(397, "100");
	msg.setField(398, "1");
	auto &vec_NoBidDescriptors = msg.getRefNoBidDescriptorsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoBidDescriptors = vec_NoBidDescriptors.emplace_back();
		g_NoBidDescriptors.setField(399, "1");
		g_NoBidDescriptors.setField(400, "VAL_400");
		g_NoBidDescriptors.setField(401, "1");
		g_NoBidDescriptors.setField(404, "100");
		g_NoBidDescriptors.setField(441, "1");
		g_NoBidDescriptors.setField(402, "100");
		g_NoBidDescriptors.setField(403, "100");
		g_NoBidDescriptors.setField(405, "100");
		g_NoBidDescriptors.setField(406, "100");
		g_NoBidDescriptors.setField(407, "100");
		g_NoBidDescriptors.setField(408, "100");
	}
	msg.setField(420, "1");
	auto &vec_NoBidComponents = msg.getRefNoBidComponentsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoBidComponents = vec_NoBidComponents.emplace_back();
		g_NoBidComponents.setField(66, "VAL_66");
		g_NoBidComponents.setField(54, "1");
		g_NoBidComponents.setField(336, "VAL_336");
		g_NoBidComponents.setField(430, "1");
		g_NoBidComponents.setField(63, "1");
		g_NoBidComponents.setField(64, "20250101");
		g_NoBidComponents.setField(1, "VAL_1");
	}
	msg.setField(409, "1");
	msg.setField(410, "100");
	msg.setField(411, "Y");
	msg.setField(412, "100");
	msg.setField(413, "100");
	msg.setField(414, "1");
	msg.setField(415, "1");
	msg.setField(416, "1");
	msg.setField(121, "Y");
	msg.setField(417, "1");
	msg.setField(75, "20250101");
	msg.setField(418, "1");
	msg.setField(419, "1");
	msg.setField(443, "20250101000000000");
	msg.setField(58, "VAL_58");
	msg.setField(354, "1");
	msg.setField(355, "DATA");
	msg.setField(10, "068");
	return msg;
}

inline fix42::messages::BidResponse createBidResponse() noexcept {
	fix42::messages::BidResponse msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000196");
	msg.setField(35, "l");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(390, "VAL_390");
	msg.setField(391, "VAL_391");
	msg.setField(420, "1");
	auto &vec_NoBidComponents = msg.getRefNoBidComponentsGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoBidComponents = vec_NoBidComponents.emplace_back();
		g_NoBidComponents.setField(12, "100");
		g_NoBidComponents.setField(13, "1");
		g_NoBidComponents.setField(66, "VAL_66");
		g_NoBidComponents.setField(421, "VAL_421");
		g_NoBidComponents.setField(54, "1");
		g_NoBidComponents.setField(44, "35.5");
		g_NoBidComponents.setField(423, "1");
		g_NoBidComponents.setField(406, "100");
		g_NoBidComponents.setField(430, "1");
		g_NoBidComponents.setField(63, "1");
		g_NoBidComponents.setField(64, "20250101");
		g_NoBidComponents.setField(336, "VAL_336");
		g_NoBidComponents.setField(58, "VAL_58");
		g_NoBidComponents.setField(354, "1");
		g_NoBidComponents.setField(355, "DATA");
	}
	msg.setField(10, "213");
	return msg;
}

inline fix42::messages::ListStrikePrice createListStrikePrice() noexcept {
	fix42::messages::ListStrikePrice msg;
	msg.setField(8, "FIX4.2");
	msg.setField(9, "000306");
	msg.setField(35, "m");
	msg.setField(49, "BRK");
	msg.setField(56, "CLT");
	msg.setField(34, "1");
	msg.setField(52, "20250101000000000");
	msg.setField(66, "VAL_66");
	msg.setField(422, "1");
	msg.setField(428, "1");
	auto &vec_NoStrikes = msg.getRefNoStrikesGroup();
	for (int i = 0; i < 1; ++i) {
		auto &g_NoStrikes = vec_NoStrikes.emplace_back();
		g_NoStrikes.setField(55, "VAL_55");
		g_NoStrikes.setField(65, "VAL_65");
		g_NoStrikes.setField(48, "VAL_48");
		g_NoStrikes.setField(22, "VAL_22");
		g_NoStrikes.setField(167, "VAL_167");
		g_NoStrikes.setField(200, "122035");
		g_NoStrikes.setField(205, "15");
		g_NoStrikes.setField(201, "1");
		g_NoStrikes.setField(202, "35.5");
		g_NoStrikes.setField(206, "1");
		g_NoStrikes.setField(231, "100");
		g_NoStrikes.setField(223, "100");
		g_NoStrikes.setField(207, "NYSE");
		g_NoStrikes.setField(106, "VAL_106");
		g_NoStrikes.setField(348, "1");
		g_NoStrikes.setField(349, "DATA");
		g_NoStrikes.setField(107, "VAL_107");
		g_NoStrikes.setField(350, "1");
		g_NoStrikes.setField(351, "DATA");
		g_NoStrikes.setField(140, "35.5");
		g_NoStrikes.setField(11, "CLORDID_123");
		g_NoStrikes.setField(54, "1");
		g_NoStrikes.setField(44, "35.5");
		g_NoStrikes.setField(15, "DOL");
		g_NoStrikes.setField(58, "VAL_58");
		g_NoStrikes.setField(354, "1");
		g_NoStrikes.setField(355, "DATA");
	}
	msg.setField(10, "087");
	return msg;
}

} // namespace fix42::samples
