// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: bc4ba6f5728976b7

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

namespace fix44::components {

class ContAmtGrp {
public:
	struct NoContAmts {
		static constexpr std::size_t P_ContAmtType                  = 0;
		static constexpr std::size_t P_ContAmtValue                 = 1;
		static constexpr std::size_t P_ContAmtCurr                  = 2;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 91;

		types::INT m_ContAmtType{fields::NULL_INT};
		types::FLOAT m_ContAmtValue{fields::NULL_FLOAT};
		types::CURRENCY<32> m_ContAmtCurr{fields::ContAmtCurr_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::INT &getContAmtType() const noexcept { return m_ContAmtType; }
		const types::FLOAT &getContAmtValue() const noexcept { return m_ContAmtValue; }
		const types::CURRENCY<32> &getContAmtCurr() const noexcept { return m_ContAmtCurr; }

		// mutators
		void setContAmtType(types::INT v) noexcept { m_ContAmtType = v; m_presence |= (1ULL << P_ContAmtType); }
		void setContAmtValue(types::FLOAT v) noexcept { m_ContAmtValue = v; m_presence |= (1ULL << P_ContAmtValue); }
		void setContAmtCurr(const types::CURRENCY<32> &v) noexcept { m_ContAmtCurr = v; m_presence |= (1ULL << P_ContAmtCurr); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasContAmtType() const noexcept { return (m_presence & (1ULL << P_ContAmtType)) != 0; }
		bool hasContAmtValue() const noexcept { return (m_presence & (1ULL << P_ContAmtValue)) != 0; }
		bool hasContAmtCurr() const noexcept { return (m_presence & (1ULL << P_ContAmtCurr)) != 0; }
	};

private:
	static constexpr std::size_t P_NoContAmts                   = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoContAmts> m_NoContAmtsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoContAmtsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoContAmts> &getRefNoContAmtsGroup() noexcept { return m_NoContAmtsGroup; }
	const std::vector<NoContAmts> &getRefNoContAmtsGroup() const noexcept { return m_NoContAmtsGroup; }
	std::size_t getNoContAmts() const noexcept { return m_NoContAmtsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoContAmtsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoContAmts() const noexcept { return !m_NoContAmtsGroup.empty(); }
};

} // namespace fix44::components
