// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 946d4c7ce313eff2

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

namespace fix44::components {

class ExecCollGrp {
public:
	struct NoExecs {
		static constexpr std::size_t P_ExecID                       = 0;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 36;

		types::STRING<32> m_ExecID{fields::ExecID_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::STRING<32> &getExecID() const noexcept { return m_ExecID; }

		// mutators
		void setExecID(const types::STRING<32> &v) noexcept { m_ExecID = v; m_presence |= (1ULL << P_ExecID); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasExecID() const noexcept { return (m_presence & (1ULL << P_ExecID)) != 0; }
	};

private:
	static constexpr std::size_t P_NoExecs                      = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoExecs> m_NoExecsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoExecsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoExecs> &getRefNoExecsGroup() noexcept { return m_NoExecsGroup; }
	const std::vector<NoExecs> &getRefNoExecsGroup() const noexcept { return m_NoExecsGroup; }
	std::size_t getNoExecs() const noexcept { return m_NoExecsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoExecsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoExecs() const noexcept { return !m_NoExecsGroup.empty(); }
};

} // namespace fix44::components
