// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 623aef162c6800e0

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

#include <utils/error_codes.h>
#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

#include <FIX4.4/components/AttrbGrp.h>

namespace fix44::components {

class InstrumentExtension {
	static constexpr std::size_t P_DeliveryForm                 = 0;
	static constexpr std::size_t P_PctAtRisk                    = 1;

	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 54;

	types::INT m_DeliveryForm{fields::NULL_INT};
	types::FLOAT m_PctAtRisk{fields::NULL_PERCENTAGE};
	AttrbGrp m_AttrbGrp{};

	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		return MAX_ENCODE_SIZE
			+ m_AttrbGrp.compute_buffer_size();
	}

	// accessors
	const types::INT &getDeliveryForm() const noexcept { return m_DeliveryForm; }
	const types::FLOAT &getPctAtRisk() const noexcept { return m_PctAtRisk; }
	AttrbGrp &getRefAttrbGrp() noexcept { return m_AttrbGrp; }
	const AttrbGrp &getRefAttrbGrp() const noexcept { return m_AttrbGrp; }

	// mutators
	void setDeliveryForm(types::INT v) noexcept { m_DeliveryForm = v; m_presence |= (1ULL << P_DeliveryForm); }
	void setPctAtRisk(types::FLOAT v) noexcept { m_PctAtRisk = v; m_presence |= (1ULL << P_PctAtRisk); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (m_AttrbGrp.hasAnySet()) { return true; }
		return false;
	}
	bool hasDeliveryForm() const noexcept { return (m_presence & (1ULL << P_DeliveryForm)) != 0; }
	bool hasPctAtRisk() const noexcept { return (m_presence & (1ULL << P_PctAtRisk)) != 0; }
};

} // namespace fix44::components
