// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: e574679f38d9fce8

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

#include <FIX4.4/components/NestedParties2.h>

namespace fix44::components {

class LegPreAllocGrp {
public:
	struct NoLegAllocs {
		static constexpr std::size_t P_LegAllocAccount              = 0;
		static constexpr std::size_t P_LegIndividualAllocID         = 1;
		static constexpr std::size_t P_LegAllocQty                  = 2;
		static constexpr std::size_t P_LegAllocAcctIDSource         = 3;
		static constexpr std::size_t P_LegSettlCurrency             = 4;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 177;

		types::STRING<32> m_LegAllocAccount{fields::LegAllocAccount_NULL};
		types::STRING<32> m_LegIndividualAllocID{fields::LegIndividualAllocID_NULL};
		NestedParties2 m_NestedParties2{};
		types::FLOAT m_LegAllocQty{fields::NULL_QTY};
		types::STRING<32> m_LegAllocAcctIDSource{fields::LegAllocAcctIDSource_NULL};
		types::CURRENCY<32> m_LegSettlCurrency{fields::LegSettlCurrency_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_NestedParties2.compute_buffer_size();
		}

		// accessors
		NestedParties2 &getRefNestedParties2() noexcept { return m_NestedParties2; }
		const NestedParties2 &getRefNestedParties2() const noexcept { return m_NestedParties2; }
		const types::STRING<32> &getLegAllocAccount() const noexcept { return m_LegAllocAccount; }
		const types::STRING<32> &getLegIndividualAllocID() const noexcept { return m_LegIndividualAllocID; }
		const types::FLOAT &getLegAllocQty() const noexcept { return m_LegAllocQty; }
		const types::STRING<32> &getLegAllocAcctIDSource() const noexcept { return m_LegAllocAcctIDSource; }
		const types::CURRENCY<32> &getLegSettlCurrency() const noexcept { return m_LegSettlCurrency; }

		// mutators
		void setLegAllocAccount(const types::STRING<32> &v) noexcept { m_LegAllocAccount = v; m_presence |= (1ULL << P_LegAllocAccount); }
		void setLegIndividualAllocID(const types::STRING<32> &v) noexcept { m_LegIndividualAllocID = v; m_presence |= (1ULL << P_LegIndividualAllocID); }
		void setLegAllocQty(types::FLOAT v) noexcept { m_LegAllocQty = v; m_presence |= (1ULL << P_LegAllocQty); }
		void setLegAllocAcctIDSource(const types::STRING<32> &v) noexcept { m_LegAllocAcctIDSource = v; m_presence |= (1ULL << P_LegAllocAcctIDSource); }
		void setLegSettlCurrency(const types::CURRENCY<32> &v) noexcept { m_LegSettlCurrency = v; m_presence |= (1ULL << P_LegSettlCurrency); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_NestedParties2.hasAnySet()) { return true; }
			return false;
		}
		bool hasLegAllocAccount() const noexcept { return (m_presence & (1ULL << P_LegAllocAccount)) != 0; }
		bool hasLegIndividualAllocID() const noexcept { return (m_presence & (1ULL << P_LegIndividualAllocID)) != 0; }
		bool hasLegAllocQty() const noexcept { return (m_presence & (1ULL << P_LegAllocQty)) != 0; }
		bool hasLegAllocAcctIDSource() const noexcept { return (m_presence & (1ULL << P_LegAllocAcctIDSource)) != 0; }
		bool hasLegSettlCurrency() const noexcept { return (m_presence & (1ULL << P_LegSettlCurrency)) != 0; }
	};

private:
	static constexpr std::size_t P_NoLegAllocs                  = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoLegAllocs> m_NoLegAllocsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoLegAllocsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoLegAllocs> &getRefNoLegAllocsGroup() noexcept { return m_NoLegAllocsGroup; }
	const std::vector<NoLegAllocs> &getRefNoLegAllocsGroup() const noexcept { return m_NoLegAllocsGroup; }
	std::size_t getNoLegAllocs() const noexcept { return m_NoLegAllocsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoLegAllocsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoLegAllocs() const noexcept { return !m_NoLegAllocsGroup.empty(); }
};

} // namespace fix44::components
