// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 135928a7cae748f0

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

#include <FIX4.4/components/UnderlyingInstrument.h>

namespace fix44::components {

class PosUndInstrmtGrp {
public:
	struct NoUnderlyings {
		static constexpr std::size_t P_UnderlyingSettlPrice         = 0;
		static constexpr std::size_t P_UnderlyingSettlPriceType     = 1;

		static constexpr uint64_t REQUIRED =
			(1ULL << 0) |
			(1ULL << 1);
		static constexpr std::size_t MAX_ENCODE_SIZE = 54;

		UnderlyingInstrument m_UnderlyingInstrument{};
		types::FLOAT m_UnderlyingSettlPrice{fields::NULL_PRICE};
		types::INT m_UnderlyingSettlPriceType{fields::NULL_INT};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_UnderlyingInstrument.compute_buffer_size();
		}

		// accessors
		UnderlyingInstrument &getRefUnderlyingInstrument() noexcept { return m_UnderlyingInstrument; }
		const UnderlyingInstrument &getRefUnderlyingInstrument() const noexcept { return m_UnderlyingInstrument; }
		const types::FLOAT &getUnderlyingSettlPrice() const noexcept { return m_UnderlyingSettlPrice; }
		const types::INT &getUnderlyingSettlPriceType() const noexcept { return m_UnderlyingSettlPriceType; }

		// mutators
		void setUnderlyingSettlPrice(types::FLOAT v) noexcept { m_UnderlyingSettlPrice = v; m_presence |= (1ULL << P_UnderlyingSettlPrice); }
		void setUnderlyingSettlPriceType(types::INT v) noexcept { m_UnderlyingSettlPriceType = v; m_presence |= (1ULL << P_UnderlyingSettlPriceType); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_UnderlyingInstrument.hasAnySet()) { return true; }
			return false;
		}
		bool hasUnderlyingSettlPrice() const noexcept { return (m_presence & (1ULL << P_UnderlyingSettlPrice)) != 0; }
		bool hasUnderlyingSettlPriceType() const noexcept { return (m_presence & (1ULL << P_UnderlyingSettlPriceType)) != 0; }
	};

private:
	static constexpr std::size_t P_NoUnderlyings                = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoUnderlyings> m_NoUnderlyingsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoUnderlyingsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoUnderlyings> &getRefNoUnderlyingsGroup() noexcept { return m_NoUnderlyingsGroup; }
	const std::vector<NoUnderlyings> &getRefNoUnderlyingsGroup() const noexcept { return m_NoUnderlyingsGroup; }
	std::size_t getNoUnderlyings() const noexcept { return m_NoUnderlyingsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoUnderlyingsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoUnderlyings() const noexcept { return !m_NoUnderlyingsGroup.empty(); }
};

} // namespace fix44::components
