// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: fbd2d8885c0376ca

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

namespace fix44::components {

class QuotQualGrp {
public:
	struct NoQuoteQualifiers {
		static constexpr std::size_t P_QuoteQualifier               = 0;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 6;

		types::CHAR m_QuoteQualifier{fields::NULL_CHAR};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::CHAR &getQuoteQualifier() const noexcept { return m_QuoteQualifier; }

		// mutators
		void setQuoteQualifier(types::CHAR v) noexcept { m_QuoteQualifier = v; m_presence |= (1ULL << P_QuoteQualifier); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasQuoteQualifier() const noexcept { return (m_presence & (1ULL << P_QuoteQualifier)) != 0; }
	};

private:
	static constexpr std::size_t P_NoQuoteQualifiers            = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoQuoteQualifiers> m_NoQuoteQualifiersGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoQuoteQualifiersGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoQuoteQualifiers> &getRefNoQuoteQualifiersGroup() noexcept { return m_NoQuoteQualifiersGroup; }
	const std::vector<NoQuoteQualifiers> &getRefNoQuoteQualifiersGroup() const noexcept { return m_NoQuoteQualifiersGroup; }
	std::size_t getNoQuoteQualifiers() const noexcept { return m_NoQuoteQualifiersGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoQuoteQualifiersGroup.empty()) { return true; }
		return false;
	}
	bool hasNoQuoteQualifiers() const noexcept { return !m_NoQuoteQualifiersGroup.empty(); }
};

} // namespace fix44::components
