// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 59d9ece7d9b426c6

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

namespace fix44::components {

class RgstDistInstGrp {
public:
	struct NoDistribInsts {
		static constexpr std::size_t P_DistribPaymentMethod         = 0;
		static constexpr std::size_t P_DistribPercentage            = 1;
		static constexpr std::size_t P_CashDistribCurr              = 2;
		static constexpr std::size_t P_CashDistribAgentName         = 3;
		static constexpr std::size_t P_CashDistribAgentCode         = 4;
		static constexpr std::size_t P_CashDistribAgentAcctNumber   = 5;
		static constexpr std::size_t P_CashDistribPayRef            = 6;
		static constexpr std::size_t P_CashDistribAgentAcctName     = 7;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 276;

		types::INT m_DistribPaymentMethod{fields::NULL_INT};
		types::FLOAT m_DistribPercentage{fields::NULL_PERCENTAGE};
		types::CURRENCY<32> m_CashDistribCurr{fields::CashDistribCurr_NULL};
		types::STRING<32> m_CashDistribAgentName{fields::CashDistribAgentName_NULL};
		types::STRING<32> m_CashDistribAgentCode{fields::CashDistribAgentCode_NULL};
		types::STRING<32> m_CashDistribAgentAcctNumber{fields::CashDistribAgentAcctNumber_NULL};
		types::STRING<32> m_CashDistribPayRef{fields::CashDistribPayRef_NULL};
		types::STRING<32> m_CashDistribAgentAcctName{fields::CashDistribAgentAcctName_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::INT &getDistribPaymentMethod() const noexcept { return m_DistribPaymentMethod; }
		const types::FLOAT &getDistribPercentage() const noexcept { return m_DistribPercentage; }
		const types::CURRENCY<32> &getCashDistribCurr() const noexcept { return m_CashDistribCurr; }
		const types::STRING<32> &getCashDistribAgentName() const noexcept { return m_CashDistribAgentName; }
		const types::STRING<32> &getCashDistribAgentCode() const noexcept { return m_CashDistribAgentCode; }
		const types::STRING<32> &getCashDistribAgentAcctNumber() const noexcept { return m_CashDistribAgentAcctNumber; }
		const types::STRING<32> &getCashDistribPayRef() const noexcept { return m_CashDistribPayRef; }
		const types::STRING<32> &getCashDistribAgentAcctName() const noexcept { return m_CashDistribAgentAcctName; }

		// mutators
		void setDistribPaymentMethod(types::INT v) noexcept { m_DistribPaymentMethod = v; m_presence |= (1ULL << P_DistribPaymentMethod); }
		void setDistribPercentage(types::FLOAT v) noexcept { m_DistribPercentage = v; m_presence |= (1ULL << P_DistribPercentage); }
		void setCashDistribCurr(const types::CURRENCY<32> &v) noexcept { m_CashDistribCurr = v; m_presence |= (1ULL << P_CashDistribCurr); }
		void setCashDistribAgentName(const types::STRING<32> &v) noexcept { m_CashDistribAgentName = v; m_presence |= (1ULL << P_CashDistribAgentName); }
		void setCashDistribAgentCode(const types::STRING<32> &v) noexcept { m_CashDistribAgentCode = v; m_presence |= (1ULL << P_CashDistribAgentCode); }
		void setCashDistribAgentAcctNumber(const types::STRING<32> &v) noexcept { m_CashDistribAgentAcctNumber = v; m_presence |= (1ULL << P_CashDistribAgentAcctNumber); }
		void setCashDistribPayRef(const types::STRING<32> &v) noexcept { m_CashDistribPayRef = v; m_presence |= (1ULL << P_CashDistribPayRef); }
		void setCashDistribAgentAcctName(const types::STRING<32> &v) noexcept { m_CashDistribAgentAcctName = v; m_presence |= (1ULL << P_CashDistribAgentAcctName); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasDistribPaymentMethod() const noexcept { return (m_presence & (1ULL << P_DistribPaymentMethod)) != 0; }
		bool hasDistribPercentage() const noexcept { return (m_presence & (1ULL << P_DistribPercentage)) != 0; }
		bool hasCashDistribCurr() const noexcept { return (m_presence & (1ULL << P_CashDistribCurr)) != 0; }
		bool hasCashDistribAgentName() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentName)) != 0; }
		bool hasCashDistribAgentCode() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentCode)) != 0; }
		bool hasCashDistribAgentAcctNumber() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentAcctNumber)) != 0; }
		bool hasCashDistribPayRef() const noexcept { return (m_presence & (1ULL << P_CashDistribPayRef)) != 0; }
		bool hasCashDistribAgentAcctName() const noexcept { return (m_presence & (1ULL << P_CashDistribAgentAcctName)) != 0; }
	};

private:
	static constexpr std::size_t P_NoDistribInsts               = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoDistribInsts> m_NoDistribInstsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoDistribInstsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoDistribInsts> &getRefNoDistribInstsGroup() noexcept { return m_NoDistribInstsGroup; }
	const std::vector<NoDistribInsts> &getRefNoDistribInstsGroup() const noexcept { return m_NoDistribInstsGroup; }
	std::size_t getNoDistribInsts() const noexcept { return m_NoDistribInstsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoDistribInstsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoDistribInsts() const noexcept { return !m_NoDistribInstsGroup.empty(); }
};

} // namespace fix44::components
