// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 06c31351475ee73d

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

#include <FIX4.4/components/FinancingDetails.h>
#include <FIX4.4/components/InstrmtLegSecListGrp.h>
#include <FIX4.4/components/Instrument.h>
#include <FIX4.4/components/InstrumentExtension.h>
#include <FIX4.4/components/SpreadOrBenchmarkCurveData.h>
#include <FIX4.4/components/Stipulations.h>
#include <FIX4.4/components/UndInstrmtGrp.h>
#include <FIX4.4/components/YieldData.h>

namespace fix44::components {

class SecListGrp {
public:
	struct NoRelatedSym {
		static constexpr std::size_t P_Currency                     = 0;
		static constexpr std::size_t P_RoundLot                     = 1;
		static constexpr std::size_t P_MinTradeVol                  = 2;
		static constexpr std::size_t P_TradingSessionID             = 3;
		static constexpr std::size_t P_TradingSessionSubID          = 4;
		static constexpr std::size_t P_ExpirationCycle              = 5;
		static constexpr std::size_t P_Text                         = 6;
		static constexpr std::size_t P_EncodedTextLen               = 7;
		static constexpr std::size_t P_EncodedText                  = 8;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 291;

		Instrument m_Instrument{};
		InstrumentExtension m_InstrumentExtension{};
		FinancingDetails m_FinancingDetails{};
		UndInstrmtGrp m_UndInstrmtGrp{};
		types::CURRENCY<32> m_Currency{fields::Currency_NULL};
		Stipulations m_Stipulations{};
		InstrmtLegSecListGrp m_InstrmtLegSecListGrp{};
		SpreadOrBenchmarkCurveData m_SpreadOrBenchmarkCurveData{};
		YieldData m_YieldData{};
		types::FLOAT m_RoundLot{fields::NULL_QTY};
		types::FLOAT m_MinTradeVol{fields::NULL_QTY};
		types::STRING<32> m_TradingSessionID{fields::TradingSessionID_NULL};
		types::STRING<32> m_TradingSessionSubID{fields::TradingSessionSubID_NULL};
		types::INT m_ExpirationCycle{fields::NULL_INT};
		types::STRING<32> m_Text{fields::Text_NULL};
		types::LENGTH m_EncodedTextLen{fields::NULL_LENGTH};
		types::DATA<32> m_EncodedText{fields::EncodedText_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_Instrument.compute_buffer_size()
				+ m_InstrumentExtension.compute_buffer_size()
				+ m_FinancingDetails.compute_buffer_size()
				+ m_UndInstrmtGrp.compute_buffer_size()
				+ m_Stipulations.compute_buffer_size()
				+ m_InstrmtLegSecListGrp.compute_buffer_size()
				+ m_SpreadOrBenchmarkCurveData.compute_buffer_size()
				+ m_YieldData.compute_buffer_size();
		}

		// accessors
		Instrument &getRefInstrument() noexcept { return m_Instrument; }
		const Instrument &getRefInstrument() const noexcept { return m_Instrument; }
		InstrumentExtension &getRefInstrumentExtension() noexcept { return m_InstrumentExtension; }
		const InstrumentExtension &getRefInstrumentExtension() const noexcept { return m_InstrumentExtension; }
		FinancingDetails &getRefFinancingDetails() noexcept { return m_FinancingDetails; }
		const FinancingDetails &getRefFinancingDetails() const noexcept { return m_FinancingDetails; }
		UndInstrmtGrp &getRefUndInstrmtGrp() noexcept { return m_UndInstrmtGrp; }
		const UndInstrmtGrp &getRefUndInstrmtGrp() const noexcept { return m_UndInstrmtGrp; }
		Stipulations &getRefStipulations() noexcept { return m_Stipulations; }
		const Stipulations &getRefStipulations() const noexcept { return m_Stipulations; }
		InstrmtLegSecListGrp &getRefInstrmtLegSecListGrp() noexcept { return m_InstrmtLegSecListGrp; }
		const InstrmtLegSecListGrp &getRefInstrmtLegSecListGrp() const noexcept { return m_InstrmtLegSecListGrp; }
		SpreadOrBenchmarkCurveData &getRefSpreadOrBenchmarkCurveData() noexcept { return m_SpreadOrBenchmarkCurveData; }
		const SpreadOrBenchmarkCurveData &getRefSpreadOrBenchmarkCurveData() const noexcept { return m_SpreadOrBenchmarkCurveData; }
		YieldData &getRefYieldData() noexcept { return m_YieldData; }
		const YieldData &getRefYieldData() const noexcept { return m_YieldData; }
		const types::CURRENCY<32> &getCurrency() const noexcept { return m_Currency; }
		const types::FLOAT &getRoundLot() const noexcept { return m_RoundLot; }
		const types::FLOAT &getMinTradeVol() const noexcept { return m_MinTradeVol; }
		const types::STRING<32> &getTradingSessionID() const noexcept { return m_TradingSessionID; }
		const types::STRING<32> &getTradingSessionSubID() const noexcept { return m_TradingSessionSubID; }
		const types::INT &getExpirationCycle() const noexcept { return m_ExpirationCycle; }
		const types::STRING<32> &getText() const noexcept { return m_Text; }
		const types::LENGTH &getEncodedTextLen() const noexcept { return m_EncodedTextLen; }
		const types::DATA<32> &getEncodedText() const noexcept { return m_EncodedText; }

		// mutators
		void setCurrency(const types::CURRENCY<32> &v) noexcept { m_Currency = v; m_presence |= (1ULL << P_Currency); }
		void setRoundLot(types::FLOAT v) noexcept { m_RoundLot = v; m_presence |= (1ULL << P_RoundLot); }
		void setMinTradeVol(types::FLOAT v) noexcept { m_MinTradeVol = v; m_presence |= (1ULL << P_MinTradeVol); }
		void setTradingSessionID(const types::STRING<32> &v) noexcept { m_TradingSessionID = v; m_presence |= (1ULL << P_TradingSessionID); }
		void setTradingSessionSubID(const types::STRING<32> &v) noexcept { m_TradingSessionSubID = v; m_presence |= (1ULL << P_TradingSessionSubID); }
		void setExpirationCycle(types::INT v) noexcept { m_ExpirationCycle = v; m_presence |= (1ULL << P_ExpirationCycle); }
		void setText(const types::STRING<32> &v) noexcept { m_Text = v; m_presence |= (1ULL << P_Text); }
		void setEncodedTextLen(types::LENGTH v) noexcept { m_EncodedTextLen = v; m_presence |= (1ULL << P_EncodedTextLen); }
		void setEncodedText(const types::DATA<32> &v) noexcept { m_EncodedText = v; m_presence |= (1ULL << P_EncodedText); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_Instrument.hasAnySet()) { return true; }
			if (m_InstrumentExtension.hasAnySet()) { return true; }
			if (m_FinancingDetails.hasAnySet()) { return true; }
			if (m_UndInstrmtGrp.hasAnySet()) { return true; }
			if (m_Stipulations.hasAnySet()) { return true; }
			if (m_InstrmtLegSecListGrp.hasAnySet()) { return true; }
			if (m_SpreadOrBenchmarkCurveData.hasAnySet()) { return true; }
			if (m_YieldData.hasAnySet()) { return true; }
			return false;
		}
		bool hasCurrency() const noexcept { return (m_presence & (1ULL << P_Currency)) != 0; }
		bool hasRoundLot() const noexcept { return (m_presence & (1ULL << P_RoundLot)) != 0; }
		bool hasMinTradeVol() const noexcept { return (m_presence & (1ULL << P_MinTradeVol)) != 0; }
		bool hasTradingSessionID() const noexcept { return (m_presence & (1ULL << P_TradingSessionID)) != 0; }
		bool hasTradingSessionSubID() const noexcept { return (m_presence & (1ULL << P_TradingSessionSubID)) != 0; }
		bool hasExpirationCycle() const noexcept { return (m_presence & (1ULL << P_ExpirationCycle)) != 0; }
		bool hasText() const noexcept { return (m_presence & (1ULL << P_Text)) != 0; }
		bool hasEncodedTextLen() const noexcept { return (m_presence & (1ULL << P_EncodedTextLen)) != 0; }
		bool hasEncodedText() const noexcept { return (m_presence & (1ULL << P_EncodedText)) != 0; }
	};

private:
	static constexpr std::size_t P_NoRelatedSym                 = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoRelatedSym> m_NoRelatedSymGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoRelatedSymGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoRelatedSym> &getRefNoRelatedSymGroup() noexcept { return m_NoRelatedSymGroup; }
	const std::vector<NoRelatedSym> &getRefNoRelatedSymGroup() const noexcept { return m_NoRelatedSymGroup; }
	std::size_t getNoRelatedSym() const noexcept { return m_NoRelatedSymGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoRelatedSymGroup.empty()) { return true; }
		return false;
	}
	bool hasNoRelatedSym() const noexcept { return !m_NoRelatedSymGroup.empty(); }
};

} // namespace fix44::components
