// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 7565f4523af7d6d7

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.4/core/field_id.h>
#include <FIX4.4/core/null_fields.h>
#include <FIX4.4/core/types.h>

#include <FIX4.4/components/NestedParties2.h>

namespace fix44::components {

class TrdAllocGrp {
public:
	struct NoAllocs {
		static constexpr std::size_t P_AllocAccount                 = 0;
		static constexpr std::size_t P_AllocAcctIDSource            = 1;
		static constexpr std::size_t P_AllocSettlCurrency           = 2;
		static constexpr std::size_t P_IndividualAllocID            = 3;
		static constexpr std::size_t P_AllocQty                     = 4;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 163;

		types::STRING<32> m_AllocAccount{fields::AllocAccount_NULL};
		types::INT m_AllocAcctIDSource{fields::NULL_INT};
		types::CURRENCY<32> m_AllocSettlCurrency{fields::AllocSettlCurrency_NULL};
		types::STRING<32> m_IndividualAllocID{fields::IndividualAllocID_NULL};
		NestedParties2 m_NestedParties2{};
		types::FLOAT m_AllocQty{fields::NULL_QTY};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		std::size_t compute_buffer_size() const noexcept {
			return MAX_ENCODE_SIZE
				+ m_NestedParties2.compute_buffer_size();
		}

		// accessors
		NestedParties2 &getRefNestedParties2() noexcept { return m_NestedParties2; }
		const NestedParties2 &getRefNestedParties2() const noexcept { return m_NestedParties2; }
		const types::STRING<32> &getAllocAccount() const noexcept { return m_AllocAccount; }
		const types::INT &getAllocAcctIDSource() const noexcept { return m_AllocAcctIDSource; }
		const types::CURRENCY<32> &getAllocSettlCurrency() const noexcept { return m_AllocSettlCurrency; }
		const types::STRING<32> &getIndividualAllocID() const noexcept { return m_IndividualAllocID; }
		const types::FLOAT &getAllocQty() const noexcept { return m_AllocQty; }

		// mutators
		void setAllocAccount(const types::STRING<32> &v) noexcept { m_AllocAccount = v; m_presence |= (1ULL << P_AllocAccount); }
		void setAllocAcctIDSource(types::INT v) noexcept { m_AllocAcctIDSource = v; m_presence |= (1ULL << P_AllocAcctIDSource); }
		void setAllocSettlCurrency(const types::CURRENCY<32> &v) noexcept { m_AllocSettlCurrency = v; m_presence |= (1ULL << P_AllocSettlCurrency); }
		void setIndividualAllocID(const types::STRING<32> &v) noexcept { m_IndividualAllocID = v; m_presence |= (1ULL << P_IndividualAllocID); }
		void setAllocQty(types::FLOAT v) noexcept { m_AllocQty = v; m_presence |= (1ULL << P_AllocQty); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			if (m_NestedParties2.hasAnySet()) { return true; }
			return false;
		}
		bool hasAllocAccount() const noexcept { return (m_presence & (1ULL << P_AllocAccount)) != 0; }
		bool hasAllocAcctIDSource() const noexcept { return (m_presence & (1ULL << P_AllocAcctIDSource)) != 0; }
		bool hasAllocSettlCurrency() const noexcept { return (m_presence & (1ULL << P_AllocSettlCurrency)) != 0; }
		bool hasIndividualAllocID() const noexcept { return (m_presence & (1ULL << P_IndividualAllocID)) != 0; }
		bool hasAllocQty() const noexcept { return (m_presence & (1ULL << P_AllocQty)) != 0; }
	};

private:
	static constexpr std::size_t P_NoAllocs                     = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 24;

	std::vector<NoAllocs> m_NoAllocsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoAllocsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoAllocs> &getRefNoAllocsGroup() noexcept { return m_NoAllocsGroup; }
	const std::vector<NoAllocs> &getRefNoAllocsGroup() const noexcept { return m_NoAllocsGroup; }
	std::size_t getNoAllocs() const noexcept { return m_NoAllocsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoAllocsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoAllocs() const noexcept { return !m_NoAllocsGroup.empty(); }
};

} // namespace fix44::components
