// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Auto-generated FIX code. Do not edit by hand.

// Generated by FalconFIX Generator
// ContentHash: 36d8e9f9ba12edd6

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

#include <utils/error_codes.h>
#include <FIX4.3/core/field_id.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/types.h>

namespace fix43::components {

class CommissionData {
	static constexpr std::size_t P_Commission                   = 0;
	static constexpr std::size_t P_CommType                     = 1;
	static constexpr std::size_t P_CommCurrency                 = 2;
	static constexpr std::size_t P_FundRenewWaiv                = 3;

	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 76;

	types::FLOAT m_Commission{fields::NULL_AMT};
	types::CHAR m_CommType{fields::NULL_CHAR};
	types::CURRENCY<32> m_CommCurrency{fields::CommCurrency_NULL};
	types::CHAR m_FundRenewWaiv{fields::NULL_CHAR};

	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

	// accessors
	const types::FLOAT &getCommission() const noexcept { return m_Commission; }
	const types::CHAR &getCommType() const noexcept { return m_CommType; }
	const types::CURRENCY<32> &getCommCurrency() const noexcept { return m_CommCurrency; }
	const types::CHAR &getFundRenewWaiv() const noexcept { return m_FundRenewWaiv; }

	// mutators
	void setCommission(types::FLOAT v) noexcept { m_Commission = v; m_presence |= (1ULL << P_Commission); }
	void setCommType(types::CHAR v) noexcept { m_CommType = v; m_presence |= (1ULL << P_CommType); }
	void setCommCurrency(const types::CURRENCY<32> &v) noexcept { m_CommCurrency = v; m_presence |= (1ULL << P_CommCurrency); }
	void setFundRenewWaiv(types::CHAR v) noexcept { m_FundRenewWaiv = v; m_presence |= (1ULL << P_FundRenewWaiv); }

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		return false;
	}
	bool hasCommission() const noexcept { return (m_presence & (1ULL << P_Commission)) != 0; }
	bool hasCommType() const noexcept { return (m_presence & (1ULL << P_CommType)) != 0; }
	bool hasCommCurrency() const noexcept { return (m_presence & (1ULL << P_CommCurrency)) != 0; }
	bool hasFundRenewWaiv() const noexcept { return (m_presence & (1ULL << P_FundRenewWaiv)) != 0; }
};

} // namespace fix43::components
