// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Michel Tonetti, Herik Lima, and Fabio Galuppo
// Generated by FalconFIX Generator
// ContentHash: 95ded871f63b2964

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>
#include <vector>

#include <FIX4.3/core/field_id.h>
#include <FIX4.3/core/null_fields.h>
#include <FIX4.3/core/types.h>

namespace fix43::components {

class Stipulations {
public:
	struct NoStipulations {
		static constexpr std::size_t P_StipulationType              = 0;
		static constexpr std::size_t P_StipulationValue             = 1;

		static constexpr uint64_t REQUIRED = 0ULL;
		static constexpr std::size_t MAX_ENCODE_SIZE = 74;

		types::STRING<32> m_StipulationType{fields::StipulationType_NULL};
		types::STRING<32> m_StipulationValue{fields::StipulationValue_NULL};

		uint64_t m_presence{0};

	public:
		// lifecycle
		void reset() noexcept;

		// validation
		bool checkRequired() const noexcept;

		// decode
		bool decode(const char *&p, const char *end) noexcept;
		bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

		// encode
		char *encode(char *p, bool includeMilliseconds = true) const noexcept;
		bool setField(int32_t tag, const char *begin, const char *end) noexcept;
		inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
		static constexpr std::size_t compute_buffer_size() noexcept { return MAX_ENCODE_SIZE; }

		// accessors
		const types::STRING<32> &getStipulationType() const noexcept { return m_StipulationType; }
		const types::STRING<32> &getStipulationValue() const noexcept { return m_StipulationValue; }

		// mutators
		void setStipulationType(const types::STRING<32> &v) noexcept { m_StipulationType = v; m_presence |= (1ULL << P_StipulationType); }
		void setStipulationValue(const types::STRING<32> &v) noexcept { m_StipulationValue = v; m_presence |= (1ULL << P_StipulationValue); }

		// presence
		bool hasAnySet() const noexcept {
			if (m_presence != 0) { return true; }
			return false;
		}
		bool hasStipulationType() const noexcept { return (m_presence & (1ULL << P_StipulationType)) != 0; }
		bool hasStipulationValue() const noexcept { return (m_presence & (1ULL << P_StipulationValue)) != 0; }
	};

private:
	static constexpr std::size_t P_NoStipulations               = 0;
	static constexpr uint64_t REQUIRED = 0ULL;
	static constexpr std::size_t MAX_ENCODE_SIZE = 25;

	std::vector<NoStipulations> m_NoStipulationsGroup{};
	uint64_t m_presence{0};

public:
	// lifecycle
	void reset() noexcept;

	// validation
	bool checkRequired() const noexcept;

	// decode
	bool decode(const char *&p, const char *end) noexcept;
	bool decode(const char *&p, const char *end, int32_t stop_tag, bool stop_on_repetition) noexcept;

	// encode
	char *encode(char *p, bool includeMilliseconds = true) const noexcept;
	bool setField(int32_t tag, const char *begin, const char *end) noexcept;
	inline bool setField(int32_t tag, std::string_view value) noexcept { return setField(tag, value.data(), value.data() + value.size()); }
	std::size_t compute_buffer_size() const noexcept {
		std::size_t total = MAX_ENCODE_SIZE;
		for (const auto &entry : m_NoStipulationsGroup) { total += entry.compute_buffer_size(); }
		return total;
	}

	// accessors
	std::vector<NoStipulations> &getRefNoStipulationsGroup() noexcept { return m_NoStipulationsGroup; }
	const std::vector<NoStipulations> &getRefNoStipulationsGroup() const noexcept { return m_NoStipulationsGroup; }
	std::size_t getNoStipulations() const noexcept { return m_NoStipulationsGroup.size(); }

	// mutators

	// presence
	bool hasAnySet() const noexcept {
		if (m_presence != 0) { return true; }
		if (!m_NoStipulationsGroup.empty()) { return true; }
		return false;
	}
	bool hasNoStipulations() const noexcept { return !m_NoStipulationsGroup.empty(); }
};

} // namespace fix43::components
